### ISSUE TITLE
Template feedback: eventbridge-lambda

### ISSUE THREAD

**Issue by ljacobsson** [aws-samples/serverless-patterns#10]
* Custom event is received, but no eventbus is specified leading the user to use the default eventbus for custom events
* Inconsistent usage of quotes (` - "prefix": "EUR-"`)

**Comment by jbesw** [comment]
Thanks for the feedback! 

This pattern is to show how to use the bus rather than provide guidance on how to organize buses, so I decided not to create a bus in this pattern.
