### ISSUE TITLE
New pattern submission: EventBridge to Appsync

### ISSUE THREAD

**Issue by onlybakam** [aws-samples/serverless-patterns#100]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create an Event Bridge Bus that sends events to an AppSync API via a destination.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

NodeJs

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

EventBridge to AppSync

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

In this pattern, AWS AppSync is configured with a a schema to manage and read todos. The pattern uses an event bridge bus and an EventBridge [API destination](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-api-destinations.html) to trigger the AppSync GraphQL `updateTodo` mutation when an event that matches the defined rule is received. The AppSync [API KEY](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#api-key-authorization) is used as the mode of authorization

## Deployment commands

cdk deploy

## Author bio 
Name: Josh Kahn
Photo URL: https://avatars.githubusercontent.com/u/6618?v=4
Twitter handle: jkahn117
Description (up to 255 chars): Josh Kahn is a Principal Solution Architect at AWS

**Comment by jbesw** [comment]
Thanks for this contribution! This is now live at: https://serverlessland.com/patterns/eventbridge-appsync-cdk.
