### ISSUE TITLE
Something wrong with the Rust section - 403 error retrieving files

### ISSUE THREAD

**Issue by ymwjbxxq** [aws-samples/serverless-patterns#1013]
Hello,

If you open the Rust section https://serverlessland.com/patterns?framework=SAM&language=Rust you will see 18 templates.

Many of them do not show the yml preview, for example:
- https://serverlessland.com/patterns/appconfig-lambda-rust
- https://serverlessland.com/patterns/eventbridge-lambda-rust
- https://serverlessland.com/patterns/lambda-dynamodb-rust
- https://serverlessland.com/patterns/lambda-eventbridge-rust
- https://serverlessland.com/patterns/lambda-rekognition-rust
- https://serverlessland.com/patterns/lambda-s3-rust
- https://serverlessland.com/patterns/lambda-sfn-rust
- https://serverlessland.com/patterns/lambda-sqs-rust-sam
- https://serverlessland.com/patterns/s3-eventbridge-rust
- https://serverlessland.com/patterns/sns-sqs-lambda-sam-rust
- https://serverlessland.com/patterns/sqs-lambda-partial-batch-rust-sam
- https://serverlessland.com/patterns/sqs-lambda-rust-sam
- https://serverlessland.com/patterns/eventbridge-lambda-rust

For example:
I can see a 403 for
Request URL: https://serverlessland.com/patterns-cache/eventbridge-lambda-rust/template.yaml

but the file in the repo is .yml, not yaml
https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-lambda-rust/template.yml

**Comment by julianwood** [comment]
Thanks, these should be resolved with: https://github.com/aws-samples/serverless-patterns/commit/b20150c987169a0a0d2fd640c2fc93551913d9b6
