### ISSUE TITLE
Serverless Patterns Collection - suggestion for Amazon API Gateway section

### ISSUE THREAD

**Issue by ymwjbxxq** [aws-samples/serverless-patterns#1015]
Hello all,

Currently, we can filter by Tpe and Language>
Amazon API Gateway has:
- REST
- HTTP

It would be nice to distinguish them and to have an option also to filter:
- CloudFormation vs OpenAPI

It will make the section much clearer.

Feel free to close this suggestion if not possible.

Daniele.

**Comment by jbesw** [comment]
Thanks for the suggestion - we'll add this to the roadmap!
