### ISSUE TITLE
New pattern submission: Amazon Public (or private) API Gateway to Private API Gateway integration

### ISSUE THREAD

**Issue by rajneeshr** [aws-samples/serverless-patterns#104]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Amazon Public (or private) API Gateway to Private API Gateway integration

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
TypeScript

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Public API Gateway to Private (VPC) API Gateway

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern in CDK offers an example to create  
a. Amazon API Gateway with a GET / api which invokes private API gateway backed by lambda 
b. Private API endpoint with a greedy proxy ("{proxy+}") and "ANY" method from the specified path, meaning it will accept by default any method and any path. The VPC Lambda function provided in JavaScript only returns the path
c. To make the connection possible following resources are also created
   i. VPC Endpoint for execute-api in your VPC
  ii. ELB target group using the private IPs created for each AZ as part of the VPC endpoint creation for TCP 443
 iii. Private NLB listening on TCP 443 configured to use the target group
 iv. VPC link in API Gateway linking NLB created above

## Deployment commands
npx cdk bootstrap aws://accountnumber/region
npx cdk deploy --app 'ts-node .' --all

## GitHub PR for template: 
[PR 103](https://github.com/aws-samples/serverless-patterns/pull/103)
## Author bio 
Name: Rajneesh Ranjan
Photo URL: https://github.com/rajneeshr
Twitter handle:
Description (up to 255 chars): Rajneesh works at AWS Professional Services and is a Serverless and Container enthusiast.

Name: Britney Tong
Photo URL: https://avatars.githubusercontent.com/u/8812922?s=400&u=2b2d05ff8a3d21147a16fb6a50e3d3a1707822b2&v=4
Twitter handle:
Description (up to 255 chars): Britney is an Professional Service and a Serverless enthusiast at Amazon Web Services based in Austin, US. Prior to joining AWS Britney worked in a number of different technical roles specializing in IoT integration, workflow Automation, and Platform as a Service (PaaS).

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-to-private-apig-cdk.
