### ISSUE TITLE
[New repo]: Serverless Java Frameworks Samples

### ISSUE THREAD

**Issue by muraria** [aws-samples/serverless-patterns#1040]
### Description

A large number of Java applications are built using popular frameworks like Spring Boot, Micronaut and Quarkus. This repo has sample application that is developed in each of these frameworks and can be deployed in three different ways: 
1. Managed Java Runtime without SnapStart.
2. Managed Java Runtime with SnapStart.
3. Custom runtime with GraalVM native image.
The repo also has metrics that compare cold start and warm start times for all these modes with each of the frameworks.

### language

English

### runtime

Java

### Level

300

### Type

Examples

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/serverless-java-frameworks-samples/blob/main/imgs/diagram.jpg

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Sample Spring Boot, Micronaut, Quarkus and Daggaer applications on AWS Lambda

### Repo URL

https://github.com/aws-samples/serverless-java-frameworks-samples

### Author Name

Aneel Murari

### Author Bio

I am a Senior Serverless Specialist Solutions Architect at AWS. I help customers design scalable, highly performant, secure, and cost effective solutions on AWS. I am is passionate about using event-driven architecture and Serverless solutions to solve various customer challenges.

### Author Twitter handle

@aneelmurari

### Author LinkedIn URL

https://www.linkedin.com/in/aneelmurari/

**Comment by jbesw** [comment]
This has now been merged at https://serverlessland.com/repos/serverless-java-frameworks-samples. Thanks for your contribution!
