### ISSUE TITLE
[New Repo]: Create a Serverless Twitter Clone with CDK

### ISSUE THREAD

**Issue by richhouse83** [aws-samples/serverless-patterns#1041]
### Description

This project is designed to give a basic introduction to building a Serverless back end on AWS, using CDK. It provides the main structure and suggested solution, but allows you the opportunity to experiment with different options and ideas, so see what you can come up with!

### language

English

### runtime

Typescript

### Level

200

### Type

Workshop

### Use case

Backend

### Primary image

https://business.time.com/wp-content/uploads/sites/2/2013/11/failwhale.gif?w=720&h=432&crop=1

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Create your own Social Media back end

### Repo URL

https://github.com/richhouse83/cdk-twitter-clone

### Author Name

Rich House

### Author Image URL

https://avatars.githubusercontent.com/u/67099777?v=4

### Author Bio

Rich House is a developer and cloud engineer from Manchester England. In 2022 he was part of the AWS GameDay World Championship winning team, D55.

### Author Twitter handle

rich_house

### Author LinkedIn URL

https://www.linkedin.com/in/rich-house-3ab5553a/

**Comment by jbesw** [comment]
This has now been merged at https://serverlessland.com/repos/cdk-twitter-clone. Thanks for your contribution!
