### ISSUE TITLE
Support Fifo SNS target

### ISSUE THREAD

**Issue by amit-chaudhary-cko** [aws-samples/serverless-patterns#1044]
Can't find `PipeTargetParameters` for fifo SNS. Though FIFO SQS target is supported and we can provide `PipeTargetSqsQueueParameters` with 
```
{
  "MessageDeduplicationId" : String,
  "MessageGroupId" : String
}

```
Is there anything similar for SNS with fifo enabled?

**Comment by jbesw** [comment]
Hi! Is this related to a published pattern?
