### ISSUE TITLE
[New repo]: aws-samples/amazon-eventbridge-pipes-architectural-patterns

### ISSUE THREAD

**Issue by dominik-richter** [aws-samples/serverless-patterns#1045]
### Description

This repo implements four enterprise integration patterns using Amazon EventBridge Pipes. This helps customers to simplify their architectures. It can also reduce the amount of code they have to write and maintain.

### language

English

### runtime

TypeScript

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/amazon-eventbridge-pipes-architectural-patterns/main/images/Picture8.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Implementing architectural patterns with Amazon EventBridge Pipes

### Repo URL

https://github.com/aws-samples/amazon-eventbridge-pipes-architectural-patterns

### Additional resources

- [Implementing architectural patterns with Amazon EventBridge Pipes | AWS Compute Blog](https://aws.amazon.com/blogs/compute/implementing-architectural-patterns-with-amazon-eventbridge-pipes/)
- [Content Filter pattern | ServerlessLand - Patterns](https://serverlessland.com/patterns/content-filter-pattern-kinesis-cdk)
- [Message Translator Pattern | ServerlessLand - Patterns](https://serverlessland.com/patterns/message-translator-pattern-cdk)
- [Normalizer Pattern | ServerlessLand - Patterns](https://serverlessland.com/patterns/normalizer-pattern-cdk)
- [Claim Check pattern | ServerlessLand - Patterns](https://serverlessland.com/patterns/claim-check-pattern-cdk) 

### Author Name

Dominik Richter

### Author Image URL

https://avatars.githubusercontent.com/u/29404931

### Author Bio

Solutions Architect at AWS, passionate about event-driven architectures and Serverless.

### Author LinkedIn URL

https://www.linkedin.com/in/do-richter/

**Comment by jbesw** [comment]
Live at https://serverlessland.com/repos/amazon-eventbridge-pipes-architectural-patterns. Thanks!
