### ISSUE TITLE
Mutual TLS for Java based AWS Lambda functions

### ISSUE THREAD

**Issue by dmahapatro** [aws-samples/serverless-patterns#1047]
### Description

Learn how to use mutual TLS in Java based Lambda functions when the Lambda function establishes network connections to other services through HTTPS.

Modern secure applications establish network connections to other services through HTTPS. This is to ensure that the application connects to the right party and to encrypt the data before sending it over the network. As a service provider, you might not want unauthenticated users to connect to your service. One solution to this requirement is to use mutual TLS (Transport Layer Security). Mutual TLS (or mTLS) is a common security mechanism that uses client certificates to add an authentication layer. This allows the service provider to verify the client’s identity cryptographically.

### language

English

### runtime

Java

### Level

400

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/aws-samples/serverless-mutual-tls/blob/main/doc/Java_Lambda_mTLS_Architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Mutual TLS for Java based AWS Lambda functions

### Repo URL

https://github.com/aws-samples/serverless-mutual-tls

### Author Name

Dhiraj Mahapatro, Christian Mueller

### Author Image URL

https://i.postimg.cc/cr6qVWdr/mahadhir-high-res-current-photo.jpg

### Author Bio

Dhiraj Mahapatro is a Principal Serverless Specialist Solutions Architect at AWS. Dhiraj specializes in helping enterprise financial services adopt serverless and event-driven architectures to modernize their applications and accelerate their pace of innovation. Dhiraj comes from a Java development background. He has helped many customers with Groovy, Grails, Spring Boot implementations. He has an affinity towards building technical solutions for real life business problems.

### Author Twitter handle

dhirajmahapatro

### Author LinkedIn URL

https://www.linkedin.com/in/dmahapatro/

**Comment by dmahapatro** [comment]
Please note that this repo has multiple authors. [@muellerc ](https://github.com/muellerc)is the co-author of this repo.

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/serverless-mutual-tls.
