### ISSUE TITLE
[New repo]: Java GraalVM native image on serverless custom runtime

### ISSUE THREAD

**Issue by dmahapatro** [aws-samples/serverless-patterns#1050]
### Description

Learn how to use GraalVM native image in Java-based Lambda functions. When you create an executable binary using GraalVM native image, you can use AWS Lambda's custom runtime and execute the native image. Running GraalVM native image shows major performance optimization for Java based Lambda functions. Visit this repository to see the performance benchmarks on running GraalVM native image at scale.

This is a simple serverless application built in Java and uses the GraalVM native-image tool. It consists of an [Amazon API Gateway](https://aws.amazon.com/api-gateway/) backed by four [AWS Lambda](https://aws.amazon.com/lambda/) functions and an [Amazon DynamoDB](https://aws.amazon.com/dynamodb/) table for storage.

### language

Java

### runtime

Custom

### Level

300

### Type

Examples

### Use case

Performance

### Primary image

https://github.com/aws-samples/serverless-graalvm-demo/blob/main/imgs/performance_results.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Java GraalVM native image on serverless custom runtime

### Repo URL

https://github.com/aws-samples/serverless-graalvm-demo

### Author Name

Mark Sailes

### Author Image URL

https://pbs.twimg.com/profile_images/1562826122068369408/-fbfOE5n_400x400.jpg

### Author Bio

Mark is a specialist solutions architect focusing on serverless services at AWS. His love of serverless technology came from his time as an AWS customer, where he successfully transformed an in-house sports trading solution to cloud native technology. He holds 8 AWS certifications and is currently chasing the rest.

### Author Twitter handle

MarkSailes3

### Author LinkedIn URL

https://www.linkedin.com/in/mark-sailes/

**Comment by jbesw** [comment]
Added at https://serverlessland.com/repos/serverless-graalvm-demo. Thanks!
