### ISSUE TITLE
[New repo]: Serverless service template, AWS Lambda handler Cookbook

### ISSUE THREAD

**Issue by ran-isenberg** [aws-samples/serverless-patterns#1051]
### Description

This project aims to reduce cognitive load for Servelress newcomers by providing a skeleton Python Serverless service template that implements best practices for AWS Lambda, Serverless CI/CD, and AWS CDK in one template project.

### language

English

### runtime

Python 3.9

### Level

100

### Type

Application

### Use case

Backend

### Primary image

https://static.wixstatic.com/media/2e76fb_6a00765be5124a1a91933cb6cb4c1e64~mv2.jpeg/v1/fill/w_770,h_513,al_c,q_85,enc_auto/2e76fb_6a00765be5124a1a91933cb6cb4c1e64~mv2.jpeg

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

AWS Lambda Handler Cookbook - A Serverless Service Template

### Repo URL

https://github.com/ran-isenberg/aws-lambda-handler-cookbook

### Additional resources

documentation: https://ran-isenberg.github.io/aws-lambda-handler-cookbook/

### Author Name

Ran Isenberg

### Author Image URL

https://static.wixstatic.com/media/2e76fb_4d11e72ae9f44e35b3a40e71fe783d3e~mv2.png/v1/fill/w_846,h_734,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/%D7%A4%D7%A8%D7%95%D7%A4%D7%99%D7%9C_edited.png

### Author Bio

Ran Isenberg is an AWS Community Builder, a Principal Software Architect, a [blogger](https://www.ranthebuilder.cloud/), and a [public speaker](https://www.ranthebuilder.cloud/webinars).

Ran has vast experience designing Serverless applications and over ten years of hands-on software development.
Ran maintains a [website](https://www.ranthebuilder.cloud/) where he shares his knowledge and experience in the Serverless world.

### Author Twitter handle

IsenbergRan

### Author LinkedIn URL

https://www.linkedin.com/in/ranisenberg/

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/aws-lambda-handler-cookbook.

**Comment by ran-isenberg** [comment]
@jbesw thank you!
For some reason, the documentation link https://ran-isenberg.github.io/aws-lambda-handler-cookbook/ wasnt added. is it because i wrote "documentation:" before the link?

**Comment by jbesw** [comment]
Thanks - we'll add the link to the "Additional resources" panel. It will be visible in the next few mins.
