### ISSUE TITLE
[New repo]: Lambda Coldstart Performance Analysis

### ISSUE THREAD

**Issue by maxday** [aws-samples/serverless-patterns#1052]
### Description

Always up-to-date Lambda Cold Starts performance benchmark.
Visualize 10 Cold Starts for each runtime, updated daily.
Supports currently 15+ runtimes

### language

English

### runtime

all

### Level

100

### Type

Application

### Use case

Performance

### Primary image

https://drive.google.com/file/d/1wGwG7TkjuOEVRNbtDwOaiMb6-1RA39hU/view?usp=share_link

### IaC framework

Serverless framework + AWS sdk

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Lambda Coldstart Performance Analysis

### Repo URL

https://maxday.github.io/lambda-perf/

### Additional resources

https://github.com/maxday/lambda-perf
https://www.youtube.com/watch?v=Idys2BAmqIU

### Author Name

Maxime David

### Author Image URL

https://avatars.githubusercontent.com/u/864493?v=4

### Author Bio

Maxime David is a life-long open source aficionado and Senior Software Engineer advancing serverless topics at Datadog. He’s keen on code profiling, and believes that performance in software matters. When he’s not optimizing software, he likes to try every banana bread he can find.

### Author Twitter handle

_maxday

### Author LinkedIn URL

https://www.linkedin.com/in/maxday/

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/lambda-perf-benchmarks.
