### ISSUE TITLE
[New repo]: Serverless Run Watch

### ISSUE THREAD

**Issue by astuyve** [aws-samples/serverless-patterns#1053]
### Description

This [Serverless](https://github.com/serverless/serverless) plugin provides a fast iterate -> test loop in your CLI.

Logs delivered from CloudWatch to your terminal.

Deployments skip CloudFormation, and use direct updateFunction and updateFunctionConfiguration API calls which take only a few seconds.

Supports all runtimes

### language

English

### runtime

Python, Node, Go, Java, Ruby, Dotnet, Rust, and more!

### Level

100

### Type

Application

### Use case

Backend

### Primary image

https://user-images.githubusercontent.com/1598537/213583355-1c08619f-da92-454d-b431-3df21d40ed09.gif

### IaC framework

Serverless Framework

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Cloud-local developer experience for Serverless. Single-digit second deploys, and logs streamed from CloudWatch straight to your terminal

### Repo URL

https://github.com/astuyve/serverless-run-watch

### Additional resources

www.aaronstuyvenberg.com
www.serverless.com

### Author Name

AJ Stuyvenberg

### Author Image URL

https://avatars.githubusercontent.com/u/1598537?s=400&u=baf345a4be02117797eb5a3fc21ad8375ecdb4f7

### Author Bio

AJ Stuyvenberg is the Engineering Lead for Serverless APM at Datadog, and has been a member of the Serverless community for 6+ years. He’s an AWS Community Builder, serverless meetup organizer, and frequently blogs about Serverless topics.

Before Datadog, he was a Principal Engineer at Serverless Inc, the company building the Serverless Framework.

In his spare time, AJ is an avid BASE jumper and enjoys flying his wingsuit in the Alps.

### Author Twitter handle

@astuyve

### Author LinkedIn URL

https://www.linkedin.com/in/aaron-stuyvenberg/

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/serverless-run-watch.
