### ISSUE TITLE
[New repo]: Text to Speech Converter

### ISSUE THREAD

**Issue by deeheber** [aws-samples/serverless-patterns#1056]
### Description

A Fullstack Serverless application that accepts text and outputs an audio file of the submitted text using Amazon Polly. Have fun trying out different voices for various collections of text. Note that this application was written with US-English in mind, but it may work for other languages too. The web UI is built using react and has a minimal design.

Also included is a deployment pipeline via a Code Build project triggered by a Cloud Formation Custom Resource that builds the Frontend code and places the built files in an S3 bucket while connecting the Frontend to the deployed API.

### language

English

### runtime

Node.js

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://user-images.githubusercontent.com/12616554/218244422-cdb357c4-01b8-4d34-b47c-c2eb4e06bb1a.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Text to Speech Converter

### Repo URL

https://github.com/deeheber/text-to-speech-converter

### Additional resources

https://github.com/deeheber/text-to-speech-converter/blob/main/README.md

### Author Name

Danielle Heberling

### Author Image URL

https://user-images.githubusercontent.com/12616554/218244653-423c11bf-b087-4e9a-8008-bb2b2f5ab093.JPG

### Author Bio

Danielle Heberling is a software engineer with a background that includes being a musician and teaching at a public school. She’s passionate about building things that make the world a better place, whether that be through social change or a good laugh.

### Author Twitter handle

@deeheber

### Author LinkedIn URL

https://www.linkedin.com/in/deeheber/

**Comment by bls20AWS** [comment]
Thank you for your contribution to the repos collection.
