### ISSUE TITLE
[New repo]: Serverless Rust Collection

### ISSUE THREAD

**Issue by jeastham1993** [aws-samples/serverless-patterns#1060]
### Description

This repository contains a collection of examples using the Rust programming language to build serverless applications on AWS. Ranging from API's using API Gateway and Lambda, to asynchronous processing using SQS.

The sample code aims to show how to use Rust within the context of AWS Lambda and is not a thorough analysis on the Rust programming language itself.

### language

English

### runtime

Rust

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/jeastham1993/learning-rust/blob/main/assets/rust-programming.jpg

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

A collection of serverless application examples built using the Rust programming language.

### Repo URL

https://github.com/jeastham1993/rust-on-serverless

### Additional resources

- [Serverless Rust YouTube Playlist](https://www.youtube.com/watch?v=i6FKvK5JQ8o&list=PLCOG9xkUD90KQ1IPQT_m1NbPRXXRFb63s)
- [Cargo Lambda](https://www.cargo-lambda.info/)

### Author Name

James Eastham

### Author Image URL

https://serverlessland.com/assets/images/resources/contributors/james-eastham.jpg

### Author Bio

James Eastham is a Senior Cloud Architect at AWS. His specialism is building serverless applications with .NET and he is currently learning Rust within the context of AWS Serverless technologies..

### Author Twitter handle

plantpowerjames

### Author LinkedIn URL

https://www.linkedin.com/in/james-eastham

**Comment by jbesw** [comment]
Thanks! This is live at https://serverlessland.com/repos/serverless-rust-collection.
