### ISSUE TITLE
Wrong image for the API Gateway REST API to EventBridge with event payload composition and SQS as target pattern

### ISSUE THREAD

**Issue by ymwjbxxq** [aws-samples/serverless-patterns#1068]
Hello,

if you open this pattern
https://serverlessland.com/patterns?services=apigw%2Csqs%2Ceventbridge&framework=SAM

You will see that the image associated with the pattern is wrong. It should be:

APIGW -> EB -> SQS -> Lambda

The SQS icon should be before the Lambda and not after

**Comment by jbesw** [comment]
Thanks for catching this - I've updated the diagram and it will be live in a few minutes.
