### ISSUE TITLE
[New repo]: build web application with AWS serverless 

### ISSUE THREAD

**Issue by zxkane** [aws-samples/serverless-patterns#1070]
### Description

Building web application is a common use case, leveraging cloud services could accelerate the builders to develop and deploy the services. With AWS serverless services, the application can easily get the capabilities like security, highly availability, scalability, resiliency and cost optimized.

This is a series posts to demonstrate how building a serverless TODO web application on AWS with AWS serverless services and AWS CDK, it consists of,

- [Restful HTTP APIs](https://kane.mx/posts/2022/build-serverless-app-on-aws/restful-api/), use [Amazon API Gateway](https://aws.amazon.com/api-gateway/) and [Amazon DynamoDB](https://aws.amazon.com/dynamodb/)
- Securely and accelerately [distribute the static website](https://kane.mx/posts/2022/build-serverless-app-on-aws/static-website/) via [Amazon CloudFront](https://aws.amazon.com/cloudfront/) and [Amazon S3](https://aws.amazon.com/s3/)
- [Authentication and Authorization](https://kane.mx/posts/2022/build-serverless-app-on-aws/protect-website-with-cognito/) via [Amazon Cognito](https://aws.amazon.com/cognito/) and [AWS Amplify](https://aws.amazon.com/amplify/)
- [Federated OIDC authentication](https://kane.mx/posts/2022/build-serverless-app-on-aws/federated-oidc-login-with-cognito-and-amplify/) with [Amazon Cognito](https://aws.amazon.com/cognito/)
- CI/CD [DevOps pipeline](https://kane.mx/posts/2022/build-serverless-app-on-aws/devops-pipeline/)
- [source code](https://github.com/zxkane/cdk-collections/tree/master/serverlesstodo) written by [AWS CDK](https://aws.amazon.com/cdk/) to archive above features

### language

English 

### runtime

typescript 

### Level

300

### Type

None

### Use case

Backend

### Primary image

https://kanr.mx/posts/2022/build-serverless-app-on-aws/images/cover.png

### IaC framework

Aws cdk

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [x] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Building web application is a common use case, leveraging cloud services could accelerate the builders to develop and deploy the services. With AWS serverless services, the application can easily get the capabilities like security, highly availability, scalability, resiliency and cost optimized.

### Repo URL

https://github.com/zxkane/cdk-collections/tree/master/serverlesstodo

**Comment by bls20AWS** [comment]
https://serverlessland.com/repos/to-do-web-application merged, to be published later today
thanks for the contribution !
