### ISSUE TITLE
Uncaught Exception in "eventbridge-schedule-remove-one-time-schedules" pattern

### ISSUE THREAD

**Issue by mmkader85** [aws-samples/serverless-patterns#1077]
Hi,

I was looking for solution to delete all the one-time schedules which are old. i.e., Already executed in the past. I was directed by AWS support to deploy this pattern and I did it without modifying any configuration. I followed the instructions in https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-schedule-remove-one-time-schedules/README.md to deploy it.

After successful deployment, it also ran on its scheduled time as expected which is on 17 Feb 2023 00:00:00 (UTC +00:00). But the old one-time schedules are not deleted as there is a bug in the application code.

I found this error in CloudWatch logs of the lambda which is invoked by this schedule. Here is the error. Please help fix it.

```javascript
// INIT_START Runtime Version: nodejs:16.v11	Runtime Version ARN: arn:aws:lambda:ap-southeast-1::runtime:ee071345fbee0f4751fcbcd47a5784052d8f7d4256ca7f31e6056b294cee515c

// 2023-02-17T00:00:11.381Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'find-schedules'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'find-schedules'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}

// START RequestId: 0e63eec3-8039-4dc8-982a-96a583f2aee3 Version: $LATEST

// Unknown application error occurred
// Runtime.ImportModuleError

// END RequestId: 0e63eec3-8039-4dc8-982a-96a583f2aee3
```

Runtime: `Node.js 16.x`
Architecture: `x86_64`

I have also tried to manually trigger this lambda from console using "Test" option in the page, it produced the same error.

Thanks.

**Comment by boyney123** [comment]
Hi @mmkader85 

Thanks for raising the issue and patience. 

How many schedule's are you looking to delete?

I can have a look, but in the mean time you might have to manually delete them if you are worried about the number of schedules you have, we are also looking to add new functionality with scheduler to help customers with this soon, which can help.

**Comment by boyney123** [comment]
Just looked now, looks like the `sam build` command might be failing with your node version.

Can you try a `18.x` version of node locally?

1. Run `sam build`
1. Run `sam deploy --guided`

[nvm](https://github.com/nvm-sh/nvm) can be a great way to switch versions, this hopefully will get you unlocked, I just tried on version 16 and 18 and got it working locally.

Let me know how it goes.

**Comment by mmkader85** [comment]
Upgrade to `18.x` helps. Thanks @boyney123 .
