### ISSUE TITLE
Lib item is missing so build/deploy can't be done...

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/serverless-patterns#1083]
In the following example, AppSync StepFunctions (Synchronous Express Workflows)...
https://github.com/aws-samples/serverless-patterns/tree/main/appsync-stepfunctions-express-cdk

this seems to be missing-->../lib/appsync-stepfunctions-express-cdk

**Comment by julianwood** [comment]
Thanks, sorry, somehow a missing file. Now added: https://github.com/aws-samples/serverless-patterns/commit/eb5d05e9b3d15e81591a94d4ae66d2f7726766a0
