### ISSUE TITLE
[New repo]: Bidirectional event integrations with Salesforce and Amazon EventBridge

### ISSUE THREAD

**Issue by rohanmeh** [aws-samples/serverless-patterns#1095]
### Description

In this repo, you learn how to set up a bidirectional integration between Salesforce and EventBridge and use cases for working with Salesforce events. You see an example application for interacting with Salesforce support case events with automated workflows for detecting sentiment with AWS AI/ML services and enriching support cases with customer order data.

See this [blog post](https://aws.amazon.com/blogs/compute/introducing-bidirectional-event-integrations-with-salesforce-and-amazon-eventbridge/) for more info about the project. 

### language

English

### runtime

Node.js

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2022/08/11/salesforce1-1024x541.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Bidirectional integration between Salesforce and EventBridge.

### Repo URL

https://github.com/aws-samples/eventbridge-salesforce-integration

### Author Name

Alseny Diallo, Rohan Mehta

### Author Bio

Alseny Diallo is a Prototype Solutions Architect at AWS.

Rohan Mehta is a Cloud Application Architect at AWS.

### Author Twitter handle

rohanmehta_dev

### Author LinkedIn URL

https://www.linkedin.com/in/alseny-diallo-66b64080/, https://www.linkedin.com/in/rohan-mehta-dev/

**Comment by bls20AWS** [comment]
Merged.
