### ISSUE TITLE
Does not pass a checkov scan

### ISSUE THREAD

**Issue by balq60** [aws-samples/serverless-patterns#1104]
I pulled the code down and wrapped it in some pre-commits.  

Attached see the issues checkov found.

Not saying they all should be fixed, but there are some things in here that should be.  And if not fixed, a comment as to why not fixing.
[checkov-run-results.zip](https://github.com/aws-samples/serverless-patterns/files/10853868/checkov-run-results.zip)

**Comment by jbesw** [comment]
The patterns library is intended to provide a quick starting point for developers building serverless applications. The patterns are run through a number of internal tests to ensure we balance secure implementations with practical guidance. 

If you have concerns over a specific pattern, please open one ticket per pattern so we can send to the author.
