### ISSUE TITLE
Async Step Functions integration with API Gateway

### ISSUE THREAD

**Issue by benbpyle** [aws-samples/serverless-patterns#1109]
### Async Step Functions integration with API Gateway

Demonstrates a sample webhooks style integration which allows API Gateway to trigger a Step Function async and return back to the client.  Code contains

  * TypeScript for CDK
  * Golang for the simple Lambda handler

### language

English

### runtime

TypeScript, Golang

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://www.binaryheap.com/wp-content/uploads/2023/03/header-cropped.jpg

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Async Step Functions integration with API Gateway

### Repo URL

https://github.com/benbpyle/cdk-steps-gateway-sample

### Author Name

Benjamen Pyle

### Author Image URL

https://www.binaryheap.com/wp-content/uploads/2023/02/cropped-Photo-on-1-26-23-at-8.57-AM-2.png

### Author Bio

Hi there, I'm Benjamen Pyle. I'm glad you found my site and this slice of the web. I've been into tech and sports pretty much my whole life and this blog is an expression of those interests. I am currently an [AWS Community Builder](https://aws.amazon.com/developer/community/community-builders/) specializing in Serverless so you will find some how-to articles, tips, tricks and plenty of source code about building, deploying and running those workloads. Occasionally I'll throw in some musings about golf as well.

I'm currently working as the CTO for Curantis Solutions building a world class EHR using many Event Driven Architecture design principles and capabilities

I'm also a husband and a father and view those two titles as the most important in my life.

### Author Twitter handle

https://twitter.com/benjamenpyle

### Author LinkedIn URL

https://www.linkedin.com/in/benjamenpyle/

**Comment by bls20AWS** [comment]
Tank you for contributing
