### ISSUE TITLE
New repo - Serverless Weather Reporting with AWS Step Functions and CDK

### ISSUE THREAD

**Issue by deeheber** [aws-samples/serverless-patterns#1110]
### Description

Former residents of Portland, Oregon created a website, isitsnowinginpdx.com. I cannot speak for their motivations, but I personally find this site both entertaining and informative.

After moving out of Portland into the suburbs, I noticed that the site was not as accurate, so I decided to build my own site isitsnowinginhillsboro.com. Behind the scenes it it a Step Function workflow and auto updates the site status based off of the Open Weather Map API.

You can clone the repo following the instructions in the README.md file to create your own weather site. Plug in the latitude and longitude of your city. Also, it’s not limited to snow!

### language

English

### runtime

Typescript

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://user-images.githubusercontent.com/12616554/221385438-87a3509a-788c-41cf-8a76-ddac15bcc7fd.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Weather Reporting

### Repo URL

https://github.com/deeheber/weather-site

### Additional resources

https://www.danielleheberling.xyz/blog/serverless-weather-reporting/

### Author Name

Danielle Heberling

### Author Image URL

https://avatars.githubusercontent.com/u/12616554?v=4

### Author Bio

Danielle Heberling is a software engineer with a background that includes being a musician and teaching at a public school. She’s passionate about building things that make the world a better place, whether that be through social change or a good laugh.

### Author Twitter handle

deeheber

### Author LinkedIn URL

https://www.linkedin.com/in/deeheber/

**Comment by bls20AWS** [comment]
thank you for contributing.
