### ISSUE TITLE
Using DynamoDB Streams with EventBridge Pipes

### ISSUE THREAD

**Issue by benbpyle** [aws-samples/serverless-patterns#1111]
## Using DynamoDB Streams with EventBridge Pipes

Demonstrates a solution that defines a DynamoDB table and uses its stream to be an input source to EventBridge Pipes.   The Pipe then filters the input, transforms the output to remove some of the DDB noise that isn't needed downstream and publishes it to a custom EventBus

An EventBridge Rule is then used to forward this filtered and transformed event into a Lambda written in Golang

This is just a sample but highlights how to get started and connect these Serverless pieces together

### language

English

### runtime

Golang

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://www.binaryheap.com/wp-content/uploads/2023/03/gears.jpg

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Using DynamoDB Streams with EventBridge Pipes

### Repo URL

https://github.com/benbpyle/dynamodb-eventbridge-pipes

### Author Name

Benjamen Pyle

### Author Image URL

https://www.binaryheap.com/wp-content/uploads/2023/02/cropped-Photo-on-1-26-23-at-8.57-AM-2.png

### Author Bio

Hi there, I'm Benjamen Pyle. I'm glad you found my site and this slice of the web. I've been into tech and sports pretty much my whole life and this blog is an expression of those interests. I am currently an [AWS Community Builder](https://aws.amazon.com/developer/community/community-builders/) specializing in Serverless so you will find some how-to articles, tips, tricks and plenty of source code about building, deploying and running those workloads. Occasionally I'll throw in some musings about golf as well.

I'm currently working as the CTO for Curantis Solutions building a world class EHR using many Event Driven Architecture design principles and capabilities

I'm also a husband and a father and view those two titles as the most important in my life.

### Author Twitter handle

https://twitter.com/benjamenpyle

### Author LinkedIn URL

https://www.linkedin.com/in/benjamenpyle/

**Comment by bls20AWS** [comment]
thank you for contributing.
