### ISSUE TITLE
new repo - Detect Entities with AWS Comprehend using Serverless

### ISSUE THREAD

**Issue by moitrasayan007** [aws-samples/serverless-patterns#1116]
### Description

A serverless application built with AWS SAM, focused around using AWS Comprehend to perform NLP on given text.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/moitrasayan007/aws-serverless-comprehend-app/blob/master/entity_comprehend.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

A serverless application built with AWS SAM, focused around using AWS Comprehend to perform NLP on given text.

### Repo URL

https://github.com/moitrasayan007/aws-serverless-comprehend-app

### Additional resources

https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html

### Author Name

Sayan Moitra

### Author Image URL

https://github.com/moitrasayan007/aws-serverless-comprehend-app/blob/master/sayan.png

### Author Bio

Sayan is a Solutions Architect at Amazon Web Services based in India.

### Author Twitter handle

https://twitter.com/moitra_sayan007

### Author LinkedIn URL

https://www.linkedin.com/in/sayanmoitra/

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/repos/aws-serverless-comprehend-app shortly.
