### ISSUE TITLE
apigw-http-api-eventbridge this template doesn't push event to default bridge

### ISSUE THREAD

**Issue by LokeshSingal** [aws-samples/serverless-patterns#112]
apigw-http-api-eventbridge this template doesn't push event to default bridge , though http api is working fine.

It seems there is some issue in IAM Role which has been configured or can you help me how to check the integration logs.

I have added the logs in http api resource, but it doesn't show integration logs (http api to event bridge)

**Comment by LokeshSingal** [comment]
AWS HTTP API doesn't work with AWS Services, then how come we can you guys make wrong templates and upload here.

**Comment by jbesw** [comment]
This pattern deploys an HTTP API endpoint that puts an event on the default event bus with a source of "WebApp". It also deploys a Lambda function which receives these events and logs them out to CloudWatch Logs.

1. If you deploy using an account with appropriate permissions using `sam deploy --guided`, it creates all three resources.
2. Use the outputs to retrieve the URL of the endpoint.
3. You can then use curl or Postman to invoke the endpoint with a JSON payload, using the format shown in the README.
4. The Lambda function logs show the logged event:

```
2021-09-07T10:54:01.645Z	f28516eb-e740-4abb-9af3-2bffda122226	INFO	
{
    "version": "0",
    "id": "c5d64c59-24b1-11d5-f9fc-657e0270425d",
    "detail-type": "MyDetailType",
    "source": "WebApp",
    "account": "123456789012",
    "time": "2021-09-07T10:54:00Z",
    "region": "us-east-1",
    "resources": [],
    "detail": {
        "message": "This is my test"
    }
}
```

If you are having issues, please provide step-by-step instructions of what you are doing and any screen output you see, and we will try to help. When I deployed this pattern just now, I could not find any issues and was able to deploy and test with the instructions provided.

**Comment by LokeshSingal** [comment]
Sorry, my bad had an issue with my EventPattern, i configured the wrong event pattern.
Thanks for taking out the time.
