### ISSUE TITLE
[New repo]: Micro-Frontends in AWS

### ISSUE THREAD

**Issue by lucamezzalira** [aws-samples/serverless-patterns#1121]
### Description

Micro-Frontends are the technical representation of a business subdomain, they allow independent implementations with the same or different technology, they should minimize the code shared with other subdomains and they are own by a single team.

These characteristics might seem familiar if you have built distibuted systems in the past. Micro-Frontends are the answer when you need to scale your organizations having multiple teams working together in the same project.

In this repository we collect examples to implement Micro-Frontends in AWS, leveraging several AWS services that represents the building blocks for stitching together distributed architecterues not only for the backend but now for the frontend too.

### language

English

### runtime

Node.js

### Level

400

### Type

Examples

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/ssr-micro-frontends/raw/main/images/diagram.png

### IaC framework

AWS SAM, AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Server-Side Rendering Micro-Frontends in AWS

### Repo URL

https://github.com/aws-samples/ssr-micro-frontends

### Author Name

Luca Mezzalira

### Author Image URL

https://miro.medium.com/max/2400/1*5F16W-IYa89gvYxKWRUQHQ.jpeg

### Author Bio

[Luca Mezzalira](https://www.linkedin.com/in/lucamezzalira) is principal serverless specialist solutions architect at AWS, an international speaker, and books author. Over the past 20 years, he’s mastered software architectures from frontend to the cloud, providing the right solution for the context of the job at hand.

### Author Twitter handle

https://twitter.com/lucamezzalira

### Author LinkedIn URL

https://www.linkedin.com/in/lucamezzalira

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/ssr-micro-frontends.
