### ISSUE TITLE
New pattern submission - SNS to EventBridge Pipes that triggers a Step Function with CDK

### ISSUE THREAD

**Issue by benbpyle** [aws-samples/serverless-patterns#1129]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

I completed by the README.md and the example-pattern.json file.  I've also added the PR below.  

This is my first time issuing a PR and going through this process so if I didn't get something right, I'm more than happy to adjust.  

I didn't add details as the way I read the above is that they need to be in the two files mentioned which I've done.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cdk-sns-sqs-eventbridge-pipes-stepfunctions.
