### ISSUE TITLE
[New repo]: Basic Serverless Feature Flag Service

### ISSUE THREAD

**Issue by Hatton92** [aws-samples/serverless-patterns#1130]
### Description

# Application demonstrating a serverless feature flag service defined using C# and CDK

This simple application will deploy an API with basic create, delete and update code to allow a user to manage feature flags. This demonstrates using CDK written in .NET to define the serverless services being used (API Gateway, Lambda, DynamoDB). The API uses proxy integration with Lambda to process the relevant request based on the action and interacts with DynamoDB where feature flags are stored as key value pairs.

### language

English

### runtime

.NET

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/Hatton92/aws-basic-serverless-feature-flag-service/blob/main/overview.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Basic Serverless Feature Flag Service

### Repo URL

https://github.com/Hatton92/aws-basic-serverless-feature-flag-service

### Author Name

John Hatton

### Author Image URL

https://media.licdn.com/dms/image/D4D03AQG5l51GOPpQhg/profile-displayphoto-shrink_200_200/0/1669136779147?e=1684368000&v=beta&t=DVf0J5yGQS-15O1l3p_jBItKkCOFJRaP2hsgXEGLELk

### Author Bio

A Tech Lead who's passionate about event-driven architecture and Serverless, who specialises in cloud-native. Was part of the AWS GameDay World Championship 2022 winning team. Have many years experience working with high traffic public facing websites & applications

### Author LinkedIn URL

https://www.linkedin.com/in/john-hatton-04653b1b7/

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/repos/aws-basic-serverless-feature-flag-service shortly.
