### ISSUE TITLE
[New repo]: Java Lambda functions using a Lambda layer

### ISSUE THREAD

**Issue by roamingthings** [aws-samples/serverless-patterns#1136]
### Description

This project demonstrates how to deploy an application to AWS with a Lambda written in Java using a layer for all
dependencies.

Serverless applications that contain multiple Lambda functions will inevitably share a lot of dependencies between those
lambda functions. This would usually mean that you are deploying these dependencies over and over again with every
lambda function. This will lead to big deployment assets (usually >20MB) and can lead to long deployment times and
further problems e.g. when deploying using a CDK CodePipeline that currently limits the total deployment size to 256MB. 

Lambda layers help to reduce deployment size of a single Lambda function and additional simplify dependency management.

### language

English

### runtime

Java

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/roamingthings/java-lambda-deps-layer/main/docs/images/architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Use Lambda Layers for Shared Dependencies for Java Functions

### Repo URL

https://github.com/roamingthings/java-lambda-deps-layer

### Author Name

Alexander Sparkowsky

### Author Image URL

https://roamingthings.de/avatar.png

### Author Bio

Software Engineer, Tinkerer and Maker. Focused on JVM based enterprise applications, backends, frontends, agile, DDD and embedded systems. AWS Cloud enthusiast.

### Author LinkedIn URL

https://www.linkedin.com/in/roamingthings/

**Comment by bls20AWS** [comment]
thank you for adding.
