### ISSUE TITLE
New pattern submission: Step Function to Step Function

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/serverless-patterns#114]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Demonstrates how to use an AWS Step Functions state machine to launch another state machine execution. The SAM template deploys 2 State Machines, where invoking the "Parent" State Machine executes a "Child" State Machine. The AWS SAM template deploys the resources and the IAM permissions required to run the application. Resources include the 2 State Machines, with CloudWatch Log Groups.

## Deployment commands
`sam deploy --guided`

## Author bio 
Name: Shehryar Abbasi
Photo URL: https://phonetool.amazon.com/users/shehryaa
Twitter handle: n/a
Description (up to 255 chars): Senior DevOps Cloud Architect at AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/sfn-sfn.
