### ISSUE TITLE
Amazon API Gateway with IAM authorization

### ISSUE THREAD

**Issue by aaronkerr** [aws-samples/serverless-patterns#1145]
New pattern for Serverlessland.com. Details in JSON file:
[websocketapi-iam-pattern.json.zip](https://github.com/aws-samples/serverless-patterns/files/11010700/websocketapi-iam-pattern.json.zip)

**Comment by jbesw** [comment]
Please submit using the issue template so we can test and merge: https://github.com/aws-samples/serverless-patterns/issues/new?assignees=jbesw&labels=&template=new-serverless-pattern-submission.md&title=New+pattern+submission.
