### ISSUE TITLE
[New repo]: Alphafold2 on AWS

### ISSUE THREAD

**Issue by wttat** [aws-samples/serverless-patterns#1146]
### Description

We first designed an API+HPC-based task scheduling logic, with Amazon Lambda as the serverless backend, processing user-submitted task requests and decoupling them through the Amazon SQS message queue service; then the task requests were submitted to Amazon Batch to invoke GPU computation instances, and the Alphafold2 algorithm was analyzed The source code structure is analyzed and optimized into a container image format usable by Amazon Batch and stored in the Amazon ECR hosted container repository; the protein database files used by the Alphafold2 algorithm are located in the Amazon Fsx for Lustre high-performance distributed file system; the user-submitted task process information is stored using Amazon Dynamodb as the NoSQL database storage; all input amino acid sequence files and output protein structure prediction files are stored using Amazon S3 object storage; algorithm scientists can use NICE DCV-based high-performance remote desktop to mount S3 directory via goofys protocol to visualize and analyze directly on the cloud The protein structure prediction files generated by Alphafold2. Finally, for the above deployment process, the infrastructure-as-code is realized through AWS CDK packaging, which is convenient for customers to deploy with one click.

### language

English

### runtime

nodejs

### Level

400

### Type

Examples

### Use case

Performance

### Primary image

https://github.com/wttat/af2-batch-cdk/blob/main/architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

one click construction of a highly available protein structure prediction platform on AWS

### Repo URL

https://github.com/wttat/af2-batch-cdk

**Comment by bls20AWS** [comment]
merged. Thank-you for contributing
