### ISSUE TITLE
[New repo]: AWS Athena Auto Update Index

### ISSUE THREAD

**Issue by daknhh** [aws-samples/serverless-patterns#1151]
### Description

In this CDK project are all the resources that updated glue indexes for Athena Tables automated. You can find more information about this solution at this [blogpost](https://globaldatanet.com/tech-blog/serverless-querying-and-evaluating-of-logs-using-athena-part-2). 

### language

English

### runtime

Typescript

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://globaldatanet.com/images/cms/seo/b94fb2a9a881bdaa8a454a071c0fe90351a71cc6-1280x1600.jpg

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Automate partition parameters updates for Glue tables

### Repo URL

https://github.com/daknhh/cdk-glue-autoupdate

### Additional resources

https://globaldatanet.com/tech-blog/serverless-querying-and-evaluating-of-logs-using-athena-part-2

### Author Name

David Krohn

### Author Image URL

https://globaldatanet.com/images/cms/421ccde235a8880427bf6a956a9c0637533c407d-1000x1000.webp

### Author Bio

Hi, I am David, a Cloud enthusiast, focusing on building solutions on AWS. As the cloud evolves every day, I continue to educate myself. I am a strong believer in continuing education and love to learn something new every day. My specialities are Cloud Automation, Infrastructure as Code, Continuous Delivery, microservices and Cloud Security on AWS. In gratitude for contributing to the AWS Community - AWS nominated me in 2020 to be an AWS Community Builder and APN Ambassador.

### Author Twitter handle

https://twitter.com/DAKNHH

### Author LinkedIn URL

https://www.linkedin.com/in/daknhh/

**Comment by bls20AWS** [comment]
merged. Thanks for contributing to the repo collection
