### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by vaidehip86** [aws-samples/serverless-patterns#1165]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
This pattern deploys a REST API Gateway with an integration of the AWS type to access Kinesis.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-kinesis.html
- Framework: currently, we support SAM or CDK.
SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
I'm a Solutions Architect at Amazon Web Services based in Dallas,TX. I'm a serverless enthusiast, I like to build and architect serverless applications.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/1164

**Comment by vaidehip86** [comment]
Hi, Im not seeing any review update on my pull request

**Comment by jbesw** [comment]
Sorry, we are backed up currently but will aim to get this tested/merged shortly. @singledigit is working on this one.
