### ISSUE TITLE
New pattern submission - s3-object-lambda

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#117]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Amazon S3 with S3 Object Lambda

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## YouTube videoId (optional e.g. "VI79XQW4dIM")
n/a

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
S3 via S3 Object Lambda Access Point to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The SAM template deploys a Lambda function, an S3 bucket, an S3 Access Point, and an S3 Object Lambda Access Point. This application uses S3 Object Lambda to return a thumbnail version of an image in S3. The Lambda function execution role has CRUD access to the S3 bucket and s3-object-lambda:WriteGetObjectResponse.

## Deployment commands
sam deploy --guided

## GitHub PR for template: 
#116 

## Payload example (e.g. Lambda event payload from source service).
No sample payload is required, two example images are available.

## Additional resources (optional: link and anchor text, up to 5 resources)
* [Introducing Amazon S3 Object Lambda – Use Your Code to Process Data as It Is Being Retrieved from S3](https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/)
* [Transforming objects with S3 Object Lambda](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transforming-objects.html)
* [S3 Object Lambda pricing](https://aws.amazon.com/s3/pricing/)

## Author bio 
Name: Greg Davis
Photo URL/LinkedIn: https://www.linkedin.com/in/gregtx/
Twitter handle: n/a
Description (up to 255 chars): I am a Senior Solutions Architect, AWS Cloud Architect, Full-Stack Developer, Database Engineer, Data Integration Architect, and Serverless Enthusiast.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/s3-object-lambda.
