### ISSUE TITLE
New pattern submission: CDK version of EventBridge to Lambda

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/serverless-patterns#118]
## Description
Create an EventBridge Rule which invokes a Lambda Function, written in CDK

## Language
Python

## Framework
 CDK

## Services from/to
 EventBridge to Lambda

## Description
CDK code describes the EventBridge Rule and the Lambda Function, along with the minimal required IAM permissions.
The EventBridge rule filters the events based upon the criteria in the `event_pattern`. When matching events are sent to EventBridge that trigger the rule, they are delivered as a JSON event payload to the Lambda function.

## Deployment commands
cdk deploy

## GitHub PR for template:  
https://github.com/aws-samples/serverless-patterns/pull/119

## Payload example.
```
{
    "version": "0",
    "id": "12345678-12a3-01b2-a1b2-123456789012",
    "detail-type": "transaction",
    "source": "cdk.myApp",
    "account": "123456789012",
    "time": "2021-09-21T19:24:45Z",
    "region": "us-west-2",
    "resources": [],
    "detail": {}
}
```
### Testing
`aws events put-events --entries file://event.json`

## Author bio 
Name: Shehryar Abbasi
Photo URL: https://phonetool.amazon.com/users/shehryaa
LinkedIn: https://www.linkedin.com/in/shehryarabbasi
Description (up to 255 chars): Shehryar is a Senior DevOps Cloud Architect at AWS based in Chicago.

**Comment by ShehryarAbbasi** [comment]
added PR link

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-lambda-cdk.
