### ISSUE TITLE
[New repo]: Serverless Metadata Enrichment Solution

### ISSUE THREAD

**Issue by deeptichugh28** [aws-samples/serverless-patterns#1192]
### Description

Metadata Enrichment is a key exercise for Media personals. This sample project will help news agency/channels to automate metadata enrichment. There are thousands of media assets coming every day to media agencies from different sources like photographers, social media, events and when these assets come to media firms, team managers have to manually categorize, label and position these images in respective locations for easy access.

Serverless solution designed to automate the cumbersome process of asset tagging.It consists of major 3 components
1) React Application to upload/view images
2) Serverless  Workflow that will be triggered whenever an S3 bucket receives an image 
3) Search Component

### language

English

### runtime

Node Js

### Level

300

### Type

Application

### Use case

Interactive workload

### Primary image

https://github.com/nittysharma/metdata-enrichment/blob/236f06f5e08cf469016e6a0f2d3b76cbf7bb0fad/MetadataEnrichment-Architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Metadata Enrichment Solution

### Repo URL

gh repo clone nittysharma/metdata-enrichment

### Additional resources

[cdk_22MB.zip](https://github.com/aws-samples/serverless-patterns/files/11124021/cdk_22MB.zip)
[Steps to setup project.pdf](https://github.com/aws-samples/serverless-patterns/files/11124035/Steps.to.setup.project.pdf)
[Metadata Enrichment - Serverless Capstone Project.docx](https://github.com/aws-samples/serverless-patterns/files/11124039/Metadata.Enrichment.-.Serverless.Capstone.Project.docx)

### Author Name

Ananthan Rudran, Deepti Chugh, Nitin Sharma

**Comment by deeptichugh28** [comment]
Hi Team, Please review and let us know if there is something required from our side.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/repos/meta-enrichment.
