### ISSUE TITLE
New pattern submission - apigw-http-api-lambda

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#12]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates an Amazon API Gateway HTTP API and an AWS Lambda function.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Node.js

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

Amazon API Gateway HTTP API to AWS Lambda to Amazon CloudWatch Logs

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern deploys an Amazon API Gateway HTTP API with a default route and basic CORS configuration. The default route is integrated with an AWS Lambda function written in Node.js. The function logs the incoming API event (v2) and context object to an Amazon CloudWatch Logs log group and returns basic information about the event to the caller.  The function execution role only requires AWSLambdaBasicExecutionRole.  Only the HTTP API can invoke the function.

## Deployment commands

- sam deploy -guided
- AppName: apigw-http-api-lambda

## GitHub PR for template: 

[#8](https://github.com/aws-samples/serverless-patterns/pull/8)

## Payload example (e.g. Lambda event payload from source service).

[HTTP API v2 event](https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/nodejs-apig/event-v2.json)

## Additional resources (optional: link and anchor text, up to 5 resources)

See documentation links in README.md

## Author bio 
Name: Greg Davis
Photo URL: [http://gregdavis.me](http://gregdavis.me) or [image](https://media-exp1.licdn.com/dms/image/C4E03AQFl1vcqCzlaYw/profile-displayphoto-shrink_200_200/0/1598784569935?e=1622678400&v=beta&t=VfoG-axGTOQj-ifnqbrPncUlxAZecx6Yi1osGliZeTY)
Twitter handle: n/a
Description (up to 255 chars): I am a Senior Solutions Architect, AWS Cloud Architect, Full-Stack Developer, Database Engineer, Data Integration Architect, and Serverless Enthusiast.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-lambda.
