### ISSUE TITLE
New pattern submission: CDK version of Lambda to DynamoDB

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#120]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a Lambda Function that executes a `put` item to DynamoDB when called, written in CDK.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

TypeScript

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

Lambda to DynamoDB

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

CDK code describes the Lambda function and DynamoDB table with permissions granted for Lambda to write to DynamoDB using the in-built `grantWriteData` property. This is the CDK implementation of the [lambda-dynamodb](https://github.com/aws-samples/serverless-patterns/tree/main/lambda-dynamodb) example. The function code and the tests remain the same from the SAM version.

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#121

## Payload example (e.g. Lambda event payload from source service).

```json
{ 
    "Metadata": "Hello"
}
```

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn: https://www.linkedin.com/in/glenn-chia-291344142
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks for this contribution! This is now live at https://serverlessland.com/patterns/lambda-dynamodb-cdk.

**Comment by GlennChia** [comment]
@jbesw Thanks for maintaining this repo! It was fun studying existing patterns and adapting the best practices to new examples! I noticed at the live link that the linkedin URL has extra stuff appended at the front. I get a the following when I copy the link address `https://www.linkedin.com/in/https://www.linkedin.com/in/glenn-chia-291344142/` where `https://www.linkedin.com/in` is duplicated. Is there a way to amend it? Thanks! I really appreciate the good work you are doing in this repo :)

**Comment by jbesw** [comment]
Thanks, Glenn! Sorry about that - I've fixed the typo and it should be correct now.
