### ISSUE TITLE
New serverless pattern - fanout-pattern-using-sns-sqs-cdk-dotnet

### ISSUE THREAD

**Issue by vedhait2004** [aws-samples/serverless-patterns#1215]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works. - Create SNS-SQS based fanout pattern using cdk and dotnet. This application will pick configuration based on appSettings.json file, adds 'n' number of queues and subscription filters based on message attribute or message body. 
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK. - CDK, dotnet (c#)
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio. - Cloud Application Architect at AWS

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
merged will go live this week
