### ISSUE TITLE
New pattern submission - lambda-sns-sms-cdk Python

### ISSUE THREAD

**Issue by ianlarson** [aws-samples/serverless-patterns#122]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create CDK version of the Lambda-SNS-sms pattern

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python for CDK - NodeJS for lambda

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Lambda to SNS-sms

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Create CDK version of the Lambda-sns-sms pattern

## Deployment commands
Included in README

## GitHub PR for template: 
In progress

## Payload example (e.g. Lambda event payload from source service).
None

## Author bio 
Name: Ian Larson
Photo URL: https://phonetool.amazon.com/users/illarso
Description (up to 255 chars):
Ian is a Sr. Cloud Infrastructure Architect with AWS.  When he's not building cloud solutions with AWS customers, he can be found on his bike exploring the roads less traveled.

**Comment by ianlarson** [comment]
PR #123 submitted for review

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-sns-sms-cdk.
