### ISSUE TITLE
New pattern submission: EventBridge Scheduler to start association once

### ISSUE THREAD

**Issue by cswing-chan** [aws-samples/serverless-patterns#1239]
## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/1238

**Comment by jlosaws** [comment]
@cswing-chan - you linked the SAM PR. Your issue should link to #1238

**Comment by cswing-chan** [comment]
@jlosaws , corrected the PR link. Thanks.

**Comment by bls20AWS** [comment]
Merged, will go like this week.
