### ISSUE TITLE
[New repo]: Optimizing AWS Lambda extensions in C# and Rust

### ISSUE THREAD

**Issue by serjkazhura** [aws-samples/serverless-patterns#1242]
### Description

How to measure the impact an extension has on the function performance using key performance metrics on an dashboard.

The focus is on Lambda extensions written in [C#](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) and [Rust](https://en.wikipedia.org/wiki/Rust_(programming_language)). It shows the benefits of choosing to write Lambda extensions in Rust. Also, it explains how you can optimize a Lambda extension written in C# to deliver three times better performance. The [solution](https://github.com/aws-samples/lambda-extension-optimization) can be converted to the programming languages of your choice.

### language

English

### runtime

.NET, Rust

### Level

400

### Type

Examples

### Use case

Performance

### Primary image

https://github.com/aws-samples/lambda-extension-optimization/blob/main/assets/ec-extension.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Optimizing AWS Lambda extensions in C# and Rust

### Repo URL

https://github.com/aws-samples/lambda-extension-optimization

### Additional resources

Blog - https://aws-preview.aka.amazon.com/blogs/compute/optimizing-aws-lambda-extensions-in-c-and-rust/

### Author Name

Siarhei Kazhura

### Author Image URL

https://avatars.githubusercontent.com/u/17185947?s=400&u=5c4500ef4b773cfa4cde4e5ef02922d54984bef1&v=4

### Author Bio

AWS Senior Specialist Solutions Architect, Serverless

### Author LinkedIn URL

https://www.linkedin.com/in/%F0%9F%87%A8%F0%9F%87%A6-sergey-k-a121b028/

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/lambda-extension-optimization.
