### ISSUE TITLE
New pattern submission: CDK version of EventBridge to CloudWatch Logs

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/serverless-patterns#125]
## Description 
User CDK to create an EventBridge Rule that sends events to CloudWatch Logs 

## Language
Python

## Framework
CDK

## Services from/to
EventBridge to CloudWatch Logs

## Description
CDK code describes the EventBridge Rule and a CloudWatch Logs Group, along with the minimal required IAM permissions.
The EventBridge rule filters the events based upon the criteria in the `event_pattern`. When matching events are sent to EventBridge that trigger the rule, they are delivered to the CloudWatch Logs Group.

## Deployment commands
`cdk deploy`

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/128

## Payload example 
```json
{
    "version": "0",
    "id": "1a1123ab-ab1c-1abc1-1abc-a111abcd12345",
    "detail-type": "message",
    "source": "my-cdk-application",
    "account": "123456789012",
    "time": "2021-09-27T20:14:09Z",
    "region": "us-west-2",
    "resources": [],
    "detail": {
        "message": "Hello CDK world!"
    }
}
```

### Testing
`aws events put-events --entries file://event.json`

## Author bio 
Photo URL: https://phonetool.amazon.com/users/shehryaa
LinkedIn: https://www.linkedin.com/in/shehryarabbasi
Description (up to 255 chars): Shehryar is a Senior DevOps Cloud Architect at AWS based in Chicago.

**Comment by ShehryarAbbasi** [comment]
adds PR link

**Comment by jbesw** [comment]
Thanks for your contribution! This is live at https://serverlessland.com/patterns/eventbridge-cloudwatch-cdk.
