### ISSUE TITLE
[serverless-django]: https://github.com/aws-hebrew-book/serverless-django

### ISSUE THREAD

**Issue by aws-hebrew-book** [aws-samples/serverless-patterns#1257]
### Description

This repository contains a Python Django application designed to run seamlessly inside an AWS Lambda environment, leveraging the AWS Lambda Adapter extension. The application is built to efficiently handle Serverless workloads and connect to a PostgreSQL database, providing a scalable, cost-effective, and high-performance solution for modern web applications. By using the AWS Lambda Adapter, the Django app can utilize the event-driven nature of Lambda while maintaining its traditional web application structure.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://s3.amazonaws.com/sharatless.cloud/django-project-logo.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Harnessing Lambda Adapter Extension: Django-Powered Serverless Web App with PostgreSQL Integration

### Repo URL

https://github.com/aws-hebrew-book/serverless-django

### Author Name

Efi Merdler-Kravitz

### Author Image URL

https://s3.amazonaws.com/sharatless.cloud/efi-logo.jpg

### Author Bio

AWS Serverless Hero with 15 years of experience in building and leading R&D teams and developing products from scratch and a comprehensive background in cloud technologies.

### Author Twitter handle

TServerless

### Author LinkedIn URL

https://www.linkedin.com/in/efime/

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/repos/serverless-django shortly.
