### ISSUE TITLE
[New repo] Serverless Asynchronous REST APIs on AWS

### ISSUE THREAD

**Issue by ziedbentahar** [aws-samples/serverless-patterns#1266]
### Description

This repository provides a practical example on building a Serverless Async Request/Response REST API. This pattern is particularly useful when clients need to perform long running tasks through HTTP requests such as text-to-speech or audio-to-text conversions, or report generation.

In this guide, we leverage the use API Gateway AWS integrations and EventBridge Pipe to build such an API which minimizes the amount of Lambda "glue code" that needs to be written. This approach simplifies the development process and allows better flexibility and scalability.

 

### language

English

### runtime

Node

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://user-images.githubusercontent.com/6813975/232885387-7cc8efed-c141-4fb5-84b1-99068f379f3e.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Building an asynchronous Request/Response REST APIs

### Repo URL

https://github.com/ziedbentahar/async-rest-api-on-aws

### Additional resources

https://dev.to/aws-builders/serverless-asynchronous-rest-apis-on-aws-5cji

### Author Name

Zied Ben Tahar

### Author Image URL

https://serverlessland.com/assets/images/resources/contributors/Tahar.jpeg

### Author Twitter handle

https://twitter.com/wow_sig

### Author LinkedIn URL

https://www.linkedin.com/in/zied-ben-tahar-5200913/

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/repos/async-rest-api-on-aws.

**Comment by ziedbentahar** [comment]
Thanks 😃
