### ISSUE TITLE
[New repo]: Spark On AWS Lambda (SoAL)

### ISSUE THREAD

**Issue by JohnChe88** [aws-samples/serverless-patterns#1268]
### Description

Spark on AWS Lambda(SoAL) GitHub repository contains the spark runtime docker image. SoAL Framework provides a standalone or local-mode Apache Spark installation within a Docker container. Execution is facilitated by AWS Lambda working in tandem with PySpark scripts. Utilizing container-based image cache along with AWS Lambda's warm-instance features, it was noticed an overall reduction of JVM warm-up time to under 30 seconds. The SOAL Framework solution is ideal for batch and streaming workloads. Based on the benchmarking studies conducted by our team, it was observed that the framework performs well with batch payloads up to 400 MB and streaming data from Amazon MSK and Amazon Kinesis. Workload per session costs depend upon the run duration, AWS Lambda memory, and CPU usage.

### language

English

### runtime

Spark

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/aws-samples/spark-on-aws-lambda/blob/main/images/Github-diagram.jpg

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Spark Runtime for AWS Lambda-SoAL framework

### Repo URL

https://github.com/aws-samples/spark-on-aws-lambda

### Author Name

John Cherian

### Author Bio

John Cherian is spark enthusiast and exploring various options to make spark enterprise framework.

### Author LinkedIn URL

www.linkedin.com/in/ john-cherian-26810b61

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/repos/spark-on-aws-lambda shortly.
