### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by dobeerman** [aws-samples/serverless-patterns#127]
## Description
Create an API Gateway that sends events to EventBridge (+Custom domain)

## Framework 
SAM

## Service from/to
API Gateway to EventBridge

## Derscription
This pattern deploys an API Gateway HTTP API with a custom domain configuration and permissions to publish HTTP requests as an events to EventBridge.

## Deployment commands

```bash
$ sam deploy
```

## GitHub PR for template: 

#23 

## Payload example

```json
{
  "mybody": {
    "attr1": "payload could be any json",
    "attr2": [1, 2]
  }
}
```

## Testing

```bash
curl --location --request POST 'https://dev-events.example.com/apigw2eb/mysource/mydetailtype' \
--header 'Content-Type: application/json' \
--data-raw '{
    "mybody": {
        "attr1": "payload could be any json",
        "attr2": [1, 2]
    }
}'
```

## Author bio 

Name: Alexander Smirnoff
LinkedIn: https://www.linkedin.com/in/dobeerman/
Description: Senior Software Engineer at [Seven.One Entertainment Group](https://www.seven.one/) | Syndication team

**Comment by jbesw** [comment]
Thanks for the contribution! This is now published at https://serverlessland.com/patterns/apigateway-http-eventbridge-custom.
