### ISSUE TITLE
Template feedback: lambda-lambda & lambda

### ISSUE THREAD

**Issue by ljacobsson** [aws-samples/serverless-patterns#13]
* Inconsistent casing of resources. Mixed camelCase and PascalCase

**Comment by julianwood** [comment]
Thanks, amended with https://github.com/aws-samples/serverless-patterns/commit/2fb51586552113b346f279a372b84c9d79e911c7 and https://github.com/aws-samples/serverless-patterns/commit/41a2e6686bbcf13a4afbd0fc1be1f7de56d1f6a2
