### ISSUE TITLE
[New repo]: Software Security Module serverless micro-service delivered via GitOps

### ISSUE THREAD

**Issue by deltapip** [aws-samples/serverless-patterns#1300]
### Description

The Software Security Module (SSM) sample application is a simple micro-service that exposes a REST API with 3 resources: Version, Wrap, and Unwrap. The version resource allows users to obtain information about the micro-service. The wrap resource allows users to encrypt a payload. While the unwrap resource allows users to decrypt a payload. This application comes configured with components that enable developers to follow GitOps principles, e.g, the state of the application is always kept in a git repository and such repository is the application source of truth.  The motivation of this sample application is to provide an option for Kubernetes Developers that love the GitOps principles but will like to move away from managing a Kubernetes Cluster. 

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/deltapip/ssm_serverless/raw/main/diagrams/SSMServerless.jpeg

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Love GitOps principles but looking for a Serverless alternative? This sample application provides some options for you

### Repo URL

https://github.com/deltapip/ssm_serverless

### Additional resources

https://aws.amazon.com/blogs/aws/building-a-modern-ci-cd-pipeline-in-the-serverless-era-with-gitops/
https://aws.amazon.com/blogs/compute/using-github-actions-to-deploy-serverless-applications/
https://itnext.io/an-aws-lambda-serverless-journey-part-3-turn-your-devoops-into-devops-with-gitops-ee81ac7c76f2

### Author Name

David Peraza

### Author Bio

Have been working on cloud computing since 2008. Have seen the evolution of compute from Physical Hardware, Virtualization via Hypervisors, through containerization and now with serverelss. Contributed to private cloud solutions from Cisco and IBM, both proprietary and open source. Contributed to IBM KMS service and now contributing to AWS Cloud as Technical Account Manager. Enjoy solving problems that have business impact with clear goals.

**Comment by jbesw** [comment]
Thanks for the contribution! This is will be live shortly at https://serverlessland.com/repos/ssm_serverless.

**Comment by deltapip** [comment]
Thanks @jbesw
