### ISSUE TITLE
[New repo]: Serverless GraphQL API

### ISSUE THREAD

**Issue by giedri** [aws-samples/serverless-patterns#1313]
### Description

These GraphQL API examples demonstrate end-to-end implementations of a simple application using a serverless approach that includes CI/CD pipelines, automated unit and integration testing, and workload observability.
The examples include multiple implementations of the same application using a variety of development platform and infrastructure as a code approaches. The patterns here will benefit beginners as well as seasoned developers looking to improve their applications by automating routine tasks.

### language

English

### runtime

JavaScript, Pyhon

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/aws-samples/serverless-samples/blob/main/serverless-graphql-api/assets/Architecture.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Sample microservice implementation using Amazon AppSync that includes CI/CD, automated testing, and workload observability

### Repo URL

https://github.com/aws-samples/serverless-samples/tree/main/serverless-graphql-api

### Author Name

Giedrius Praspaliauskas

### Author Bio

Giedrius is a Senior Solutions Architect focusing on serverless at AWS.

### Author LinkedIn URL

https://www.linkedin.com/in/gpraspaliauskas/

**Comment by jbesw** [comment]
Thanks! This will be live shortly at https://serverlessland.com/repos/serverless-graphql-api.
