### ISSUE TITLE
[New repo]: amplify-with-terraform

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1339]
### Description

 In this workshop you will create a serverless fullstack Amplify App, backed by an Event-Driven Architecture (EDA), and deploy it all with Terraform! The application will include Storage, a Database, Authentication, and an API. You will also learn how to leverage the Amplify Client libraries, and experience the process for customizing the Amplify App. Sample data is ingested through the an Amazon S3 Bucket referenced as the Landing Zone S3 Bucket, and can be ingested from any service within or connected to the AWS cloud. This is an event-driven architecture. 

### language

English

### runtime

JavaScript

### Level

300

### Type

Workshop

### Use case

Interactive workload

### Primary image

https://github.com/salmandjing/amplify-with-terraform/blob/main/resources/aws-terraform-amplify.png

### IaC framework

Terraform

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Automating Deployment of AWS Amplify Apps with Terraform

### Repo URL

https://github.com/salmandjing/amplify-with-terraform

### Additional resources

https://catalog.workshops.aws/amplify-with-terraform/en-US

### Author Name

Kevon Mayers

### Author Image URL

https://drive.google.com/file/d/1fUFUa9p_qvsZ31vD5ctGI5eMxTGn1CnC/view?usp=sharing

### Author Bio

Kevon is a Solutions Architect on the AWS Energy & Utilities team, apart of the larger AWS Industries organization. He enjoys full-stack development, using infrastructure as code, and helping customers use technology to solve sustainability and renewable energy challenges. Fun fact, Kevon comes from a non-traditional background. Prior to working at AWS, Kevon was a Studio Manager/Music Producer/Audio Engineer working with the GRAMMYs. He also owns his own production company, where he spends his free time working with artists.

### Author LinkedIn URL

https://www.linkedin.com/in/kevonmayers/

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/repos/amplify-with-terraform shortly.
