### ISSUE TITLE
New pattern submission - AWS IoT event to Lambda 

### ISSUE THREAD

**Issue by coderade** [aws-samples/serverless-patterns#134]
## Description 

The SAM template deploys a Lambda function, an IoT thing, and the least IAM resources required to run the application.

When a IoT event is sent to a IoT topic, a Lambda will be invoked. This pattern configures a Lambda function to poll this event. The function is invoked with a payload containing the contents of the message event.

## Language: 

Javascript/YAML

## Framework 

SAM

## Services from/to 

AWS IoT to Lambda

## Deployment commands

    sam deploy --guided

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/133

## Payload example (e.g. Lambda event payload from source service).

    {
        "message": "Hello from AWS IoT console"
    }

## Author bio 

Name: Valdeci Gomes 
Photo URL: https://avatars.githubusercontent.com/u/9141708?v=4
Linkedin Profile: https://www.linkedin.com/in/valdeci/
Description (up to 255 chars): Cloud Application Architect @ AWS.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/iot-lambda.
