### ISSUE TITLE
[New repo]: Restore objects from S3 Glacier using AWS Sfn distributed map 

### ISSUE THREAD

**Issue by richardkeit** [aws-samples/serverless-patterns#1340]
### Description

Solution using direct SDK integrations to list all objects in a S3 bucket and subsequently begin the restore procedure from S3 Glacier. Once restored, next execution of the stepfunction with copy them permanently to STANDARD storage.

More detail available: https://github.com/keit-labs/restore-objects-from-glacier#considerations-on-approach 

### language

English

### runtime

Nill

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/keit-labs/restore-objects-from-glacier/raw/main/resources/stepfunction_overview.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

AWS Stepfunction distributed map to restore S3 Glacier objects

### Repo URL

https://github.com/keit-labs/restore-objects-from-glacier

### Author Name

Richard Keit

### Author Image URL

https://media.licdn.com/dms/image/D5603AQGyqSHBhMToAA/profile-displayphoto-shrink_400_400/0/1670973123324?e=1689206400&v=beta&t=6l-jtiWic6AL7A_QMF8whpIPizhsE2V31ErLpDuRH9M

### Author Bio

Staff Engineer passionate about elegancy through simplicity and well thought through solutions

### Author LinkedIn URL

www.linkedin.com/in/richard-keit

**Comment by jbesw** [comment]
Thanks! This will be live at serverlessland.com/repos/restore-objects-from-glacier shortly.
