### ISSUE TITLE
[New repo]: Monitor your SNS-based applications end-to-end with AWS X-Ray Active Tracing

### ISSUE THREAD

**Issue by lorchda** [aws-samples/serverless-patterns#1350]
### Description

With AWS X-Ray active tracing enabled for SNS, you can identify bottlenecks and monitor the health of event-driven applications by looking at segment details for SNS topics, such as resource metadata, faults, errors, and message delivery latency for each subscriber.

In this sample application, we demonstrate common use cases where AWS X-Ray active tracing enabled for SNS provides a consistent view of tracing data across AWS services in real-world scenarios. We cover two architectural patterns which allow you to gain accurate visibility of your end-to-end tracing: SNS to [Amazon Simple Queue Service (Amazon SQS)](https://aws.amazon.com/sqs/) queues and SNS topics to [Amazon Kinesis Data Firehose](https://aws.amazon.com/kinesis/) streams.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Observability

### Primary image

https://raw.githubusercontent.com/aws-samples/sns-xray-active-tracing-blog-source-code/main/images/x-ray-sns-tracing-integration-use-case-2-architecture.drawio.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

This sample application demonstrates Amazon SNS with AWS X-Ray active tracing

### Repo URL

https://github.com/aws-samples/sns-xray-active-tracing-blog-source-code

### Additional resources

- Blog post: https://aws.amazon.com/blogs/compute/monitor-amazon-sns-based-applications-end-to-end-with-aws-x-ray-active-tracing/

### Author Name

Daniel Lorch

### Author Image URL

https://avatars.githubusercontent.com/u/98748454?v=4

### Author Bio

Daniel Lorch is a Senior Consultant at Amazon Web Services based out of Switzerland. He is part of the Cloud Operations specialist team and passionate about helping customers implementing observability in their applications.

### Author LinkedIn URL

https://www.linkedin.com/in/dlorch/

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/repos/sns-xray-active-tracing-blog-source-code soon.
