### ISSUE TITLE
Bug: Broken github link - Eventbridge-pipes-msk-iam-auth-to-lambda

### ISSUE THREAD

**Issue by pputhran** [aws-samples/serverless-patterns#1355]
“Visit the [GitHub repo for this pattern](https://serverlessland.com/patterns/eventbridge-pipes-msk-iam-auth-to-lambda)” on this page is pointing to incorrect link. 

What's the best way to go about to fix this?

**Comment by jbesw** [comment]
Thanks for catching - this will be updated in the next few minutes.
