### ISSUE TITLE
[bug] aurora-serverless-ingestion-Function

### ISSUE THREAD

**Issue by ct-19** [aws-samples/serverless-patterns#1359]
On movies.csv upload the function errors with the below cloud watch log

[ERROR] Exception: Waited for Aurora Serveless but still got errorsTraceback (most recent call last):  File "/var/task/DataIngest.py", line 59, in lambda_handler    wake_aurora()  File "/var/task/DataIngest.py", line 55, in wake_aurora    raise Exception('Waited for Aurora Serveless but still got errors') | [ERROR] Exception: Waited for Aurora Serveless but still got errors Traceback (most recent call last):   File "/var/task/DataIngest.py", line 59, in lambda_handler     wake_aurora()   File "/var/task/DataIngest.py", line 55, in wake_aurora     raise Exception('Waited for Aurora Serveless but still got errors')
-- | --

verified Aurora is up and in ready state

**Comment by jbesw** [comment]
Hello - which pattern is this for?

**Comment by ct-19** [comment]
https://github.com/aws-samples/serverless-patterns/tree/main/aurora-serverless-s3-ingestion

**Comment by jbesw** [comment]
Hi @dhnomura - could you verify your pattern?

**Comment by jbesw** [comment]
Sorry for the problems. We have removed this pattern due to quality issues.
