### ISSUE TITLE
[New repo]: Serverless Web Scraper on AWS 

### ISSUE THREAD

**Issue by knight-18** [aws-samples/serverless-patterns#1363]
### Description

An application which demonstrates web scraping solution on AWS using Serverless services to schedule scraping jobs or run on-demand.It creates Amazon ECS tasks which uses docker image of an application to extract data and store in Amazon S3 bucket. The jobs can be triggered using AWS Lambda functions.

### language

English

### runtime

Nodejs

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://drive.google.com/file/d/1RliqgXg52ehu6r1OntBDCIeJnbWhwl8w/view?usp=sharing

### IaC framework

AWS Cloudformation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

An AWS Cloudformation template which deploys infrastructure to run web scraper on AWS using serverless technologies.

### Repo URL

https://github.com/knight-18/sample-web-scraper

### Author Name

Sameer Shrivastava

### Author Image URL

https://drive.google.com/file/d/1FbzHKXsEtyhHnWzK66PHcdEIrVIbM09r/view?usp=sharing

### Author Bio

Solutions Architect @ AWS India

### Author LinkedIn URL

https://www.linkedin.com/in/sameer-shrivastava/

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/repos/sample-web-scraper.
