### ISSUE TITLE
[New repo]: DALL-E Image Generator Application

### ISSUE THREAD

**Issue by moitrasayan007** [aws-samples/serverless-patterns#1369]
### Description

This application takes a text prompt from the user and generates an image based on the input using the DALL-E AI model. It uses a React front-end application to take user inputs and an AWS Lambda function to generate the image. The generated image is stored in an S3 bucket and a pre-signed URL is provided to the user for viewing the image. The application also saves image metadata, including the URL and the text prompt, in a DynamoDB table.

This project is a simple image generator using the OpenAI DALL-E API. It's composed of a React frontend and a Python AWS Lambda backend.

### language

English

### runtime

Python

### Level

400

### Type

Application

### Use case

Interactive workload

### Primary image

https://github.com/moitrasayan007/dall-e-aws-serverless/blob/master/dall-e.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

DALL-E Image Generator Application

### Repo URL

https://github.com/moitrasayan007/dall-e-aws-serverless

### Additional resources

https://openai.com/research/dall-e
https://aws.amazon.com/lambda/

### Author Name

Sayan Moitra

### Author Image URL

https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-pipes-dynamodbstream-sns/smoitra.png

### Author Bio

Sayan is a Solutions Architect working with Amazon Web Services

### Author LinkedIn URL

https://www.linkedin.com/in/sayanmoitra/

**Comment by jbesw** [comment]
We are getting a 404 on this repo. Is this URL correct?

**Comment by moitrasayan007** [comment]
> We are getting a 404 on this repo. Is this URL correct?

My apologies, I set the repo to private; I have changed the visibility to public now. Please check and let me know.

**Comment by moitrasayan007** [comment]
Hi @jbesw , Can you please check if the repo is visible?

**Comment by bls20AWS** [comment]
all good now @moitrasayan007  thanks.

**Comment by moitrasayan007** [comment]
Hi @bls20AWS , looks like the repo is not yet published on the serverlessland repo page.
