### ISSUE TITLE
[New repo]: Language translator using secure synchronous state-machine

### ISSUE THREAD

**Issue by AvinandanBandyopadhyay** [aws-samples/serverless-patterns#1381]
### Description

Building a secure instantaneous language translator using AWS serverless services

### language

English

### runtime

JavaScript

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/AvinandanBandyopadhyay/language_translator/blob/main/Architecture.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [X] Amazon Transcribe
- [X] Amazon Translate

### Description headline

Building a secure instantaneous language translator using AWS serverless services

### Repo URL

https://github.com/AvinandanBandyopadhyay/language_translator

### Author Name

AVINANDAN BANDYOPADHYAY

### Author Image URL

https://github.com/AvinandanBandyopadhyay/language_translator/blob/main/Profile_1.jpg

### Author Bio

Solutions Architect AWS India

### Author LinkedIn URL

https://www.linkedin.com/in/avinandan-bandyopadhyay-8592ab29/

**Comment by jbesw** [comment]
This will be live at https://serverlessland.com/repos/new-repo-language-translator-using-secure-synchronous-state-machine shortly.
