### ISSUE TITLE
Amazon OpenSearch Service name is missing

### ISSUE THREAD

**Issue by rupeshtiwari** [aws-samples/serverless-patterns#1385]
Hi , in the services list amazon open search service name is missing. Kindly add! 
<img width="363" alt="image" src="https://github.com/aws-samples/serverless-patterns/assets/330383/82205648-71a4-412b-b028-84419879fbf1">

**Comment by jbesw** [comment]
Hi - OpenSearch is present in the list on the patterns page. https://serverlessland.com/patterns?services=opensearch

![image](https://github.com/aws-samples/serverless-patterns/assets/24660852/40cb4ce6-b4f3-4226-ba2d-153dc4a7b585)
