### ISSUE TITLE
[New repo]: serverless-website-analytics

### ISSUE THREAD

**Issue by rehanvdm** [aws-samples/serverless-patterns#1398]
### Description

A CDK construct that consists of a serverless backend, frontend and client side code to track website analytics. Involves AWS Lambda, Lambda Function URL, CloudFront reverse proxying, Athena, S3. Build in TS using tRPC between the backend and frontend.

### language

English

### runtime

TypeScript

### Level

300

### Type

Application

### Use case

Interactive workload

### Primary image

https://github.com/rehanvdm/serverless-website-analytics/blob/main/docs%2Fimgs%2Fserverless-website-analytics.drawio.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

A CDK construct that consists of a serverless backend, frontend and client side code to track website analytics

### Repo URL

https://github.com/rehanvdm/serverless-website-analytics

### Author Name

Rehan van der Merwe

### Author Twitter handle

https://twitter.com/der_rehan

### Author LinkedIn URL

https://www.linkedin.com/in/rehan-van-der-merwe-600b40172/

**Comment by jbesw** [comment]
Thanks - this will be live shortly at https://serverlessland.com/repos/new-repo-serverless-website-analytics.
