### ISSUE TITLE
New pattern submission: CDK version of EventBridge to SQS

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/serverless-patterns#140]
## Description
Create an EventBridge Rule to send events to an SQS Queue

## Language
Python

## Framework
CDK

## Services from/to
EventBridge to SQS

## Description
CDK code describes a Custom EventBridge Bus, an EventBridge Rule, and an SQS Queue, along with the minimal required SQS Access Policy permissions which are automatically added by CDK: . The EventBridge Rule filters the events based upon the criteria in the provided example code's `rule.add_event_pattern` section. When matching events are sent to the Custom EventBridge Bus that trigger this Rule, they are delivered to the SQS Queue.

## Deployment commands
`cdk deploy`

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/141

## Payload example
{
    "version": "0",
    "id": "1a1123ab-ab1c-1abc1-1abc-a111abcd12345",
    "detail-type": "message-for-queue",
    "source": "my-cdk-application",
    "account": "123456789012",
    "time": "2021-09-27T20:14:09Z",
    "region": "us-west-2",
    "resources": [],
    "detail": {
        "message": "Hello CDK world!"
    }
}

## Author bio 
Name: Shehryar Abbasi
Photo URL: https://phonetool.amazon.com/users/shehryaa
LinkedIn: https://www.linkedin.com/in/shehryarabbasi
Description (up to 255 chars): Shehryar is a Senior DevOps Cloud Architect at AWS based in Chicago.

**Comment by jbesw** [comment]
Thanks for the submission - this is now live at https://serverlessland.com/patterns/eventbridge-sqs-cdk.
