### ISSUE TITLE
[New repo]: https://github.com/cloudandthings/terraform-aws-clickops-notifier

### ISSUE THREAD

**Issue by phzietsman** [aws-samples/serverless-patterns#1406]
### Description

The project uses CloudTrail events, on either an account or organization level to determine and notify when users are making configuration changes via the AWS Console.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Observability

### Primary image

None

### IaC framework

Terraform

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

ClickOps Notifier 

### Repo URL

https://github.com/cloudandthings/terraform-aws-clickops-notifier

**Comment by jbesw** [comment]
Hi - can you provide us with some bio information to list with this repo? We can't list repos without any author information.
