### ISSUE TITLE
[New repo]: Simulating IoT data into Timestream

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1411]
### Description

This blog will teach you how to create a cloud formation IoT simulator, send IoT data into AWS and use that data for your own visualizations. In 30 minutes you will
 learn how to use a [CloudFormation](https://docs.aws.amazon.com/cloudformation/index.html) template to create IoT data simulator. You will then 
generate and capture that time series data into [AWS IoT Core](https://docs.aws.amazon.com/iot/index.html). Finally,
 you will send that data into [Amazon Timestream](https://docs.aws.amazon.com/timestream/index.html) for your custom visualization. 

### language

English

### runtime

AWS

### Level

200

### Type

Workshop

### Use case

Interactive workload

### Primary image

https://github.com/salmandjing/IotDataToTimestream/blob/main/IotToTimestream.png

### IaC framework

Cloud Formation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [X] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Simulating IoT data into AWS IoT Core and AWS Timestream

### Repo URL

https://github.com/salmandjing/IotDataToTimestream

### Additional resources

https://docs.aws.amazon.com/iot/index.html,https://docs.aws.amazon.com/timestream/index.html

### Author Name

Salman Djingueinabaye

### Author Image URL

https://drive.google.com/file/d/1sbydKhoJ4ZXouinrQ8OeEuxP3rHHQMUX/view?usp=sharing

### Author Bio

Salman is an AWS Energy Solution Architect based in Miami. 

### Author LinkedIn URL

https://www.linkedin.com/in/salman-djingueinabaye-41643a1ba/

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/repos/iot-data-to-timestream shortly.
