### ISSUE TITLE
 aws-serverless-multithreaded-concurrency

### ISSUE THREAD

**Issue by brtorbic** [aws-samples/serverless-patterns#1425]
### Description

The code in this repository can be used to understand how to implement multithreaded concurrency in [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/welcome.html) by leveraging the [concurrent.futures](https://docs.python.org/3.10/library/concurrent.futures.html) Python module which is available in Python version 3.2, and later.

Multithreaded concurrency is a technique that allows for more than one thread to be executed at the same time, with each thread progressing as CPU cycles become available. The rapid switching that occurs between threads as CPU cycles become available enables the threads to execute concurrently. This concurrent execution technique can be applied to I/O bound tasks for performance efficiency and cost optimization in AWS Lambda.

The examples will utilize AWS Lambda functions running on Python version 3.10 with a single-core ARM processor and 128MB of RAM. The AWS Lambda function examples will utilize the [AWS Software Development Kit (SDK) for Python (Boto3)](https://aws.amazon.com/sdk-for-python/) to make Application Programming Interface (API) calls to the [Amazon Elastic Compute Cloud (EC2)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html) service and create [Amazon Elastic Block Store (EBS)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html) volumes. The AWS Lambda function examples will be deployed as a single AWS Lambda application using [AWS Serverless Application Model (SAM](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html)).

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Performance

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Python multithreaded concurrency in AWS Lambda

### Author Name

Brian Torbich

### Author Bio

Brian Torbich is a Solutions Architect at Amazon Web Services.

**Comment by jbesw** [comment]
Hello - the repo provided must be publicly accessible, along with the image. Please do not share internal AWS links here.
