### ISSUE TITLE
Create Multi repo pipeline for AWS SAM using CDK

### ISSUE THREAD

**Issue by masudur-rahman-niloy** [aws-samples/serverless-patterns#1428]
### Description

This project creates CodeCommit repos for SAM applications and a CodePipeline for them. When we push to a repo, the pipeline creates/updates new stacks. Push to every branch creates new Cloudformation stacks. Which makes development in new features easier. 

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://drive.google.com/file/d/1uTuFWWX4-pvTFSPh_37RfaBE-aRadN-0/view

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

CDK app to create Multi Repo CodePipeline for AWS SAM 

### Repo URL

https://github.com/masudur-rahman-niloy/multirepo-pipeline-for-sam

### Author Name

Md Masudur Rahman Niloy

### Author Image URL

https://drive.google.com/file/d/1Dodr56ePLbQbfzV40egJWiZM4HrpjvSW/view

### Author Bio

I'm Md Masudur Rahman Niloy. 2x AWS Certified. Working in ShadhinLab LLC as Lead Solutions Engineer(Cloud). My current projects include developing serverless applications using SAM and Python.

### Author LinkedIn URL

https://www.linkedin.com/in/niloy369/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/create-multi-repo-pipeline-for-aws-sam-using-cdk shortly.

**Comment by masudur-rahman-niloy** [comment]
@jbesw thanks
