### ISSUE TITLE
[New repo]: Database schema migrations with Custom Resources and CDK

### ISSUE THREAD

**Issue by ziedbentahar** [aws-samples/serverless-patterns#1430]
### Description

This repository provides an example of using custom resources to handle schema migrations on an Aurora Serverless V2 database. The custom resource executes schema changes during the stack deployment, ensuring that any new changes are automatically applied to the database when necessary.

### language

English

### runtime

NodeJs

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://user-images.githubusercontent.com/6813975/245704087-c39e19fd-e600-4dc0-a027-47ac358f098c.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Learn how to use CDK and Custom resources to perform database schema migrations on an Aurora Serverless V2 Database

### Repo URL

https://github.com/ziedbentahar/db-schema-migration-with-custom-resources

### Additional resources

https://dev.to/aws-builders/database-schema-migrations-on-aws-with-custom-resources-and-cdk-3e9d

### Author Name

Zied Ben Tahar

### Author Image URL

https://serverlessland.com/assets/images/resources/contributors/zied-ben-tahar.jpg

### Author Twitter handle

wow_sig

### Author LinkedIn URL

https://www.linkedin.com/in/zied-ben-tahar-5200913/

**Comment by jbesw** [comment]
Published at https://serverlessland.com/repos/db-schema-migration-with-custom-resources
