### ISSUE TITLE
New pattern submission - SNS to SQS CDK

### ISSUE THREAD

**Issue by ianlarson** [aws-samples/serverless-patterns#146]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
CDK version of SNS to SQS Serverless pattern

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK - Python

## Services from/to (e.g. "Lambda to EventBridge)
SNS to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Work in progress 

## Payload example (e.g. Lambda event payload from source service).
TBD

## Additional resources (optional: link and anchor text, up to 5 resources)
TBD

## Author bio 
Name: Ian Larson
Photo URL: https://phonetool.amazon.com/users/illarso
Twitter handle:
Description (up to 255 chars): Ian is a Sr. Cloud Infrastructure Architect with AWS. When he's not building cloud solutions with AWS customers, he can be found on his bike exploring the roads less traveled.

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/sns-sqs-cdk.
