### ISSUE TITLE
[New repo]: 

### ISSUE THREAD

**Issue by ajayv-AWS** [aws-samples/serverless-patterns#1497]
### Description

Serverless pattern to setup SNS-LAMBDA-Slack/Teams integration using terraform.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/ajayv-AWS/Img/blob/870961eb05a4732ea2ee6a36af8ad1fd6a7ef206/SNS-teams-slack.drawio.png?raw=true

### IaC framework

Terraform

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

SNS-Slack-Teams integration

### Repo URL

https://github.com/ajayv-AWS/serverless_standalone/tree/main/sns-slack-teams-terraform-python

### Author Name

Ajay Vasant

### Author Image URL

https://drive.google.com/file/d/1Pgj-tshLgNfFwvHP-uBWuTLFVeANirFB/view?usp=drivesdk

### Author Bio

I am a cloud computing enthusiast working as Cloud Support Engineer at Amazon Web Services.

### Author LinkedIn URL

https://www.linkedin.com/in/ajay-vasant-545155ab

**Comment by ajayv-AWS** [comment]
New branch

https://github.com/ajayv-AWS/serverless-patterns/tree/AWS-feature-SNS-Slack-serverless-py

**Comment by jbesw** [comment]
This is missing a useful README and still references Serverless Patterns. The Repos Collection is intended to host high quality stand-alone repos with documentation.

**Comment by ajayv-AWS** [comment]
Created a new repo with just a single folder containing the code for use case. It contains the readme file to get started and successfully deploy the code. Please let me know if anything specific needs to be added to README file.

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/sns-slack-teams-terraform-python soon.
