### ISSUE TITLE
[New repo]: AWS Firewall Factory

### ISSUE THREAD

**Issue by daknhh** [aws-samples/serverless-patterns#1498]
### Description

AWS Web Application Firewalls (WAFs) protect web applications and APIs from typical attacks from the Internet that can compromise security and availability, and put undue strain on servers and resources. The AWS WAF provides prebuilt security rules that help control bot traffic and block attack patterns. You can also create your own rules based on your own requirements. In simple scenarios and for smaller applications, this is very easy to implement on an individual basis. However, in larger environments with tens or even hundreds of applications, it is advisable to aim for central governance and automation. This simple solution helps you deploy, update and stage your Web Application Firewalls while managing them centrally via AWS Firewall Manager.

### language

English

### runtime

Typescript

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://drive.google.com/file/d/14zZAz_m1Q9iwmWQSi-W8BYB-nLrHE3Yy/view?usp=sharing

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

aws-firewall-factory

### Repo URL

https://github.com/globaldatanet/aws-firewall-factory

### Additional resources

https://www.youtube.com/watch?v=jrYpr0DLKfo
https://docs.google.com/file/d/1YJCfTt8ILa2R9n23fHDFLpfLhTwhB4ea/edit?filetype=mspresentation
https://globaldatanet.com/webinars/managing-aws-web-application-firewalls-at-scale
https://globaldatanet.com/webinars/aws-security-with-security-in-the-cloud

### Author Name

David Krohn

### Author Image URL

https://globaldatanet.com/images/cms/421ccde235a8880427bf6a956a9c0637533c407d-1000x1000.webp

### Author Bio

Hi, I am David, a Cloud enthusiast, focusing on building solutions on AWS. As the cloud evolves every day, I continue to educate myself. I am a strong believer in continuing education and love to learn something new every day. My specialities are Cloud Automation, Infrastructure as Code, Continuous Delivery, microservices and Cloud Security on AWS. In gratitude for contributing to the AWS Community - AWS nominated me in 2020 to be an AWS Community Builder and APN Ambassador.

### Author Twitter handle

https://twitter.com/DAKNHH

### Author LinkedIn URL

https://www.linkedin.com/in/daknhh/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/aws-firewall-factory shortly.

**Comment by daknhh** [comment]
Thanks. The picture of the repo is somehow wrong. Could we change that? Thanks

**Comment by jbesw** [comment]
Yes - this is now updated. Thanks!

**Comment by daknhh** [comment]
Could we also add the Additional resources?
