### ISSUE TITLE
New pattern submission - apigw-http-api-SQS-Lambda

### ISSUE THREAD

**Issue by isbkch** [aws-samples/serverless-patterns#15]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
AWS API Gateway HTTP APIs to Lambda Function through Amazon SQS Queue for buffering

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
NodeJs 12

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway to Lambda through SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
In this pattern, called "Queue based leveling", a serverless queue is introduced between your API Gateway and your workers -Lambda function in our case. The introduced queue acts as a buffer to alleviate spike concerns and make sure your BE application can sustain the load that is coming in by buffering all the requests and not loosing them.It also gives the benefit to your downstream consumers to process the incoming requests at their own pace.

## Deployment commands
- sam deploy --guided
- AppName: apigw-sqs-lambda

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/14

## Payload example (e.g. Lambda event payload from source service).
https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/nodejs-apig/event-v2.json

## Author bio 
Name: iLyas Bakouch
Photo URL: https://avatars.githubusercontent.com/u/216867?v=4
Twitter handle: @isbkch
Description (up to 255 chars):  Senior Solutions Architect @AWS

**Comment by jbesw** [comment]
Hi ILyas - I'm just reviewing this pattern. Can you also provide testing steps in the README in the PR?

**Comment by isbkch** [comment]
Hi @jbesw I will. Thanks

**Comment by isbkch** [comment]
@jbesw I added test steps in this PR https://github.com/aws-samples/serverless-patterns/pull/22

**Comment by jbesw** [comment]
Thanks for the contribution! This has now been merged and will be live on the site in the next couple of hours.
