### ISSUE TITLE
New pattern submission: CDK version of IoT to Lambda

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/serverless-patterns#150]
## Description
Create an IoT Rule which sends the event to a Lambda Function

## Language
Python

## Framework
CDK

## Services from/to
IoT to Lambda

## Description
Create a Lambda Function, an IoT Thing, an IoT Rule which invokes the Lambda Function with a SQL statement to filter incoming events based on a specific IoT Topic Name, and the required Lambda invocation permissions. When an IoT event is published to an IoT topic, the Lambda function is invoked by the IoT Rule, with a payload containing the contents of the message event.

## Deployment commands
`cdk deploy`

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/151

## Payload example
```json
{
    "message": "Hello from AWS IoT console"
}


## Author bio 
Name: Shehryar Abbasi
Photo URL: https://phonetool.amazon.com/users/shehryaa
LinkedIn: https://www.linkedin.com/in/shehryarabbasi
Description (up to 255 chars): Shehryar is a Senior DevOps Cloud Architect at AWS based in Chicago.

**Comment by jbesw** [comment]
Thanks for the submission - this is now live at https://serverlessland.com/patterns/iot-lambda-cdk.
