### ISSUE TITLE
[New repo]: documentdb-stream-lambda-eventbridge-cdk

### ISSUE THREAD

**Issue by MajdSoufan** [aws-samples/serverless-patterns#1500]
### Description

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for configuring and deploying a CDC Stream (Similar to DynamoDB Stream) for Amazon DocumentDB using AWS Lambda and EventBridge. The stream will processes changes and send them to an EventBridge Bus for further processing.

DocumentDBStream
![DocDbArch](https://github.com/aws-samples/serverless-patterns/assets/16642196/4c917797-98d1-4e90-9740-fabe14341382)

The following resources will be provisioned:

A Lambda Function that processes the changes from an already existing Amazon DocumentDB Database and sends them to an EventBridge Bus
An AWS CDK Custom Resource Lambda Function that enables the CDC of Amazon DocumentDB onto the stream Lambda Function
A VPC Endpoint for the AWS Lambda Service (This is crucial to enabling the Lambda Event Source Mapping off of the Amazon DocumentDB Database)
A VPC Endpoint for the AWS Secret Manager Service (This is crucial to allow the Lambda Event Source Mapping off of the Amazon DocumentDB Database)
A VPC Endpoint for the AWS EventBridge Service
An EventBridge Bus that will receive changes from the Lambda and publish them to an EventBridge Rule
An EventBridge Rule that receives the changes for the bus and publishes them to given targets for further processing
A Lambda Function that acts as a target for the EventBridge Rule and further processes the changes

### language

English

### runtime

Typescript

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://github.com/SoufanConsulting/company-images/blob/main/DocDbArch.svg

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Amazon DocumentDB Stream To EventBridge via AWS Lambda Integration

### Repo URL

https://github.com/SoufanConsulting/documentdb-stream-lambda-eventbridge-cdk

### Author Name

Majd & Mohamad Soufan

### Author Image URL

https://pbs.twimg.com/profile_images/1467593280896450562/jRZ4fMWb_400x400.jpg

### Author Bio

Mohamad is an AWS 5x Certified Cloud Enthusiast who love building solutions with focus on Serverless and Networking. (Majd's twin brother)

### Author Twitter handle

@MohamadSoufan4

### Author LinkedIn URL

/mohamad-soufan

**Comment by MajdSoufan** [comment]
@jbesw I have created a new public repo with the necessary code only. Should I create PR now?

**Comment by MajdSoufan** [comment]
@bls20AWS  & @jbesw I have the repo ready to be pushed. What are the next steps?

**Comment by jbesw** [comment]
Thanks - this will be listed at https://serverlessland.com/repos/documentdb-stream-lambda-eventbridge-cdk shortly.

**Comment by MajdSoufan** [comment]
@jbesw thank you for posting this.
One more thing, my brother and I both worked on this and I could not add another author to the repo
Here is my brother info from example-pattern.json:

`{
      "name": "Majd Soufan",
      "image": "https://pbs.twimg.com/profile_images/1467263476473090048/JmklQbC8_400x400.jpg",
      "bio": "Majd is an AWS 5x Certified Cloud Enthusiast who love building solutions with focus on Serverless and Database. (Mohamad's twin brother)",
      "linkedin": "/majd-soufan",
      "twitter": "@Majd95RF"
    }`

**Comment by jbesw** [comment]
No problem - this change will be live shortly.
