### ISSUE TITLE
[New repo]: AWS CDK Powertools CLI

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1502]
### Description

This command line interface tool automates many of the tedious tasks of building, adding to, documenting, and extending AWS CDK applications. It is an opinionated tool that integrates Well-Architected principals of cloud native software design by default.

### language

English

### runtime

CDK

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://drive.google.com/file/d/1f6nGDIy7SQvgs7xtz6WcXha5EIhbtq7R/view?usp=sharing

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

AWS CDK Powertools CLI

### Repo URL

https://github.com/aws-samples/cdk-powertools-cli

### Author Name

Sam Ward Biddle

### Author Image URL

https://drive.google.com/file/d/1Ib9y7i-PO4cqGNBE4OzB0-S9CPbTv0zx/view?usp=sharing

### Author Bio

Sam is a Solution Architect with AWS for Energy. 

### Author LinkedIn URL

https://www.linkedin.com/in/sam-biddle/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/aws-cdk-powertools-cli shortly.
