### ISSUE TITLE
[New repo]: Running Simulations on HPC Cluster

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1503]
### Description

Learn how to use a Windows HPC to run a batch of grid analysis scenarios with high computational requirements. Then you will use the Extract, Transform and load (or ETL), query and business intelligence services on AWS to analyze and visualize the simulation output. You will also learn to load data in an integrated machine learning environment to perform data wrangling, mining and plotting, preparing input for ML model development.

### language

English

### runtime

CloudFormation

### Level

400

### Type

Workshop

### Use case

Interactive workload

### Primary image

https://drive.google.com/file/d/1kZ7CIff4o5cPtd63LiSPLPlHE8swu7Tp/view?usp=sharing

### IaC framework

Cloud Formation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Running Grid Simulations with HPC on AWS

### Repo URL

https://catalog.us-east-1.prod.workshops.aws/workshops/ff8849a5-859f-424a-abf4-7b8cdfcb99b2/en-US

### Author Name

Song Zhang

### Author Image URL

https://drive.google.com/file/d/14Xpk5w-pAqiJR9zg49UgA-vTZNMBnY1M/view?usp=sharing

### Author Bio

Song Zhang is an AWS SA with AWS Energy

### Author LinkedIn URL

https://www.linkedin.com/in/szhang86/

**Comment by bls20AWS** [comment]
merged

**Comment by bls20AWS** [comment]
Added as a workshop instead of a repo

**Comment by salmandjing** [comment]
Hey where is the link to this?  I can't seem to find it

**Comment by salmandjing** [comment]
Hey, Just following up on this. Thanks
