### ISSUE TITLE
[New repo]: AI Driven Visual Inspection of Wind Turbines based on Drones Pictures

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1510]
### Description

Keeping wind turbines operational also means keeping them well maintained. One of the steps in maintenance is regular visual inspection. This  post will demonstrate how to use [Machine Learning on AWS](https://aws.amazon.com/machine-learning/) for visual inspection augmented with [serverless technologies](https://aws.amazon.com/serverless/) to build an automated process based on a custom business logic. We will employ [Amazon Rekognition Custom Labels](https://aws.amazon.com/rekognition/custom-labels-features/) to identify objects and scenes specific to your case. We also discuss important metrics regarding AI/ML-based inspection. Finally, [AWS Serverless Application Model (AWS SAM)](https://aws.amazon.com/serverless/sam/) will help us to deploy an event-driven solution that builds the business logic on top of Amazon Rekognition findings.

### language

English

### runtime

Python

### Level

300

### Type

Workshop

### Use case

Backend

### Primary image

https://drive.google.com/file/d/16T_DClYFLY0A_3eI5rf1BJmw0ZGxx1X5/view?usp=sharing

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [X] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

AI-Driven Visual Inspection of Wind Turbines Based on Drone Imaging

### Repo URL

https://github.com/aws-samples/ai-based-windturbine-inspection-blogpost/tree/main

### Additional resources

https://aws.amazon.com/blogs/industries/ai-driven-visual-inspection-wind-turbines-drone-imaging/

### Author Name

Burak Gozluklu

### Author Image URL

https://drive.google.com/file/d/1JTFy_uySQWFQssftClxLnURduzI1T8gZ/view?usp=sharing

### Author Bio

Burak is a Principal AI/ML Specialist SA at AWS. 

### Author LinkedIn URL

https://www.linkedin.com/in/burak-gozluklu-72a10a12/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/ai-driven-visual-inspection-of-wind-turbines-based-on-drones-pictures shortly.
