### ISSUE TITLE
[New repo]: 

### ISSUE THREAD

**Issue by ajayv-AWS** [aws-samples/serverless-patterns#1522]
### Description

Serverless pattern to setup SNS-LAMBDA-Slack/Teams integration using CloudFormation

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/ajayv-AWS/Img/blob/870961eb05a4732ea2ee6a36af8ad1fd6a7ef206/SNS-teams-slack.drawio.png?raw=true

### IaC framework

CloudFormation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

SNS-Slack-Teams integration using CloudFormation

### Repo URL

https://github.com/ajayv-AWS/serverless_pattern_cloudFormation

### Author Name

Ajay Vasant

### Author Image URL

https://drive.google.com/file/d/1Pgj-tshLgNfFwvHP-uBWuTLFVeANirFB/view?usp=drivesdk

### Author Bio

I am a cloud computing enthusiast working as Cloud Support Engineer at Amazon Web Services.

### Author LinkedIn URL

https://www.linkedin.com/in/ajay-vasant-545155ab

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/sns-slack-teams-cloudformation-node shortly.
