### ISSUE TITLE
[New repo]: Passwordless authentication with Amazon Cognito - FIDO2 (Webauthn, Passkeys), Magic Links, SMS OTP Step Up

### ISSUE THREAD

**Issue by ottokruse** [aws-samples/serverless-patterns#1547]
### Description

Passwordless authentication improves security, reduces friction and provides better user experience for end-users of customer facing applications. Amazon Cognito provides features to implement custom authentication flows, which can be used to expand authentication factors for your application. This solution demonstrates several patterns to support passwordless authentication and provides reference implementations for these methods:

- FIDO2: aka WebAuthn, i.e. sign in with Face, Touch, YubiKey, etc. This includes support for Passkeys.
- Magic Link Sign In: sign in with a one-time-use secret link that's emailed to you (and works across browsers).
- SMS based Step-Up auth: let an already signed-in user verify their identity again with a SMS One-Time-Password (OTP) without requiring them to type in their password.

### language

English

### runtime

NodeJS

### Level

300

### Type

Examples

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/main/drawings/fido2.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Passwordless authentication with Amazon Cognito: FIDO2 (WebAuthn, support for Passkeys), Magic Link, SMS OTP Step Up 

### Repo URL

https://github.com/aws-samples/amazon-cognito-passwordless-auth

### Author Name

Otto Kruse

### Author Image URL

https://d2908q01vomqb2.cloudfront.net/5b384ce32d8cdef02bc3a139d4cac0a22bb029e8/2023/05/16/ottokrus.jpg

### Author Bio

Otto Kruse is a Senior Solutions Developer within AWS Industries – Prototyping and Customer Engineering (PACE), a multi-disciplinary team dedicated to helping large companies utilize the potential of the AWS cloud by exploring and implementing innovative ideas. Otto focuses on application development and security.

### Author Twitter handle

ottokruse

**Comment by ottokruse** [comment]
I see the repo is already listed, but that listing isn't quite right: wrong description and wrong repo link

**Comment by jbesw** [comment]
Sorry about that - this should now be fixed.

**Comment by ottokruse** [comment]
Thanks @jbesw one thing though, the description in the search results is still off, it's still talking about Airline booking (totally different repo):

![image](https://github.com/aws-samples/serverless-patterns/assets/6275520/4fac8ce0-5876-4ea3-84a6-0bb9f3d56585)

**Comment by jbesw** [comment]
Sorry, I think this was a cached result from before but has been fixed now.
