### ISSUE TITLE
New Workshop - Implement Passwordless authentication with Amazon Cognito and WebAuthn

### ISSUE THREAD

**Issue by ottokruse** [aws-samples/serverless-patterns#1548]
Link to workshop: https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US

Description:

> In this workshop we'll walk you through adding Passwordless sign-in to your Amazon Cognito User Pool:
>
> - FIDO2: aka WebAuthn, i.e. sign with Face, Touch, YubiKey, etc. This includes support for Passkeys.
> - Magic Link Sign In: sign in with a one-time-use secret link that's emailed to you (and works across browsers).

Picture: https://static.us-east-1.prod.workshops.aws/public/7cd1df91-9ea2-4bb0-8f1a-c4ada95c9823/static/sign-in-page-screen-shot.png

Level: intermediate

Duration: 60 min

**Comment by ottokruse** [comment]
Let me know what other info you need. Thanks!

**Comment by jbesw** [comment]
This has been added and will appear on the site in the next few minutes.
