### ISSUE TITLE
[How to]: Serverless Solution to change listener priority and enable fixed response in Multi-Region Loadbalancer with logging & notification

### ISSUE THREAD

**Issue by paulkannan** [aws-samples/serverless-patterns#1570]
### Description

Implementing maintenance windows for On-premises and AWS workloads, especially across multiple regions, can be a complex task for organizations. There are several approaches being followed to address this challenge. We present a serverless solution that seamlessly implements static response mechanisms at the Application Load Balancer level deployed in various regions with monitoring and notifying mechanisms. This approach offers a straightforward and cost-effective way to notify end users during maintenance periods without relying on additional AWS resources like static websites or Lambda functions.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Observability

### Primary image

https://github.com/paulkannan/serverless-solution-enable-fixed-response-loadbalancer/blob/main/awsalb/awsalb.jpg

### IaC framework

Terraform

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Solution to enable fixed response in Loadbalancer

### Repo URL

https://github.com/paulkannan/serverless-solution-enable-fixed-response-loadbalancer

### Author Name

Paul Kannan

### Author Image URL

https://github.com/paulkannan/Cloudformation/blob/main/IMG-0484.JPG

### Author Bio

Paul is a Technical Account Manager at Amazon Web Services. He helps AWS Customers to learn about and love how serverless technologies can transform the way they build and run applications. He was an Enterprise Cloud Architect and Manager in Global Enterprises for more than 18 years before going all in on Serverless at AWS.

### Author LinkedIn URL

https://www.linkedin.com/in/paulkannan/

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/repos/serverless-solution-enable-fixed-response-loadbalancer shortly.
