### ISSUE TITLE
[New repo]: https://github.com/aws-samples/aws-lambda-function-url-secured

### ISSUE THREAD

**Issue by jeromevdl** [aws-samples/serverless-patterns#1592]
### Description

This project shows how to use CloudFront and Lambda@Edge to protect a Lambda function URL configured with the `AWS_IAM` authentication type by adding the appropriate headers to the request before it reaches the origin. It goes with the blog post "[Protecting a Lambda Function URL with Amazon CloudFront and Lambda@Edge](https://aws.amazon.com/blogs/compute/protecting-an-aws-lambda-function-url-with-amazon-cloudfront-and-lambdaedge/)"

### language

English

### runtime

Typescript

### Level

300

### Type

Examples

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/aws-lambda-function-url-secured/raw/main/assets/archi.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Protecting Lambda function URL with Lambda@edge

### Repo URL

https://github.com/aws-samples/aws-lambda-function-url-secured

### Author Name

Jerome Van Der Linden

### Author Image URL

https://avatars.githubusercontent.com/u/117538?v=4

### Author Bio

Jerome is a Solutions Architect Builder at AWS. Passionate about building stuff using the AWS services, and especially the serverless ones.

### Author Twitter handle

jeromevdl

### Author LinkedIn URL

https://www.linkedin.com/in/jeromevdl/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/aws-lambda-function-url-secured shortly.
