### ISSUE TITLE
Serverless Observability Best Practices 

### ISSUE THREAD

**Issue by poprahul** [aws-samples/serverless-patterns#1594]
### Description

Learn how to apply AWS Observability Best Practices for Lambda based Serverless applications.
https://aws-observability.github.io/observability-best-practices/guides/serverless/aws-native/lambda-based-observability.

This guide covers an opinionated best practices when using AWS Native services like CloudWatch logs, metrics, and X-Ray traces for observability.

### language

English

### runtime

Custom

### Level

200

### Type

Tips

### Use case

Observability

### Primary image

https://aws-observability.github.io/observability-best-practices/images/three-pillars.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Observability Best Practices

### Repo URL

https://github.com/aws-observability/observability-best-practices

### Author Name

Rahul Popat

### Author Image URL

https://internal-cdn.amazon.com/badgephotos.amazon.com/?Region=master&FullsizeImage=Yes&uid=poprahul

### Author Bio

Rahul is a Sr. Solutions Architect at AWS. He helps customers with all sizes, from start-ups to the world's largest enterprises, to effectively use AWS Serverless technologies. Rahul is passionate about AWS Serverless technology and has a strong application development and architecture background.

### Author LinkedIn URL

https://www.linkedin.com/in/rahulpopat/

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/repos/serverless-observability-best-practices shortly.
