### ISSUE TITLE
[New repo]: https://github.com/aws-samples/lwa-nextjs-response-streaming-example

### ISSUE THREAD

**Issue by xjiaqing** [aws-samples/serverless-patterns#1596]
### Description

This is an example of how to implement Response stream in Lambda using Lambda Web Adapter. It was referenced in this blog post: https://aws.amazon.com/cn/blogs/compute/using-response-streaming-with-aws-lambda-web-adapter-to-optimize-performance/

### language

English

### runtime

Node.js

### Level

300

### Type

Examples

### Use case

Performance

### Primary image

https://github.com/awslabs/aws-lambda-web-adapter/raw/main/docs/images/lambda-adapter-overview.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Lambda Web Adapter Response streaming Next.js example

### Repo URL

https://github.com/aws-samples/lwa-nextjs-response-streaming-example

### Author Name

Xue Jiaqing

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/repos/lwa-nextjs-response-streaming-example shortly.
