### ISSUE TITLE
[New repo]: Serverless Second Screen Sign In

### ISSUE THREAD

**Issue by Podginator** [aws-samples/serverless-patterns#1622]
### Description

Second screen sign on is a complete web application that demonstrates the use of Websockets to allow users to use a second device to login. Second Screen Sign On is a feature of many web apps, especially those that have TV Apps, that allows the user to sign in from another device, such as a smart phone or laptop, and have the TV Login simulataneously.

### language

English

### runtime

NodeJS

### Level

300

### Type

Application

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/serverless-second-screen-sign-in/raw/main/docs/img/screenshot.png

### IaC framework

AWS CDK 

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Second screen sign on is a complete web application that demonstrates the use of Websockets to allow users to use a second device to login

### Repo URL

https://github.com/aws-samples/serverless-second-screen-sign-in

### Author Name

Thomas Rogers

### Author Image URL

https://avatars.githubusercontent.com/u/3532775?s=96&v=4

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/serverless-second-screen-sign-in shortly.
