### ISSUE TITLE
[New repo]: Predictive Maintenance using Amazon Lookout for Equipment

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1627]
### Description

The solution deploys a python CDK for a predictive maintenance inferencing pipeline for Amazon Lookout for Equipment by using AWS IoT Core, Amazon S3, Amazon SNS, Amazon Kinesis Firehose and AWS Lambda. 

### language

English

### runtime

Python

### Level

300

### Type

None

### Use case

Observability

### Primary image

https://drive.google.com/file/d/1o4FUrrCHEO4iko9naMzU5kYPKA_9khrT/view?usp=sharing

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [X] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Predictive Maintenance using Amazon Lookout for Equipment

### Repo URL

https://github.com/salmandjing/preventive-maintenance-lookout

### Author Name

Godswill Iroh

### Author Image URL

https://drive.google.com/file/d/1ySQPGr3bOfPJSD-zO32yqef4eH2Bds1f/view?usp=sharing

### Author Bio

Godswill Iroh was a solution architect intern at AWS for Energy.

### Author LinkedIn URL

https://www.linkedin.com/in/god-swill-iroh-79a936170/

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/repos/new-repo-predictive-maintenance-using-amazon-lookout-for-equipment shortly.
