### ISSUE TITLE
[New repo]: TwinGraph Wind Farm Simulation

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1628]
### Description

The [TwinGraph ](https://github.com/aws-samples/twingraph) Wind Farm Simulation workshop covers the complete workflow of running a wind farm optimization simulation using TwinGraph. You will use an AWS open source framework called TwinGraph to implement a wake model using AWS Lambda, Apache TinkerGraph, Celery, and Redis. 

### language

English

### runtime

Python

### Level

300

### Type

Workshop

### Use case

Interactive workload

### Primary image

https://drive.google.com/file/d/1B8MIk51FGuaS0zMVDOO5A-6ddNp9bFBB/view?usp=sharing

### IaC framework

AWS CloudFormation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

TwinGraph Wind Farm Simulation

### Repo URL

https://catalog.us-east-1.prod.workshops.aws/workshops/7ca5bb82-e1d9-4429-9306-3ac3ff859c31/en-US

### Author Name

Lorenzo Mondragon

### Author Image URL

https://drive.google.com/file/d/1BJbsbUp7LOf8-1jRXAyyDSRZ4Mon3_Hq/view?usp=sharing

### Author Bio

Lorenzo was an SA intern at AWS for Energy.

### Author LinkedIn URL

https://www.linkedin.com/in/lorenzo-mondragon/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/twingraph-wind-farm-simulation shortly.
