### ISSUE TITLE
[New repo]: Analyzing Sentiments Extracted from Amazon Rekognition Using Amazon Athena & QuickSight

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1629]
### Description

This workshop demonstrates how you can leverage Amazon Rekognition to perform sentiment analysis on facial images. Analyzing facial sentiments of people in images can help you determine their mood & reactions. An extended use case for this can be gathering feedback from customers/employees in buildings and other places with video monitoring.

### language

English

### runtime

Python

### Level

300

### Type

Workshop

### Use case

Backend

### Primary image

https://drive.google.com/file/d/1SHZT2eqkfCfRbGckYB9RamnlT73pjFB-/view?usp=sharing

### IaC framework

CloudFormation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Analyzing Sentiments Extracted from Amazon Rekognition Using Amazon Athena & QuickSight

### Repo URL

https://catalog.us-east-1.prod.workshops.aws/workshops/3ace0b9e-e080-455e-a13f-c87c30a3a32d/en-US

### Author Name

Khush Patel & Ankit Patel & Naimisha Pinna

### Author Bio

Khush, Ankit, and Naimisha are solution architects at AWS.

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/analyzing-sentiments-extracted-from-amazon-rekognition-using-amazon-athena-quicksight shortly.
