### ISSUE TITLE
New pattern submission - API Gateway REST API to SageMaker

### ISSUE THREAD

**Issue by naba819** [aws-samples/serverless-patterns#1651]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Note the following information for the model:
- Description: This sample project demonstrates how to use an use a API Gateway REST API to invoke a SageMaker endpoint. This pattern is leveraging the native AWS service integration between these 2 services. The pattern deploys a SageMaker endpoint for the Flan-T5 foundation model in Amazon SageMaker JumpStart. To deploy the pattern with a different model, replace the ModelData and ImageURI parameters in the template.yaml file. The template also deploys a REST API with AWS service integration to invoke the SageMaker endpoint directly. 
- Resources should like to AWS documentation and AWS blogs related to the post : 1.  https://repost.aws/knowledge-center/api-gateway-proxy-integrate-service, 2. https://aws.amazon.com/blogs/machine-learning/zero-shot-prompting-for-the-flan-t5-foundation-model-in-amazon-sagemaker-jumpstart/
- Framework: SAM
- Author bio: Cloud Support Engineer II @AWS - LinkedIn : https://www.linkedin.com/in/nabanita-paul/ - Nabanita Paul

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
merged
