### ISSUE TITLE
[New repo]: Serverless-Webhook-Forwarder

### ISSUE THREAD

**Issue by drsp123isen** [aws-samples/serverless-patterns#1657]
### Description

This sample deployed a pipeline to build and test a custom Lambda extension to forward HTTP events over the Tailscale VPN network to a configurable destination.  In this example, the custom Lambda extension forms a secure WireGuard VPN connection to a target in a private subnet behind a stateful firewall and NAT Gateway. This example sets up a public HTTPS endpoint to receive events, selectively filters, and proxies requests over the WireGuard connection. This example uses a serverless architecture to minimize maintenance overhead and running costs.

### language

English

### runtime

NodeJS

### Level

400

### Type

Examples

### Use case

Interactive workload

### Primary image

https://github.com/aws-samples/serverless-webhook-forwarder/blob/main/images/ArchitectureDiagram.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Webhook Forwarder

### Repo URL

https://github.com/aws-samples/serverless-webhook-forwarder

### Additional resources

https://aws.amazon.com/blogs/compute/building-a-secure-webhook-forwarder-using-an-aws-lambda-extension-and-tailscale/

### Author Name

Duncan Parsons & Simon Kok

**Comment by jbesw** [comment]
Thanks - this will be lively at https://serverlessland.com/repos/serverless-webhook-forwarder shortly.
