### ISSUE TITLE
[apigw-sqs-lambda-ddb] template does not validate

### ISSUE THREAD

**Issue by cionz0** [aws-samples/serverless-patterns#1672]
When validating the template with
`sam validate`

I get the following

```Template provided at '/Users/cionz0/patterns/serverless-patterns/apigw-sqs-lambda-ddb/template.yaml' was invalid SAM Template.
Error: [InvalidResourceException('HttpApi', "Unable to add Auth configuration because 'DefinitionBody' does not contain a valid OpenApi definition.")] ('HttpApi', "Unable to add Auth configuration because 'DefinitionBody' does not contain a valid OpenApi definition.")```

Providing the `--lint` option to the above command I get basically the same message

```
E0001 Error transforming template: Resource with id [HttpApi] is invalid. Unable to add Auth configuration because 'DefinitionBody' does not contain a valid OpenApi definition.
/Users/cionz0/patterns/serverless-patterns/apigw-sqs-lambda-ddb/template.yaml:1:1
```

**Comment by jbesw** [comment]
Pinged Ravi Kiran Ganji to update pattern.

**Comment by jbesw** [comment]
Thanks for the fix!
