### ISSUE TITLE
[New repo]: 

### ISSUE THREAD

**Issue by bensontwu** [aws-samples/serverless-patterns#1673]
### Description

This pattern automates the process of signing function code during deployments using AWS Step Functions. 

Signing AWS Lambda function code helps ensure function images are valid and unmodified. However, this is an extra step in the deployment process that may dissuade developers from using it. This pattern simplifies this process by providing an AWS Step Functions workflow that automates this process.

### language

English

### runtime

Javascript

### Level

300

### Type

None

### Use case

Backend

### Primary image

https://gitlab.aws.dev/wubenso/automated-lambda-code-signing/-/blob/main/automated-image-signing.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

This pattern automates the process of signing function code during deployments using AWS Step Functions.

### Repo URL

https://gitlab.aws.dev/wubenso/automated-lambda-code-signing

### Author Name

Benson Wu

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/signing-function-code-during-deployments shortly.
