### ISSUE TITLE
[Existing repo]: documentdb-stream-lambda-eventbridge-cdk

### ISSUE THREAD

**Issue by majd-soufan-pct** [aws-samples/serverless-patterns#1680]
### Description

I am raising this issue to correct the public URL on my published repo on AWServerlessLand
https://serverlessland.com/repos/documentdb-stream-lambda-eventbridge-cdk

The correct public repo for this pattern is https://github.com/SoufanConsulting/documentdb-stream-lambda-eventbridge-cdk

<img width="1227" alt="image" src="https://github.com/aws-samples/serverless-patterns/assets/120661532/16138121-36aa-4237-b64d-d7930acebea6">
Every time I press the `GitHub repo for this workflow` button it sends me to this URL instead (https://github.com/SoufanConsulting/serverless-patterns/tree/main/documentdb-stream-lambda-eventbridge-cdk)

Can you fix that, please?

### language

English

### runtime

Node

### Level

400

### Type

None

### Use case

Backend

### Primary image

https://github.com/SoufanConsulting/documentdb-stream-lambda-eventbridge-cdk/assets/16642196/78c06356-1fb7-4067-95e3-30692f114a28

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Change data capture with Amazon DocumentDB

### Repo URL

https://github.com/SoufanConsulting/documentdb-stream-lambda-eventbridge-cdk

**Comment by jbesw** [comment]
Thanks - this update will be live in the next few minutes.
