### ISSUE TITLE
[New repo]: Publish different version of AWS Step Function using AWS API Gateway

### ISSUE THREAD

**Issue by aws-gt** [aws-samples/serverless-patterns#1694]
### Description

In this workshop I will show one simple and effective way to achieve that.

Using AWS Cloud Development Kit ([CDK](https://aws.amazon.com/cdk/)) stack to automate the creation of resources reduce the risk of mistakes.

There are three main components in this example:
- [AWS Step Function](https://aws.amazon.com/step-functions/): is the core of the ‘solution’. The CDK stack creates it and publishes version 1. It doesn't require inputs and returns ‘Version Alpha’.
- [AWS Lambda](https://aws.amazon.com/lambda/): the CDK stack deploys a Lambda function. The function contains the logic to invoke the right step function version.
- [AWS API Gateway](https://aws.amazon.com/apigateway/): the CDK stack automates the API creation. It also creates the GET method that triggers the Lambda.

In the example you will automate the following steps:
- Deploy a demo AWS Step Function
- Deploy a AWS Lambda capable to invoke the AWS Step Function
- Create a AWS API Gateway API
- Create a GET invoke that triggers the AWS Lambda
- Deploy a AWS API Gateway Stage to a specific URL that invoke a specific AWS StepFunction Version

In addition to the previous, I am going to show you how to:
- Apply changes to your AWS Step Function
- Publish a new AWS Step Function Version
- Deploy a new AWS API Gateway Stage to a specific URL that invoke a specific AWS StepFunction Version

### language

English

### runtime

CDK Typescript

### Level

200

### Type

Workshop

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/oneapi-multiplestepfunctionversion/main/API-GW-SFN-VERSION-Architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

You have one [AWS Step Function](https://aws.amazon.com/step-functions/) and you want to invoke it via API using [AWS API Gateway](https://aws.amazon.com/api-gateway/).  You also require to publish multiple version of the same Step Function.

### Repo URL

https://github.com/aws-samples/oneapi-multiplestepfunctionversion

### Author Name

Gianfranco Turrini (GT)

### Author Image URL

https://badgephotos.corp.amazon.com/?uid=gturrini

### Author Bio

GT is a Migration & Modernization Specialist SA within AWS Industries.

### Author LinkedIn URL

https://www.linkedin.com/in/gianfranco-turrini/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/oneapi-multiplestepfunctionversion shortly.
