### ISSUE TITLE
New pattern submission: appsync-notify-subscribers-of-database-updates

### ISSUE THREAD

**Issue by xai1983kbu** [aws-samples/serverless-patterns#170]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern describes how to notify AWS AppSync subscribers of external database updates that aren't performed by client-side mutations.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## YouTube videoId (optional e.g. "VI79XQW4dIM")
KrmFAcucjzQ

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
from EventBridge to AppSync
from Lambda to AppSync

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
In working with AppSync, one of the common patterns is publishing “out-of-band” database updates to subscribers. An “out-of-band” update occurs when some system alters data independent of an AppSync mutation.
This pattern about - how do I notify AWS AppSync subscribers of external database updates that aren't performed by client-side mutations?

The demonstration of this pattern consists of 3 parts.
In 1 part, we create:
    - a Cognito user pool in order to login to AppSync service in AWS console.
    - AppSync resources - some of them are mutation with resolver type None and subscription to this mutation.
In 2 part, we create:
    - resources in EventBridge with API destination connected to AppSync.
In 3 part, we create 3 lambdas, each of them trigger mutation with resolver type None:
    - first lambda send HTTP request with header "x-api-key".
    - second lambda sends an event to EventBridge with an API destination connected to AppSync.
    - third lambda consumes IAM role which allows trigger mutation via JavaScript Client for AppSync.
To test - we log in to AppSync using the user's email and password, start the subscription in AWS console and after that we:
  - using postman to send HTTP request.
  - using AWS console, EventBridge page to send an event.
  - using AWS console, Lambda page to run each of 3 lambdas.
 
A role for EventBridge Rule to invoke Api Destination
```
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: eventbridge-invoke-api-destination
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: events:InvokeApiDestination
                Resource:
                  - !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:api-destination/${ApiDestination}/*"
```
A role for lambda, which uses JavaScript Client for AppSync to trigger mutation:
```
  AppSyncLambdaRole: # for lambda which uses IAM to have access to AppSync
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: AppSyncLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource: arn:aws:logs:*
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          - Effect: Allow
            Resource:
            - !Sub 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphQLApiId}/*'
            Action:
            - appsync:GraphQL
```

Note: EventBridge does not guarantee "only once event delivery".

## Deployment commands
```
sam build
sam deploy -g --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM
```

## GitHub PR for template:
#159

## Payload example (e.g. Lambda event payload from source service).

1. For testing part 1:
Configure postman authorization - add header "x-api-key".
Set request body:
      ```
      mutation MyMutation {
        publishStatusUpdate(
            orderId: "123",
            prevStatus: PENDING,
            status: IN_PROGRESS,
            updatedAt: "2021-10-07T20:38:18.683Z"
        ) {
          orderId
          prevStatus
          status
          updatedAt
        }
      }
      ```

2. For testing part 2:
Open EventBridge in AWS Console. Choose tab - "Events/Event buses" and choose EventBus - "orders", click on button "Send events". Send event with the next attributes:

      Event source:
      ```
      orders.system
      ```
      
      Detail type:
      ```
      Order Status Update
      ```
      
      Event detail:
      ```
      {
          "order-id": "123",
          "status": "IN_PROGRESS",
          "previous-status": "SHIPPED"
      }
      ```

3. For testing part 3:
    Open each Lambda in AWS console, run them with test event.
      ```
      {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
      }
      ```
      
## Additional resources (optional: link and anchor text, up to 5 resources)
1. https://aws.amazon.com/premiumsupport/knowledge-center/appsync-notify-subscribers-real-time/

2. https://aws.amazon.com/blogs/mobile/appsync-eventbridge/

3. https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/

4. https://github.com/aws-samples/serverless-patterns/tree/main/cognito-httpapi

5. https://www.youtube.com/watch?v=J0qfMYRmQcc

6. https://docs.aws.amazon.com/wellarchitected/latest/serverless-applications-lens/serverless-event-submission-with-status-updates.html

7. https://aws.amazon.com/blogs/mobile/create-an-ios-tracker-application-with-amazon-location-service-and-aws-amplify/

## Author bio
Name: Andriy Sorochan
Photo URL: https://lh3.googleusercontent.com/ogw/ADea4I43Bm5kTf412f-FU3IHvRjzRNlruD5rc5bK7c9HHg=s192-c-mo
Twitter handle: @s_andriy_
Description (up to 255 chars):

**Comment by xai1983kbu** [comment]
Hello! I think there is a small mistakeCleanup
1. Delete the stack: npx cdk destroy.

I think it should be
Cleanup
1. Delete the stack: aws cloudformation delete-stack --stack-name STACK_NAME
Thank you!

**Comment by jbesw** [comment]
Thanks - this has now been updated.
