### ISSUE TITLE
[New repo]: IoT Event Processing through AWS Serverless Services

### ISSUE THREAD

**Issue by biswanathmukherjee** [aws-samples/serverless-patterns#1709]
### Description

The SAM application deploys an IoT Thing, an event processor Lambda function, an SNS topic, three SQS fanout queues, a consumer Lambda function, a DynamoDB table and the IAM permissions required to run the application. When an IoT event is sent to an IoT topic, the event processor Lambda function is invoked. The event processor Lambda function to poll this event, filters out the events that are not required and publishes the required events to a SNS topic. There is an SNS-SQS fan out pattern using subscription filter policy. The events from SNS topics moves to the respective SQS queues depnding on the filter policy. The consumer Lambda function reads from the SQS queue and stored the event in a DynamoDB table.

### language

English

### runtime

node js

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://d1rwvjey2iif32.cloudfront.net/ioteventprocessing.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [X] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

IoT Event Processing through AWS Serverless Services

### Repo URL

https://github.com/aws-samples/iot-lambda-sns-sqs-lambda-dynamodb

### Author Name

Biswanath Mukherjee

### Author Image URL

https://d1rwvjey2iif32.cloudfront.net

### Author Bio

I am a Sr. Solutions Architect working at AWS India.

### Author LinkedIn URL

https://www.linkedin.com/in/biswanathmukherjee

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/iot-lambda-sns-sqs-lambda-dynamodb shortly.
