### ISSUE TITLE
Incorrect presenter name configured in new pattern in Serverlessland

### ISSUE THREAD

**Issue by biswanathmukherjee** [aws-samples/serverless-patterns#1713]
Hi,

My recent PR for a new pattern is merged to main branch. However, the Serverless pattern page is showing presenter as someone else. Can you please fix the issue:

PR: https://github.com/aws-samples/serverless-patterns/pull/1702
Serverlessland Pattern Page: https://serverlessland.com/patterns/eventbridge-batch-sam

My profile information: https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-batch-sam/example-pattern.json

**Comment by jbesw** [comment]
This will be updated in the next few minutes.
