### ISSUE TITLE
[New repo]: Right of Way Inspection Using Computer Vision on AWS

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1727]
### Description

Right of way is the legal right to pass along a specific route through property belonging to another. This is used across many industries. For example power & utility companies use to build transmission lines. Before construction begins, a right of way  inspection must be done. This inspection is typically done manually which is inefficient, time intensive and subject to human error. 
This blog demonstrate how the traditional inspection method can be innovated and automated using IoT and computer vision on AWS. 

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/salmandjing/iot-drone-automated-image-rekognition/blob/master/architecture.PNG

### IaC framework

CloudFormation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [X] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Right of Way Inspection Using Computer Vision on AWS

### Repo URL

https://github.com/salmandjing/iot-drone-automated-image-rekognition/tree/master

### Author Name

Sean Murray

### Author Bio

Sean Murray is a Sr. Partner Solution Architect at AWS for Energy 

### Author LinkedIn URL

https://www.linkedin.com/in/sean-m-85692956/

**Comment by jbesw** [comment]
This is not the right content type for repos. We only list applications with complete code examples in the repo, not indirections.
