### ISSUE TITLE
[New repo]: Sumerian Hosts on AWS

### ISSUE THREAD

**Issue by salmandjing** [aws-samples/serverless-patterns#1736]
### Description

In this repository you will learn how to leverage AWS technology to bring interactive and intelligent 3D character to life. Efficiency in communication with customers is vital, as it fosters stronger relationships, enhances customer lifetime value, and promotes a positive brand image through customer-focused techniques. However, can we automate customer interactions without losing efficacy or the human touch? The answer is yes, with a skillfully developed chatbot solution that delivers a seamless and personalized experience.

### language

English

### runtime

Python

### Level

200

### Type

Workshop

### Use case

Interactive workload

### Primary image

https://drive.google.com/file/d/1tlaChUIEru5emaKUfjGPEMF4t34ad9ru/view?usp=sharing

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Sumerian Hosts on AWS

### Repo URL

https://github.com/prathyushanandam/Character-workshop

### Author Name

 Prathyusha Nandam

### Author Image URL

https://drive.google.com/file/d/1u1VHAuyWj7u8X2kT3YBARRf9RQYrPPVN/view?usp=sharing

### Author Bio

 Prathyusha is a solution architect at AWS for Energy.

### Author LinkedIn URL

https://www.linkedin.com/in/prathyusha-nandam/

**Comment by jbesw** [comment]
Amazon Sumerian is no longer available - https://aws.amazon.com/blogs/aws/amazon-sumerian-now-generally-available/#:~:text=Update%20May%2018%2C%202022%20%E2%80%93%20Amazon,be%20published%20using%20AWS%20Amplify..
