### ISSUE TITLE
[New repo]: Serverless and Security - Integrated Application

### ISSUE THREAD

**Issue by jtmcduf** [aws-samples/serverless-patterns#1748]
### Description

A Secure Serverless Application demonstrating how to quickly and easily integrate key security services like Cognito and Amazon Verified Permissions, with a serverless architecture utilizing API Gateway and Lambda, to build quick and secure serverless applications using modern cloud infrastructure. 

### language

English

### runtime

Javascript, Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

NA

### IaC framework

AWS Amplify, AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Secure and Serverless

### Repo URL

https://code.amazon.com/packages/AmazonVerifiedPermissions-Demo/trees/mainline#

### Author Name

James McDuffie

### Author Image URL

https://media.licdn.com/dms/image/C5603AQE9yORsFMfGuQ/profile-displayphoto-shrink_200_200/0/1581629573802?e=1702512000&v=beta&t=IWy6uxwbwxsiMTiFyOmDPtwaUg-U9v7170rRQIRXRRs

### Author Bio

James is a Senior Technical Account Manager. He has over 20 years of experience in software development, with previous roles in Software and Hardware Security Architecture in Industrial IoT. He is an active member of the AWS Security community, and he works closely with our customers to help them solve complex security challenges at scale.

### Author LinkedIn URL

https://www.linkedin.com/in/james-mcduffie/

**Comment by jbesw** [comment]
The Repos Collection is intended for publicly available repos, not internal code. Please migrate to GitHub or another public repo and update your submission info.

**Comment by jtmcduf** [comment]
Sounds good, I'll try to get it on the public github this next week and re-submit.
