### ISSUE TITLE
[New repo]: Amazon CloudFront with on-the-fly Image Resizing

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#1749]
### Description

The purpose of this solution is to serve images through Amazon CloudFront with support for on-the-fly image resizing. The solution uses CloudFront, S3, API Gateway, and Lambda. The CloudFront distribution includes a cache behavior with an origin group and two origins, an S3 bucket and an HTTP API integrated with a Lambda function. If the image is not available in the CloudFront cache or the S3 bucket, the Lambda function returns a resized image in the requested dimensions.

### language

English

### runtime

Node.js

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://github.com/serverlessguy/samples/blob/main/cloudfront-resize-image/docs/cloudfront-resize-image.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Amazon CloudFront with on-the-fly Image Resizing

### Repo URL

https://github.com/serverlessguy/samples/tree/main/cloudfront-resize-image

### Author Name

Greg Davis

### Author Image URL

https://avatars.githubusercontent.com/u/123254355?s=400&u=e5772932b1dcac36a13373373a7be6cba82c7527&v=4

### Author Bio

Greg Davis is a Sr. Engineering Manager at Amazon Web Services. He is an experienced leader with 25+ years in diverse technical roles. Greg has a passion for developing scalable, distributed, cloud-native solutions. His technical expertise extends across a wide spectrum of technologies, cloud services, and programming languages, with a particular focus on backend infrastructure, Serverless development, event-driven architecture, purpose-built databases, data engineering, and data analysis.

### Author Twitter handle

ServerlessGuy

### Author LinkedIn URL

https://www.linkedin.com/in/gregtx/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/cloudfront-resize-image in the next hour.
