### ISSUE TITLE
[New repo]: Receiving webhooks on AWS: Innovate with event notifcations

### ISSUE THREAD

**Issue by wirjo** [aws-samples/serverless-patterns#1761]
### Description

This repository is intended for developers looking to receive webhooks using AWS.

Commonly known as *reverse APIs* or *push APIs*, webhooks provide a way for applications to integrate to each other and communicate in near real-time. It enables integration for business and system events. 

Whether you’re building a software as a service (SaaS) application integrating with your customer workflows, or transaction notifications from a vendor, webhooks play a critical role in unlocking innovation, enhancing user experience, and streamlining operations.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/webhooks/main/receive-webhooks/images/architecture-receive-webhooks.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Receiving webhooks on AWS: Innovate with event notifcations

### Repo URL

https://github.com/aws-samples/webhooks/tree/main/receive-webhooks

### Additional resources

https://aws.amazon.com/blogs/compute/sending-and-receiving-webhooks-on-aws-innovate-with-event-notifications/

### Author Name

jplock

### Author Bio

Principal Solutions Architect at AWS

### Author Twitter handle

jplock

### Author LinkedIn URL

https://www.linkedin.com/in/justinplock/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/receive-webhooks in the next hour.
