### ISSUE TITLE
[New repo]: Send webhooks on AWS: Innovate with event notifcations

### ISSUE THREAD

**Issue by wirjo** [aws-samples/serverless-patterns#1762]
### Description

This repository is intended for developers looking to send webhooks using AWS.

Commonly known as *reverse APIs* or *push APIs*, webhooks provide a way for applications to integrate to each other and communicate in near real-time. It enables integration for business and system events. 

Whether you’re building a software as a service (SaaS) application integrating with your customer workflows, or transaction notifications from a vendor, webhooks play a critical role in unlocking innovation, enhancing user experience, and streamlining operations.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/webhooks/main/send-webhooks/images/architecture-send-webhooks.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Sending webhooks on AWS: Innovate with event notifcations

### Repo URL

https://github.com/aws-samples/webhooks/tree/main/send-webhooks

### Additional resources

https://aws.amazon.com/blogs/compute/sending-and-receiving-webhooks-on-aws-innovate-with-event-notifications/

### Author Name

wirjo

### Author Image URL

https://avatars.githubusercontent.com/u/165846?v=4

### Author Bio

Daniel is a Solutions Architect at Amazon Web Services (AWS) based in Australia. He advises startups and innovators building on AWS, collaborating with CTOs, engineers and the startup ecosystem.  Primarily focused in the intersection of financial services and technology, Daniel is a builder of high-performing teams, and loves learning and staying abreast of emerging technologies to ensure customer success. 

### Author LinkedIn URL

https://www.linkedin.com/in/wirjo/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/send-webhooks shortly.
