### ISSUE TITLE
[New repo]: dynamodb-streams-to-msk-transactional-outbox-pattern-java

### ISSUE THREAD

**Issue by sajedaws** [aws-samples/serverless-patterns#1763]
### Description

Implementation of transactional microservices outbox pattern with AWS Serverless Technology stack Amazon DynamoDB, AWS Lambda,  Amazon MSK, Amazon API Gateway, AWS SAM.

The transactional outbox pattern resolves the dual write operations issue that occurs in distributed systems when a single operation involves both a database write operation and a message or event notification. A dual write operation occurs when an application writes to two different systems; for example, when a microservice needs to persist data in the database and send a message to notify other systems. A failure in one of these operations might result in inconsistent data.

### language

English

### runtime

Java

### Level

400

### Type

Example

### Use case

Backend

### Primary image

https://github.com/sajedaws/dynamodb-streams-to-msk-transactional-outbox-pattern-java/blob/main/Outbox-pattern-Architecture.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [x] Amazon API Gateway
- [x] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [x] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Transactional outbox microservice pattern implementation with DynamoDB

### Repo URL

https://github.com/sajedaws/dynamodb-streams-to-msk-transactional-outbox-pattern-java/tree/main

### Additional resources

[Amazon DynamoDB streams](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html)
 [AWS Serverless Application Model](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) 
[Create MSK Cluster](https://docs.aws.amazon.com/msk/latest/developerguide/create-cluster.html)

### Author Name

Sajed Parathanalli

### Author Image URL

https://www.linkedin.com/in/sajedahmad/

### Author Bio

Sajed is a Lead Consultant at Amazon Web Services based in India.

### Author LinkedIn URL

https://www.linkedin.com/in/sajedahmad/

**Comment by jbesw** [comment]
Thanks - this is live at https://serverlessland.com/repos/dynamodb-streams-to-msk-transactional-outbox-pattern-java
