### ISSUE TITLE
New pattern submission - s3-lambda-transcribe-sam

### ISSUE THREAD

**Issue by anushreeumesh** [aws-samples/serverless-patterns#1785]
Description:

This pattern contains a sample AWS Serverless Application Model (SAM) template that deploys a Lambda Function with an S3 object created trigger to start an Amazon Transcribe job and place the results in another S3 bucket.

Resources:

- https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html
- https://aws.amazon.com/transcribe/

Framework: SAM

Author:

- Name: Anushree Umesh
- Bio: Anushree Umesh is an Associate Solutions Architect with Amazon Web Services
- LinkedIn: https://www.linkedin.com/in/anushreeumesh/

**Comment by bls20AWS** [comment]
Merged
