### ISSUE TITLE
Amazon API Gateway to AWS Lambda using mutual TLS

### ISSUE THREAD

**Issue by sudheery80** [aws-samples/serverless-patterns#179]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a public API Gateway that calls a Lambda function and authenticated using mutual TLS
## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node js
## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
API Gateway to Lambda
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern deploys a public Amazon API Gateway API that is integrated with a AWS Lambda function written in Python and the API calls are authenticated using mutual TLS. 
## Deployment commands
sam deploy --guided
## Payload example (e.g. Lambda event payload from source service).
NA
## Additional resources (optional: link and anchor text, up to 5 resources)
Extended examples of this pattern implementation - https://github.com/aws-samples/serverless-samples/tree/main/serverless-rest-api
## Author bio 
Name: Sudheer Yalamanchili
Photo URL:
Twitter handle:
Description (up to 255 chars):
Sudheer is a cloud application architect working with AWS ProServ.

**Comment by jbesw** [comment]
Is there a pull request for this submission?

**Comment by sudheery80** [comment]
I don't have a PR yet, will submit it next week

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-lambda-tls.
