### ISSUE TITLE
[New repo]: Serverless-Intelligent-Document-Processing

### ISSUE THREAD

**Issue by paulkannan** [aws-samples/serverless-patterns#1803]
### Description

This architecture is designed to provide a serverless, efficient, and automated solution for identifying valid Indian ID cards from uploaded documents into S3 and through API Gateway. The application supports identification and validation of Aadhaar, Indian Driving License, Indian Passport and Permanent Account Number in .jpg, .jpeg, and .png file formats only.  The workflow comprises three main phases: Image Validation by Amazon Rekognition, Data Extraction by Amazon Textract, and PII Entity Identification by Amazon Comprehend, followed by document categorization into valid and invalid ID cards. A notification is sent to end users through Amazon SNS, and the data is forwarded to Amazon SQS for consumption by end user applications.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/paulkannan/Serverless-Intelligent-Document-Processing/blob/main/dataprocessing.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Intelligent Document Processing

### Repo URL

https://github.com/paulkannan/Serverless-Intelligent-Document-Processing

### Author Name

Paul Kannan

### Author Image URL

https://github.com/paulkannan/Cloudformation/blob/main/IMG-0484.JPG

### Author Bio

Im an AWS Technical Account Manager. I specialise in simplifying complex issues with simple solutions for our customers.

### Author LinkedIn URL

https://www.linkedin.com/in/paulkannan/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/serverless-intelligent-document-processing shortly.
