### ISSUE TITLE
[New repo]: Sentiment Powered News Feed

### ISSUE THREAD

**Issue by ssnskar** [aws-samples/serverless-patterns#1804]
### Description

In the digital age, staying informed about current events is essential, but the sheer volume of news available can be overwhelming. To address this issue, we present the "Sentiment-Powered News Feed" project, a novel solution that leverages the power of the AWS services to deliver a more personalized and emotionally resonant news experience.

### language

English

### runtime

Python

### Level

100

### Type

Examples

### Use case

Observability

### Primary image

https://github.com/ssnskar/sentiment-powered-news-feed/blob/main/Architecture.png

### IaC framework

Cloudformation

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Sentiment Powered News Feed

### Repo URL

https://github.com/ssnskar/sentiment-powered-news-feed

### Additional resources

[Using AWS Lambda and Amazon Comprehend for sentiment analysis](https://aws.amazon.com/blogs/compute/using-aws-lambda-and-amazon-comprehend-for-sentiment-analysis/)

### Author Name

Sanskar

### Author Image URL

https://serverlessland.com/assets/images/resources/contributors/ext-sanskar-sanyal.jpg

### Author Bio

Sanskar is a Serverless Cloud Engineer at Amazon Web Services and is based in India. Sanskar has avid interest in microservices and serverless architecture.

**Comment by jbesw** [comment]
The architecture diagram is not accessible. Please update the repo README and asset here,

**Comment by ssnskar** [comment]
Hello, thank you for pointing out that. I have updated the README file with the architecture diagram.

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/sentiment-powered-news-feed shortly.
