### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by jkahn117** [aws-samples/serverless-patterns#181]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

EventBridge API Destination to AWS AppSync GraphQL API with OAuth authorization.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

TypeScript, Python (Lambda function)

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

EventBridge, AppSync (+Cognito, Lambda)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

Create an EventBridge bus and destination with OAuth authorization to trigger an AppSync GraphQL API

## Deployment commands

`cdk deploy --parameters authDomainName=<your_domain_name>

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/180

## Author bio 
Name: Josh Kahn
Photo URL: https://serverlessland.com/assets/images/resources/contributors/joshhahn.jpg
Twitter handle: joshuaakahn
Description (up to 255 chars): Josh is the Tech Leader for Serverless.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-api-appsync-cdk.
