### ISSUE TITLE
New pattern submission: API Gateway to Fargate CDK 

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#182]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Integrate API Gateway with a private application load balanced Fargate Service that uses a custom image, written in CDK.

## Language:

TypeScript

## Framework

CDK

## Services from/to

Amazon API Gateway to AWS Fargate

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for integrating Amazon API Gateway HTTP API with a private Application Load Balanced AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built `ecs.ContainerImage.fromAsset` method. The custom image has a base route `/` to output a message.

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#183 

## Payload example (e.g. Lambda event payload from source service).

Simple CURL to the API Gateway URL to display the output from API Gateway:

```bash
curl --location --request GET '<REPLACE WITH API GATEWAY URL>'
# Example
curl --location --request GET 'https://abcd123efg.execute-api.ap-southeast-2.amazonaws.com/'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

Retrieve the API Gateway URL from `cdk deploy`

![image](https://user-images.githubusercontent.com/31919569/140104920-80139e15-dbec-43e0-9a35-bff4891c5cb0.png)

Running the GET request should produce the following output:

![image](https://user-images.githubusercontent.com/31919569/140104906-d21fa5bc-9f54-4f5f-9590-a4bb99d9f02c.png)

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn (Handle for Serverless Pattern website): https://www.linkedin.com/in/glenn-chia-291344142
Twitter (Handle for Twitter mentions): @ glenncjw (https://twitter.com/glenncjw)
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks Glenn! This is now live at https://serverlessland.com/patterns/apigw-fargate-cdk.
