### ISSUE TITLE
lambda-bedrock-response-streaming does not work - broken imports

### ISSUE THREAD

**Issue by shafkevi** [aws-samples/serverless-patterns#1822]
When deploying https://github.com/aws-samples/serverless-patterns/tree/main/lambda-bedrock-response-streaming, I receive an error in the lambda execution via curl of `Unknown application error occurred Runtime.Unknown`.

And when I invoke the function in the console, I get an error about the imports not being valid `Cannot find package '@aws-sdk/client-bedrock-runtime' imported from /var/task/fn.mjs`

**Comment by jbesw** [comment]
@mavi888 Please can you review?

**Comment by mavi888** [comment]
@shafkevi you need to run npm install inside the src folder and then deploy again.
