### ISSUE TITLE
[New repo]:  amazon-sns-sms-detailed-monitoring-dashboard

### ISSUE THREAD

**Issue by SparshWadhwa** [aws-samples/serverless-patterns#1830]
### Description

[Please Refer read me](https://github.com/aws-samples/amazon-sns-sms-detailed-monitoring-dashboard/#readme)

### language

English

### runtime

NodeJs

### Level

300

### Type

Tips

### Use case

Observability

### Primary image

https://raw.githubusercontent.com/aws-samples/amazon-sns-sms-detailed-monitoring-dashboard/main/Assets/Metric-based-Insights.png

### IaC framework

AWS Cloudformation

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

It helps customers in creating Custom CloudWatch dashboard which can be used for efficiently monitoring SMS messages sent using Amazon SNS. Monitor the SMS messages for delivery rates in different countries, idenitfy issues at the right time, quickly fetch the required logs & statstics and escalate the issues at the right time.

### Repo URL

https://github.com/aws-samples/amazon-sns-sms-detailed-monitoring-dashboard/

### Author Name

Sparsh Wadhwa

### Author Bio

Cloud Engineer II at AWS. SNS and SQS Subject Matter Expert

### Author LinkedIn URL

https://www.linkedin.com/in/sparsh-wadhwa/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/amazon-sns-sms-detailed-monitoring-dashboard soon.
