### ISSUE TITLE
[New repo]: CDK Python project for deploying Rest API that can insert and list Marketplace Metering records.

### ISSUE THREAD

**Issue by saikotag** [aws-samples/serverless-patterns#1837]
### Description

Marketplace consumption based pricing (a.k.a usage-based dimentions consumption-based dimensions, or metered dimensions) should be reported to AWS Marketplace and must be stored in a DynamoDB table called AWSMarketplaceMeteringRecords. This table gets created in the Seller’s AWS account as part of AWS Markerplace SaaS quickstart integration.

Sellers manually insert meterning record into AWSMarketplaceMeteringRecords table. But in production, they are expected to automatically insert records based on monitoring buyers' consumption.

This CDK project will create API Gateway Rest API endpoints that can help sellers, incorporate them into their Billing systems, to automate sending metering information to AWS Marketplace.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/saikotag/cdk-apigw-marketplace-metering-records/blob/main/images/MP-metering-records.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

CDK Python project for deploying Rest API that can insert and list Marketplace Metering records.

### Repo URL

https://github.com/saikotag/cdk-apigw-marketplace-metering-records.git

### Additional resources

This CDK project will create API Gateway Rest API endpoints that can help sellers, incorporate them into their Billing systems, to automate sending metering information to AWS Marketplace.

### Author Name

Sai Kotagiri

### Author Image URL

https://media.licdn.com/dms/image/C4E03AQGAb4MkiGJCPA/profile-displayphoto-shrink_400_400/0/1639449171855?e=1704326400&v=beta&t=dOvwJ1zdZ27asMn8LpTXmMHLrIbDYugnUOswWpOAkn4

### Author Bio

Sai Kotagiri is a Partner Solutions Architect at Amazon Web Services based in New York metropolitan area. Sai has over 20 years of experience focusing on digital transformation and IT strategy

### Author LinkedIn URL

https://www.linkedin.com/in/sai-diwakar-kotagiri-1251928/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/cdk-apigw-marketplace-metering-records shortly.
