### ISSUE TITLE
[New repo]: Serverless Retrieval Augmented Generation RAG with Python

### ISSUE THREAD

**Issue by giusedroid** [aws-samples/serverless-patterns#1838]
### Description

This pattern demonstates an implementation of Retrieval Augmented Generation, making usage of Bedrock, Lambda, and LanceDB embedding store backed by S3.

### language

English

### runtime

Python

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/giusedroid/serverless-rag-python/main/assets/ServerlessRAG.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Retrieval Augmented Generation, but no servers involved. Backed by S3

### Repo URL

https://github.com/giusedroid/serverless-rag-python

### Additional resources

https://arxiv.org/abs/2005.11401
https://aws.amazon.com/bedrock/titan/#Titan_Embeddings_.28generally_available.29

### Author Name

giusedroid,shafkevi

### Author Bio

**Giuseppe Battista** leads soultions architecture for Early Stage Startups in UK at AWS.
**Kevin Shaffer-Morrison** is a Sr Solutions Architect at AWS. He's helped hundreds of startups get off the ground quickly and up into the cloud.

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/serverless-rag-python soon.
