### ISSUE TITLE
Location Tracking using AWS Location Services, Event Bridge, Lambda and DynamoDB

### ISSUE THREAD

**Issue by sundarsh123** [aws-samples/serverless-patterns#1839]
### Description

This sample project demonstrates how to use an AWS Location Services Tracker API for position updates from your device that send the trackers coordinates to a dynamoDB database. Trackers offer three position filtering options to help manage costs and reduce jitter in your location updates (Accuracy-based, Distance-based, Time-based). The test event triggers a Lambda function that receives a payload from your location services APP and sends location tracker update via the BatchUpdateDevicePosition API. An Event Bridge rule then listens for the Amazon Location Services API (BatchUpdateDevicePosition) being called via cloudtrail and invokes a another lambda function which calls another Amazon Location API (GetDevicePosition) with the tracker information to get the most recent position and updated the DynamoDB table with the location information.

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/sundarsh123/serverless-examples/blob/main/geo-tracking-sam/pic/GeoLocation%20Tracking%20Serverless.jpg

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Invoking AWS Location Trackers API for tracker movement to trigger an event that send the trackers information including coordinates to a dynamoDB database

### Repo URL

https://github.com/sundarsh123/serverless-examples/tree/main/geo-tracking-sam

### Additional resources

https://docs.aws.amazon.com/location/latest/developerguide/start-tracking.html
https://docs.aws.amazon.com/location/latest/developerguide/location-events.html

### Author Name

Shyam Sundar

### Author Image URL

https://github.com/sundarsh123/serverless-examples/blob/main/geo-tracking-sam/pic/authorPic.jpeg

### Author Bio

Solutions Architect @ AWS

### Author LinkedIn URL

https://www.linkedin.com/in/shyam--sundar/

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/repos/geo-tracking-sam shortly.
