### ISSUE TITLE
[New repo]: Image Insight application with Rekognition and Bedrock

### ISSUE THREAD

**Issue by higoyal01** [aws-samples/serverless-patterns#1841]
### Description

This project is a serverless application that uses AWS services to provide image description based on AWS Rekognition and Bedrock services. It's designed to help you analyse and describe the content of images.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/higoyal01/image-insight/blob/main/ImageInsightsWorkflow.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Image Insight Application

### Repo URL

https://github.com/higoyal01/image-insight

### Author Name

Himanshu Goyal

### Author Image URL

https://media.licdn.com/dms/image/D4D03AQGfOBBJOHCFnw/profile-displayphoto-shrink_800_800/0/1674582869052?e=1704326400&v=beta&t=-G0aRVpMC8PBt8uh8PnEqd1iAgnkxZ_WPKsKffPkIw0

### Author Bio

A Serverless Cloud Engineer and technical writer, dedicated to crafting efficient and scalable solutions using AWS services. My expertise in serverless architecture empowers me to create innovative and cost-effective cloud solutions. I enjoy sharing my knowledge with the serverless community through articles and patterns, helping others explore the vast potential of serverless computing.

### Author LinkedIn URL

https://www.linkedin.com/in/himanshugoyal20/

**Comment by jbesw** [comment]
Closed as duplicate.
