### ISSUE TITLE
New pattern submission - DymanoDB to Kinesis CDK

### ISSUE THREAD

**Issue by migodau** [aws-samples/serverless-patterns#186]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description
The CDK stack deploys a DynamoDB table and a Kinesis Data Stream.

## Language:
Typescript

## Framework
CDK

## Services from/to 
DymanoDB to Kinesis

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The CDK stack deploys a DynamoDB table and a Kinesis Data Stream.

When new items are added to the DynamoDB table, the item-level changes in the table will be streamed to the Kinesis Data Stream.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ``` 
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```
    cd dynamodb-kinesis-cdk/src
    ```
3. Install dependencies
    ```
    npm install
    ```
4. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:
    ```
    cdk deploy
    ```

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/185

## Author bio 
Name: Milena Godau
Photo URL: https://avatars.githubusercontent.com/u/2366386?s=400&u=a865fb7ba5a05f72078da1bf96d4d3009d00dc57&v=4
Twitter handle: @ MiGodau
Description (up to 255 chars): Milena is a Front End Developer at AWS based in São Paulo

**Comment by jbesw** [comment]
Many thanks for your contribution! This is now live at https://serverlessland.com/patterns/dynamodb-kinesis-cdk.
