### ISSUE TITLE
[Update repo]: How to use WhatsApp to send Cognito OTP messages

### ISSUE THREAD

**Issue by ReethiJ** [aws-samples/serverless-patterns#1876]
Regarding the recently published serverless repo [How to use WhatsApp to send Cognito OTP messages](https://github.com/aws-samples/serverless-patterns/issues/1846) please update the repo URL to: https://github.com/aws-samples/amazon-cognito-whatsapp-otp 
Also, the author images were not added:

Nideesh KT: https://drive.google.com/file/d/1leKzwJxa7Voandp1MhO_mzKdr-73GK4t/view 
Reethi: https://drive.google.com/file/d/1fthW0WuTMx8dKt3EPoh6NHFdj-jBrtvf/view

**Comment by jbesw** [comment]
Thanks - this will be updated shortly.
