### ISSUE TITLE
[New repo]: Serverless Shoppable Video Web Application

### ISSUE THREAD

**Issue by rohitraj-11** [aws-samples/serverless-patterns#1879]
### Description

Shoppable Video, a serverless web application is a solution which will let the user take a snapshot of scene in the movie/tv show, mark items/celebrities of interest and analyse the snapshotted frame. Then the solution would display the identified celebrities with details and the list of products available for purchasing on e-commerce sites for identified items. The solution would also recommend movie titles to the user considering user’s interaction with celebrities. The snapshots taken by the user would get added in snapshots library which is a searchable list.

### language

English

### runtime

Node.js

### Level

400

### Type

Application

### Use case

Interactive workload

### Primary image

https://github.com/rohitraj-11/shoppable-video/blob/main/user-engagement-and-monetisation-for-streaming-media-content/public/images/Architecture.drawio.png

### IaC framework

AWS CloudFormation

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Shoppable Video: Snap scenes, identify items/celebs, shop products, discover celeb info and get movie suggestions

### Repo URL

https://github.com/rohitraj-11/shoppable-video

### Author Name

Rohit Raj & Thejashree Neralakere Chandrakumara

### Author Bio

Rohit & Thejashree are Solutions Architects focusing on Serverless at AWS.

### Author Twitter handle

https://twitter.com/RohitRaj_11

### Author LinkedIn URL

https://www.linkedin.com/in/rohitraj-11/

**Comment by jbesw** [comment]
Thanks - this will be live shortly at serverlessland.com/repos/shoppable-video.
