### ISSUE TITLE
New pattern submission : Eventbridge-SNS-cdk

### ISSUE THREAD

**Issue by shsnket** [aws-samples/serverless-patterns#188]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
The CDK stack deploys an SNS topic that is triggered by an EventBridge rule.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
EventBridge to SNS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This CDK template deploys an SNS topic that is triggered by an EventBridge rule. The SNS topic policy provides the permission for EventBridge to invoke the SNS topic.

## Deployment commands

1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```bash 
    git clone https://github.com/aws-samples/serverless-patterns
    ```
1. Change directory to the pattern directory:
    ```bash
    cd eventbridge-sns-cdk
    ```
1. Create a virtual environment for python:
    ```bash
    python3 -m venv .venv
    ```
1. Activate the virtual environment:
    ```bash
    source .venv/bin/activate
    ```
1. Install python modules:
    ```bash
    python3 -m pip install -r requirements.txt
    ```
1. From the command line, use CDK to synthesize the CloudFormation template and check for errors:
    ```bash
    cdk synth
    ```
1. From the command line, use CDK to deploy the stack:
    ```bash
    cdk deploy
    ```

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/187

## Payload example (e.g. Lambda event payload from source service).
Note - Account Number and SigningCertURL are masked in the example paylod.
```
{
  "Type" : "Notification",
  "MessageId" : "ecc4f3ed-47eb-5374-b5a4-aa16ec96b0a1",
  "TopicArn" : "arn:aws:sns:us-east-1:<*AccountNumber*>:EventbridgeSnsCdkStack-MySnsTopicCB85459E-1VN8RJK7ZDOSB",
  "Message" : "{\"version\":\"0\",\"id\":\"3a91138a-dc4b-8fff-0325-5e18f7247415\",\"detail-type\":\"message\",\"source\":\"my-application\",\"account\":\"<*AccountNumber*>\",\"time\":\"2021-11-02T21:10:21Z\",\"region\":\"us-east-1\",\"resources\":[],\"detail\":{\"message\":\"Hello from EventBridge to SNS Topic!\"}}",
  "Timestamp" : "2021-11-02T21:10:21.802Z",
  "SignatureVersion" : "1",
  "Signature" : "OQBlVrpA8e4sFu211RkLjn2SPWVv1cThCXfG7YBaFkoulyNM+8SvlApbHLR/t+BtLyzmU8DIh7MOb8zyR4rpBhKCkjEvqNpX1AO+Da294onD+NHGrqjnRMkMyjcDzxe7poTKSEwwYBp16jjDNBBXRZmM6YX5XiL1zY41NrfJiUXro76xJr1nqr7BoxNJ1a3ACzh2cv6lyoGS0oxTgXztevUvUmfvxqtbfiFAapEjxde6IWPT6pellzy6HGfls8z7UI1NndBqfCAo4z8dCAxrczDM4Yozc+KvoquSbttKPcMkApe184teOWp0ZOT5dhO6mOV4hgCPoe9hUipoFq4Acw==",
  "SigningCertURL" : "******",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:<AccountNumber>:EventbridgeSnsCdkStack-MySnsTopicCB85459E-1VN8RJK7ZDOSB:175aa034-1d2d-4a83-a0e4-dbd830fce265"
}
```
## Author bio 
Name: Sanket Shinde
Photo URL: https://avatars.githubusercontent.com/u/81987730?s=400&u=6ee77a41f2a59a88c05a04522908a7497c0e9f02&v=4
Twitter handle:
Description (up to 255 chars): Sanket is a Data Engineer at AWS Professional Service.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-sns-cdk.
