### ISSUE TITLE
[New repo]: Image insight application with Amazon Rekognition and Amazon Bedrock (NodeJs)

### ISSUE THREAD

**Issue by higoyal01** [aws-samples/serverless-patterns#1883]
### Description

This project is a serverless application that uses AWS services to provide image description based on Amazon Rekognition and Amazon Bedrock services. It's designed to help you analzse and describe the content of images.

### language

English

### runtime

NodeJs

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/higoyal01/image-insight-nodejs/blob/main/ImageInsightsWorkflow.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Image Insight Application

### Repo URL

https://github.com/higoyal01/image-insight-nodejs

### Additional resources

Python version of the same application - https://serverlessland.com/repos/insight-application-with-rekognition-and-bedrock

### Author Name

Aditya Pandita

### Author Image URL

https://media.licdn.com/dms/image/D4D03AQGP1ihI84aT6g/profile-displayphoto-shrink_800_800/0/1694371829036?e=1705536000&v=beta&t=jszDFMjSc4puZMdnSiNkpoKjZr_TzE_lQCfAIr4JyuI

### Author Bio

A Serverless Cloud Engineer and technical writer, dedicated to crafting efficient and scalable solutions using AWS services. My expertise lies in the world of serverless architecture, where I thrive on creating innovative, cost-effective cloud solutions. With a strong commitment to knowledge sharing, I enjoy empowering the serverless community through insightful articles and patterns.

### Author LinkedIn URL

https://www.linkedin.com/in/adityapandita97/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/image-insight-nodejs shortly.
