### ISSUE TITLE
[New repo]: ddb-stream-opensearh-serverless

### ISSUE THREAD

**Issue by fanhongy** [aws-samples/serverless-patterns#1899]
### Description

This pattern allows you to stream new created item on a specific DynamoDB talbe to a Opensearch serverless collection for searching capability for DyanmoDB table.

### language

English

### runtime

TypeScript, Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/fanhongy/ddb-stream-opensearh-serverless/blob/main/image/ddb-stream-aoss.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

This pattern will create a DynamoDB table, an Opensearch Serverless collections. When any new item being created on the DynamoDB table, it will trigger the lambda function which index the item with it's partition key to the Opensearch serverless collection. Removing the item in DynamoDB will also trigger the lambda function to remove the it from the Opensearch Serverless collection.

### Repo URL

https://github.com/fanhongy/ddb-stream-opensearh-serverless

### Author Name

Stan Fan

### Author Image URL

https://avatars.githubusercontent.com/u/58756168?v=4

### Author Bio

Stan Fan is a Solutions Architect at Amazon Web Services (AWS) based on Sydney, Australia.

### Author LinkedIn URL

https://www.linkedin.com/in/hongyi-fan-05101992/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/ddb-stream-opensearch-serverless shortly.
