### ISSUE TITLE
New pattern submission: EventBridge to Step Function

### ISSUE THREAD

**Issue by brysontyrrell** [aws-samples/serverless-patterns#19]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a Step Function that triggers on an EventBridge rule.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

n/a

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

EventBridge to Step Function

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

The template creates a shell Step Function, with a CloudWatch log group for error reporting, that triggers on select EC2 instance state changes and branches based on the value.

## Deployment commands

```shell
sam deploy
```

## GitHub PR for template: 

#18 

## Payload example (e.g. Lambda event payload from source service).

```json
{
  "version": "0",
  "id": "6a7e8feb-b491-4cf7-a9f1-bf3703467718",
  "detail-type": "EC2 Instance State-change Notification",
  "source": "aws.ec2",
  "account": "111122223333",
  "time": "2017-12-22T18:43:48Z",
  "region": "us-west-1",
  "resources": [
    "arn:aws:ec2:us-west-1:123456789012:instance/i-1234567890abcdef0"
  ],
  "detail": {
    "instance-id": " i-1234567890abcdef0",
    "state": "terminated"
  }
}
```

## Author bio 
Name: Bryson Tyrrell
Photo URL: https://media-exp1.licdn.com/dms/image/C4E03AQFJcTd01L5vXg/profile-displayphoto-shrink_800_800/0/1567693724568?e=1622678400&v=beta&t=STGgHkgH09XmldMv5FZM0PW0-FRmr22F_GfKnl638OA

Twitter handle: bryson3gps
Description (up to 255 chars): Staff Systems Development Engineer at Jamf

**Comment by jbesw** [comment]
Hi Bryson! Can you provide a bio and photo URL for us to use in the credit box. Thanks.

**Comment by brysontyrrell** [comment]
I think that'll do for now.

**Comment by jbesw** [comment]
This was published at https://serverlessland.com/patterns/eventbridge-sfn.
