### ISSUE TITLE
New pattern submission - apigw-iam

### ISSUE THREAD

**Issue by rafaelliu** [aws-samples/serverless-patterns#190]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Creates Amazon API Gateway REST API with IAM authorizer

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

NodeJS

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

API Gateway to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This patterns creates a REST API and a `Prod` stage with a single `/` resource with a `GET` method. IAM is configured as the authorization method, and a Lambda integration with is defined with caller credentials enabled.

Two IAM users are created, one to test the correct required permission and another with insufficient permissions. Both contain policies with scoped down actions and resources. 

## Deployment commands

1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ``` 
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```
    cd apigw-iam
    ```
3. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:
    ```
    sam deploy --guided
    ```
1. During the prompts:
    * Enter a stack name
    * Enter the desired AWS Region
    * Allow SAM CLI to create IAM roles with the required permissions.

## GitHub PR for template: 

#189 

## Payload example (e.g. Lambda event payload from source service).

No payload is required. Any payload provided will be ignored.

## Author bio 
Name: Rafael Liu
Photo URL: https://d2908q01vomqb2.cloudfront.net/5b384ce32d8cdef02bc3a139d4cac0a22bb029e8/2021/09/13/headshot.jpg
Twitter handle: @rafaelliu
Description (up to 255 chars): Rafael Liu is passionate about all things software engineering and solving hard problems. He helps customers design and build architectures and processes, often leveraging DevOps and Serverless. Unashamedly a Java fan, Linux and Open Source enthusiast.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-iam.
