### ISSUE TITLE
[New repo]: Java Serverless Migration

### ISSUE THREAD

**Issue by msailes** [aws-samples/serverless-patterns#1909]
### Description

Example code for re:Invent 2023 session SVS402

### language

English

### runtime

Java

### Level

400

### Type

Application

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/maschnetwork/svs402-java-serverless-migration/main/docs/header.png?token=GHSAT0AAAAAABUPSUHOIFTQ3VGJOKQW6MAEZK7G6MQ

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Refactor Java applications to Serverless

### Repo URL

https://github.com/maschnetwork/svs402-java-serverless-migration

### Author Name

Maximilian Schellhorn

### Author Image URL

https://avatars.githubusercontent.com/u/36627945?v=4

### Author Bio

Maximilian Schellhorn works as a Solutions Architect at Amazon Web Services. Before that he worked for more than 10 years as a Software Engineer & Architect on distributed system design and monolith-to-microservice transformations. His recent work focuses on SaaS, Serverless (Java) and Event Driven Architectures.

### Author Twitter handle

https://twitter.com/maschnetwork

### Author LinkedIn URL

https://www.linkedin.com/in/maxschell/

**Comment by msailes** [comment]
This repo is currently private, and can be made public before the session.

**Comment by msailes** [comment]
The repo is now public and is ready to be added.

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/repos/svs402-java-serverless-migration shortly.
