### ISSUE TITLE
New pattern submission: Fargate to SQS CDK

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#191]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Create a Fargate Service that uses a custom image that integrates with SQS using various endpoints to `sendMessage` and `receiveMessage`, written in CDK.

## Language:

TypeScript

## Framework

CDK

## Services from/to

AWS Fargate to Amazon SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster with an Application Load Balancer in-front. The AWS Fargate service makes `sendMessage` and `receiveMessage` calls to an Amazon Simple Queue Service (SQS) queue. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built `ecs.ContainerImage.fromAsset` method. The custom image has a base route `/` for health checks, `/sendmessage` for adding to the queue and `/readmessage` for reading messages from the queue. Environment variables like the SQS Queue URL and AWS region are passed to the image to enable it to perform actions on the SQS Queue.

This project also shows how to set up an SQS Interface Endpoint to the VPC. A VPC Endpoint policy is created to only allow the Fargate task definition to perform actions through the VPC endpoint. In addition, an access policy is set on the SQS queue to deny requests that are not from the created Interface Endpoint.

IAM permissions

1. Read and Writes to the bucket are controlled using the built-in CDK permissions via `sqsQueue.grantSendMessages(fargate.taskDefinition.taskRole);` and `sqsQueue.grantConsumeMessages(fargate.taskDefinition.taskRole);`
2. VPC Endpoint policies allow only the Fargate Service `'sqs:SendMessage', 'sqs:ReceiveMessage'` actions on the SQS queue
3. Custom SQS Access Policies deny access to the SQS queue if it isn't from the VPC Endpoint.  This forces requests to only come from within the AWS network. The template for the access policy is referenced from [AWS SQS Developer Guide: Deny access if it isn't from a VPC endpoint](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-creating-custom-policies-access-policy-examples.html#deny-not-from-vpc)

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#192 

## Payload example (e.g. Lambda event payload from source service).

There are 2 endpoints that integrate with the SQS queue.

Make a POST request to the `/sendmessage` endpoint. This adds a message to the SQS queue. For example:

```bash
curl --location --request POST '<REPLACE WITH FARGATE SERVICE URL>/sendmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "MessageBody": "hello serverless fargate sqs"
}'
# Example
curl --location --request POST 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/sendmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "MessageBody": "hello serverless fargate sqs"
}'
```

Make a GET request to the `/readmessage` endpoint. This retrieves the message from the queue. For example:

```bash
curl --location --request GET '<REPLACE WITH FARGATE SERVICE URL>/readmessage'
# Example
curl --location --request GET 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/readmessage'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

Retrieve the Service URL from `cdk deploy`

![image](https://user-images.githubusercontent.com/31919569/140491415-b8263e4c-f5d8-4a60-8b3d-59c3941c930e.png)

Running all the requests above should produce the following output:

![image](https://user-images.githubusercontent.com/31919569/140491436-1971906e-7961-44fe-92dd-bd97e8f223a9.png)

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn (Handle for Serverless Pattern website): https://www.linkedin.com/in/glenn-chia-291344142
Twitter (Handle for Twitter mentions): @ glenncjw (https://twitter.com/glenncjw)
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/patterns/cdk-fargate-sqs.
