### ISSUE TITLE
[New repo]: GenAI chatbot for Text Generation use-case.

### ISSUE THREAD

**Issue by awsarippa** [aws-samples/serverless-patterns#1918]
### Description

The repository shows a serverless way of how to leverage GenAI capabilities to build a NextGen chatbot. The PR shows creating a solution/pattern utilizing Amazon Lex, Lambda, and Bedrock to leverage GenAI capabilities in Lex-based chatbots.

### language

English

### runtime

Python

### Level

100

### Type

Application

### Use case

Backend

### Primary image

https://github.com/awsarippa/lex-lambda-bedrock-cdk-python/blob/main/diagrams/architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

The solution is built on three AWS services - Bedrock, Lambda, and Lex. This pattern will create a Lex chatbot and a Lambda. When a user interacts with Lex bot to generate some text, the Lambda interacts with Bedrock service through API calls and subsequently interacts with Claude-2 Foundation model from Anthropic for generating text. The generated text is then sent back to the user.

Users can change the Foundation Model as required according to their choice and needs to be added as an environment variable in the CDK code for deploying application.

### Repo URL

https://github.com/awsarippa/lex-lambda-bedrock-cdk-python

### Author Name

Arjun Arippa

### Author Image URL

https://github.com/awsarippa/amazon-textract-comprehend-pii-analysis/blob/main/image.png

### Author Bio

Arjun Arippa is a Solutions Architect with AWS India, based out of Bangalore, India. Arjun works with some of the strategic and global customers in building solutions on AWS.

### Author LinkedIn URL

https://www.linkedin.com/in/arjun-arippa/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/amazon-textract-comprehend-pii-analysis shortly.

**Comment by awsarippa** [comment]
@jbesw - Thnx. However one point. The url to the link should've been  https://serverlessland.com/repos/lex-lambda-bedrock-cdk-python instead of https://serverlessland.com/repos/amazon-textract-comprehend-pii-analysis
