### ISSUE TITLE
[New repo]: MongoDB Atlas with API Gateway and Cognito User Pool 

### ISSUE THREAD

**Issue by deeptichugh28** [aws-samples/serverless-patterns#1923]
### Description

A quick-start project for API based application with MongoDB Atlas, APIGW and Lambda.A step-by-step guide for deploying a robust REST API powered by Lambda functions, expertly bridging the gap between MongoDB Atlas and AWS, all with the added convenience of automation through AWS CDK.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/deeptichugh28/Quickstart_APIGW_MongoDB/blob/main/QuickStartArchitecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

MongoDB Atlas with API Gateway and Cognito User Pool 

### Repo URL

https://github.com/deeptichugh28/Quickstart_APIGW_MongoDB.git

### Additional resources

[https://github.com/deeptichugh28/Quickstart_APIGW_MongoDB/blob/main/MongoDB%20Atlas%20with%20API%20Gateway%20and%20Cognito%20User%20Pool%20V2.docx](url)

### Author Name

Deepti Chugh(Senior PSA - AWS), Bharath S(Senior PSA - AWS) and Babu Srinivasan(Senior PSA - MongoDB)

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/quickstart-apigw-mongodb shortly.
