### ISSUE TITLE
[New repo]: Fair Play Guardian - Collusion Detection in Multiplayer Online Gaming through Profile Picture Validation.

### ISSUE THREAD

**Issue by sshekghub** [aws-samples/serverless-patterns#1931]
### Description

Collusion detection in multiplayer online gaming has seen a rise, with players now uploading their 
profile pictures along with their cell phone numbers. 
This facilitates easy communication among players, enabling them to collaborate and engage in collusion 
or cheating activities aimed at gaining an unfair advantage over others during gameplay. 
Those participating in collusion efforts cooperate to assist one another, share information, 
or deliberately lose in order to favor a particular player or group of players.

This application provides a remedy for identifying collusion in multiplayer online gaming by verifying the profile picture. 
Upon the user's upload of the profile picture, the application uses Amazon Textract to recognize text within the image 
promptly. Subsequently, it applies a Gaussian blur filter to obscure the detected text.

### language

English

### runtime

Python 3.11

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/aws-samples/fair-play-guardian/blob/main/FPG-Architecture.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Fair Play Guardian - Collusion Detection in Multiplayer Online Gaming through Profile Picture Validation.

### Repo URL

https://github.com/aws-samples/fair-play-guardian

### Additional resources

https://aws.amazon.com/textract/
https://pillow.readthedocs.io/en/stable/handbook/overview.html

### Author Name

Shekhar Shrinivasan

### Author Image URL

https://avatars.githubusercontent.com/u/58206425?s=400&u=90899732423049a2e45523f631ab0379330aec62&v=4

### Author Bio

Senior Technical Consultant specializing in AWS cloud, adept at guiding clients through seamless cloud adoption. Proven expertise in designing and architecting robust solutions, ensuring optimal performance and efficiency for diverse business needs.

### Author LinkedIn URL

https://www.linkedin.com/in/shekhar-shrinivasan/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/fair-play-guardian shortly.
