### ISSUE TITLE
[New repo]: Amazon API Gateway Custom Domain for Private API

### ISSUE THREAD

**Issue by tgpadua** [aws-samples/serverless-patterns#1932]
### Description

This CDK pattern implements the workaround solution presented [here](https://serverlessland.com/repos/apigw-private-custom-domain-name).
API calls to a fully qualified name (FQDN), such as private.domain.com, are resolved by Route53 to a Network Load Balancer (NLB) and forwarded to the API Gateway.

### language

English

### runtime

Node.JS

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/apigateway-custom-domain-for-private-api-cdk/main/resources/architecture.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Amazon API Gateway Custom Domain for Private API CDK Project

### Repo URL

https://github.com/aws-samples/apigateway-custom-domain-for-private-api-cdk

### Additional resources

https://serverlessland.com/repos/apigw-private-custom-domain-name

### Author Name

Thiago Pádua

### Author Image URL

https://serverlessland.com/assets/images/resources/thiago-padua.jpeg

### Author Bio

Senior Partner Solutions Architect, Serverless at Amazon Web Services (AWS)

### Author LinkedIn URL

https://www.linkedin.com/in/thiagopadua

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/apigateway-custom-domain-for-private-api-cdk shortly.
