### ISSUE TITLE
Auth0 API Destination addition

### ISSUE THREAD

**Issue by PurpleAmyr** [aws-samples/serverless-patterns#1948]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**IMPORTANT**
Patterns are intended to be primarily IaC-focused implementations of 2-4 AWS services, with minimum custom code. They should be commonly used combinations that help developers get started quickly. If you have a utility, demo, or application, submit these to the [Serverless Repos Collection](https://serverlessland.com/repos) instead.

**ONLY SUBMIT ONE PATTERN CHANGE PER PR**. Multiple patterns or files spanning multiple pattern directories will be automatically rejected.

Patterns may take up to 4-6 weeks to review, test, and merge but there is no SLA and can take significantly longer due to other work the team has.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:

Description:
This pattern creates an API Destination for the Auth0 SignUp API. Once deployed, the pattern allows a user to send events easily through EventBridge to Auth0 in order to create users. The pattern creates the following resources: EventBridge Bus, EventBridge Connection, EventBridge API Destination, EventBridge rule, IAM role, and SQS queue.

The EventBridge rule uses the API Destination and Connection as a target, SQS queue as a DLQ, and the IAM role as its role. To send events, go to the bus and send sample events. Enter “MyAuth0App” for the source, the bus created by the pattern for the Event Bus Name, and any call that follows the format for the SignUp API as the detail (https://auth0.com/docs/api/authentication?http#signup).

The following information is needed to use the pattern: 
	Environment Name: Needed in order to create the API Call
	Client ID: Required and will be put within the API Call as a secret ID by the template
	Email, Password, Connection type: Will be needed in Request Body
	
The IAM role created by the pattern only has the permission to allow InvokeApiDestination access to the EventBridge rule.

Resources:
https://auth0.com/docs/api/authentication?http#signup
https://auth0.com/docs/authenticate/identity-providers/test-connections
https://auth0.com/docs/authenticate/identity-providers/view-connections

Author:
Omid Khan. AWS Solutions Architect. https://www.linkedin.com/in/ok6av/

Request:
https://github.com/aws-samples/serverless-patterns/pull/1945
#1945

**Comment by jbesw** [comment]
This pattern is does not contain all the files needed for a submission. Please review the guidelines and resubmit with a complete package.
