### ISSUE TITLE
New serverless pattern - apigw-http-api-lambda-cdk

### ISSUE THREAD

**Issue by eduborto** [aws-samples/serverless-patterns#195]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create and Amazon API Gateway HTTP API with a Lambda function as backend

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway HTTP API to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern creates an Amazon API Gateway HTTP API and an AWS Lambda function using AWS Cloud Development Kit (AWS CDK) in Python. This template also has a sample CORS configuration. The sample application was developed in Python and it shows some context, event and environment variables properties.

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/194

## Additional resources (optional: link and anchor text, up to 5 resources)
[Working with HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html)
[Working with AWS Lambda proxy integrations for HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)
[Lambda function handler in Python](https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html)
[AWS Lambda context object in Python](https://docs.aws.amazon.com/lambda/latest/dg/python-context.html)

## Author bio 
Name: Eduardo Bortoluzzi
Photo URL: https://photos.google.com/share/AF1QipP5x0EZDy75uIwSEaNiw2BsushKjt7OyFQDPwcfqb5oXzHb70u7W1WBwi-eacSGdA?key=S0p4STNpMkx0REQxcHBJZUJobWdLd2tMZzRKOUN3 
Twitter handle: @edubortoluzzi
Description (up to 255 chars): I am an AWS Cloud Applications Architect at the Professional Services team. I have been working with Cloud Computing since 2008 and I recommends serverless every time I can.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-http-lambda-cdk.
