### ISSUE TITLE
API Gateway HTTP API and REST API mismatch

### ISSUE THREAD

**Issue by garysassano** [aws-samples/serverless-patterns#1958]
I have observed multiple inconsistencies between the architecture diagrams and descriptions regarding the use of API Gateway in various serverless patterns.

![api-gateway-api-mismatch-1](https://github.com/aws-samples/serverless-patterns/assets/10464497/6ef86c49-71ec-4634-ab8b-86052b0ed380)
![api-gateway-api-mismatch-2](https://github.com/aws-samples/serverless-patterns/assets/10464497/a90bba4e-a2c1-4688-930b-555549ad82b1)

**Comment by bls20AWS** [comment]
Thanks for reporting, i have fixed some that i have found. if you spot any more please share the link to the page.
