### ISSUE TITLE
Update CDK patterns using API Gateway HTTP API

### ISSUE THREAD

**Issue by garysassano** [aws-samples/serverless-patterns#1959]
Numerous CDK patterns in Serverless Land utilizing API Gateway HTTP API should be updated to incorporate the newly stable `aws_apigatewayv2`, introduced in CDK [v2.114.0](https://github.com/aws/aws-cdk/releases/tag/v2.114.0), replacing the `aws_apigatewayv2_alpha` module.

**Comment by jbesw** [comment]
I'll pass this request to the team but close this for now, since we only use Issues to track new patterns or specific bugs where code has been proposed.
