### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by jainniha** [aws-samples/serverless-patterns#1962]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**IMPORTANT**
Patterns are intended to be primarily IaC-focused implementations of 2-4 AWS services, with minimum custom code. They should be commonly used combinations that help developers get started quickly. If you have a utility, demo, or application, submit these to the [Serverless Repos Collection](https://serverlessland.com/repos) instead.

**ONLY SUBMIT ONE PATTERN CHANGE PER PR**. Multiple patterns or files spanning multiple pattern directories will be automatically rejected.

Patterns may take up to 4-6 weeks to review, test, and merge but there is no SLA and can take significantly longer due to other work the team has.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
This pattern send personalized web push notifications using pinpoint, amplify, lambda and api gateway.
<img width="811" alt="Screenshot 2023-12-15 at 11 29 24 AM" src="https://github.com/aws-samples/serverless-patterns/assets/120422574/97078ea3-5cbb-4370-b4b7-fa8d7ee37f5b">

This is the target architecture we are building. This will use react for the front end and the authentication will be done through AWS Cognito and Amplify will automate the deployment process and we are using it for the web hosting.

 There is an api gateway infront of the two lambda's we are using. One of the lambda is used to send notifications using pinpoint. The pinpoint then connects with FCM ( Firebase Cloud Messaging) to send the notifications. The other lambda is used to update the token in the dynamodb table (user table). Each user will have a unique token to which we send the web push notifications. In case of push notifications to the mobile device, A unique token is issued for each mobile which allows to send the notifications to the mobile. 

AWS Amplify

Amazon Pinpoint

ReactJS

AWS Cognito

Amazon API Gateway

AWS Lambda

NodeJS

Android Studio (emulator)

Java

Amazon DynamoDB

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).

- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/1961

**Comment by bls20AWS** [comment]
closed, please resubmit as a repo
