### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by shaniru-aws** [aws-samples/serverless-patterns#1964]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**IMPORTANT**
Patterns are intended to be primarily IaC-focused implementations of 2-4 AWS services, with minimum custom code. They should be commonly used combinations that help developers get started quickly. If you have a utility, demo, or application, submit these to the [Serverless Repos Collection](https://serverlessland.com/repos) instead.

**ONLY SUBMIT ONE PATTERN CHANGE PER PR**. Multiple patterns or files spanning multiple pattern directories will be automatically rejected.

Patterns may take up to 4-6 weeks to review, test, and merge but there is no SLA and can take significantly longer due to other work the team has.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.

This pattern demonstrates how to create an EventBridge scheduler that would send a reminder email if no action is taken on a CodePipeline Manual Approval action after a given duration.

This pattern takes sender and receiver email address along with SNS topic as an input. This SNS topic should be linked to the Manual approval action of a pipeline. When the pipeline reaches manual approval action, SNS topic invokes a Lambda function which collects all the relevant pipeline and manual approval action details and creates a scheduler. Scheduler invokes a Lambda function after 6 hours to check if status of pipeline and manual approval stage, if no new action has been taken on the pipeline yet then it sends a new email using SES.

Language: (optional e.g. "Python", if you have a Lambda function in your example)
----
Python for Lambda function, Typescript for CDK. 

Framework (currently we support SAM or CDK)
----
CDK

Services from/to (e.g. "Lambda to EventBridge)
----

SNS -> Lambda ->  EventBridgeScheduler -> Lambda -> SES

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
https://docs.aws.amazon.com/codepipeline/latest/userguide/approvals.html
https://docs.aws.amazon.com/scheduler/latest/UserGuide/getting-started.html

- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
----

I am Anirudh, a Cloud Support Engineer - 2 at AWS India. I help customers solve complex problems with simple solutions.

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Please resubmit as a repo

https://serverlessland.com/repos. Patterns are intended to be small, low-code IaC integrations only.
