### ISSUE TITLE
New pattern submission - sfn-sqs-cdk

### ISSUE THREAD

**Issue by revanthreddy** [aws-samples/serverless-patterns#197]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AWS Step Functions workflow to integrate with Amazon SQS using CDK.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Functions to Amazon SQS (CDK)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This CDK application deploys a Step Functions workflow, that takes in a payload and sends part of it to an Amazon SQS. In this pattern, the state machine does not wait for a callback from the queue. The application contains the minimum IAM resources required to run the workflow. You can find the SAM template for the same pattern [here](https://serverlessland.com/patterns/sfn-sqs)

## Deployment commands
`cdk deploy`

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/196

## Payload example (e.g. Lambda event payload from source service).
`
{
    "message": {
      "hello" : "world"
    }
}
`

_Note: This payload is part of execution input of the step function resource that is created._

## Author bio 
Name: Revanth Anireddy
Photo URL: https://twitter.com/revanthreddy/photo
Twitter handle: @revanthreddy
Description (up to 255 chars): Senior Cloud Applications Architect @ AWS. 
Swimmer, Artist, Foodie, Movie & Sports trivia enthusiast in my spare time.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at: https://serverlessland.com/patterns/sfn-sqs-cdk.
