### ISSUE TITLE
[New repo]: serverless pattern Remove completed Amazon EventBridge Schedules and sent notification using Amazon SNS

### ISSUE THREAD

**Issue by manikandanks2000** [aws-samples/serverless-patterns#1993]
### Description

Remove completed Amazon EventBridge Schedules and sent notification using Amazon SNS

This pattern will create an Amazon EventBridge Scheduler and will run every five minutes and will use AWS Lambda to identify expired and completed Amazon Evenbridge Scheduler tasks that are expired 7 days or more and will send an SNS notification once the activity is completed. The pattern is deployed using the AWS Cloud Development Kit (AWS CDK) for Python.

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

PNG

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Remove completed Amazon EventBridge Schedules and sent notification using Amazon SNS 

### Repo URL

https://github.com/aws-samples/serverless-patterns/pull/1992

### Additional resources

https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_scheduler/CfnSchedule.html

### Author Name

Manikandan Karimanal

### Author Image URL

https://drive.google.com/file/d/16r4jGGMpPhu4Igez-lzstIe-L5nJVMxf/view

### Author Bio

Manikandan Karimanal is a Senior Solution Architect at Amazon Web Services. He supports Travel and Hospitality customers in their transformation journey and love how serverless technologies can accelerate the way they build and run applications. He played multiple roles in product organizations and consulting organizations for more than 22 years covering Retail, eCommerce, Hospitality,Insurance and POS customers.

### Author LinkedIn URL

https://www.linkedin.com/in/manikandanks/

**Comment by bls20AWS** [comment]
I belive you have also submitted this as a pattern? It is currently under review in that context and will be published as such when complete.
