### ISSUE TITLE
[New repo]: serverless pattern EventBridge Pipe from SQS to Step Functions with filter and transformation

### ISSUE THREAD

**Issue by manikandanks2000** [aws-samples/serverless-patterns#1995]
### Description

This pattern will use Amazon EventBridge Pipe to accept source messages from Amazon Simple Queue Service and will apply filter and transformation before sending the target message to AWS Step Functions.

### language

English

### runtime

Python

### Level

300

### Type

Examples

### Use case

Backend

### Primary image

PNG

### IaC framework

CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [X] Amazon EventBridge
- [ ] AWS IoT
- [ ] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Amazon EventBridge Pipe from SQS to Step Functions with filter and transformation

### Repo URL

https://github.com/aws-samples/serverless-patterns/pull/1994

### Additional resources

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html

### Author Name

Manikandan Karimanal

### Author Image URL

https://drive.google.com/file/d/16r4jGGMpPhu4Igez-lzstIe-L5nJVMxf/view

### Author Bio

Senior Solution Architect @AWS

### Author LinkedIn URL

https://www.linkedin.com/in/manikandanks/

**Comment by bls20AWS** [comment]
I believe you have also submitted this as a pattern? it will be reviewed and published in that PR: https://github.com/aws-samples/serverless-patterns/pull/1994, not as a repo.
