### ISSUE TITLE
Add allowHeaders?

### ISSUE THREAD

**Issue by asunar** [aws-samples/serverless-patterns#2]
Do we need to add allow headers to api.yaml similar to [here](https://github.com/aws-samples/contact-form-processing-with-synchronous-express-workflows/blob/93be0c3b0fffd009667508b12b8858dad35c0145/api.yaml#L25) to avoid CORS errors?

Details:
https://forums.aws.amazon.com/thread.jspa?threadID=337219&tstart=0

**Comment by jbesw** [comment]
Hi! Which pattern are you referring to?

**Comment by asunar** [comment]
Sorry, `apigw-sfn`

**Comment by bls20AWS** [comment]
Hi Asunar. If you wanted to call the service from a web browser then yes thank should help to avoid CORS errors: you could also add some configuration to the SAM template similar to this example:
https://github.com/aws-samples/happy-path/blob/master/backend/template.yaml
