### ISSUE TITLE
New repo - Generative AI Prompt Chaining

### ISSUE THREAD

**Issue by clareliguori** [aws-samples/serverless-patterns#2003]
### Description

Prompt chaining is a generative AI technique for accomplishing complex tasks with large language models (LLMs). With prompt chaining, complex tasks are broken down into smaller well-defined subtask prompts, and each prompt is fed to the LLM in a defined order. This repository provides an example application that uses AWS Step Functions and Amazon Bedrock to build complex generative AI functionality with prompt chaining.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://raw.githubusercontent.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/main/docs/architecture/ServerlessPromptChainingArchitecture-Small.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [X] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Use AWS Step Functions to chain generative AI prompts and invoke large language models on Amazon Bedrock.

### Repo URL

https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining

### Author Name

Clare Liguori

### Author Bio

Clare Liguori is a Senior Principal Software Engineer at AWS. She works on Amazon Q and focuses on improving developer productivity through generative AI.

### Author Twitter handle

clare_liguori

### Author LinkedIn URL

https://www.linkedin.com/in/clareliguori

**Comment by jbesw** [comment]
Thanks - this is now live on https://serverlessland.com/repos/amazon-bedrock-serverless-prompt-chaining.
