### ISSUE TITLE
[New repo]: GenAI chatbot for Image Generation use-case

### ISSUE THREAD

**Issue by awsarippa** [aws-samples/serverless-patterns#2006]
### Description

The repository shows a serverless way of how to leverage GenAI capabilities to build a NextGen chatbot. The PR shows creating a solution/pattern utilising Amazon Lex, Lambda, and Bedrock to leverage GenAI capabilities in Lex-based chatbots.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://github.com/awsarippa/lex-lambda-genai-imagegen-chatbot/blob/main/diagrams/archie_diagram.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

The solution is built on four AWS services - Bedrock, Lambda, S3, and Lex. This pattern will create a Lex chatbot, S3 bucket, and a Lambda. When a user interacts with Lex bot to generate some image, the Lambda interacts with Bedrock service through API calls and subsequently interacts with Stable Diffusion XL foundation model from StabilityAI for generating image. The generated image is then stored in a S3 bucket and a pre-signed url is sent back to the user.  Users can change the Foundation Model as required according to their choice and needs to be added as an environment variable in the CDK code for deploying application.

### Repo URL

https://github.com/awsarippa/lex-lambda-genai-imagegen-chatbot/tree/main

### Author Name

Arjun Arippa

### Author Image URL

https://github.com/awsarippa/amazon-textract-comprehend-pii-analysis/blob/main/image.png

### Author Bio

Arjun Arippa is a Solutions Architect based in Bangalore, India. He works with some of the strategic and global customers in India, to build and architect their applications on AWS. Before joining AWS, Arjun spent over a decade working as a Software Developer. Reach out to him on LinkedIn

### Author LinkedIn URL

https://www.linkedin.com/in/arjun-arippa/

**Comment by bls20AWS** [comment]
will be published to https://serverlessland.com/repos/genai-chatbot-for-image-generation-use-case within 24 hours

**Comment by awsarippa** [comment]
Thanks a lot @bls20AWS - Appreciate the effort for the review and suggestions.
