### ISSUE TITLE
New pattern submission - s3-to-lambda-cdk

### ISSUE THREAD

**Issue by mariofonteles** [aws-samples/serverless-patterns#202]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that triggers when objects are stored in a S3 bucket.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
NodeJS.

## Framework (currently we support SAM or CDK)

CDK.
## Services from/to (e.g. "Lambda to EventBridge)

S3 to Lambda (CDK).
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This CDK stack deploys a Lambda function, a S3 bucket, and the minimum IAM resources required to run the application.

When items are written in the S3 bucket, the changes are sent to a stream. This pattern configures a Lambda function to poll this stream, and log some information to CloudWatch. The function is invoked with a payload containing the information of the event.
## Deployment commands
`cdk deploy`
## GitHub PR for template: 

#201 

## Payload example (e.g. Lambda event payload from source service).

No payload is required, the pattern already has an example file to use with instructions. However, if one wishes to test with a different file, all that is required is pushing the file to the S3 bucket like this:

```bash
aws s3 cp 'path/to/file.format'  s3://{SourceBucketName}
```
More detailed instructions are included in the pattern's README.

## Author bio 
Name: Mário Fonteles
Photo URL: https://avatars.githubusercontent.com/u/7582742?v=4
Twitter handle:
Description (up to 255 chars): Mário is a Frontend Developer at AWS.

**Comment by jbesw** [comment]
Thanks for your contribution! This is live at https://serverlessland.com/patterns/s3-lambda-cdk.
