### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by revanthreddy** [aws-samples/serverless-patterns#204]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AWS Step Functions workflow to integrate with Amazon DynamoDB

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Functions to Amazon DynamoDB (CDK)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The CDK application deploys a Step Functions workflow, that takes in a payload and puts the item in DynamoBb. Additionally, this workflow also shows how to read an item directly from the DynamoDB table. The CDK application contains the minimum IAM resources required to run the application. You can find the SAM template for the same pattern [here](https://serverlessland.com/patterns/sfn-dynamodb) 

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/203

## Payload example (e.g. Lambda event payload from source service).
`
{
    "id": "12345"
}
`

_Note: This payload is part of execution input to the step function resource that is created as part of this stack._

## Author bio 
Name: Revanth Anireddy
Photo URL: https://twitter.com/revanthreddy/photo
Twitter handle: @revanthreddy
Description (up to 255 chars): Senior Cloud Applications Architect @ AWS. 
Swimmer, Artist, Foodie, Movie & Sports trivia enthusiast in my spare time.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/sfn-dynamodb-cdk.
