### ISSUE TITLE
[New repo]: Multi region solution with SNS FIFO-SQS FIFO using DDB global tables

### ISSUE THREAD

**Issue by DeepaliTandale** [aws-samples/serverless-patterns#2056]
### Description

Multi region solution using sqs and sns extended library gives you ability to process your messages >256KB. It involves setting up a duplicated message queue that can handle messages larger than 256 Kb while maintaining their sequence. Additionally, a sqs in backup region process messages if any service in the main region encounters issues. For this solution Lambda is a producers and consumers, but customer can have there own logic or services with similar multi-region architecture for message processing.

### language

English

### runtime

Python

### Level

200

### Type

Application

### Use case

Backend

### Primary image

https://gitlab.aws.dev/dtandale/multiregionwithextendedlibapp/-/raw/main/img_2.png

### IaC framework

AWS CDK

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Multi region solution with SNS FIFO-SQS FIFO using DDB global tables

### Repo URL

https://gitlab.aws.dev/dtandale/multiregionwithextendedlibapp

### Author Name

Deepali Tandale

**Comment by jbesw** [comment]
We can only publish public repos - please update this with a public GitHub repo and ensure you bio information is complete.

**Comment by DeepaliTandale** [comment]
Hello, moved my code to GitHUB repo. Here's the link. https://github.com/DeepaliTandale/multiregionwithextendedlibapp 
Thank you.

**Comment by julianwood** [comment]
This has been added to Serverless Land and will be available at: https://serverlessland.com/repos/multi-region-with-sns-fifo-sqs-fifo-using-ddb-global-tables
