### ISSUE TITLE
New pattern submission - IoT rule to SQS with custom authorizer

### ISSUE THREAD

**Issue by enochtsai** [aws-samples/serverless-patterns#206]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an IoT rule that fowards events to SQS

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
nodejs

## YouTube videoId (optional e.g. "VI79XQW4dIM")
None

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
IoT to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Create IoT Rule to receive iot events and forward to a SQS queue to be processed by a lambda function. It also creates a custom authorizer to allow users to bring their own authentication to iot data endpoint to receive events through mqtt over http 

## Deployment commands
sam deploy --guided --capabilities CAPABILITY_NAMED_IAM

## GitHub PR for template: 
[205](https://github.com/aws-samples/serverless-patterns/pull/205)

## Additional resources (optional: link and anchor text, up to 5 resources)
IoT Rule: https://docs.aws.amazon.com/iot/latest/developerguide/iot-rules.html
Understanding the custom authentication workflow: https://docs.aws.amazon.com/iot/latest/developerguide/custom-authorizer.html

## Author bio 
Name: Enoch Tsai
Photo URL:
Twitter handle:
Description (up to 255 chars):
Enoch Tsai is a cloud application architect advocate for Serverless Applications at Amazon Web Services based in the US. Prior to joining AWS Enoch worked in a number of different technical roles specializing in native cloud development and adaption for enterprise system.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/iot-sqs.
