### ISSUE TITLE
New pattern submission - API Gateway to S3

### ISSUE THREAD

**Issue by ykkarra** [aws-samples/serverless-patterns#208]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This AWS CDK Construct implements an Amazon API Gateway REST API connected to Amazon S3 bucket(s).

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

N/A

## YouTube videoId (optional e.g. "VI79XQW4dIM")

N/A

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

API Gateway to S3

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

A new Solutions Constructs pattern that creates a REST API as an Amazon S3 proxy in API Gateway. An IAM role with S3 (Read and Write access) will be created and associated to API Gateway. 

## Deployment commands

cdk deploy

## GitHub PR for template: 

N/A

## Payload example (e.g. Lambda event payload from source service).

N/A

## Author bio 
Name: Yogananda Karra
Photo URL:
Twitter handle:
Description (up to 255 chars):

**Comment by jbesw** [comment]
Is there a PR for this submission?

**Comment by jbesw** [comment]
Each submission must reference a pull request (PR) with the associated template, code and README. Please see one of the closed issues for an example.

**Comment by jbesw** [comment]
Please reopen once a PR is ready.
