### ISSUE TITLE
New serverless pattern - lambda-redpanda-serverless 

### ISSUE THREAD

**Issue by dlamb2471** [aws-samples/serverless-patterns#2083]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern demonstrates how to deploy and configure a Redpanda cluster in Amazon EKS, and to enable integration with Lambda event triggering via the Kafka API interface.
This allows you to easily use Lambda functions to consume data streams from your topics in Redpanda.

Language: (optional e.g. "Python", if you have a Lambda function in your example)

N/A
YouTube videoId (optional e.g. "VI79XQW4dIM")
Framework (currently we support SAM or CDK)

SAM
Services from/to (e.g. "Lambda to EventBridge)

Lambda to Redpanda (Running on EKS)
Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern demonstrates how to deploy and configure a Redpanda cluster in Amazon EKS, and to enable integration with Lambda event triggering via the Kafka API interface.",

This allows you to easily use Lambda functions to consume data streams from your topics in Redpanda.

The template will deploy a Private Route 53 Hosted Zone with A name records for the Redpanda nodes. It will also deploy a Lambda function to receive the published messages from our Redpanda topic, along with a role granting the Lambda function the necessary permissions. Further, it will create VPC Endpoints for Lambda, STS, and Secretsmanager, to enable secure communications to these services from the EKS cluster. Finally, a Secrets Manager secret will be created with the credentials needed for the Lambda function to receive events from Redpanda.

Deployment commands

sam deploy -t template.yaml --guided --capabilities CAPABILITY_NAMED_IAM
GitHub PR for template:

https://github.com/aws-samples/serverless-patterns/pull/2082
Payload example (e.g. Lambda event payload from source service).

N/A
Additional resources (optional: link and anchor text, up to 5 resources)

[AWS Lambda](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html)
[Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
[Deploy a Redpanda Cluster in Amazon Elastic Kubernetes Service](https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/eks-guide/)

Author bio

Name: David Lamb
Photo URL: n/a
Twitter handle: n/a
Description (up to 255 chars): Solutions Architect at AWS.
Name: Mithun Mallick
Photo URL:n/a
Twitter handle: n/a
Description (up to 255 chars): Serverless Principal Solutions Architect at AWS.

**Comment by pputhran** [comment]
PR has been merged in
