### ISSUE TITLE
New pattern submission: API Gateway to AWS Batch

### ISSUE THREAD

**Issue by pputhran** [aws-samples/serverless-patterns#209]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a REST API to submit a job to AWS Batch

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway to AWS Batch

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This template creates an API Gateway REST API integration with AWS Batch and can submit jobs to AWS Batch. This pattern addresses some nuances with defining the VTL template mapping when integrating with AWS Batch. It also creates an IAM execution role with permissions to submit AWS Batch job.

## Deployment commands
sam deploy

## Payload example (e.g. Lambda event payload from source service).
`{
  "jobName": "jobname",
  "jobQueue": "JobQueue-83cec74b31f900a",
  "jobDefinition": "JobDefinition-578791ccae9e80e"
}`

## Author bio 
Name: Pawan Puthran
Photo URL:  https://twitter.com/pawanputhran/photo
Twitter handle:  https://twitter.com/pawanputhran
Description (up to 255 chars): Principal Serverless Specialist at AWS.

**Comment by jbesw** [comment]
Hello, is there a PR for this pattern submission?

**Comment by pputhran** [comment]
[PR 216](https://github.com/aws-samples/serverless-patterns/pull/216)

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/patterns/apigw-rest-batch.
