### ISSUE TITLE
[New repo]: Redpanda Integration with AWS Lambda

### ISSUE THREAD

**Issue by dlamb2471** [aws-samples/serverless-patterns#2094]
### Description

This example demonstrates how to deploy and configure a Redpanda cluster in Amazon EKS, and to enable integration with Lambda event triggering via the Kafka API interface.

This allows you to easily use Lambda functions to consume data streams from your topics in Redpanda.

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/dlamb2471/lambda-redpanda/raw/main/architecture-lambda-redpanda.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Redpanda Integration with AWS Lambda

### Repo URL

https://github.com/dlamb2471/lambda-redpanda

### Additional resources

[AWS Lambda](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html)
[Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
[Deploy a Redpanda Cluster in Amazon Elastic Kubernetes Service](https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/eks-guide/)

### Author Name

David Lamb & Mithun Mallick

### Author Image URL

https://github.com/dlamb2471/lambda-redpanda/blob/main/DavidLamb.jpg

### Author Bio

David Lamb is a Solutions Architect with AWS.
Mithun Mallick is a Serverless Principal Solutions Architect at AWS.

### Author LinkedIn URL

https://www.linkedin.com/in/david-lamb-1059a62

**Comment by julianwood** [comment]
Thanks, this repo will be available on Serverless Land shortly
