### ISSUE TITLE
CDK deploy fails on "eventbridge_pipes_dynamodbstream_to_sqs_cdk_python"

### ISSUE THREAD

**Issue by mslshao** [aws-samples/serverless-patterns#2098]
Can't get `eventbridge_pipes_dynamodbstream_to_sqs_cdk_python` to run.

Followed setup instructions in the main `README.md`, here: https://github.com/aws-samples/serverless-patterns/tree/main/eventbridge-pipes-dynamodbstream-to-sqs-cdk-python

`cdk deploy` fails with a very obscure error message.

**Comment by boyney123** [comment]
Thanks @mslshao I will take a look at this.

**Comment by boyney123** [comment]
Can you paste the error you are getting @mslshao ?

**Comment by boyney123** [comment]
Just tried the pattern, following the instructions and managed to deploy.

**Comment by mslshao** [comment]
Which version of CDK are you on? I am using `0.39.7` now but was using a different version before.

**Comment by boyney123** [comment]
`2.90.0`, is it working now?

I'm going to close the issue, but please re-open if you still have issues. Try updating your CDK version if possible.
