### ISSUE TITLE
New pattern submission: Fargate to Aurora Serverless

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#210]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Create a Fargate Service that uses a custom image that integrates with Aurora Serverless using various endpoints to execute SQL commands, written in CDK.

## Language:

TypeScript

## Framework

CDK

## Services from/to

AWS Fargate to Amazon Aurora Serverless

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster with an Application Load Balancer in-front. The AWS Fargate service executes commands against an Amazon Aurora Serverless Cluster. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built `ecs.ContainerImage.fromAsset` method. The custom image has a base route `/` for health checks, `/createtable` for adding a table to the database, and `/showtables` for displaying a list of tables in the database. Environment variables like the database name, secrets ARN, and Aurora Serverless Cluster ARN are passed to the image to enable it to perform actions on the Database.

IAM permissions

1. Read and Writes to the Data API are controlled using the using the built-in CDK permissions via `auroraServerlessCluster.grantDataApiAccess(fargate.taskDefinition.taskRole);`

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#211

## Payload example (e.g. Lambda event payload from source service).

There are 2 endpoints that integrate with the Aurora Serverless Cluster.

Make a POST request to the `/createtable` endpoint. This creates a table with the specified table name in the Aurora Serverless Cluster database. For example:

```bash
curl --location --request POST '<REPLACE WITH FARGATE SERVICE URL>/createtable' \
--header 'Content-Type: application/json' \
--data-raw '{
    "tableName": "music"
}'
# Example
curl --location --request POST 'http://CdkSt-Farga-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/createtable' \
--header 'Content-Type: application/json' \
--data-raw '{
    "tableName": "music"
}'
```

Make a GET request to the `/showtables` endpoint. This retrieves the tables from the database. For example:

```bash
curl --location --request GET '<REPLACE WITH FARGATE SERVICE URL>/showtables'
# Example
curl --location --request GET 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/showtables'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

Retrieve the Service URL from `cdk deploy`

![image](https://user-images.githubusercontent.com/31919569/142186611-990ff99f-03b1-4db0-955b-de338f01fb27.png)

Running all the requests above should produce the following output:

![image](https://user-images.githubusercontent.com/31919569/142186674-db4cce05-b820-4adf-90b0-210fbf565b83.png)

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn (Handle for Serverless Pattern website): https://www.linkedin.com/in/glenn-chia-291344142
Twitter (Handle for Twitter mentions): @ glenncjw (https://twitter.com/glenncjw)
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks, Glenn! This is now live at https://serverlessland.com/patterns/cdk-fargate-aurora-serverless.
