### ISSUE TITLE
New pattern submission - sfn-comprehend-sdk-integration

### ISSUE THREAD

**Issue by revanthreddy** [aws-samples/serverless-patterns#213]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AWS Step Functions workflow to integrate with Amazon Comprehend using AWS SDK integrations.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Function to Amazon Comprehend (Sentiment Analysis API)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This CDK application deploys a Step Functions workflow, that takes in a payload and sends it to the sentiment analysis API of the Amazon Comprehend service. The output of the Sentiment Analysis API returns the overall sentiment ((Positive, Negative, Neutral, or Mixed) of the text we have provided. This pattern exactly shows how we can use AWS Step Functions SDK integrations to call any of the over two hundred AWS services directly from your state machine. The application contains the minimum IAM resources required to run the workflow.

## Deployment commands
`
pip install -r requirements.txt 
`
`
cdk deploy
`
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/212

## Payload example (e.g. Lambda event payload from source service).
`
{
    "text": "Hope you have a great day."
}
`
## Author bio 
Name: Revanth Anireddy
Photo URL: https://twitter.com/revanthreddy/photo
Twitter handle: @revanthreddy
Description (up to 255 chars): Senior Cloud Applications Architect @ AWS. 
Swimmer, Artist, Foodie, Movie & Sports trivia enthusiast in my spare time.

**Comment by jbesw** [comment]
Thanks! This is now live at https://serverlessland.com/patterns/sfn-comprehend.
