### ISSUE TITLE
[New repo]: Serverless Streaming Pipeline to Deliver Reliable Messaging

### ISSUE THREAD

**Issue by vaibhavshah2108** [aws-samples/serverless-patterns#2158]
### Description

Modern systems often use a much wider array of inputs for decision making, including images, unstructured text, historical values, and other large data elements. These large data elements pose a challenge to traditional audit systems that deal with relatively small text messages in structured formats. This solution shows the use of serverless technology to create a reliable, performant, traceable, and durable streaming pipeline for audit processing.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2024/02/08/reliable_message_pipeline.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Serverless Streaming Pipeline to Deliver Reliable Messaging

### Repo URL

https://github.com/aws-samples/blog-serverless-reliable-messaging/tree/main

**Comment by jbesw** [comment]
We cannot add repos with no contact information. Please create a new issue and correct these errors.
