### ISSUE TITLE
Serverless Reliable Messaging

### ISSUE THREAD

**Issue by harmjeff** [aws-samples/serverless-patterns#2168]
### Description

In support of blog post: Building a Serverless Pipeline to Deliver Reliable Messaging

Many industries are required to provide audit trails for decision and transactional systems. AI assisted decision making requires monitoring the full inputs to the decision system in near real time to prevent fraud, detect model drift, and discrimination. Modern systems often use a much wider array of inputs for decision making, including images, unstructured text, historical values, and other large data elements. These large data elements pose a challenge to traditional audit systems that deal with relatively small text messages in structured formats. This repository demonstrated the use of serverless technology to create a reliable, performant, traceable, and durable pipeline for audit processing.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/aws-samples/blog-serverless-reliable-messaging/raw/main/media/architecture.png

### IaC framework

AWS SAM

### AWS Serverless services used

- [ ] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [X] AWS Step Functions
- [X] Amazon SNS
- [X] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Building a Serverless Pipeline to Deliver Reliable Messaging

### Repo URL

https://github.com/aws-samples/blog-serverless-reliable-messaging

### Author Name

Jeff Harman

### Author Image URL

https://media.licdn.com/dms/image/D4E03AQE_Zudlwp39RQ/profile-displayphoto-shrink_200_200/0/1709914957434?e=1715212800&v=beta&t=TSi_q4XdiuDgSJyODZzga0F9X6iIzr0rNtlTINm2OZA

### Author Bio

Jeff Harman is a Senior Prototyping Architect at AWS based out of New York city. He has a passion for designing and implementing scalable, modern platforms on the cloud.

### Author LinkedIn URL

https://www.linkedin.com/in/jeffrey-i-harman/

**Comment by jbesw** [comment]
Thanks - this will be visible at https://serverlessland.com/repos/blog-serverless-reliable-messaging shortly.
