### ISSUE TITLE
[New repo]: Amazon API Gateway Multi-Region Public REST API Failover

### ISSUE THREAD

**Issue by marcosortiz** [aws-samples/serverless-patterns#2176]
### Description

Companies often have multiple teams managing different services behind a shared public API. In disaster recovery scenarios, each team needs the ability to fail over their services independently.

This demo demonstrates an Amazon API Gateway multi-region active-passive public API that proxies two independent multi-region active-passive service APIs. The primary and secondary regions can be configured independently for the external API and each service. This allows you to fail over the external API and each service independently as needed for disaster recovery.

![diagram](https://github.com/aws-samples/serverless-patterns/assets/293381/6e510857-ab02-4847-9b5d-079d69991502)

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/aws-samples/apigw-multi-region-failover/blob/main/images/diagram.jpg

### IaC framework

AWS SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

This demo demonstrates an Amazon API Gateway multi-region active-passive public API that proxies two independent multi-region active-passive service APIs. The primary and secondary regions can be configured independently for the external API and each service. This allows you to fail over the external API and each service independently as needed for disaster recovery.

### Repo URL

https://github.com/aws-samples/apigw-multi-region-failover

### Author Name

Marcos Ortiz

### Author Image URL

https://media.licdn.com/dms/image/C4E03AQFduMYE0e9Oyw/profile-displayphoto-shrink_400_400/0/1550341719130?e=1715817600&v=beta&t=3_1XZp_evuNe4B90fsGpv0TlGwBIuum_sXSV7e-Fl2o

### Author Bio

Marcos Ortiz is a Principal AWS Solutions Architect.

### Author LinkedIn URL

https://www.linkedin.com/in/ortizmarcos/

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/repos/apigw-multi-region-failover shortly.
