### ISSUE TITLE
New pattern submission - parallel-e2e-pipeline-cdk

### ISSUE THREAD

**Issue by wisolee** [aws-samples/serverless-patterns#219]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern in CDK provides scaffolding for a CI/CD pipeline with parallelized End-to-End (E2E) tests.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
TypeScript

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
CodeCommit to CodeBuild via CodePipeline

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern creates a simple CI/CD pipeline using AWS CodePipeline with a stage that can be used to run E2E tests in parallel.

<img width="779" alt="parallel-cicd" src="https://user-images.githubusercontent.com/31529018/143146730-8fcaaeb0-64da-4be7-a4d6-537d7cd2a532.png">

This patterns deploys a pipeline consisting of two stages: `Source` and `End_to_End_Tests`. The `Source` stage is linked to your AWS CodeCommit repository, so whenever any commit(s) is pushed to that repository, the pipeline will be triggered. Once the `Source` stage passes, the `End_to_End_Tests` stage will run. In this stage, two AWS CodeBuild servers are provisioned and each is assigned a group of test(s). The tests are then ran in parallel.

The described pattern can be modified to meet your needs. For example:
* Introduce a deployment stage before `End_to_End_Tests`
* Provision N AWS CodeBuild servers
* Run tests that use the framework you desire (e.g. Cypress, Puppeteer, Jest)

There are two IAM roles: `pipeline-role` and `e2e-code-build-role`.
* `pipeline-role`: The role the pipeline uses, which contains specific codecommit, codebuild, and codedeploy actions.
* `e2e-code-build-role`: The role the codebuild server(s) use, which in this case only has permissions to interact with S3 to store pipeline artifacts.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```bash
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Create an AWS CodeCommit repository and add it as a remote:
    ```
    git remote add << repository name >> << repository url >>
    ```
2. Change directory to the pattern directory:
    ```bash
    cd parallel-e2e-pipeline-cdk
    ```
3. Change directory to the pipeline directory:
    ```bash
    cd src/pipeline
    ```
4. From the command line, use npm to install the development dependencies:
    ```bash
    npm install
    ```
5. Configure the pipeline based on your environment. Navigate to pipeline-stack.ts and make changes based on the TODO comments.
5. From the command line, configure environment variables for the AWS account you desire to deploy the pipeline to (the pipeline should be deployed in the same region as the AWS CodeCommit repo). For example:
    ```bash
    export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
    export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    export AWS_DEFAULT_REGION=us-west-2
    ```
6. Navigate back to the pipeline directory and from the command line, use CDK to deploy the AWS resources for the pattern:
    ```bash
    cdk synth ParallelE2EPipelineCDK
    cdk deploy ParallelE2EPipelineCDK
    ```

## GitHub PR for template: 
#218 

## Payload example (e.g. Lambda event payload from source service).
N/A

## Additional resources (optional: link and anchor text, up to 5 resources)
* [AWS CodeCommit](https://docs.aws.amazon.com/codecommit/latest/userguide/welcome.html) - A version control service
* [AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/welcome.html) - A managed build service
* [AWS CodeDeploy](https://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html) - A deployment service
* [AWS CodePipeline](https://docs.aws.amazon.com/codepipeline/latest/userguide/welcome.html) - A continuous delivery service

## Author bio 
Name: William Sola Lee
Photo URL: 
* https://media-exp1.licdn.com/dms/image/C4E03AQFtvgM199GNDg/profile-displayphoto-shrink_800_800/0/1565228195260?e=1643241600&v=beta&t=m2L7_W1OqpUmGxtaUVPTiD0BIdM7lZ-ePplN6eeyYlQ
* https://www.linkedin.com/in/william-sola-lee/

Twitter handle: N/A
Description (up to 255 chars): I am a Service Engineering Consultant.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/codepipeline-cdk.
