### ISSUE TITLE
New pattern submission:- Implementing AWS CDK Log Notification Pattern for Error Logs

### ISSUE THREAD

**Issue by thavasnippets** [aws-samples/serverless-patterns#2196]
## Introduction
Monitoring logs for errors is crucial for maintaining the reliability and performance of cloud-based applications. AWS offers services like CloudWatch Logs for log management and Amazon SNS for notification delivery. By combining these services, you can set up automated error detection and notification systems, ensuring that you're promptly alerted to any issues in your applications.

AWS CDK simplifies the process of provisioning and managing AWS infrastructure by allowing you to define it using familiar programming languages such as Python. We'll leverage the AWS CDK to implement a log notification pattern that detects errors in log streams and sends notifications via email using Amazon SNS.

![pattern](https://github.com/aws-samples/serverless-patterns/assets/15138302/a9eec5f0-2a27-4457-a484-38e9caaa9fd8)

## Implementation Steps
1. **Setting up the AWS CDK Environment:**
   - Ensure you have the AWS CDK installed and configured on your local machine.
   - Create a new AWS CDK project or use an existing one.

2. **Defining the CDK Stack:**
   - Import the necessary AWS CDK modules (`aws_lambda`, `aws_sns`, `aws_iam`, `aws_logs`).
   - Define a new CDK stack class that inherits from `Stack`.
   - Define constructor arguments for the stack, such as log group names, email for notifications, environment, cost center, and contact information.

3. **Creating an SNS Topic:**
   - Create an Amazon SNS topic to which error notifications will be sent.
   - Apply custom tags to the SNS topic for better organization and management.

4. **Creating a Lambda Function:**
   - Define an AWS Lambda function using the `Function` construct.
   - Specify the runtime, handler function, and code location (e.g., from an asset directory).
   - Pass the SNS topic ARN as an environment variable to the Lambda function.
   - Add IAM permissions to the Lambda function to allow it to publish messages to SNS and interact with CloudWatch Logs.

5. **Configuring CloudWatch Logs Subscription Filters:**
   - Iterate over the provided log group names.
   - Create CloudWatch subscription filters for each log group to filter error messages.
   - Specify the Lambda function as the destination for filtered log events.

6. **Adding Email Subscription to SNS Topic:**
   - Add an email subscription to the SNS topic to receive error notifications via email.

Pattern Repository:

https://github.com/thavasnippets/aws-cdk-log-notification-pattern

**Comment by julianwood** [comment]
Please resubmit via the standard PR system:
