### ISSUE TITLE
New pattern submission - LogGroup export to S3 using SNF

### ISSUE THREAD

**Issue by dprotsiv** [aws-samples/serverless-patterns#224]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This AWS SAM pattern demonstrates how to use AWS Step Functions to orchestrate log export to S3 on a schedule

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Functions and Lambda use to export CloudWatch Logs to S3, EventBridge Rules

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This template creates an AWS Step Functions workflow used to orchestrate export of CloudWatch LogGroups with matching tags to S3 on monthly schedule for archival purposes. The workflow is triggered using EventBridge Rules. It also creates an IAM execution roles with permissions to invoke Lambda functions, write to S3 bucket as well as S3 bucket into which logs will be exported.

## Deployment commands
sam deploy
## Payload example (e.g. Lambda event payload from source service).
Step functions input payload:
`{}`
## Author bio 
Name: Dmytro Protsiv
Photo URL: N/A
Twitter handle: N/A
Description (up to 255 chars): Cloud Application Architect at AWS

**Comment by dprotsiv** [comment]
[PR 223](https://github.com/aws-samples/serverless-patterns/pull/223) for this issue

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/sfn-log-export.
