### ISSUE TITLE
AWS SAM Pattern: AWS Glue Job call from AWS Step Functions

### ISSUE THREAD

**Issue by NicoliAraujo** [aws-samples/serverless-patterns#225]
## Description: 
AWS SAM Pattern: AWS Glue Job call from AWS Step Functions

## Language: 
Python

## Framework: 
AWS SAM

## Services from/to : 
Step Functions from Glue

## Description:
This patters deploys a Step Functions that includes a Glue Job as one of its steps. The Glue Job may be used to process data from S3 or other AWS storage services. Parameters input to Glue Job are handled via AWS Systems Manager Parameter Store

The SAM template deploys: 
* A Step Functions State Machine 
* An EventBridge rule that triggers the Step Functions every 2 days 
* A Glue Job 
* AWS Systems Manager Parameter Store
* IAM roles required to run the application.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
```bash
> git clone https://github.com/aws-samples/serverless-patterns.git
```

2. Change directory to the pattern directory:
```bash
> cd sfn-glue-sam/
```

3. Copy glue job script and libs:

```bash
> aws s3 cp code/glue s3://<ARTIFACTS_BUCKET>/glue --recursive
```

4. Build and deploy stack: 

```bash

> sam build --template code/cloudformation/stack.yaml


> sam deploy --guided
```

## Testing
In order to test, run the Step Functions:

```bash
aws stepfunctions start-execution --state-machine-arn "{STEP_FUNCTIONS_ARN}"
```

The output should be the description and status of Glue Job run:

```json
{
  "glue_job_result": {
    "AllocatedCapacity": 1,
    "Attempt": 0,
    "CompletedOn": 1638296059130,
    "ExecutionTime": 49,
    "GlueVersion": "1.0",
    "Id": "jr_ee276c9398f2d981c850f79cb7b54a28b57d9f6484deb8a9051db4bcbbc12d1f",
    "JobName": "Feature Engineering",
    "JobRunState": "SUCCEEDED",
    "LastModifiedOn": 1638296059130,
    "LogGroupName": "/aws-glue/python-jobs",
    "MaxCapacity": 1,
    "PredecessorRuns": [],
    "StartedOn": 1638296005295,
    "Timeout": 2880
  }
}
```

## Cleanup
1. Delete the stack: 
```bash
> aws cloudformation delete-stack --stack-name STACK_NAME
```
2. Confirm the stack has been deleted: 
```bash
> aws cloudformation list-stacks --query "StackSummaries[?contains(StackName,'STACK_NAME')].StackStatus"
```

## GitHub PR for template:
#227 

## Additional resources (optional: link and anchor text, up to 5 resources)
[Glue Job in AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html)
[Glue to Step Functions](https://docs.aws.amazon.com/step-functions/latest/dg/connect-glue.html)
[Permission for Glue to write on CloudWatch Logs](https://aws.amazon.com/premiumsupport/knowledge-center/glue-not-writing-logs-cloudwatch/#:~:text=If%20your%20AWS%20Glue%20jobs,service%20to%20use%20the%20key.)
[More on Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html)

## Author bio 
Name: Nicoli Araujo
Photo URL: https://photos.app.goo.gl/4dYo2wUqbeWyd8wp6
Description (up to 255 chars): Associate Data Scientist at AWS.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/sfn-glue.
