### ISSUE TITLE
[New repo]: Image insight with Amazon Rekognition and Amazon Bedrock

### ISSUE THREAD

**Issue by higoyal01** [aws-samples/serverless-patterns#2264]
### Description

This project is a serverless application that uses AWS services to provide image description based on Amazon Rekognition and Amazon Bedrock services. It's designed to help you analyze and describe the content of images.

### language

English

### runtime

Python

### Level

300

### Type

Application

### Use case

Backend

### Primary image

https://github.com/higoyal01/image-insight/blob/main/ImageInsightsWorkflow.png

### IaC framework

SAM

### AWS Serverless services used

- [X] Amazon API Gateway
- [X] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [X] Amazon Rekognition
- [ ] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Image insights with ML and GenAI

### Repo URL

https://github.com/higoyal01/image-insight

### Author Name

Himanshu Goyal

### Author Image URL

https://serverlessland.com/assets/images/resources/contributors/Himanshu%20Goyal.jpg

### Author Bio

A Serverless Cloud Engineer and technical writer, dedicated to crafting efficient and scalable solutions using AWS services. My expertise in serverless architecture empowers me to create innovative and cost-effective cloud solutions. I enjoy sharing my knowledge with the serverless community through articles and patterns, helping others explore the vast potential of serverless computing.

### Author LinkedIn URL

https://www.linkedin.com/in/himanshugoyal20

**Comment by higoyal01** [comment]
This is a resubmission of previously submitted repo. Not sure how I can add my files in "aws-samples" path.

**Comment by julianwood** [comment]
You need to use the internal AWS open source process to publish your repo on aws-samples. Contact me for internally for details if you can't find it.
