### ISSUE TITLE
New repo - trigger-mwaa-dag-using-s3-event

### ISSUE THREAD

**Issue by nikhilswagle** [aws-samples/serverless-patterns#2274]
### Description

This repository demonstrates how to trigger a DAG workflow hosted in MWAA (Managed Wokflow for Apache Airflow) using input request files uploaded in a source S3 bucket.

Important: this application uses various AWS services and there are costs associated with these services after the Free Tier usage - please see the [AWS Pricing page](https://aws.amazon.com/pricing/) for details. You are responsible for any AWS costs incurred. No warranty is implied in this example.

### language

English

### runtime

Python

### Level

200

### Type

Examples

### Use case

Backend

### Primary image

https://github.com/aws-samples/trigger-mwaa-dag-using-s3-event/blob/main/img/design.png

### IaC framework

Terraform

### AWS Serverless services used

- [ ] Amazon API Gateway
- [ ] Amazon DynamoDB
- [ ] Amazon EventBridge
- [ ] AWS IoT
- [X] AWS Lambda
- [ ] Amazon Rekognition
- [X] Amazon S3
- [ ] AWS Step Functions
- [ ] Amazon SNS
- [ ] Amazon SQS
- [ ] Amazon Transcribe
- [ ] Amazon Translate

### Description headline

Triggering DAG (Directed Acyclical Graph) workflow in MWAA (Managed Wokflow for Apache Airflow) using S3 file upload events

### Repo URL

https://github.com/aws-samples/trigger-mwaa-dag-using-s3-event

### Additional resources

[Invoking DAGs with a Lambda Function](https://docs.aws.amazon.com/mwaa/latest/userguide/samples-lambda.html)
[Airflow Core Concepts](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/index.html)

### Author Name

Damodar Shenvi Wagle

### Author Image URL

https://drive.google.com/file/d/1o-NvTy-Ock12bKOLoMiwyolqizNNMhv8/view?usp=sharing

### Author Bio

Damodar Shenvi Wagle is a Senior Cloud Application Architect at AWS Professional Services.

### Author LinkedIn URL

https://www.linkedin.com/in/damodar-shenvi-wagle-72375548/

**Comment by nikhilswagle** [comment]
Submitted the issue based on the suggestion in [this](https://github.com/aws-samples/serverless-patterns/pull/2197) PR.
Did not find Amazon MWAA (Managed Wokflow for Apache Airflow) service in the options.

**Comment by julianwood** [comment]
Added
