### ISSUE TITLE
Fix Issues in Existing Pattern

### ISSUE THREAD

**Issue by rajavaid77** [aws-samples/serverless-patterns#2288]
* Corrected default values in template.yml for AOSS resources
* Added requirements.txt and Metadata section to LayerVersion to enable layer build using SAM
* Updated README to update dependency build step to use sam build
* Updated IndexCreationLambda function to add field mappings to newly created AoSS Index
*

PR [#2289](https://github.com/aws-samples/serverless-patterns/pull/2289)

**Comment by julianwood** [comment]
Added, thanks
