### ISSUE TITLE
New pattern submission - ta-eventbridge-lambda-s3

### ISSUE THREAD

**Issue by seandall** [aws-samples/serverless-patterns#229]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Use AWS Trusted Advisor to monitor your AWS resources and trigger a Lambda function via Amazon EventBridge, remediating the issue on the resource in question.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python
## Framework (currently we support SAM or CDK)
CDK
## Services from/to (e.g. "Lambda to EventBridge)
TrustedAdvisor to EventBridge to Lambda to S3
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern utilizes AWS Trusted Advisor to execute an AWS Lambda Function via Amazon EventBridge, to remove public access to an S3 Bucket once it has been flagged as public. 
Incorrectly configured S3 buckets can be the source of a data leak in your organization. After deploying this serverless pattern, you will be automating the lock-down of your 
S3 buckets to prevent any accidental data leaks. If an S3 Bucket meets the use-case for being open to the public, simply "Exclude & Refresh" the specific resource in 
the [AWS Trusted Advisor Console](https://console.aws.amazon.com/trustedadvisor/home) and they will be ignored by the 'S3 Bucket Privatizer'. 

The 'Amazon S3 Bucket Permissions' Trusted Advisor check is only available to AWS Accounts subscribed to [Business or Enterprise support plans](https://aws.amazon.com/premiumsupport/plans/)

Learn more about this pattern at Serverless Land Patterns: https://serverlessland.com/patterns/ta-eventbridge-lambda-s3

Important: this application uses various AWS services and there are costs associated with these services after the Free Tier usage - please see the [AWS Pricing page](https://aws.amazon.com/pricing/) for details. 
You are responsible for any AWS costs incurred. No warranty is implied in this example.

## Deployment commands
After setting up your command-line environment, simply un the command: `cdk deploy` with the below attributes on each account.

Example: cdk deploy --parameters notificationemailaddress=email@example.com --parameters profiling=TRUE --parameters tracing=TRUE --parameters trustedadvisorrefreshminutes=7

**Parameter Definitions:**
    * **notificationemailaddress:** **[Required]** The E-mail address you wish to send notifications to when a WARN or ERROR flag is identified
    * **profiling:** TRUE or FALSE. If set to true, [CodeGuru Profiler](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html) will be enabled. **Default:** FALSE
    * **tracing:** TRUE or FALSE. If set to true, [AWS X-Ray Tracing](https://aws.amazon.com/xray/) will be enabled. **Default:** FALSE
    * **trustedadvisorrefreshminutes:** Integer value between 5 and 1440. The number of minutes you wish to schedule a Trusted Advisor Check Refresh for S3 Bucket Permissions. **Default:** 7
   

 
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/228

## Author bio 
Name: Sean Kendall
Photo URL:https://www.seankendall.com/SeansAmazonHeadShot.jpg
Twitter handle:
Description (up to 255 chars):
AWS Sr. Technical Account Manager and Serverless Specialist. Sean enjoys helping AWS customers improve their serverless architecture by teaching new concepts, and performing architecture reviews.

**Comment by jbesw** [comment]
Sean, can you verify this PR? It has over 1700 files - it should be no more than 5-20.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/ta-eventbridge-lambda-cdk.
