### ISSUE TITLE
Update Lambda examples to use node 20.x

### ISSUE THREAD

**Issue by trivikr** [aws-samples/serverless-patterns#2290]
### Is your feature request related to a problem? Please describe.

There are multiple samples which uses Lambda Node.js versions which are end-of-life
* nodejs16.x https://github.com/search?q=repo%3Aaws-samples%2Fserverless-patterns+%22Runtime%3A+nodejs16.x%22&type=code
  * Deprecation is on `Jun 12, 2024` and function create will be blocked on `Feb 28, 2025`
* nodejs14.x https://github.com/search?q=repo%3Aaws-samples%2Fserverless-patterns+%22Runtime%3A+nodejs14.x%22&type=code
  * Function create was blocked on `Jan 9, 2024`

Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Describe the solution you'd like

Update Lambda examples to use node 20.x, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

### Describe alternatives you've considered
N/A

**Comment by trivikr** [comment]
Example error in https://github.com/aws-samples/serverless-patterns/tree/main/lambda

```console
$ cd lambda

$ sam --version
SAM CLI, version 1.117.0

$ sam deploy --guided
...
CREATE_FAILED             AWS::Lambda::Function     SimpleFunction            Resource handler        
                                                                              returned message: "The  
                                                                              runtime parameter of    
                                                                              nodejs14.x is no longer 
                                                                              supported for creating  
                                                                              or updating AWS Lambda  
                                                                              functions. We recommend 
                                                                              you use the new runtime 
                                                                              (nodejs20.x) while      
                                                                              creating or updating    
                                                                              functions. (Service:    
                                                                              Lambda, Status Code:    
                                                                              400, Request ID: c492d1 
                                                                              48-2b9e-4b74-bb84-3650a 
                                                                              0c5f726)"               
                                                                              (RequestToken: cff98e85 
                                                                              -94ad-c6da-9d6e-5d667e9 
                                                                              fbf6b,                  
                                                                              HandlerErrorCode:       
                                                                              InvalidRequest)         
CREATE_FAILED             AWS::CloudFormation::St   sam-app                   The following           
                          ack                                                 resource(s) failed to   
                                                                              create:                 
                                                                              [SimpleFunction].
```

**Comment by trivikr** [comment]
I posted an example PR for reference at https://github.com/aws-samples/serverless-patterns/pull/2291, which just required updating nodejs version in sam template.

Some other packages will require upgrading from AWS SDK for JavaScript v2 to v3, like https://github.com/aws-samples/serverless-patterns/blob/843c78ae490d37cf7aca67393ead2a4dad8ee211/s3-object-lambda/src/app.js#L5

**Comment by julianwood** [comment]
Updated

**Comment by trivikr** [comment]
@julianwood The PR https://github.com/aws-samples/serverless-patterns/pull/2291 was just one example

This issue needs to be reopened, as there are 87 other files which need to be updated
https://github.com/search?q=repo%3Aaws-samples%2Fserverless-patterns+%22Runtime%3A+nodejs16.x%22&type=code

**Comment by trivikr** [comment]
@cornelcroi This issue is incomplete as only one PR is merged.

This issue needs to be reopened, as there are 98 other files which need to be updated
[github.com/search?q=repo%3Aaws-samples%2Fserverless-patterns+nodejs16.x&type=code](https://github.com/search?q=repo%3Aaws-samples%2Fserverless-patterns+nodejs16.x&type=code), and there are 3 open PRs.

**Comment by julianwood** [comment]
Added, thanks
