### ISSUE TITLE
New pattern submission - S3 - CloudTrail - EventBridge - SQS

### ISSUE THREAD

**Issue by jyotiraws** [aws-samples/serverless-patterns#230]
## Description
Publish events from Amazon S3 to Amazon EventBridge using AWS CloudTrail

## Language: 
YAML

## Framework
SAM

## Services from/to 
Amazon S3 to AWS CloudTrail to Amazon EventBridge

## Description
This pattern sends Amazon S3 events to Amazon EventBridge using AWS CloudTrail. EventBridge event is sent to SQS for monitoring.

Data events are not logged by default. To record CloudTrail data events, supported resources or resource types have to be explicitly added. (See Resources section for additional context)

The SAM template deploys:
	* An S3 Bucket - where source images are pushed
	* CloudTrail - that captures Data events on above S3 bucket
	* Another S3 bucket - where cloud trail writes its logs
	* A BucketPolicy - that allows cloud trail to write to logs  bucket
	* An EventBridge rule that identifies s3 data events and sends them to an SQS
	* An SQS Queue - where event notifications are sent
	* A QueuePolicy - that allows for Event to be sent to the SQS queue

## Deployment commands

1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository

```
git clone https://github.com/aws-samples/serverless-patterns
```

2. Change directory to the pattern directory:

```
cd s3-eventbridge
```

3. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:

```
sam deploy —guided
```

4. During the prompts:
	* Enter a stack name
	* Enter the desired AWS Region
	* Enter unique bucket names
	* Allow SAM CLI to create IAM roles with the required permissions.

```
Once you have run `sam deploy -guided` mode once and saved arguments to a configuration file (samconfig.toml), you can use `sam deploy` in future to use these defaults.
```

5. Note the outputs from the SAM deployment process. The URL for SQS is present and will be used for testing.

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/231

## Payload example
Event Generated

## Additional resources (optional: link and anchor text, up to 5 resources)
[Logging data events for trails - AWS CloudTrail](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html)
[Amazon S3 CloudTrail events - Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudtrail-logging-s3-info.html)
[Event-Driven Architecture](https://aws.amazon.com/event-driven-architecture/)

## Author bio 
Name: Jyoti Rathi
Photo URL: https://avatars.githubusercontent.com/u/82823572?s=400&u=2c0484936e56545e72f1cb25c4d1484a9720e193&v=4
Twitter handle: NA
Description (up to 255 chars): Cloud Application Architect @ AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/s3-cloudtrail-eventbridge.
