### ISSUE TITLE
Adding new Serverless pattern - apigw-s3-lambda-dotnet

### ISSUE THREAD

**Issue by chrisnel52** [aws-samples/serverless-patterns#2310]
This is a submission for a new Serverless pattern: apigw-s3-lambda-dotnet

## Description
This pattern demonstrates how to create an Amazon API Gateway REST API with a direct proxy to an Amazon S3 bucket. The API allows files to be uploaded to the S3 bucket. An AWS Lambda authorizer will authorize the incoming HTTP requests. Asynchronously trigger a Lambda to process the uploaded file.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/2309

**Comment by julianwood** [comment]
Thanks, merged
