### ISSUE TITLE
New pattern submission - apigw-http-api-lambda-rds-proxy-cdk

### ISSUE THREAD

**Issue by jgoeglein** [aws-samples/serverless-patterns#233]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern sets up API Gateway HTTP API using AWS Lambda function as an integration which talks to RDS Aurora(Postgres) via RDS Proxy with IAM Authentication enabled. The Lambda function will only be using short-lived credentials to authenticate through RDS proxy via IAM authentication using the popular JavaScript ORM [sequelize](https://sequelize.org).

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

NodeJS

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

HTTP API GW -> Lambda -> RDS Proxy -> Aurora(Postgres)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern sets up API Gateway HTTP API using AWS Lambda function as an integration which talks to RDS Aurora(Postgres) via RDS Proxy with IAM Authentication enabled. The Lambda function will only be using short-lived credentials to authenticate through RDS proxy via IAM authentication using the popular JavaScript ORM [sequelize](https://sequelize.org).

RDS Proxy has to exist in the same VPC as your database and it cannot be public. Security groups are configured to [only allow communication from the lambda functions to RDS proxy](./src/lib/rds-proxy-sequelize-stack.ts#L), and [from the RDS proxy to the Aurora database itself]().

[The lambda functions are granted the ability to connect to the RDS proxy using the provided username](). 

While the lambda authenticates to your proxy using IAM authentication, RDS proxy still connects to your database using native database authentication. Therefore, a new set of RDS credentials are created in secrets manager which allow RDS proxy to connect to the database. See [the connecting to a database through RDS Proxy documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy-setup.html#rds-proxy-iam-setup) for more information.

RDS proxy supports connecting to your database with multiple database users. This means that different usernames with limited privileges *inside your database* could be configured for different lambda functions if necessary.

The [`beforeConnect` lifecycle hook](./src/lambda/sequelize.ts#L26) provided by sequelize is used to generate a current, short-lived access token.

## Deployment commands

1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ``` bash
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```bash
    cd apigw-http-api-lambda-rds-proxy-cdk/src
    ```
3. Install dependencies:
    ```bash
    npm install
    ```
4. Deploy the application. This will take some time to provision the database.
    ```bash
    cdk deploy
    ```

## GitHub PR for template: 

#232 

## Payload example (e.g. Lambda event payload from source service).

```sh
curl --request GET https://aabbccddee.execute-api.us-west-2.amazonaws.com/
```

## Additional resources (optional: link and anchor text, up to 5 resources)

* [Connecting to a database through RDS Proxy documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy-setup.html#rds-proxy-iam-setup)
* [Using RDS Proxy](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html)
* [Using Amazon RDS Proxy with AWS Lambda](https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/)

## Author bio 
Name: Jesse Goeglein
Photo URL: https://github.com/jgoeglein.png
Twitter handle:
Description (up to 255 chars):
Jesse is a Cloud Application Architect with AWS Professional Services helping customers succeed with AWS.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-http-api-lambda-rds-proxy-cdk.
