### ISSUE TITLE
New pattern submission - cdk-apigw-lambda-dynamodb

### ISSUE THREAD

**Issue by iAmSherifCodes** [aws-samples/serverless-patterns#2354]
**Description Headline**: Create an Lambda function with API Gateway as event source and  DynamoDB as event destination.
This pattern is a simple workflow that creates an API in Amazon API Gateway, uses AWS Lambda function for compute, and Amazon DynamoDB as database.

**Language**
NodeJS

**Framework**
CDK

**Services:**
Amazon API Gateway --> AWS Lambda --> Amazon DynamoDB

**Description:**

This pattern is simple workflow that creates an API in Amazon API Gateway, uses AWS Lambda function for compute, and Amazon DynamoDB as database.
This pattern deploys an API in API Gateway that triggers a Lambda function that is handling your request and save to DynamoDB table. API Gateway validates the request by comparing with a custom Model before it then triggers the Lambda function. The function is given a Write permissions to a DynamoDb table. The stack creates the following resources:
- API: An API named NewApi in API Gateway.
- Model: A request model named EmailValidator.
- Request Validator: A request validator named EmailRequestValidator.
- Function: A Lambda function named LambdaFunction.
- Table: A dynamoDB table named CdkSampleTable.
- Sample Request:

```
    {
      "email": "example@email.com"
    }
```
- Sample Response:
```
    {
      "message": "Your email has been saved!"
    }
```
    
**Deployment Commands:**
- cdk synth
- cdk deploy

**GitHub PR for template:**
#2353 

**Additional resources:**
- [API Gateway Request Model](https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings-models.html)
- [API Gateway Request Validator](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html)

**Author bio**
Name: Sherifdeen Awofiranye
Description: AWS Serverless enthusiast
LinkedIn:https://www.linkedin.com/in/sherifawofiranye/ 
Twitter: https://x.com/AwofiranyeSher2

**Comment by julianwood** [comment]
Closed since stale
