### ISSUE TITLE
New pattern submission - AWS Lambda to Amazon Rekognition

### ISSUE THREAD

**Issue by jyotiraws** [aws-samples/serverless-patterns#237]
# Description
This pattern demonstrates how an event can be used to trigger a Lambda function and run Image analysis using Amazon Rekognition.

# Language:
NodeJS for Lambda

# Framework
SAM

# Services from/to
AWS Lambda to Amazon Rekognition

# Description
This pattern uses an EventBridge event rule to trigger a Lambda Function. The Lambda runs an image analysis on the image specified in the incoming event. 

Lambda uses Amazon Rekognition to run an analysis on that image. The image analysis used for demo is text recognition. 

The SAM template deploys:
* An EventBridge rule that identifies data events on source s3 bucket and the rule triggers a Lambda function for the matched event.
* Permissions for EventBridge to invoke a Lambda function
* An IAM role - that allows Lambda 
  — to use CloudWatch logs, 
  — to use detect_text Rekognition api, 
  — to pull an image from source S3 bucket
* A Lambda function that uses Amazon Rekognition

# Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository

```
git clone https://github.com/aws-samples/serverless-patterns
```

2. Change directory to the pattern directory:

```
cd lambda-rekognition
```

3. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:

```
sam deploy --guided --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
```

4. During the prompts:
	* Enter a stack name
	* Enter the desired AWS Region
	* Enter some bucket name that exists and can be used for testing
	* Allow SAM CLI to create IAM roles with the required permissions.

```
Once you have run `sam deploy -guided` mode once and saved arguments to a configuration file (samconfig.toml), you can use `sam deploy` in future to use these defaults.
```

# GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/238

# Payload example
```
[
  {
    "DetailType": "AWS API Call via CloudTrail",
    "Source": "simulated.aws.s3",
    "Detail": "{\"eventSource\":\"s3.amazonaws.com\",\"eventName\":\"PutObject\",\"requestParameters\": {\"bucketName\":\"lambda-rekognition-asdfg\",\"Host\":\"lambda-rekognition-asdfg.s3.us-west-2.amazonaws.com\",\"key\":\"helloworld1.png\"}}"
  }
]
```

# Additional resources (optional: link and anchor text, up to 5 resources)
[Serverless Land - s3-EventBridge pattern](https://serverlessland.com/patterns/s3-EventBridge)
[Detecting text - Amazon Rekognition](https://docs.aws.amazon.com/rekognition/latest/dg/text-detection.html)

# Author bio
Name: Jyoti Rathi
Photo URL:  [https://avatars.githubusercontent.com/u/82823572?s=400&u=2c0484936e56545e72f1cb25c4d1484a9720e193&v=4](https://avatars.githubusercontent.com/u/82823572?s=400&u=2c0484936e56545e72f1cb25c4d1484a9720e193&v=4) 
Twitter handle: NA
Description (up to 255 chars): Cloud Application Architect @ AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/lambda-rekognition.
