### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by crajeeva** [aws-samples/serverless-patterns#240]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern attaches an EFS file system to your lambda function to give it expandable, persistent storage.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Lambda to EFS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This is a pattern that attaches an EFS file system to your lambda function to give it expandable, persistent storage. Having this level of storage in a Lambda Function opens the door to many new possibilities (multiple functions can even use the same file system). 
API Gateway was created to invoke Lambda function to test the pattern.

Lambda uses your function's permissions to mount file systems. To connect to a file system, your function's execution role must have the following permissions in addition to the permissions required to connect to the file system's VPC:

Execution role permissions
    elasticfilesystem:ClientMount
    elasticfilesystem:ClientWrite (not required for read-only connections)

These permissions are included in the AmazonElasticFileSystemClientReadWriteAccess managed policy.
When you configure a file system, Lambda uses your permissions to verify mount targets. To configure a function to connect to a file system, your IAM user needs the following permissions:

User permissions
    elasticfilesystem:DescribeMountTarget

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/239

## Author bio 
Name: Rajeeva Chaurasia
Photo URL: 
Twitter handle:
Description (up to 255 chars): Cloud Application Architect - Associate

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-http-api-lambda-efs-cdk.
