### ISSUE TITLE
New pattern submission - API Gateway to Lambda to DynamoDB

### ISSUE THREAD

**Issue by ravsrin** [aws-samples/serverless-patterns#242]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern demonstrates how making an HTTP POST request to an Amazon API Gateway endpoint invokes an AWS Lambda function and inserts an item into an Amazon DynamoDB table.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Python

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

Amazon API Gateway to AWS Lambda to Amazon DynamoDB

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern explains how to deploy a SAM application with Amazon API Gateway, AWS Lambda, and Amazon DynamoDB. When an HTTP POST request is made to the Amazon API Gateway endpoint, the AWS Lambda function is invoked and inserts an item into the Amazon DynamoDB table.

The SAM template deploys:
* Lambda Function - listed in template.yaml
* DynamoDB Table - listed in template.yaml
* Lambda Permission - (allows API Gateway to invoke Lambda) - SAM generated 
* IAM Role for Lambda with BasicExecutionRole Policy and SAM DynamoDBCrud Policy - SAM generated 
* API Gateway REST API (ServerlessRestApi) - SAM generated 
* API Gateway Deployment (ServerlessRestAPIDeployment) - SAM generated 
* API Gateway Stage (ServerlessRestApiProdStage) - SAM generated 

## Deployment commands

sam deploy

## GitHub PR for template: 

#241 

## Payload example (e.g. Lambda event payload from source service).

Empty payload

## Additional resources (optional: link and anchor text, up to 5 resources)

[API Gateway console invoke REST API method](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-test-method.html)
[SAM DynamoDBCrud Policy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#dynamo-db-crud-policy)

## Author bio 
Name: Ravi Srinivasan
Photo URL: https://phonetool.amazon.com/users/rssrnv
Twitter handle:
Description (up to 255 chars): Cloud Application Architect at AWS.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-lambda-dynamodb.
