### ISSUE TITLE
New pattern submission - apigw canary deployment cdk

### ISSUE THREAD

**Issue by mitchellwandrews** [aws-samples/serverless-patterns#243]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a serverless app using API Gateway and Lambda. Then create an API Gateway canary deployment

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Python

## YouTube videoId (optional e.g. "VI79XQW4dIM")

N/A

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

API Gateway to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern shows how to create an API Gateway canary deployment with a Lambda function behind an API Gateway REST API. Once the canary deployment is live, requests will be routed to the new and old version of the Lambda function at a rate of 50/50 using the Lambda alias from the APIGW stage variables to route traffic to the correct version.

The following resources will be created:

API Gateway REST API
APIGW Account
APIGW Method
APIGW Deployment
APIGW Stage
Lambda Function
Lambda Versions
Lambda Aliases
Lambda Permissions (For API Gateway to invoke the Lambda function)

## Deployment commands

1. Create a virtual environment for Python
    ```
    python3 -m venv .venv
    ```
2. Activate the virtual environment
    ```
    source .venv/bin/activate
    ```
    For a Windows platform, activate the virtualenv like this:
    ```
    .venv\Scripts\activate.bat
    ```
3. Install the Python required dependencies:
    ```
    pip install -r requirements.txt
    ```
4. From the command line, use AWS CDK to deploy the AWS resources for the serverless application as specified in the app.py file:
    ```
    cdk deploy MyServerlessApplicationStack
    ```
5. Note the outputs from the CDK deployment process. These contain the API Gateway ID which is used for testing.
6. Once the serverless application stack is successfully deployed, you will need to [deploy new Lambda code](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html). This can be accomplished by performing the following on the Lambda page in the AWS console:

    1. On the left panel, click functions.
    2. Click on the ```MyServerlessApplicationStac-MyFunction*``` function.
    3. Under the code tab, edit the Hello World code under the EDIT ME comment.
    4. Under the file menu in the code editor, click save.
    5. In the code editor, click the deploy button. This deploys the code to the [$LATEST version](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html).

7. From the command line, use AWS CDK to deploy the AWS resources for the canary deployment as specified in the app.py file:
    ```
    cdk deploy CanaryDeploymentStack
    ```

## GitHub PR for template: 

[#236 ](https://github.com/aws-samples/serverless-patterns/pull/236)

## Payload example (e.g. Lambda event payload from source service).

Lambda event payload from API Gateway.

## Additional resources (optional: link and anchor text, up to 5 resources)

[APIGW Canary Deployment](https://docs.aws.amazon.com/apigateway/latest/developerguide/canary-release.html)
[API Gateway RESTful API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-rest-api.html)

## Author bio 
Name: Mitch Andrews
Photo URL: https://phonetool.amazon.com/users/mtchl
Twitter handle:
Description (up to 255 chars): Associate DevOps Consultant @ AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-canary-deployment-cdk.
