### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by Domt301** [aws-samples/serverless-patterns#245]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an aurora serverless cluster with associated vpc, subnets, and secrets manager

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Aurora Serverless to Secrets Manager

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Aurora Serverless cluster with VPC, Subnets, Route Tables, and Secrets Manager

## Deployment commands
```cd /CDK```
```cdk bootstrap```
```npm run build```
```cdk deploy``` 

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/244

## Author bio 
Name: Leonardo Wildt
Photo URL: https://github.com/domt301.png
Twitter handle: Domt301
Description (up to 255 chars): Aurora Serverless cluster with VPC, Subnets, Route Tables, and Secrets Manager

![aurora drawio](https://user-images.githubusercontent.com/11573996/144956221-611e7250-3a68-45ce-b1dc-dc1095409502.png)

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/rds-secrets-manager-cdk.
