### ISSUE TITLE
upgrade python runtime version to 3.8 for EventBridge inbound webhooks

### ISSUE THREAD

**Issue by chaitanyagummadi** [aws-samples/serverless-patterns#2450]
Python 3.7 is deprecation as per https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported

This change would only upgrade the 3 files python runtime from 3.7 to 3.8.

https://github.com/aws-samples/serverless-patterns/tree/main/eventbridge-webhooks

Pull Request: https://github.com/aws-samples/serverless-patterns/pull/2449

**Comment by julianwood** [comment]
Merged, thanks
