### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by mthojoh** [aws-samples/serverless-patterns#247]
## Description
Create an App Mesh implementation that fronts two services in an ECS cluster

## Language:
Node.js (for the ECS Services)

## Framework 
SAM

## Services from/to 
App Mesh to ECS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This serverless pattern will create a VPC with two public subets, two private subnets, an ECS cluster with two services, and an App Mesh service mesh with a virtual gateway, virtual routers, and virtual services. The goal is threefold: a) create endpoints that are not controlled through code, b) implement a circuit breaker pattern, and c) have a retry policy for API calls.

IAM permissions include certificate management, App Mesh Envoy access, XRay daemon and CloudWatch access, and ECS task execution.

## Deployment commands
1. Create a self-signed security certificate (details in the README)
2. Build the container images and push them to ECR (details in the README)
3. Modify needed parameters in the CloudFormation template
4. Run `sam build && sam deploy --guided`

## GitHub PR for template:
#246 

## Payload example
N/A

## Additional resources (optional: link and anchor text, up to 5 resources)
(App Mesh Overview)[https://aws.amazon.com/app-mesh]
(App Mesh Developer Guide)[https://docs.aws.amazon.com/app-mesh/latest/userguide/what-is-app-mesh.html]
(ECS on Fargate)[https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html]

## Author bio 
Name: JJ Johnson
Photo URL: https://en.gravatar.com/userimage/512850/5a1d4b0671dc15032d5cc0d13d8612fd.jpeg
Twitter handle: N/A
Description (up to 255 chars): JJ Johnson is a Cloud Application Developer for AWS ProServe based in the US.

Name: Rahul Kuppachhi
Photo URL: https://secure.gravatar.com/avatar/50c4275b36a4e6a7156e3511ceb81329
Twitter handle: N/A
Description (up to 255 chars): Rahul is an Associate Security Transformation Consultant at Amazon Web Services based in the US.

**Comment by jbesw** [comment]
Hello! We don't cover App Mesh or ECS in these patterns at this stage - I'd recommend using the internal process for publishing this content as a blog post. Please contact me internally if you have any questions.

**Comment by robzenn92** [comment]
Hi @jbesw , wondering why you don't want to cover App Mesh or ECS patterns among others at this stage.

**Comment by jbesw** [comment]
We are currently focusing on SAM/CDK templates for the services we initially started with, but we will expand to include other services over time.
