### ISSUE TITLE
New pattern submission: eventbridge-schedule-secret-rotation-cdk

### ISSUE THREAD

**Issue by senthilkumarmohan** [aws-samples/serverless-patterns#2470]
**Overview**
Pattern to rotate secrets using Amazon EventBridge Scheduler and AWS Lambda at desired intervals. 

**Language**
Python

**Services from/to**
Amazon EventBridge Scheduler to AWS Lambda to AWS Secrets Manager

**Comment by julianwood** [comment]
Merged, thanks
