### ISSUE TITLE
New pattern submission: Upload files to S3 bucket using presigned URLs (terraform)

### ISSUE THREAD

**Issue by pjx98** [aws-samples/serverless-patterns#2476]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Language
Terraform for Infrastructure as Code
Java for Lambda function

Services from/to
API Gateway to Lambda to generate S3 presigned URL
User will upload file using presigned URL to s3 bucket

Description
This sample project deploys an Amazon API Gateway REST API with an AWS Lambda integration. The Lambda function, written in Java, generates a presigned URL with write access to an Amazon S3 Bucket. The provided test class uploads a file into the S3 bucket using the presigned URL.

Deployment commands
terraform init
terraform apply

GitHub PR for template:
#2475 

Payload example
NA

Author Bio
Name: Jing Xiang Peh
LinkedIn: https://www.linkedin.com/in/jing-xiang-peh/
Description: I am a specialist solutions architect, Serveless based in Singapore

**Comment by julianwood** [comment]
Merged, thanks
