### ISSUE TITLE
New serverless pattern - Invoke a Private Amazon API Gateway REST API cross Region from an EC2 machine

### ISSUE THREAD

**Issue by luketr03** [aws-samples/serverless-patterns#2478]
# Private Amazon API Gateway REST API to be invoked from an AWS Lambda function in a different AWS Region

This pattern creates a Private Amazon API Gateway REST API, along with an Interface VPC Endpoint in an AWS Region. Subsequently, it creates a VPC, a Lambda function, a Private Hosted Zone and a VPC Peering Connection in a second AWS Region. Finally, the VPC Peering connection is created in the first AWS Region. This way, a client in an AWS Region can send requests to the Private API Gateway in a different AWS Region.

Learn more about this pattern at [Serverless Land Patterns](https://serverlessland.com/patterns/private-apigw-cross-region)

Important: this application uses various AWS services and there are costs associated with these services after the Free Tier usage - please see the [AWS Pricing page](https://aws.amazon.com/pricing/) for details. You are responsible for any AWS costs incurred. No warranty is implied in this example.

## Requirements

* [Create an AWS account](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html) if you do not already have one and log in. The IAM user that you use must have sufficient permissions to make necessary AWS service calls and manage AWS resources.
* [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html) installed and configured
* [Git Installed](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
* [AWS Serverless Application Model](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) (AWS SAM) installed

## Deployment Instructions

1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ``` 
    git clone https://github.com/aws-samples/serverless-patterns
    ```
1. Change directory to the pattern directory: (edit this)
    ```
    cd apigw-rest-api-lambda-vpc-sqs
    ```
1. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:
    ```
    sam deploy --guided
    ```
1. During the prompts:
    * Enter a stack name
    * Enter the desired AWS Region
    * Allow SAM CLI to create IAM roles with the required permissions.
    * Enter Subnets
    * Enter LambdaSecurityGroupId

    Once you have run `sam deploy --guided` mode once and saved arguments to a configuration file (samconfig.toml), you can use `sam deploy` in future to use these defaults.

1. Note the outputs from the SAM deployment process. These contain the resource names and/or ARNs which are used for testing.

## How it works

# Multi-Region VPC Peering with Private API Gateway Setup

This document outlines the process of setting up a multi-region VPC peering connection with a private API Gateway using three CloudFormation templates.

## Deployment Order and Regions

1. **Template 1**: Deployed in Region A
2. **Template 2**: Deployed in Region B (different from Region A)
3. **Template 3**: Deployed in Region A (same as Template 1)

## Important Notes

- The VPC CIDR block in Template 2 must be different from the one chosen in Template 1.
- Templates 1 and 3 are deployed in the same AWS Region.
- Template 2 is deployed in a different AWS Region from Templates 1 and 3.
- The Lambda function created in Template 2 acts as a client, sending requests to the Amazon API Gateway created in Template 1.

## Template 1: VPC with Private API Gateway

This template creates an Amazon VPC with an Amazon Private API Gateway and necessary resources in Region A. It sets up the infrastructure for a Private API that can be accessed securely from another VPC.

### Key Resources:
- VPC: Creates a new Virtual Private Cloud.
- Two Subnets: Sets up two subnets within the VPC for high availability.
- Route Table: Configures routing for the VPC.
- Security Group: Defines inbound and outbound traffic rules.
- VPC Endpoint for Execute API: Allows private access to the API Gateway.
- Private API Gateway: Creates a private API that can only be accessed within the VPC or through VPC peering.
- SSM Parameter: Stores the Route Table ID for use in Template 3.

### Outputs:
- Remote VPC CIDR: The CIDR block of the VPC created in this template.
- Peer VPC ID: The ID of the VPC created in this template.
- API Gateway ID: The ID of the created private API Gateway.
- VPC Endpoint URL: The URL of the VPC Endpoint for the Execute API service.
- Region: The region where this template is deployed.

## Template 2: VPC with Peering Connection and Lambda Function

This template creates a VPC in a different region (Region B) and sets up a peering connection to the VPC created in Template 1. It also creates a Lambda function that acts as a client to the API Gateway.

### Key Resources:
- VPC: Creates a new VPC in Region B.
- Subnet: Sets up a subnet within the VPC.
- Internet Gateway: Provides internet access for the VPC.
- Route Table: Configures routing for the VPC.
- Security Group: Defines traffic rules, allowing outbound HTTPS traffic to the remote VPC.
- VPC Peering Connection: Establishes a peering connection with the VPC in Region A.
- Route53 Hosted Zone and DNS Record: Sets up DNS resolution for the private API Gateway.
- Lambda Function: Creates a function that sends requests to the private API Gateway in Region A.

### Important Parameters:
- VPC CIDR Block: Must be different from the CIDR block used in Template 1.
- API ID: The ID of the API Gateway created in Template 1.
- Peer VPC ID: The ID of the VPC created in Template 1.
- Remote VPC CIDR: The CIDR block of the VPC created in Template 1.
- VPC Endpoint URL: The URL of the VPC Endpoint created in Template 1.
- Peer Region: The region where Template 1 was deployed (Region A).

### Outputs:
- Peering Connection ID: The ID of the VPC peering connection.
- VPC CIDR: The CIDR block of the VPC created in this template.

## Template 3: VPC Peering Route

This template adds a route in the VPC created by Template 1 to enable traffic flow through the VPC peering connection.

### Key Resources:
- Route for VPC Peering: Adds a route to the Route Table in the VPC created by Template 1, directing traffic destined for the VPC in Region B through the peering connection.

### Important Parameters:
- Peering ID: The ID of the VPC peering connection created by Template 2.
- Remote VPC CIDR: The CIDR block of the VPC created by Template 2.
- Route Table ID: Retrieved from SSM Parameter Store, set by Template 1.

## Deployment Process

1. Deploy Template 1 in Region A
   - This sets up the VPC with the private API Gateway.
2. Note the outputs from Template 1
3. Deploy Template 2 in Region B
   - Use the outputs from Template 1 as input parameters.
   - This creates a VPC in Region B and establishes the peering connection.
4. Note the Peering Connection ID from the output of Template 2
5. Deploy Template 3 in Region A
   - Use the Peering Connection ID from Template 2 and the VPC CIDR from Template 2 as input parameters.
   - This adds the necessary route to complete the peering connection.

## Lambda Function as Client

The Lambda function created in Template 2 acts as a client that sends requests to the Private API Gateway created in Template 1. This setup allows the Lambda function to securely access the private API across regions through the VPC peering connection. The function uses the DNS record created in Template 2 to resolve the API Gateway's endpoint, ensuring that the traffic flows through the VPC peering connection.

This multi-region setup creates a secure, private network between two VPCs in different regions, allowing the Lambda function in one region to communicate with a private API Gateway in another region.

## Testing the Setup

To test the setup and verify that the Lambda function can successfully communicate with the API Gateway:

1. Navigate to the AWS Lambda console in Region B.
2. Locate and select the Lambda function created by Template 2.
3. In the Lambda function details page, find the "Test" tab or button.
4. Create a new test event or use the default test event configuration.
5. Click the "Test" button to invoke the Lambda function.
6. Review the execution results to confirm successful communication with the API Gateway.

This test will demonstrate that the Lambda function in Region B can successfully send requests to the private API Gateway in Region A through the VPC peering connection.

## GitHub PR for template:
#2477 
## Documentation
- [Working with Private REST API Gateways](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html)
- [Working with Private Hosted Zones](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html)
- [What is VPC Peering?](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html)
- [VPC Endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html)

## Cleanup
 
1. Delete the stack
    ```bash
    aws cloudformation delete-stack --stack-name STACK_NAME
    ```
1. Confirm the stack has been deleted
    ```bash
    aws cloudformation list-stacks --query "StackSummaries[?contains(StackName,'STACK_NAME')].StackStatus"
    ```
## Author bio

Name: Luigi Napoleone Capasso
Technical Account Manager

**Comment by julianwood** [comment]
Merged, thanks
