### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by cheguarox** [aws-samples/serverless-patterns#249]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This SAM template creates a private REST API in Amazon API Gateway that integrates with private resources inside a VPC such as an ECS cluster via a VPC link. This allows for authenticating requests to the backend resource by adding a Cognito authorizer in API Gateway.

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
Cognito to API Gateway private REST API with private integration

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This SAM template implements an Amazon API Gateway private REST API with private integration. It can be used if you have a private API inside a VPC which is currently open to unauthenticated clients and you want to protect it by adding an authentication and authorization layer without having to modify the API itself.

The template creates a private REST API in Amazon API Gateway which sits in front of the original backend API. Requests will go through the API Gateway endpoint and will be authorized using a Cognito authorizer. The integration with the backend resource is done via a VPC link to connect to private resources inside the VPC. The API Gateway API is configured with a greedy proxy ("{proxy+}") which means that everything in the URL path will be passed to the backend without any modification. The API has an "ANY" method to accept all methods such as GET or POST. Finally, the OPTIONS method is configured so that the API can process preflight requests from browsers making cross-origin requests (CORS).

The backend API to be protected is simulated by an ECS Fargate cluster running nginx.

## Deployment commands
git clone https://github.com/aws-samples/serverless-patterns/ 
cd serverless-patterns/cognito-restapi-vpclink

sam deploy -g --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/248

## Author bio 
Name: Jose E. Montilla L.
Photo URL: https://phonetool.amazon.com/users/jmmontil
Twitter handle:
Linkedin: https://www.linkedin.com/in/montillalugo
Description (up to 255 chars):
Security Consultant at Amazon Web Services.

**Comment by jbesw** [comment]
Thanks for the submission - this is now live at https://serverlessland.com/patterns/apigw-vpclink-fargate.

**Comment by cheguarox** [comment]
Hi James, thank you for merging the pattern. However, I see that it was attributed to the wrong author. Please refer to the Author bio in this request for the correct info.
