### ISSUE TITLE
New pattern submission - dynamodb-eventbridge

### ISSUE THREAD

**Issue by tadeumendonca** [aws-samples/serverless-patterns#250]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates an DynamoDB table that streams changed data to EventBridge routing based on payload data properties.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.JS

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
DynamoDB to EventBridge

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

The SAM template deploys a DynamoDB Streams to capture changed data and push to EventBridge routing rules.

When new items are added, updated or deleted on the DynamoDB table, the item-level changes in the table will be streamed to EventBridge bus and will be subject to given routing rules configured based on payload data.

## Deployment commands
sam deploy --guided

## GitHub PR for template: 
#249 

## Author bio 
Name: Luiz Tadeu Mendonça
Photo URL: https://avatars.githubusercontent.com/u/29521634?s=400&u=22b18e1f64056e0ff6a86a4ddcc46d5501ae8546&v=4 
Twitter handle: @tadeumendonca
Description (up to 255 chars): 
  Living 🚀
  Bitcoiner 🤑
  Global Citizen 🌍
  Think Big, Start Small

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/dynamodb-lambda-eventbridge.
