### ISSUE TITLE
New pattern submission - SQS to Lambda using CDK

### ISSUE THREAD

**Issue by praghu1** [aws-samples/serverless-patterns#257]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
The CDK template deploys a Lambda function, an SQS queue and the IAM permissions required to run the application. SQS invokes the Lambda function when new messages are available.
## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Nodejs
## Framework (currently we support SAM or CDK)
CDK
## Services from/to (e.g. "Lambda to EventBridge)
SQS to Lambda
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The CDK template deploys a Lambda function, an SQS queue and the IAM permissions required to run the lambda function. An EventSourceMapping allows SQS to act as source and invoke the Lambda function when new messages are available. The entire message of the SQS queue is sent as event to the Lambda function. The lambda function logs the event to the Cloudwatch logs.

A role is created with the managed policies `AWSLambdaSQSQueueExecutionRole` and `AWSLambdaBasicExecutionRole` to allow to read the SQS messages and log the events to the Cloudwatch.

## Deployment commands
cdk deploy
## GitHub PR for template: 
#256 
## Payload example (e.g. Lambda event payload from source service).
```
{
    "Records": [
        {
            "messageId": "fa2012345678e816-0a49-4681-ba8f-1234567890",
            "receiptHandle": "1234567890NmjC1234567890qODTr1234567890/XPPk/f0qU4tJtQ1234567890ihWDp8YHKhDr3V1234567890e9amjZhgg1234567890RodR1234567890lwDGpf6oLa8/B/1234567890/Pq+xP/1234567890/1234567890fIV6nFUGs71234567890zsj616CBx912M12345678908rxtUEj1234567890J8d1234567890yDcI9E12345678905mTyYZ41S2cP01NCA1234567890jcalHD1234567890Kio+HFQp1234567890OI7bTs5I7pZJ4pu+BnM8Bcki1234567890aNML5B7S12345678904eYKKcrunp1234567890Qhz7BUWPG41",
            "body": "Test message",
            "attributes": {
                "ApproximateReceiveCount": "1",
                "SentTimestamp": "1612966720445",
                "SenderId": "AIDA3DTKMG1234567890",
                "ApproximateFirstReceiveTimestamp": "1612966720455"
            },
            "messageAttributes": {},
            "md5OfBody": "82dfa5549ebc91234567890ece5f",
            "eventSource": "aws:sqs",
            "eventSourceARN": "arn:aws:sqs:us-east-1:123456789012:patterns-sqs-to-lambda-MySqsQueue-1234567890",
            "awsRegion": "us-east-1"
        }
    ]
}
```
## Author bio 
Name: Raghu Chandra Putta Sesha
Photo URL:
Twitter handle:
Description (up to 255 chars): Lead Consultant

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/sqs-lambda-cdk.
