### ISSUE TITLE
New pattern submission - lambda-sqs-cdk

### ISSUE THREAD

**Issue by albinoneto** [aws-samples/serverless-patterns#260]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that sends messages to a Sqs Queue using CDK

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Lambda to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The CDK deploys a Lambda function, an SQS queue and the IAM permissions required to run the application. The Lambda function publishes a message to the SQS queue when invoked.

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/259

## Payload example (e.g. Lambda event payload from source service).
aws lambda invoke --function-name <Replace by function name> --cli-binary-format raw-in-base64-out --payload '{ "msg": "test" }' response.json"

## Additional resources (optional: link and anchor text, up to 5 resources)
https://aws.amazon.com/blogs/compute/choosing-between-messaging-services-for-serverless-applications/
https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

## Author bio 
Name: Jose Albino Neto
Photo URL: https://media-exp1.licdn.com/dms/image/C4D03AQEHUJn_OrYX1g/profile-displayphoto-shrink_400_400/0/1611624741365?e=1645056000&v=beta&t=ZDAHmVteh3uJ8h6hrpvCr-DH9CFWtxFN8Wp4SRPSZ5s
Twitter handle: 
Description (up to 255 chars): AppDev Consultant @ AWS. Follow me on Linkedin: https://www.linkedin.com/in/albinoneto/

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-sqs-cdk.
