### ISSUE TITLE
New pattern submission - codecommit-s3

### ISSUE THREAD

**Issue by mphauer** [aws-samples/serverless-patterns#264]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Backup CodeCommit repositories to S3 buckets

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
Codecommit to S3

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern implements the solution outlined on the https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/automate-event-driven-backups-from-codecommit-to-amazon-s3-using-codebuild-and-cloudwatch-events.html
It uses a Lambda function and a CloudFormation Custom Resource to create the CodeBuild buildspec.yml template at deployment time, and the EventBridge and CodeBuild project described on the AWS Prescriptive Guidance. It also creates the IAM roles and policies that enable:
* CodeBuild to clone the CodeCommit repository, upload files to the S3 bucket, and send logs to Amazon CloudWatch
* EventBridge to trigger AWS CodeBuild build
* Lambda to upload files to S3 bucket
After the pattern is deployed, each time the content on a CodeCommit repository is modified, the repository is cloned, zipped and sent to the S3 bucket.

## Deployment commands
```
sam deploy --guided  --capabilities CAPABILITY_NAMED_IAM
```
## GitHub PR for template: 
[#263](https://github.com/aws-samples/serverless-patterns/pull/263)

## Payload example (e.g. Lambda event payload from source service).
N/A

## Author bio 
Name: Marcos Hauer
Photo URL: https://avatars.githubusercontent.com/u/96396801?v=4
Twitter handle: N/A
Description (up to 255 chars): I'm a Cloud Architect, SRE and AWS DevOps Consultant.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/codecommit-s3.
