### ISSUE TITLE
New pattern submission - msk-lambda-cdk

### ISSUE THREAD

**Issue by sudopablosilva** [aws-samples/serverless-patterns#271]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that uses an Amazon MSK topic as an event source.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Nodejs 14.x

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
MSK to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Lambda is a consumer application for your Kafka topic. It processes records from one or more partitions and sends the payload to the target function. Lambda continues to process batches until there are no more messages in the topic.

Lambda internally polls for new messages from the event source and then synchronously invokes the target Lambda function. Lambda reads the messages in batches and provides these to your function as an event payload. The maximum batch size is configurable. (The default is 100 messages.)

The CDK template creates a Lambda Function that uses a AWSLambdaMSKExecutionRole IAM role to poll a certain topic within a certain MSK Stream as defined as the Event source in the template.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```bash
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory its source code folder:
    ```bash
      cd msk-lambda-cdk
    ```
3. From the command line, use npm to install the development dependencies:
    ```bash
      npm install
    ```
4. To deploy from the command line use the following:
    ```bash
      npx cdk bootstrap aws://accountnumber/region
      npx cdk deploy
    ```
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/270

## Payload example (e.g. Lambda event payload from source service).
```
{   "eventSource": "aws:kafka",
    "eventSourceArn": "arn:aws:kafka:sa-east-1:123456789012:cluster/vpc-2priv-2pub/751d2973-a626-431c-9d4e-d7975eb44dd7-2",
    "records": {
      "mytopic-0": [
          {
            "topic": "mytopic"
            "partition": "0",
            "offset": 15,
            "timestamp": 1545084650987,
            "timestampType": "CREATE_TIME",
            "value": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0Lg==",
          }
      ]
    }
}
```
## Additional resources (optional: link and anchor text, up to 5 resources)
- [Using Lambda with Amazon MSK](https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html)
- [Using Amazon MSK as an event source for AWS Lambda](https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/)
## Author bio 
Name: Pablo Silva
Photo URL: https://avatars.githubusercontent.com/u/87768873?s=400&u=2b9b4c5961a5b742d82c81f3620438bb29f76a9c&v=4
Linkedin: https://www.linkedin.com/in/pablo-rhuam-cavalcante-silva-42661822
Description (up to 255 chars): Sr. Consultant, DevOps at AWS Professional Services

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/msk-lambda-cdk.

**Comment by sudopablosilva** [comment]
Really appreciate, James.

Regards,
Pablo Silva
