### ISSUE TITLE
New pattern submission - Lambda to SNS CDK

### ISSUE THREAD

**Issue by JBoggan** [aws-samples/serverless-patterns#278]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This creates a Lambda function that sends an arbitrary message to an SNS topic and provides minimal publishing permissions.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python

## Framework (currently we support SAM or CDK)
CDK
## Services from/to (e.g. "Lambda to EventBridge)
Lambda to SNS
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This creates a Lambda function with associated CloudWatch logs, an SNS topic, and topic publishing permissions to the Lambda function. The desired message and topic ARN is passed to the Lambda in the event payload.

## Deployment commands

cdk deploy

## GitHub PR for template: 
#277 

## Payload example (e.g. Lambda event payload from source service).

'{ "topic_arn": "arn:aws:sns:us-west-2:xxxxxxxxxxx:LambdaSnsCdkStack-snstolambdatopic0C6A5C89-1SXVUWJ85OA77", "message": "Hello, SNS topic!" }'

## Author bio 
Name: Jake Boggan
Photo URL: https://github.com/jboggan.png
Twitter handle: @jboggan
Description (up to 255 chars): I'm an ML & Data Engineer with AWS Professional Services

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-sns-cdk.
