### ISSUE TITLE
New pattern submission - S3 to SQS CDK

### ISSUE THREAD

**Issue by JBoggan** [aws-samples/serverless-patterns#280]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This creates an S3 bucket, SQS queue, and the former notifies the latter when new objects are created, with appropriate permissions.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Python

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

S3 to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

S3 bucket is created, SQS queue is created, an event notification is assigned from the bucket to the queue which implicitly creates the sqs:GetQueueAttributes, GetQueueUrl, and SendMessage permissions for the bucket.

## Deployment commands

cdk deploy

## GitHub PR for template: 

#279 

## Author bio 
Name: Jake Boggan
Photo URL: https://github.com/jboggan.png
Twitter handle: @jboggan
Description (up to 255 chars): I'm an ML & Data Engineer with AWS Professional Services

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/s3-sqs-cdk.
