### ISSUE TITLE
New pattern submission: AWS State Functions (SFN) integration with AWS VPC Lambda 

### ISSUE THREAD

**Issue by shindeja** [aws-samples/serverless-patterns#282]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

![image](https://user-images.githubusercontent.com/93898993/147378846-ff80b348-2bc0-41f0-bc7f-78fdd97e13c5.png)

## Description 
AWS State Functions (SFN) integration with AWS VPC - Lambda 
This pattern in CDK offers a example to generate an Amazon State Machine which
consumes AWS Lambda function which is deployed inside AWS VPC.

## Description:
This pattern in CDK offers a example to generate an Amazon State Machine which
consumes AWS Lambda function which is deployed inside AWS VPC. AWS Lambda Function is created which is part of VPC's Private Subnet. Network interface created from VPC to access state functions. All traffic will route through this interface.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```
    cd cdk-vpc-lambda-stepfunctions
    ```
3. To deploy from the command line use the following:
    ```bash
      npx cdk bootstrap aws://accountnumber/region
      npm run lambda
      npx cdk synth
      npx cdk deploy
    ```

## GitHub PR for template:  
https://github.com/aws-samples/serverless-patterns/pull/281

## Author bio 
Name: Jayesh A Shinde
Photo URL: https://github.com/shindeja/shindeja/blob/main/shindeja.jpeg
Twitter handle: https://twitter.com/jayeshashinde
Description: Jayesh is Cloud Application Architect at AWS Pro-serve India.

Name: Atul Sharma
Photo URL: https://github.com/shindeja/shindeja/blob/main/atulsharma.jpeg
Twitter handle: NA
Description: Atul is Sr. Cloud Application Architect at AWS Pro-serve India.

Name: Feroz Kumar
Photo URL: https://github.com/shindeja/shindeja/blob/main/feroz.jpeg
Twitter handle: NA
Description: Feroz is Cloud Application Consultant at AWS Pro-serve India.

**Comment by jbesw** [comment]
Thanks for your contribution - this is now live at https://serverlessland.com/patterns/sfn-lambda-vpc-cdk.
