### ISSUE TITLE
New pattern submission: Fargate to SNS CDK

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#285]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Create a Fargate Service that uses a custom image that integrates with SNS by publishing messages to an SNS topic, written in CDK.

## Language:

TypeScript

## Framework

CDK

## Services from/to

AWS Fargate to Amazon SNS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster with an Application Load Balancer in-front. The AWS Fargate service makes `publish` calls to an Amazon Simple Notification Service (SNS) topic. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built `ecs.ContainerImage.fromAsset` method. The custom image has a base route `/` for health checks, `/sendmessage` for publishing to the topic. Environment variables like the SNS Topic and AWS region are passed to the image to enable it to perform actions on the SNS Topic.

This project also shows how to set up an SNS Interface Endpoint to the VPC. A VPC Endpoint policy is created to only allow the Fargate task definition to perform actions through the VPC endpoint.

IAM permissions

1. Writes to the SNS topic are controlled using the built-in CDK permissions via `topic.grantPublish(fargate.taskDefinition.taskRole);`
2. VPC Endpoint policies allow only the Fargate Service `'sns:Publish'` action on the SNS topic

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#286 

## Payload example (e.g. Lambda event payload from source service).

Make a POST request to the `/sendmessage` endpoint. This publishes a message to the SNS topic. For example:

```bash
curl --location --request POST '<REPLACE WITH FARGATE SERVICE URL>/sendmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Message": "hello serverless fargate sns"
}'
# Example
curl --location --request POST 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/sendmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Message": "hello serverless fargate sns"
}'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

Retrieve the Service URL from `cdk deploy`

![image](https://user-images.githubusercontent.com/31919569/142186611-990ff99f-03b1-4db0-955b-de338f01fb27.png)

Running all the requests above should produce the following output:

![image](https://user-images.githubusercontent.com/31919569/147472046-fca209d7-4e1d-4424-8a22-983ec5a31321.png)

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn (Handle for Serverless Pattern website): https://www.linkedin.com/in/glenn-chia-291344142
Twitter (Handle for Twitter mentions): @ glenncjw (https://twitter.com/glenncjw)
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cdk-fargate-sns.
