### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by mthojoh** [aws-samples/serverless-patterns#289]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description 
Create a WebACL and associate it with an existing API Gateway REST or Websocket API.

## Framework (currently we support SAM or CDK)
SAM

## Services from/to 
API Gateway Integration with AWS WAF

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern generates a WebACL with rate limiting, SQL injection protection, and XSS detection and associates it an existing REST or Websocket API. This is a SAM implementation of an existing CDK implementation already published in this repo.

## Deployment commands
```
sam build && sam deploy --guided
```
## GitHub PR for template: 
#288 
## Author bio 
Name: JJ Johnson
Photo URL: https://en.gravatar.com/userimage/512850/5a1d4b0671dc15032d5cc0d13d8612fd.jpeg
Twitter handle:
Description (up to 255 chars): JJ is a Cloud Application Architect who works in the US

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-waf.
