### ISSUE TITLE
New pattern submission s3-sqs-lambda

### ISSUE THREAD

**Issue by me2resh** [aws-samples/serverless-patterns#29]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an S3 bucket that sends notifications for created objects to an SQS queue that triggers a lambda function that resizes the image and uploads it to another S3 bucket

<img width="804" alt="s3-sqs-lambda" src="https://user-images.githubusercontent.com/23076/113829213-2147ec80-977d-11eb-8263-a4b5ebe30d14.png">

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
NodeJS

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
S3 to Lambda through SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This is an update to the [s3-lambda pattern](https://serverlessland.com/patterns/s3-lambda), for busy applications with high throughput to s3 buckets. Using SQS between S3 and Lambda enables scale by retaining the events in the SQS queue and throttling it for downstream services.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```bash
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```bash
    cd s3-sqs-lambda
    ```
3. Install dependencies
   ```bash
   npm --prefix ./src install ./src
   ```
4. From the command line, use AWS SAM to build and deploy the AWS resources for the pattern as specified in the template.yml file:
    ```bash
    sam build
    sam deploy --guided
    ```
5. During the prompts:
   * Enter a stack name
   * Enter a source bucket name
   * Enter a destination bucket name
   * Enter a queue name
   * Enter the desired AWS Region
   * Allow SAM CLI to create IAM roles with the required permissions.

## GitHub PR for template: 
[https://github.com/aws-samples/serverless-patterns/pull/28](https://github.com/aws-samples/serverless-patterns/pull/28)
## Payload example (e.g. Lambda event payload from source service).
```
{
    "Records": [
        {
            "messageId": "239496d6-987e-4631-bb0c-9ee00c1243a3",
            "receiptHandle": "AQEBBY2n5vRQWUo4WaTIb/0zUVANEo+ygKvLGenR0DQVHUL3efjE8l2NcObReeQbVozl6gSy9jvzHlcC8i9NycYM+/8YhxHpt6J5nstcUaJLh3+oEV9Eof0qMzqiecvb31ZJwkQAUXAQPLwpXgnhLHhozZcdBay4TCX+vKaDCcVP0P0G30MnD4FwYuT/wAqtq34KOEV9vZP9QG7TrCkQ/5ryerd/8ymkrvNlFW94SmZ0i8yi/j98zB4l151DFNdqmSt9f3H8AucdSwW3WOMNtvKedIoEXyL65kKAnnRtFrMhdw3oCrFgPhyLGQDL3AGJcuJHVeRYwZzk+/q5fFCcl6QRyNWnKgzc2oSqfWC0RRjcOtEGv09yVFZ+iOp0L1P1WKxBZEnB3VKbxY5GjN84O0ZAS6OR6cxZgyaoZ4rtJGJE5mk=",
            "body": "{\"Records\":[{\"eventVersion\":\"2.1\",\"eventSource\":\"aws:s3\",\"awsRegion\":\"eu-west-1\",\"eventTime\":\"2021-04-07T06:14:04.778Z\",\"eventName\":\"ObjectCreated:Put\",\"userIdentity\":{\"principalId\":\"A2ZDMGT5VFDF6M\"},\"requestParameters\":{\"sourceIPAddress\":\"176.27.106.101\"},\"responseElements\":{\"x-amz-request-id\":\"P1VGF5JWZMW8RR2X\",\"x-amz-id-2\":\"HUB/BNDVJZrlNyUmGs7/ZBj4TISouA+H0FcRvv2hH8E9cik3xwcSsOLmpY47mFM4pc6kBq2aRzapdQXwIQoAYvl1MEK32GAe\"},\"s3\":{\"s3SchemaVersion\":\"1.0\",\"configurationId\":\"7b5a53f8-7d1f-42ec-91aa-24639104169d\",\"bucket\":{\"name\":\"sam-app-s3-lambda-source-bucket\",\"ownerIdentity\":{\"principalId\":\"A2ZD87DEWCGF6M\"},\"arn\":\"arn:aws:s3:::sam-app-s3-lambda-source-bucket\"},\"object\":{\"key\":\"img-ui-cdgsx.jpg\",\"size\":39750,\"eTag\":\"de58b5901607f5dbcf05887673f066c9\",\"sequencer\":\"00606D4VB143BF9560\"}}}]}",
            "attributes": {
                "ApproximateReceiveCount": "12",
                "SentTimestamp": "1617776050200",
                "SenderId": "AIDAJQOC3SADRY5FRGCHS",
                "ApproximateFirstReceiveTimestamp": "1617776050200"
            },
            "messageAttributes": {},
            "md5OfBody": "d2d36a233c286f987523768f5bdf2a10",
            "eventSource": "aws:sqs",
            "eventSourceARN": "arn:aws:sqs:eu-west-1:482783742093:sam-app-s3-lambda-resizer-queue",
            "awsRegion": "eu-west-1"
        }
    ]
}
```

## Additional resources (optional: link and anchor text, up to 5 resources)
https://aws.amazon.com/blogs/compute/building-scalable-serverless-applications-with-amazon-s3-and-aws-lambda/

## Author bio 
Name: Ahmed Mohamed
Photo URL: https://www.me2resh.com/assets/img/me2resh.jpeg
Twitter handle: me2resh
Description (up to 255 chars): I am a Principal Software Engineer, Solutions Architect and Serverless Enthusiast. I spend my time learning new stuff and building large scale clinical solutions in the cloud.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/s3-sqs-lambda.

**Comment by me2resh** [comment]
Thanks @jbesw for merging this.
I noticed that the diagram in the published article doesn't have the correct flow as the one I submitted. it is in the opposite direction. should be from s3 ---> sqs ---> lambda. right now it is the opposite in the published page.

**Comment by jbesw** [comment]
Thanks for flagging this! It's has now been resolved.
