### ISSUE TITLE
New pattern submission: Fargare to SNS to SQS

### ISSUE THREAD

**Issue by arunvthangaraj** [aws-samples/serverless-patterns#290]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Create fargate service that publishes message to a SNS topic and reads a message from a SQS queue which is subscribed to the SNS topic. 

## Language: 

TypeScript

## Framework:

CDK

## Services from/to:

Fargate to SNS to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster with an Application Load Balancer in-front. The AWS Fargate service makes publish call to an Amazon Simple Notification Service (SNS) and receiveMessage call to an Amazon Simple Queue Service (SQS) queue which is subscribed to the SNS topic that the template creates. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built ecs.ContainerImage.fromAsset method. The custom image has a base route / for health checks, /publishmessage for adding to the queue and /readmessage for reading messages from the queue. Environment variables like the SQS Queue URL, SNS Topic ARN and AWS region are passed to the image to enable it to perform actions on the SNS Topic and SQS Queue.

This project also shows how to set up an SNS and SQS Interface Endpoint to the VPC. A VPC Endpoint policy is created to only allow the Fargate task definition to perform actions through the VPC endpoint. In addition, an access policy is set on the SNS topic and SQS queue to deny requests that are not from the created Interface Endpoint.

## Deployment commands

cdk deploy

## GitHub PR for template: 

#291

## Payload example (e.g. Lambda event payload from source service).

There are 2 endpoints that integrate with the SNS topic and SQS queue.

Make a POST request to the `/publishmessage` endpoint. This publishes a message to the SNS topic. For example:

```bash
curl --location --request POST '<REPLACE WITH FARGATE SERVICE URL>/publishmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "MessageBody": "hello serverless fargate sns sqs"
}'
# Example
curl --location --request POST 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/publishmessage' \
--header 'Content-Type: application/json' \
--data-raw '{
    "MessageBody": "hello serverless fargate sns sqs"
}'
```

Make a GET request to the `/readmessage` endpoint. This retrieves the message from the queue. For example:

```bash
curl --location --request GET '<REPLACE WITH FARGATE SERVICE URL>/readmessage'
# Example
curl --location --request GET 'http://CdkSt-MyFar-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/readmessage'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

- [AWS SNS Developer Guide: Deny access if it isn;t from a VPC endpoint](https://docs.aws.amazon.com/sns/latest/dg/sns-access-policy-use-cases.html#sns-restrict-publication-only-from-specified-vpc-endpoint)
- [AWS SNS Developer Guide: Creating an Amazon VPC endpoint policy for Amazon SNS](https://docs.aws.amazon.com/sns/latest/dg/sns-vpc-endpoint-policy.html)
- [AWS SNS Developer Guide: Publish a message to the topic using the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-sns.html#cli-publish-sns-topic)
- [AWS SQS Developer Guide: Deny access if it isn't from a VPC endpoint](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-creating-custom-policies-access-policy-examples.html#deny-not-from-vpc)
- [AWS SQS Developer Guide: Creating an Amazon VPC endpoint policy for Amazon SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-internetwork-traffic-privacy.html#sqs-vpc-endpoint-policy)
- [AWS SQS Developer Guide: Send a message to the queue using the AWS CLI](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-sending-messages-from-vpc.html#sqs-vpc-tutorial-publish)
- [CDK documentation for ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html)
- [CDK documentation for SNS](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-sns-readme.html)
- [AWS Javascript SDK - SNS](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html)
- [CDK documentation for SQS](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sqs-readme.html)
- [AWS JavaScript SDK - SQS](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html)

## Author bio 
Name: Arun Thangaraj
Photo URL:
Twitter handle:
Description (up to 255 chars): Arun is a Cloud Application Architect at AWS Professional Services based out of Dallas, TX

**Comment by jbesw** [comment]
Thanks for the contribution - it's now live at https://serverlessland.com/patterns/cdk-fargate-sns-sqs.
