### ISSUE TITLE
New pattern submission: Fargate to SFN CDK

### ISSUE THREAD

**Issue by GlennChia** [aws-samples/serverless-patterns#292]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description

Create a Fargate Service that uses a custom image that integrates with AWS Step Functions by starting the execution of a State Machine, written in CDK.

## Language:

TypeScript

## Framework

CDK

## Services from/to

AWS Fargate to AWS SFN

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS Fargate service running on an Amazon Elastic Container Service (ECS) cluster with an Application Load Balancer in-front. The AWS Fargate service makes `startExecution` calls to an AWS Step Functions (SFN) state machine. This template uses a custom image without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built `ecs.ContainerImage.fromAsset` method. The custom image has a base route `/` for health checks, and `/startexecution` route for executing the state machine. Environment variables like the state machine ARN and AWS region are passed to the image to enable it to perform actions on the state machine.

This project also shows how to set up an Step Functions Interface Endpoint to the VPC. A VPC Endpoint policy is created to only allow the Fargate task definition to perform actions through the VPC endpoint.

The Step Function example was inspired by the Lambda-SFN pattern that can be found here https://serverlessland.com/patterns/lambda-sfn. In this example, instead of the JSON that the link uses, I created a CDK version of it which does not require a separate JSON.

IAM permissions

1. Start execution of the State Machine is controlled using the built-in CDK permissions via `stateMachine.grantStartExecution(fargate.taskDefinition.taskRole);`
2. VPC Endpoint policies allow only the Fargate Service `'states:StartExecution'` action on the State Machine

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#293 

## Payload example (e.g. Lambda event payload from source service).

Make a POST request to the `/startexecution` endpoint. This executes the State Machine and branches based on the `true` condition. For example:

```bash
curl --location --request POST '<REPLACE WITH FARGATE SERVICE URL>/startexecution' \
--header 'Content-Type: application/json' \
--data-raw '{
    "IsHelloWorldExample": true
}'
# Example
curl --location --request POST 'http://CdkSt-Farga-123456789ABC-123456789.ap-southeast-2.elb.amazonaws.com/startexecution' \
--header 'Content-Type: application/json' \
--data-raw '{
    "IsHelloWorldExample": true
}'
```

## Additional resources (optional: link and anchor text, up to 5 resources)

Retrieve the Service URL from `cdk deploy`

![image](https://user-images.githubusercontent.com/31919569/142186611-990ff99f-03b1-4db0-955b-de338f01fb27.png)

Running the POST request with parameter set to `true` produces:

![image](https://user-images.githubusercontent.com/31919569/147874090-715e285e-598a-41ef-afb7-a86ba565686a.png)

![image](https://user-images.githubusercontent.com/31919569/147874092-ab473634-c7dc-4435-95e6-6f8ca1464227.png)

Running the POST request with parameter set to `false` produces:

![image](https://user-images.githubusercontent.com/31919569/147874098-27eb5d93-b51a-4a8c-96da-596cd6e3150c.png)

![image](https://user-images.githubusercontent.com/31919569/147874101-c6cc6ac0-971d-49c7-a79f-e47c6a927d88.png)

## Author bio 
Name: Glenn Chia Jin Wee
Photo URL: https://media-exp1.licdn.com/dms/image/C5603AQEZX1SGrS8JxQ/profile-displayphoto-shrink_200_200/0/1629195532005?e=1637798400&v=beta&t=6K7AiWi4U4nA5hdDT_xCi5fPufBaqpvUvxRMbHBSyJM
LinkedIn (Handle for Serverless Pattern website): https://www.linkedin.com/in/glenn-chia-291344142
Twitter (Handle for Twitter mentions): @ glenncjw (https://twitter.com/glenncjw)
Description (up to 255 chars): Glenn is an Associate Cloud Architect at AWS based in Singapore

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cdk-fargate-sfn.
