### ISSUE TITLE
New pattern submission - APIGW-Lambda-QLDB

### ISSUE THREAD

**Issue by mlewis7127** [aws-samples/serverless-patterns#295]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an API Gateway REST API that uses a Lambda function to call QLDB

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway to Lambda to QLDB

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern shows how to deploy a SAM template with Amazon API Gateway, AWS Lambda and Amazon Quantum Ledger Database (QLDB). The API Gateway exposes a REST API with a number of methods. Each API method uses a Lambda proxy integration to invoke a separate AWS Lambda function that interacts with a ledger in Amazon QLDB. This allows you to create a new Person record, update the record, delete the record, view the current state of the record, and view the entire revision history.

Each Lambda function is configured with the minimum set of permissions necessary. For example, only the `Get Person History` function has the `qldb:PartiQLHistoryFunction` permission needed to query the full revision history.

## Deployment commands
sam build
sam deploy --guided

## GitHub PR for template: 
#294 

## Additional resources (optional: link and anchor text, up to 5 resources)
- [Amazon QLDB documentation](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started-driver.html)
- [Real world cryptographic verification with Amazon QLDB](https://aws.amazon.com/blogs/database/real-world-cryptographic-verification-with-amazon-qldb/)
- [QLDB Shell](https://github.com/awslabs/amazon-qldb-shell)
- [AWS re:Invent 2020 - Building out a serverless application with Amazon QLDB](https://www.youtube.com/watch?v=dtBpwCBlz6M)
- [QLDB Guide](https://qldbguide.com/)

## Author bio 
Name: Matt Lewis
Photo URL: https://qldbguide.com/images/MattLewis-Profile.jpg
Twitter handle: @m_lewis
Description (up to 255 chars): Matt is an AWS Data Hero, and an organiser of the AWS South Wales User Group and ServerlessDays Cardiff conference

**Comment by jbesw** [comment]
Thanks for the submission! This is now live at https://serverlessland.com/patterns/apigw-lambda-qldb.
