### ISSUE TITLE
Duplicate `Description`-property

### ISSUE THREAD

**Issue by ljacobsson** [aws-samples/serverless-patterns#3]
There's a duplicate `Description` property in the template for sns-eventbridge

See [eventbridge-sns/template.yaml#L41](https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-sns/template.yaml#L41)

**Comment by ljacobsson** [comment]
Same is true in [dynamodb-lambda](https://github.com/aws-samples/serverless-patterns/blob/main/dynamodb-lambda/template.yaml#L11)

**Comment by jbesw** [comment]
Thanks! I've updated these - it will take a few hours to sync with the main site.
