### ISSUE TITLE
New pattern submission - Amazon Cloudfront to Amazon Cloudfront Functions to Amazon S3

### ISSUE THREAD

**Issue by cornelcroi** [aws-samples/serverless-patterns#303]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern deploys an Amazon Cloudfront distribution, an Amazon Cloudfront Function and a Amazon S3 Bucket and demonstrates how to implement an A/B testing solution.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Python

## Framework (currently we support SAM or CDK)

CDK 

## Services from/to (e.g. "Lambda to EventBridge)

Amazon Cloudfront to Amazon Cloudfront Functions to Amazon S3

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

Using Cloudfront Function change dynamically the uri to display randomly either the old home page either the new home page.

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/302

## Author bio 
Name: Corneliu Croitoru
Photo URL:
Twitter handle: cornel_croi
Description (up to 255 chars):

Developer at heart, in 2018 joined AWS as a Solution Architect and since 2021 building, jointly with customers, the most exciting and innovative prototypes on AWS.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cloudfront-functions-s3.
