### ISSUE TITLE
New pattern submission - DynamoDB Streams to Lambda fn with event filters

### ISSUE THREAD

**Issue by zachjonesnoel** [aws-samples/serverless-patterns#304]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
DynamoDB Streams which triggers Lambda fns with event based filters that are defined. If the event matches the filter criteria, it invokes the respective Lambda fn otherwise drops the event. 

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
NodeJS
## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
DynamoDB Streams to Lambda fn based on the event filter

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
DynamoDB Streams invoking Lambda function with event filters. 
The SAM template defines the following resources - 
- Amazon DynamoDB
- Amazon Lambda functions
- IAM policy for Lambda function execution

Whenever there is any change in DynamoDB with the operations `PUT`, `UPDATE`, `DELETE`, it invokes the Lambda function which have the source of invocation as DynamoDB. The Lambda function is defined with the respective IAM role to read the data from DynamoDB Streams. With DynamoDB Streams, now the invocation can be filtered with a specific expression or pattern in the invocation event JSON. 

The below `FilterCriteria` is defined with the pattern being only the items which are inserted into DynamoDB.
```yaml
          FilterCriteria:
              Filters:
                  # Filter pattern to check only inserted action on DynamoDB
                - Pattern: '{"eventName": ["INSERT"]}'
```
Whenever Lambda function polls and retrieve data from DynamoDB Streams, if the `FilterCriteria` is defined, it validates if the event JSON matches with the pattern only if that matches, the Lambda function gets invoked otherwise the event is dropped. 

## Deployment commands
Create a new directory, navigate to that directory in a terminal and clone the GitHub repository
```bash
git clone https://github.com/aws-samples/serverless-patterns
```
Change directory to the pattern directory:
```bash
cd dynamodb-streams-lambda-event-filters
```
From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:
```bash
sam build
sam deploy --guided
```

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/301
## Additional resources (optional: link and anchor text, up to 5 resources)
- [AWS announcement blog](https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-event-filtering-amazon-sqs-dynamodb-kinesis-sources/)
- [Trigger Lambda Functions with event filtering](https://dev.to/aws-builders/trigger-lambda-functions-with-event-filtering-2pnb)
- [Deep dive into Lambda event-filters for DyanmoDB](https://dev.to/aws-builders/deep-dive-into-lambda-event-filters-for-dyanmodb-320)

## Author bio 
Name: Jones Zachariah Noel N (zachjonesnoel)
Photo URL: https://photos.app.goo.gl/kXWzvqgYwy9V6d157
Twitter handle: @zachjonesnoel 
Description (up to 255 chars): Cloud Architect - Serverless @ Mobil80 Solutions and Services Pvt Ltd, India and AWS Community Builder. A serverless geek and enthusiastic about building serverless applications with SAM.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/dynamodb-lambda-filters.
