### ISSUE TITLE
New pattern submission - Amazon Cloudfront to AWS Lambda@Edge

### ISSUE THREAD

**Issue by cornelcroi** [aws-samples/serverless-patterns#306]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern demonstrates how to generate content at edge using AWS Lambda@Edge.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Python 

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/305

## Author bio 
Name: Corneliu Croitoru
Photo URL:
Twitter handle: cornel_croi
Description (up to 255 chars):

Developer at heart, in 2018 joined AWS as a Solution Architect and since 2021 building, jointly with customers, the most exciting and innovative prototypes on AWS.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cloudfront-lambda-edge.
