### ISSUE TITLE
New pattern submission - Lambda to Pinpoint

### ISSUE THREAD

**Issue by rohanmeh** [aws-samples/serverless-patterns#308]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that sends SMS via Pinpoint.
## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js
## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
Lambda to Pinpoint
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern demonstrates a Lambda function sending SMS via Pinpoint. The Lambda function has an associated IAM role that allows it to send SMS with the Pinpoint project.

## Deployment commands
sam deploy --guided
## GitHub PR for template: 
#307 
## Payload example (e.g. Lambda event payload from source service).
{
  "key": "value",
}
## Additional resources (optional: link and anchor text, up to 5 resources)
[Requesting Pinpoint Origination Number](https://docs.aws.amazon.com/pinpoint/latest/userguide/settings-sms-request-number.html)
[Verifying Pinpoint Destination Number](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-sandbox.html)

## Author bio 
Name: Rohan Mehta
Photo URL: https://phonetool.amazon.com/users/merohan
Twitter handle: @rohanmehta_dev
Description (up to 255 chars): Associate Cloud Application Architect at AWS.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-pinpoint.
