### ISSUE TITLE
New pattern submission Step Function to S3 bucket

### ISSUE THREAD

**Issue by SimonCMoore** [aws-samples/serverless-patterns#309]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern creates a Step Functions workflow that publishes a file to an S3 bucket.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
SAM template inline definition

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
Step Function to S3 bucket

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern creates a Step Functions workflow that publishes a file to an S3 bucket.
Permissions via IAM we create a role with a policy to allow the SFN to assume role and write a file to the bucket

## Deployment commands
sam deploy --guided

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/222/files

## Additional resources (optional: link and anchor text, up to 5 resources)
Execute workflow by
aws stepfunctions start-execution --state-machine-arn ENTER_YOUR_STATE_MACHINE_ARN

View the newly create file in the bucket
aws s3 ls my-sfn-bucket-destination

## Author bio 
Name: Simon Moore
Photo URL:
Twitter handle:
Description (up to 255 chars):

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/sfn-s3.
