### ISSUE TITLE
New pattern : CodeCommit-CodePipeline-Stepfunction-Athena-Glue

### ISSUE THREAD

**Issue by shindeja** [aws-samples/serverless-patterns#312]
## Description : 
This pattern in CDK offers an example to generate an AWS Code Pipeline which invokes Steps Functions to execute Athena Named Queries in Glue Data Catalog.

## Description : 

CDK CodePipeline is spin up against AWS CodeCommit repository, which will trigger AWS StepFunction to call AWS Athena NamedQueries to create Views and Tables.

Branch Name and CodeCommit repository details needs to be provided in the configuration file `src/config.ts`.

If the s3 stack fails due to already existing s3 bucket name, simply change the prefix (from `src/config.ts`) to some random unique value with 8-12 characters. This will make s3 Buckets name unique.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```
1. Change directory to the pattern directory:
    ```
    cd cdk-codecommit-codepipeline-sfn-athena-glue
    ```
1. From the command line, use AWS SAM to deploy the AWS resources for the pattern as specified in the template.yml file:
    ```bash
      npx cdk bootstrap aws://accountnumber/region
      npx cdk synth
      npx cdk deploy
    ```

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/311

## Author bio 
Name: Jayesh A Shinde
Photo URL: https://github.com/shindeja/shindeja/blob/main/shindeja.jpeg
Twitter handle: https://twitter.com/jayeshashinde
Description: Jayesh is Cloud Application Architect at AWS Pro-serve India.

Name: Atul Sharma
Photo URL: https://github.com/shindeja/shindeja/blob/main/atulsharma.jpeg
Twitter handle: NA
Description: Atul is Sr. Cloud Application Architect at AWS Pro-serve India.

Name: Feroz Kumar
Photo URL: https://github.com/shindeja/shindeja/blob/main/feroz.jpeg
Twitter handle: NA
Description: Feroz is Cloud Application Consultant at AWS Pro-serve India.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/codepipeline-sfn-glue-cdk.
