### ISSUE TITLE
New pattern submission - Eventbridge API Destinations Zendesk Integration

### ISSUE THREAD

**Issue by PurpleAmyr** [aws-samples/serverless-patterns#314]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This Pattern is an extension of the EventBridge API Destinations Pattern. It is a pattern which creates a custom event bridge connection, bus, API destination, Rule, and DLQ which allows the user to utilize the Zendesk Put Ticket API.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
YAML and JSON

## Framework (currently we support SAM or CDK)
Cloud Formation

## Services from/to (e.g. "Lambda to EventBridge)
Eventbridge, SQS, IAM from Cloud Formation (Cloud Formation creates resources in these 3 services)
EventBridge to SQS (Failed messages go to DLQ)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern creates an API Destination for the Zendesk Put Tickets API. Once deployed, the pattern allows a user to send events easily through Event Bridge to Zendesk to create tickets. The pattern creates the following resources: Event Bridge Bus, Event Bridge Connection, Event Bridge API Destination, Event Bridge Rule, IAM Role, and SQS Queue. 

The Event Bridge rule uses the API Destination and Connection as a target, SQS Queue as a DLQ, and the IAM role as its role. To send events go to the bus and send sample events. To create a ticket enter “MyTestMessage” for the detail type, “MyTestApp” for the source, the bus created by the pattern for the Event Bus Name, and any call that follows the format for the Zendesk PUT Tickets API as the detail (https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket) .

The following information is needed to use the pattern:
- Zendesk Username and Password: To create the AUTH for the Event Bridge Connection
- Zendesk Workspace: To construct the API Destination to the user’s workspace

The IAM Role created by the pattern only has the permission to allow InvokeApiDestination access to the EventBridge Rule.
To work the user must have Password Access enabled in Zendesk (https://support.zendesk.com/hc/en-us/articles/4408836402074-Using-the-API-dashboard) 

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/313
#313 

## Payload example (e.g. Lambda event payload from source service).
{
  "ticket": {
    "comment": {
      "body": "The printer started a fire again! We did not install the newest patch."
    },
    "priority": "urgent",
    "subject": "Code Red: Printer on Fire"
  }
}

## Additional resources (optional: link and anchor text, up to 5 resources)
https://support.zendesk.com/hc/en-us/articles/4408836402074-Using-the-API-dashboard
https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket

## Author bio 
Name: Omid Khan
Photo URL:
Twitter handle:
Description (up to 255 chars): AWS Associate Solutions Architect

**Comment by jbesw** [comment]
This template does not implement the principal of least privilege - please check and limit the * star permission on the role and use the cfn_nag tool to verify (https://github.com/stelligent/cfn_nag). Thanks!

**Comment by PurpleAmyr** [comment]
@jbesw updated pull request.  Implemented least privilege on role. Used cfn_nag to verify role was okay.

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/eventbridge-api-destinations-zendesk.

**Comment by PurpleAmyr** [comment]
@jbesw is it possible to change the description on serverless land to be the longer one? [Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)] I feel like it may help our customers understand how to use the pattern more.

**Comment by jbesw** [comment]
This has been updated - https://serverlessland.com/patterns/eventbridge-api-destinations-zendesk
