### ISSUE TITLE
New pattern submission - Pattern for Apigateway for Http API with Event Bridge using .NET CDK

### ISSUE THREAD

**Issue by rahul-chugh** [aws-samples/serverless-patterns#319]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an HTTP API endpoint that directly integrates with Amazon EventBridge

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
C# .NET (CDK)

## Framework (currently we support SAM or CDK)
CDK

## Services used (e.g. "Lambda to EventBridge)
API Gateway, EventBridge, Cloudwatch

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)
The .NET CDK project creates an Amazon API Gateway HTTP API endpoint. The endpoint uses service integrations to directly connect to Amazon EventBridge. An EventBridge rule sends all events to Cloudwatch Logs.

## Deployment commands
1. Clone the project to your local working directory
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```

1. Change the working directory to this pattern's directory
    ```
    cd apigw-http-api-eventbridge-dotnet-cdk
    ```

1. Build the .NET CDK project
    ```
    dotnet build src
    ```

1. Deploy the stack to your default AWS account and region. The output of this command should give you the HTTP API URL.
    ```
    cdk deploy
    ```

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/318

## Author bio 
Name: Rahul Chugh
Photo URL: https://drive.google.com/file/d/1n-F0DbsY02m1X2sLYigYb7WeACaf9uRz/view
Twitter handle: @imRahulChugh
LinkedIn: https://www.linkedin.com/in/rchugh/
Description (up to 255 chars): Rahul Chugh is a Solutions Architect at Amazon Web Services and is based in California. Rahul has avid interest in microservices and serverless patterns. Prior to AWS, Rahul has worked as a software architect at Microsoft & Bloomberg.

**Comment by jbesw** [comment]
Thanks for the submission! This is now live at https://serverlessland.com/patterns/apigateway-http-eventbridge-dotnet-cdk.
