### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by Emmanuel-AWS** [aws-samples/serverless-patterns#321]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates a lambda function and two Amazon S3 buckets and enables AWS X-ray to analyse lambda API calls using lambda layers and deploys this using AWS CDK

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Python
## Framework (currently we support SAM or CDK)
CDK
## Services used (e.g. "Lambda to EventBridge)
CDK stack to create Amazon S3 buckets which invokes a Lambda function with image uploads and stores in destination bucket, with AWS X-ray to records API calls

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)

This pattern deploys a a lambda function which is responsible for converting images, uploaded in a source Amazon S3 bucket, into a thumbnail image and stores this into a destination Amazon S3 bucket. AWS X-Ray will be enabled to analyse lambda functions API calls using lambda layers. This is all deployed using AWS CDK.

The stack creates a IAM execution role with added permissions to read, put and get objects from Amazon S3 buckets and permissions to write to AWS X-Ray. The stack requires you to change the code in the cdk stack which creates the source and destination buckets, you will have to use your own globally unique names. After upload an image of your choice into the source bucket:

- Source bucket: <your-name>-thumbnail-upload-372
- Destination bucket: <your-name>-thumbnail-upload-372-resized

## Deployment commands

cdk deploy

## GitHub PR for template: 
#320 
## Additional resources (optional: link and anchor text, up to 5 resources)

[Amazon Web Services Cloud Development Kit(AWS CDK) framework](https://aws.amazon.com/cdk/)
[Creating and sharing Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html)
[AWS X-Ray SDK for Python](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python.html)
[Tutorial: Using an Amazon S3 trigger to create thumbnail images](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-tutorial.html)

## Author bio 
Name: Emmanuel Saliu
Photo URL: [use badge photo: https://phonetool.amazon.com/users/esaliu]
Twitter handle: n/a
Description (up to 255 chars): 
I am a Associate Consultant with AWS Professional Services.

## Co-Author bio 
Name: Marc Lyon
Photo URL: (use badge photo: https://phonetool.amazon.com/users/marclyo)
Twitter handle: n/a
Description (up to 255 chars): 
I am a DevOps Consultant with AWS Professional Services.

**Comment by jbesw** [comment]
Thanks for the submission - this is now live at https://serverlessland.com/patterns/xray-lambdalayers-cdk-python.
