### ISSUE TITLE
New pattern submission - API Gateway Lambda DynamoDB

### ISSUE THREAD

**Issue by jeastham1993** [aws-samples/serverless-patterns#323]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that receives a request from API Gateway and puts an item into DynamoDB using CDK.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
C#

## Framework (currently we support SAM or CDK)
CDK

## Services used (e.g. "Lambda to EventBridge)
API Gateway to Lambda to DynamoDB

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)
This pattern explains how to deploy a CDK application with Amazon API Gateway, AWS Lambda, and Amazon DynamoDB. When an HTTP POST request is made to the Amazon API Gateway endpoint, the AWS Lambda function is invoked and inserts an item into the Amazon DynamoDB table.

The stack creates two IAM roles:

1. Used by API gateway to invoke the Lambda function
2. Used by the Lambda function and allows write permissions to the DynamoDB table

## Deployment commands

cdk deploy

## GitHub PR for template: 
[322](https://github.com/aws-samples/serverless-patterns/pull/322)

## Additional resources (optional: link and anchor text, up to 5 resources)
[Amazon Web Services Cloud Development Kit(AWS CDK) framework](https://aws.amazon.com/cdk/)
[Lambda CDK docs](https://docs.aws.amazon.com/cdk/api/v2//docs/aws-cdk-lib.aws_lambda-readme.html)
[API Gateway CDK docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway-readme.html)
[DynamoDB CDK docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb-readme.html)

## Author bio 
Name: James Eastham
Photo URL: Use badge photo https://phonetool.amazon.com/users/jamesuk
Twitter handle: plantpowerjames
Description (up to 255 chars): I am a Cloud Infrastructure Architect with AWS Professional Services.

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at: https://serverlessland.com/patterns/apigw-lambda-dynamodb-cdk
