### ISSUE TITLE
Step Function-Lambda-DynamoDB

### ISSUE THREAD

**Issue by Shrutissahu** [aws-samples/serverless-patterns#326]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Deployment commands 
sam deploy --guided

## Additional resources (optional: link and anchor text, up to 5 resources)
Steps to execute a step function from AWS Console:
https://docs.aws.amazon.com/step-functions/latest/dg/getting-started.html#start-new-execution
Steps to execute a step function from CLI:
https://docs.aws.amazon.com/cli/latest/reference/stepfunctions/start-execution.html

## Author bio 
Name: Shruti Arora
Photo URL: https://github.com/settings/profile
Twitter handle:
Description (up to 255 chars): Shruti is a Cloud Application Architect with AWS Professional Services Team. Passionate about serverless development.

**Comment by jbesw** [comment]
Thanks for the contribution. This is now live at https://serverlessland.com/patterns/sfn-lambda-ddb.
