### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by guyu-ye** [aws-samples/serverless-patterns#327]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a REST API with X-Ray SDK integrated Lambda backend that scans a DynamoDB with enhanced observability.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Typescript

## Framework (currently we support SAM or CDK)
CDK

## Services used (e.g. "Lambda to EventBridge)
API Gateway to Lambda to Dynamodb with X-Ray and X-Ray SDK

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)
AWS X-Ray records and visualizes requests made by applications, making it a great tool to analyze and debug applications built using a microservices and serverless architecture. This CDK application demonstrates how to integrate X-Ray SDK in Lambda functions to observe into downstream API calls. This example creates an Amazon API Gateway REST API that uses a Lambda function as the backend to scan a Dynamodb table. The REST API and Lambda function both have X-Ray tracing enabled. X-Ray SDK is also integrated in the Lambda function to observe into the API call to the downstream Dynamodb table.

This stack creates two IAM roles:
1. Used by API Gateway to publish Cloudwatch logs
2. Used by Lambda function and allows read permission to the Dynamodb table

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/325

## Additional resources (optional: link and anchor text, up to 5 resources)
Integrating AWS X-Ray to Observe Into Your Lambda Function:
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-tracing.html
Using AWS X-Ray service maps and trace views with API Gateway:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-using-xray-maps.html

## Author bio 
Name: Guyu Ye
Photo URL: https://phonetool.amazon.com/users/guyye
Twitter handle:
Description (up to 255 chars): Guyu is a Sustainability App Architect at AWS Professional Services.

**Comment by jbesw** [comment]
Thanks for the contribution! This pattern is now live at https://serverlessland.com/patterns/apigw-lambda-dynamodb-xray-cdk.
