### ISSUE TITLE
New pattern submission - QLDB-Kinesis-Lambda-DynamoDB

### ISSUE THREAD

**Issue by mlewis7127** [aws-samples/serverless-patterns#329]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a QLDB Stream that emit changes in QLDB to Kinesis, that are then written to DynamoDB by a Lambda function

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## Framework (currently we support SAM or CDK)
SAM

## Services used (e.g. "Lambda to EventBridge)
QLDB to Kinesis Data Streams to Lambda to DynamoDB

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)
This pattern builds on the APIGW-Lambda-QLDB serverless pattern. It creates a QLDB stream to connect up a ledger in QLDB to a Kinesis Data Stream. It also creates a Lambda function to consume from Kinesis and write to a DynamoDB table. As a user inserts, updates or deletes data in QLDB through the APIGW-Lambda-QLDB pattern, they will see these changes reflected in the DynamoDB table in near real.

An IAM role is created to allow the QLDB service to write to Kinesis. The Lambda function is set up with the permissions only to read from the Kinesis Data Stream and to interact with the DynamoDB table. In case of an error during processing from Kinesis, the Lambda function has permission to write the record to an SQS failure queue.

## Deployment commands
sam build
sam deploy --guided

## GitHub PR for template: 
#328 

## Additional resources (optional: link and anchor text, up to 5 resources)
- [Amazon QLDB documentation](https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started-driver.html)
- [AWS re:Invent 2020 - Building out a serverless application with Amazon QLDB](https://www.youtube.com/watch?v=dtBpwCBlz6M)
- [QLDB Guide](https://qldbguide.com/)

## Author bio 
Name: Matt Lewis
Photo URL: https://qldbguide.com/images/MattLewis-Profile.jpg
Twitter handle: @m_lewis
Description (up to 255 chars): Matt is an AWS Data Hero, and an organiser of the AWS South Wales User Group and ServerlessDays Cardiff conference

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/qldb-kinesis-lambda-dynamodb.
