### ISSUE TITLE
New pattern submission: Amazon Athena to AWS Glue

### ISSUE THREAD

**Issue by shindeja** [aws-samples/serverless-patterns#333]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

![image](https://user-images.githubusercontent.com/93898993/150689109-c8d734e5-7c58-497d-bd04-a672dc7eef49.png)

## Description 
Amazon Athena integration with AWS Glue

This pattern in CDK offers an example to generate an AWS Glue Tables and connect to AWS Athena to execute queries. Tables of type CSV and TSV are created with the help of CFNTable.

## Description:
This example creates AWS Glue tables of type CSV and TSV with the help of CDK using CFnTable Construct. It demonstrate the usage of serdeinfo in CDK to create tables of various types.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```
    cd cdk-athena-glue
    ```
3. To deploy from the command line use the following:
    ```bash
      npx cdk bootstrap aws://accountnumber/region
      npx cdk synth
      npx cdk deploy --all
    ```

## GitHub PR for template:  
https://github.com/aws-samples/serverless-patterns/pull/332

## Author bio 
Name: Jayesh A Shinde
Photo URL: https://github.com/shindeja/shindeja/blob/main/shindeja.jpeg
Twitter handle: https://twitter.com/jayeshashinde
Description: Jayesh is Cloud Application Architect at AWS Pro-serve India.

Name: Atul Sharma
Photo URL: https://github.com/shindeja/shindeja/blob/main/atulsharma.jpeg
Twitter handle: NA
Description: Atul is Sr. Cloud Application Architect at AWS Pro-serve India.

Name: Feroz Kumar
Photo URL: https://github.com/shindeja/shindeja/blob/main/feroz.jpeg
Twitter handle: NA
Description: Feroz is Cloud Application Consultant at AWS Pro-serve India.

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/athena-glue-s3-cdk.
