### ISSUE TITLE
New pattern submission : AWS App Runner

### ISSUE THREAD

**Issue by arunvthangaraj** [aws-samples/serverless-patterns#334]
## Description

Create an AWS App Runner service using AWS Cloud Development kit. 

## Language:

TypeScript

## Framework (currently we support SAM or CDK)

CDK

## Services used 

AWS App Runner

## Description 

AWS App Runner is an AWS service that provides a fast, simple, and cost-effective way to deploy from source code or a container image directly to a scalable and secure web application in the AWS Cloud. You don't need to learn new technologies, decide which compute service to use, or know how to provision and configure AWS resources.

App Runner connects directly to your code or image repository. It provides an automatic integration and delivery pipeline with fully managed operations, high performance, scalability, and security.

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying an AWS App Runner service. This template showes how to add a custom image for AWS App Runner service to use without having to pre-push the image to Amazon Elastic Container Registry (ECR) or another container library. This makes use of the in-built apprunner.Source.fromAsset method. The custom image used is a simple hello world Node Js application. This project also provides an example of how to pass an environment variable to the image. Note that the image can be changed to other images that suit your use case by changing the codes found in the src directory.

## Deployment commands

cdk deploy

## GitHub PR for template: 

#335 

## Additional resources (optional: link and anchor text, up to 5 resources)

- [AWS App Runner Documentation](https://docs.aws.amazon.com/apprunner/latest/dg/what-is-apprunner.html)
- [AWS App Runner CDK](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-apprunner-readme.html)

## Author bio 
Name: Arun Thangaraj
Photo URL:
LinkedIn Profile: https://www.linkedin.com/in/arunvthangaraj/
Description (up to 255 chars): Arun is a Cloud Application Architect at AWS Professional Services based out of Dallas, TX

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apprunner.
