### ISSUE TITLE
New pattern submission - Pattern for sending notifications from S3 to SQS when an object is created using .NET CDK

### ISSUE THREAD

**Issue by rahul-chugh** [aws-samples/serverless-patterns#337]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description 
Pattern for sending notifications from S3 to SQS when an object is created using .NET CDK

This creates an S3 bucket and SQS queue. S3 writes a messages to the SQS queue when a new object is put into the bucket.

## Language: 
.NET

## Framework (currently we support SAM or CDK)
.NET CDK

## Services used (e.g. "Lambda to EventBridge)
S3, SQS

## Deployment commands
1. Clone the project to your local working directory
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```

1. Change the working directory to this pattern's directory
    ```
    cd s3-sqs-dotnet-cdk
    ```

1. Build the .NET CDK project
    ```
    dotnet build src
    ```

1. Deploy the stack to your default AWS account and region. The output of this command should give you the HTTP API URL.
    ```
    cdk deploy
    ```

1. Note the outputs from the CDK deployment process. This contains the S3 <BUCKET_NAME> and SQS <QUEUE_URL> attributes used to test this deployment.

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/336

## Author bio 
Name: Rahul Chugh
Photo URL: https://drive.google.com/file/d/1n-F0DbsY02m1X2sLYigYb7WeACaf9uRz/view?usp=sharing
Twitter handle: imRahulChugh
Description (up to 255 chars): Rahul Chugh is a Solutions Architect at Amazon Web Services and is based in California. Rahul has avid interest in microservices and serverless patterns. Prior to AWS, Rahul has worked as a software architect at Microsoft & Bloomberg.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/s3-sqs-dotnet-cdk.
