### ISSUE TITLE
New pattern submission - lambda-aurora-serverless

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#34]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates an AWS Lambda function and an Amazon Aurora Serverless DB cluster with Data API and a Secrets Manager secret.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Node.js

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

Lambda to Aurora Serverless

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern creates an AWS Lambda function and an Amazon Aurora Serverless DB cluster with Data API and a Secrets Manager secret. The function creates an example table named "music", inserts a row with data from the event object, then returns the results of a select query.  The function includes a role with read access to a specific secret in Secrets Manager and to execute a sql statement in a specific Aurora DB cluster.

## Deployment commands

sam deploy --guided

## GitHub PR for template: 
#33 

## Payload example (e.g. Lambda event payload from source service).

```
{
  "body": {
    "artist": "The Beatles",
    "album": "Abbey Road"
  }
}
```
## Additional resources (optional: link and anchor text, up to 5 resources)

- [Using the Data API for Aurora Serverless](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)
- [Data API - ExecuteStatement](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html)
- [Data API - ExecuteStatement Response Elements](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html#API_ExecuteStatement_ResponseElements)

## Author bio 
Name: Greg Davis
Photo URL: http://gregdavis.me
Twitter handle: n/a
Description (up to 255 chars): I am a Senior Solutions Architect, AWS Cloud Architect, Full-Stack Developer, Database Engineer, Data Integration Architect, and Serverless Enthusiast.

**Comment by jbesw** [comment]
At the moment, we are limiting patterns to simpler integrations (usually service A to service B). Once we have completed many of these, we will expand to more complex solutions like this one. I'll keep this issue open for now but we will not merge the code just yet.

**Comment by gadavis2** [comment]
Ok, thank you!  Sounds good.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/lambda-aurora.
