### ISSUE TITLE
New pattern submission - API Gateway HTTP API to Step Functions Express workflow

### ISSUE THREAD

**Issue by jeastham1993** [aws-samples/serverless-patterns#340]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an API Gateway HTTP API that synchronously invokes a Step Function Express workflow and returns the response details in the POST response body.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

C#

## Framework (currently we support SAM or CDK)

CDK

## Services used (e.g. "Lambda to EventBridge)

API Gateway HTTP API to Step Functions Express Workflow

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)

This pattern explains how to deploy an API Gateway HTTP API that synchronously invokes a Step Function Express Workflow and returns the output state of the workflow in the HTTP request response body. The CDK application also creates a log group that the Step Function writes execution data into.

The stack creates a single IAM role:

1. Used by API Gateway to allow the StartSyncExecution action on the Step Function Express workflow

## Deployment commands

cdk deploy

## GitHub PR for template: 

#339 

## Additional resources (optional: link and anchor text, up to 5 resources)

[AWS CDK](https://aws.amazon.com/cdk/)
[API Gateway CDK docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway-readme.html)
[Step Function CDK Docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions-readme.html]
[AWS Blog describing Step Function Synchronous execution and API Gateway integration](https://aws.amazon.com/blogs/compute/new-synchronous-express-workflows-for-aws-step-functions/)

## Author bio 
Name: James Eastham
Photo URL: Use badge photo https://phonetool.amazon.com/users/jamesuk
Twitter handle: plantpowerjames
Description (up to 255 chars): I am a Cloud Infrastructure Architect with AWS Professional Services.

**Comment by jbesw** [comment]
Thanks for the contribution - this is now live at https://serverlessland.com/patterns/apigw-sfn-cdk.
