### ISSUE TITLE
New pattern submission - CloudWatch RUM using Cognito IdentityPool

### ISSUE THREAD

**Issue by paulmowat** [aws-samples/serverless-patterns#343]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a CloudWatch RUM application monitor and an associated Cognito Identity Pool.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

N/A

## Framework (currently we support SAM or CDK)

SAM

## Services used (e.g. "Lambda to EventBridge)

Cognito to CloudWatch

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)

This pattern creates a CloudWatch RUM application monitor and an associated Cognito Identity Pool. 

The Cognito Identity Pool is configured to allow unauthenticated access to the CloudWatch RUM web client in order to publish generated events.

The stack creates a single IAM role:

Used by the Cognito IdentityPool to allow the rum:PutRumEvents action to send events to CloudWatch RUM application monitor

## Deployment commands

sam deploy --guided

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/342

## Additional resources (optional: link and anchor text, up to 5 resources)

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM.html
* https://aws.amazon.com/blogs/aws/cloudwatch-rum/

## Author bio 
Name: Paul Mowat
Photo URL: https://pbs.twimg.com/profile_images/1487374974520279040/FTQYlFTP_400x400.jpg
Twitter handle: paul_mowat
Description (up to 255 chars): Paul is a Principal DevOps Architect for Advanced based in the UK

**Comment by jbesw** [comment]
Thanks for your submission! This is now live at https://serverlessland.com/patterns/cognito-cloudwatch.
