### ISSUE TITLE
Bug: Pictures are wrong on actual pattern page, where as in issue those are correct

### ISSUE THREAD

**Issue by shindeja** [aws-samples/serverless-patterns#345]
Hi while publishing the new pattern, picture of Atul Sharma is displayed wrong and some different person name popped up.

https://serverlessland.com/patterns/athena-glue-s3-cdk.

#Original Issue:

https://github.com/aws-samples/serverless-patterns/issues/333

#Author bio
Name: Jayesh A Shinde
Photo URL: https://github.com/shindeja/shindeja/blob/main/shindeja.jpeg
Twitter handle: https://twitter.com/jayeshashinde
Description: Jayesh is Cloud Application Architect at AWS Pro-serve India.

Name: Atul Sharma
Photo URL: https://github.com/shindeja/shindeja/blob/main/atulsharma.jpeg
Twitter handle: NA
Description: Atul is Sr. Cloud Application Architect at AWS Pro-serve India.

Name: Feroz Kumar
Photo URL: https://github.com/shindeja/shindeja/blob/main/feroz.jpeg
Twitter handle: NA
Description: Feroz is Cloud Application Consultant at AWS Pro-serve India.

**Comment by jbesw** [comment]
Sorry about that! The page has been updated with the correct bio information.
