### ISSUE TITLE
New pattern submission: cdk-codecommit-codebuild

### ISSUE THREAD

**Issue by jeremycare** [aws-samples/serverless-patterns#349]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description
Create Integration between CodeCommit and Codebuild to run builds on every PRs

## Language: 
Typescript

## Framework (currently we support SAM or CDK)
CDK

## Services used 
CodeCommit to Eventbridge to Codebuild to EventBridge to Lambda to CodeCommit

## Description (this must include a detailed explanation of the pattern together with details of IAM permissioning)
This pattern deploys:
- a Codebuild Project
- an EventBridge event rule to trigger the Codebuild
- a Lambda to post comments on CodeCommit Pull Request
- two EventBridge event rules to trigger the lambda when the Codebuild is finished (Success and Fail builds)

## Deployment commands

```
cdk synth
cdk deploy
```

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/348

## Author bio 
Name: Jeremy Care
Photo URL: https://avatars.githubusercontent.com/jeremycare
Twitter handle: @jeremy_care
Description (up to 255 chars): Jeremy is a Software Engineer Consultant focusing on Serverless and Event-Driven applications.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/codecommit-codebuild-cdk.
