### ISSUE TITLE
New pattern - REST API Gateway-lambda-mutual TLS CDK

### ISSUE THREAD

**Issue by sudheery80** [aws-samples/serverless-patterns#360]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
  This pattern deploys a public Amazon API Gateway REST API that is integrated with a AWS Lambda function written in Python and the API calls are authenticated using mutual TLS.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
  Extended examples of this pattern implementation - https://github.com/aws-samples/serverless-samples/tree/main/serverless-rest-api
- Framework: currently, we support SAM or CDK.
  CDK
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
  Name: Sudheer Yalamanchili
  Photo URL:
  Twitter handle:
  Description (up to 255 chars): Sudheer is a cloud application architect working with AWS ProServ.

You must ensure that the sections of the model README.me are completed in full.

**Comment by jbesw** [comment]
This is now live at https://serverlessland.com/patterns/apigw-lambda-tls-cdk,
