### ISSUE TITLE
Eventbridge API Destinations DataDog Integration

### ISSUE THREAD

**Issue by PurpleAmyr** [aws-samples/serverless-patterns#365]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.me are completed in full.
# Description:
This pattern creates an API Destination for the DataDog Send Logs API. Once deployed, the pattern allows a user to send events easily through Event Bridge to DataDog logs. The pattern creates the following resources: Event Bridge Bus, Event Bridge Connection, Event Bridge API Destination, Event Bridge Rule, IAM Role, and SQS Queue.
The Event Bridge rule uses the API Destination and Connection as a target, SQS Queue as a DLQ, and the IAM role as its role. To send events go to the bus and send sample events. To send a log enter “MyDataDogApp” for the source, the bus created by the pattern for the Event Bus Name, and any call that follows the format for the sending logs as the detail (https://docs.datadoghq.com/api/latest/logs/#send-logs) .
The following information is needed to use the pattern:

* DataDog APIKey:  To create the AUTH for the Event Bridge Connection

The IAM Role created by the pattern only has the permission to allow InvokeApiDestination access to the EventBridge Rule.

Manual configuration of this pattern with an S3 source can be found in AWS documentation (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tutorial-datadog.html)
# Resources
https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token
https://docs.datadoghq.com/api/latest/logs/#send-logs
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tutorial-datadog.html
https://aws.amazon.com/blogs/compute/using-api-destinations-with-amazon-eventbridge/

# Framework
Cloud Formation

# Author
Name: Omid Khan
Linkedin: https://www.linkedin.com/in/ok6av/
Description (up to 255 chars): AWS Associate Solutions Architect

## GitHub PR for template:
#364

# Payload Example
{
  "ddsource": "nginx",
  "ddtags": "env:staging,version:5.1",
  "hostname": "i-012345678",
  "message": "2019-11-19T14:37:58,995 INFO [process.name][20081] Hi from Eventbridge",
  "service": "payment"
}

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-api-destinations-datadog.
