### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by miracle423yy** [aws-samples/serverless-patterns#367]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.me are completed in full.

## Description:
This pattern creates an API Destination for the Freshdesk send ticket API. Once deployed, the pattern allows a user to send events easily through Event Bridge to Freshdesk tickets. The pattern creates the following resources: Event Bridge Bus, Event Bridge Connection, Event Bridge API Destination, Event Bridge Rule, IAM Role, and SQS Queue.
The Event Bridge rule uses the API Destination and Connection as a target, SQS Queue as a DLQ, and the IAM role as its role. To send events go to the bus and send sample events. To send a ticket enter “freshdesktest” for the source, the bus created by the pattern for the Event Bus Name, and any call that follows the format for the create tickets as the detail (https://developers.freshdesk.com/api/#create_ticket) .
The following information is needed to use the pattern:

- Freshdesk APIKey: To create the AUTH for the Event Bridge Connection
- Freshdesk Workspace: To construct the API Destination to the user's workspace 

The IAM Role created by the pattern only has the permission to allow InvokeApiDestination access to the EventBridge Rule.

## Resources
https://support.freshdesk.com/support/login
https://developers.freshdesk.com/api/#getting-started
https://developers.freshdesk.com/api/#create_ticket

## Framework
CloudFormation

## Author
Name: Camilla Somtakoune
Description (up to 255 chars): AWS Solutions Architect 

## GitHub PR for template:
#366 

**Payload Example**
{
"description":"Hello from AWS",
"subject":"Hi",
"email":"apple@outerspace.com",
"priority":1, 
"status":2
}

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-api-destinations-freshdesk.
