### ISSUE TITLE
New pattern submission: AWS Transfer SFTP -> S3

### ISSUE THREAD

**Issue by shindeja** [aws-samples/serverless-patterns#369]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

![image](https://user-images.githubusercontent.com/93898993/153144860-a388f7a0-3094-4cba-9eff-c06cd1215c56.png)

## Description 
AWS Transfer SFTP to S3

This pattern in CDK offers an example to setup an AWS SFTP server using [AWS Transfer for SFTP](https://aws.amazon.com/aws-transfer-family/). You can simply create a server, set up user accounts, and associate the server with one or more Amazon Simple Storage Service (Amazon S3) buckets.
You have fine-grained control over user identity, permissions, and keys. You can create users within Transfer for SFTP. You can also use IAM policies to control the level of access granted to each user.

## Description:
This pattern in CDK offers an example to setup an AWS SFTP server using [AWS Transfer for SFTP](https://aws.amazon.com/aws-transfer-family/). You can simply create a server, set up user accounts, and associate the server with one or more Amazon Simple Storage Service (Amazon S3) buckets.
You have fine-grained control over user identity, permissions, and keys. You can create users within Transfer for SFTP. You can also use IAM policies to control the level of access granted to each user.

## Deployment commands
1. Create a new directory, navigate to that directory in a terminal and clone the GitHub repository:
    ```
    git clone https://github.com/aws-samples/serverless-patterns
    ```
2. Change directory to the pattern directory:
    ```
    cd cdk-awstransfer
    ```
3. To deploy from the command line use the following:
    ```bash
      npx cdk bootstrap aws://accountnumber/region
      npx cdk synth
      npx cdk deploy --all
    ```

## GitHub PR for template:  
https://github.com/aws-samples/serverless-patterns/pull/368

## Author bio 
Name: Jayesh A Shinde
Photo URL: https://github.com/shindeja/shindeja/blob/main/shindeja.jpeg
Twitter handle: https://twitter.com/jayeshashinde
Description: Jayesh is Cloud Application Architect at AWS Pro-serve India.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/transfer-s3-cdk.

**Comment by mistertown** [comment]
The description on the pattern on serverlessland.com states _"Create AWS Glue tables from Athena and integrate with S3."_

Is there a way I can update that?
