### ISSUE TITLE
New pattern submission - apigw-rest-api-dynamodb

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#37]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates an Amazon API Gateway REST API that integrates with an Amazon DynamoDB table.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

n/a

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

From API Gateway REST API to DynamoDB

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern creates an Amazon API Gateway REST API that integrates with an Amazon DynamoDB table named "Music". The API includes an API key and usage plan. The DynamoDB table includes a Global Secondary Index named "Artist-Index". The API integrates directly with the DynamoDB API and supports [PutItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html) and [Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html) actions.

The REST API uses an IAM role to provide full access to the specific DynamoDB table and index created by the CloudFormation template.

## Deployment commands

sam deploy --guided

## GitHub PR for template: 

#36 

## Payload example (e.g. Lambda event payload from source service).

See README.me for more information.

## Additional resources (optional: link and anchor text, up to 5 resources)

- [Tutorial: Build an API Gateway REST API with AWS integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-aws-proxy.html)
- [How do I use API Gateway as a proxy for another AWS service?](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-proxy-integrate-service/)
- [Using Amazon API Gateway as a proxy for DynamoDB](https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/)
- [Setting up data transformations for REST APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html)
- [Amazon API Gateway API request and response data mapping reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html)

## Author bio 
Name: Greg Davis
Photo URL: http://gregdavis.me
Twitter handle: n/a
Description (up to 255 chars): I am a Senior Solutions Architect, AWS Cloud Architect, Full-Stack Developer, Database Engineer, Data Integration Architect, and Serverless Enthusiast.

**Comment by jbesw** [comment]
Thanks for the contribution! This has been merged and will appear on the site in the next couple of hours.
