### ISSUE TITLE
New pattern submission - s3-large-deployments-with-cdk

### ISSUE THREAD

**Issue by shahpay** [aws-samples/serverless-patterns#375]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.

The samples in this project demonstrate how to upload large file to S3 Bucket using CDK using the inbuilt CDK Assets Bucket and Custom Resource

Assets are local files, directories, or Docker images that can be bundled into AWS CDK libraries and apps; for example, a directory that contains the handler code for an AWS Lambda function. Assets can represent any artefact that the app needs to operate. You can define local files and directories as assets, and the AWS CDK packages and uploads them to Amazon S3 through the aws-s3-assets module.

A Lambda Backed Custom Resource can be used to copy your large file from the assets bucket to your custom s3 bucket

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
[Assets](https://docs.aws.amazon.com/cdk/v2/guide/assets.html)
[Custom Resource](https://medium.com/cyberark-engineering/advanced-custom-resources-with-aws-cdk-1e024d4fb2fa)

- Framework:
   CDK

- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
Name: Payal Shah
Photo URL: n/a
Twitter handle: n/a
Description (up to 255 chars): I am Professional Service Consultant specialised in DevOps/CIA.  My major area of focus is working around IAC tools
 

You must ensure that the sections of the model README.me are completed in full.

## GitHub PR for template:
[#374](https://github.com/aws-samples/serverless-patterns/pull/374)

**Comment by jbesw** [comment]
Thanks for the contribution! This pattern is now live at https://serverlessland.com/patterns/s3-lambda-s3-cdk.
