### ISSUE TITLE
New pattern submission: Apigateway-sns-sqs-lambda using dotnet

### ISSUE THREAD

**Issue by mhafeezajh** [aws-samples/serverless-patterns#378]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Note the following information for the model:

 **Description:**
This CDK application demonstrates how to set up a topic-queue-chaining pattern using Amazon SNS and Amazon SQS behind an Amazon API Gateway using Dotnet CDK. The lambda SQS handler is built using Dotnet C# SDK.
This architecture helps in setting up a highly scalable API that can consume messages/events, fan them out and process them asynchronously. 

**Resources should like to AWS documentation and AWS blogs.**
  [AWS Cloud Development Kit](https://docs.aws.amazon.com/cdk/latest/guide/cli.html) (AWS CDK) installed
  [.NET](https://dotnet.microsoft.com/en-us/download/dotnet/3.1) (.NET Core 3.1) installed

**Framework:** 
CDK

**Language:**
C#

**Author:**
https://www.linkedin.com/in/hafeezaj/

## GitHub PR for template:
#377

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-sns-sqs-cdk-dotnet.
