### ISSUE TITLE
lamba-s3-sfn

### ISSUE THREAD

**Issue by asunar** [aws-samples/serverless-patterns#39]
## Description
Create a Lambda function that stores payload and starts an Express Workflow

## Language:
Javascript

## Framework
SAM

## Services from/to
Lambda to S3 to Step Functions

## Description
- SavePayloadAndStartStateMachineFunction lambda function with a "payload" string in the input payload
  - Needs permissions provided by S3CrudPolicy to write to S3 bucket
  - Needs permissions provided by StepFunctionsExecutionPolicy (no express policy so have to manually update the role JSON post deployment 😢  )
- SavePayloadAndStartStateMachineFunction stores the payload in S3 and starts an Express Workflow passing the bucket and key
  - Step Functions Needs permissions provided by LambdaInvokePolicies to invoke lambdas
- Express Workflow calls the ProcessFileFunction, function retrieves uploaded JSON the using the bucket/key, converts to uppercase and returns it
  - Needs permissions provided by S3ReadPolicy to read from S3 bucket 
- Express Workflow calls the AddFooterFunction, function adds a footer and returns it
- Express Workflow ends and returns the result to the client

## Deployment commands
`sam deploy -g`
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/38

## Payload example (can be bigger than task input limit of 262KB)
`{ "payload": "hello world"}`
## Author bio 
Name: Alper Sunar
Photo URL:
Twitter handle: @asunar
Description (up to 255 chars): Pretends to be an architect

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/lambda-s3-sfn.
