### ISSUE TITLE
Eventbridge API Destinations PagerDuty Integration

### ISSUE THREAD

**Issue by davedimm** [aws-samples/serverless-patterns#407]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.me are completed in full.

## Description
This pattern creates an API Destionation for PagerDuty EventsV2 API.  This allows a user to forward EventBridge events to PagerDuty and trigger alarms/pages. 
The pattern creates a sample EventBus, EventBridge API Connection, EventBridge API Destination, EventBridge Rule, and IAM Role. 

To deploy the pattern you need a PagerDuty API Key and Integration Key.  Directions to create those can be found here: https://support.pagerduty.com/docs/services-and-integrations & here https://support.pagerduty.com/docs/api-access-keys#section-generating-a-general-access-rest-api-key

The EventBridge Rule matches any events with "PagerDutyDemo" as the source. Then forwards the event to the API Destination triggering the alert in PagerDuty.
The pattern includes a sample event you can send via CLI:  aws events put-events --entries file://testEvent.json

To Deploy run: sam deploy --guided

## Resources 
https://support.pagerduty.com/docs/services-and-integrations
https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgx-sending-an-alert-event
https://aws.amazon.com/blogs/compute/using-api-destinations-with-amazon-eventbridge/

## Framework
SAM

## Author
Name: Dave Dimm
LinkedIn: https://www.linkedin.com/in/david-dimm-5b223630
Description:  Dave is an AWS Technical Account Manager based in the Philadelphia area.  Dave helps enterprise customers with their AWS Cloud Journey

## GitHub PR for template: 
#406

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-api-destinations-pagerduty.

**Comment by davedimm** [comment]
@jbesw  I need to have a typo corrected in first line of description paragraph.  "This pattern creates an API Destionation "   ->  Destination
