### ISSUE TITLE
New pattern submission - cdk-eventbridge-stepfunction

### ISSUE THREAD

**Issue by a-h** [aws-samples/serverless-patterns#41]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Creates an EventBridge Event Bus that triggers a Step Function execution.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

TypeScript

## YouTube videoId (optional e.g. "VI79XQW4dIM")

N/A

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

EventBridge to Step Functions

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern creates an EventBridge Event Bus, a Step Function, and subscribes the Step Function to be executed when a `StartReminder` event is published to the newly created EventBridge Event Bus. The Step Function waits until the specified date before publishing a `Reminder` event to the EventBus using a TypeScript Lambda Function.

This pattern will create an IAM Role for the Lambda function that gives it permission to send to an EventBridge event bus that is created as part of the template. The Step Function service will also be given permission to subscribe to EventBridge events on the newly created event bus.

## Deployment commands

```sh
npx cdk deploy
```

## GitHub PR for template: 

See #40 

## Payload example (e.g. Lambda event payload from source service).

The EventBridge payload has one required field containing an ISO formatted date string:

```json
{
  "at": "2021-04-26T19:00:00Z"
}
```

## Author bio 

Name: Adrian Hesketh
Photo URL: https://adrianhesketh.com/profile.jpg
Twitter handle: adrianhesketh
Description (up to 255 chars): Adrian Hesketh works at Infinity Works in the UK, helping organisations with digital transformation and service delivery.

**Comment by a-h** [comment]
I can see the PR has been merged, but the site is currently pointing at the SAM template not the CDK template:

https://serverlessland.com/patterns/cdk-eventbridge-stepfunction

Maybe you've got a typo in the site?

Thanks!

**Comment by jbesw** [comment]
Thanks for your contribution! This has now been published at https://serverlessland.com/patterns/cdk-eventbridge-stepfunction.
