### ISSUE TITLE
New pattern submission - s3-lambda-dynamodb CDK

### ISSUE THREAD

**Issue by ykkarra** [aws-samples/serverless-patterns#410]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.me are completed in full.

## Description

This pattern in CDK offers a complete solution to load data from CSV files stored on S3. The following resources are created:
1. S3 Bucket with event notification on object creates
2. DynamoDB Table with on-demand billing mode
3. Lambda function that runs python and takes environment variables of bucket name, object key, and dynamodb table

To deploy: run 
`cdk deploy --parameters dataObject=<name of the objects>`

## Framework (currently we support SAM or CDK)

CDK

## Resources
- [Amazon S3 Event Notifications](https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html)
- [Blog: Creating a scalable serverless import process for Amazon DynamoDB](https://aws.amazon.com/blogs/compute/creating-a-scalable-serverless-import-process-for-amazon-dynamodb/)

## Author
Name: Yogananda Karra
LinkedIn: https://www.linkedin.com/in/yoganandakarra/
Description: Yogananda is an AWS Solutions Architect based in the Phoenix area. Yogananda helps enterprise Greenfield customers with their AWS Cloud Journey.

## GitHub PR for template:
[#409](https://github.com/aws-samples/serverless-patterns/pull/409)

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/s3-lambda-dynamodb-cdk.
