### ISSUE TITLE
New pattern submission - apigw-http-api-sqs-lambda-cdk

### ISSUE THREAD

**Issue by lubao** [aws-samples/serverless-patterns#452]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This pattern creates an Amazon API Gateway HTTP API with a ```send``` route that send message to a SQS queue. The  Amazon API Gateway HTTP API has basic CORS configured. Upon receiving message, SQS will trigger a Lambda function to process the message. The function will only ```print``` the message only. The function written in Python.

## Language
Python

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway HTTP API -> SQS -> Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM Permission)
The pattern will create an Amazon API Gateway HTTP API with
* ```send``` route
* ```SQS-SendMessage``` Subtype Integration

The pattern will create an IAM role for API Gateway HTTP API to access SQS with following policy:
```
        {
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:PurgeQueue",
                "sqs:DeleteMessage"
            ],
            "Resource": "$SQS_QUEUR_ARN",
            "Effect": "Allow"
        }
```

The pattern will create SQS queue and a lambda event source.

The pattern will create a Lambda function (Python 3.8) with a sample code as described below
```
def handler(event, context):
    for record in event['Records']:
        payload = record["body"]
        print(str(payload))
```

## Deployment commands
```cdk deploy```

## Additional resources
* [Using Lambda with Amazon SQS](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html)
* [Amazon API Gateway HTTP Integration subtype reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services-reference.html)

## Author bio
Name: Paul Lu
Linkin:  https://www.linkedin.com/in/paul-lu-7336b433/
Description: I am an AWS Solution Architect and a Serverless Enthusiast.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/451

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-http-sqs-lambda-cdk.
