### ISSUE TITLE
Eventbridge API Destinations Shopify Integration

### ISSUE THREAD

**Issue by PurpleAmyr** [aws-samples/serverless-patterns#454]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

# Description
This pattern creates an API Destination for the Shopify Create Product API. Once deployed, the pattern allows a user to send events easily through Event Bridge to create products in a Shopify store. The pattern creates the following resources: Event Bridge Bus, Event Bridge Connection, Event Bridge API Destination, Event Bridge Rule, IAM Role, and SQS Queue.
The Event Bridge rule uses the API Destination and Connection as a target, SQS Queue as a DLQ, and the IAM role as its role. To send events go to the bus and send sample events. 
To create a product, enter “MyShopifyApp” for the source, the bus created by the pattern for the Event Bus Name, and any call that follows the format for posting products as the detail (https://shopify.dev/api/admin-rest/2021-10/resources/product#post-products) .
Before using the pattern a Shopify app and Admin Key with the appropriate permissions should be created. (https://shopify.dev/apps/auth/admin-app-access-tokens#step-1-create-and-install-the-app)

The following information is needed to run the template:

Shopify Admin Key: To create the AUTH for the Event Bridge Connection
Shopify Store Name: To construct the call for the API destination

The IAM Role created by the pattern only has the permission to allow InvokeApiDestination access to the EventBridge Rule.

# Resources
https://shopify.dev/apps/getting-started/create
https://shopify.dev/apps/webhooks/configuration/eventbridge
https://shopify.dev/apps/auth/admin-app-access-tokens
https://shopify.dev/api/admin-rest/2021-10/resources/product#[post]/admin/api/2021-10/products.json

# Framework
Cloud formation

# Author
Name: Omid Khan
Linkedin: https://www.linkedin.com/in/ok6av/
Description (up to 255 chars): AWS Associate Solutions Architect

Name: Camilla Somtakoune
Description (up to 255 chars): AWS Solutions Architect

If possible please put both authors on page. If not then default to having Omid on the page.

## GitHub PR for template:
#453

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/eventbridge-api-destinations-shopify.
