### ISSUE TITLE
New pattern submission SQS to Lambda in Terraform with Python Lambda

### ISSUE THREAD

**Issue by claque2000** [aws-samples/serverless-patterns#465]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

# Description
This sample project demonstrates how to use a Lambda function to parse messages when they are received by an SQS queue.
This pattern creates the following resources: SQS queue, Lambda function, CloudWatch Log group, IAM role and IAM policy with least privileges.
The Lambda function uses lambda-powertools-python layer for best logging practices.

# Resources
https://serverlessland.com/patterns/sqs-lambda

# Framework
Terraform 

# Author
Name: Nicolas Diez
LinkedIn: https://linkedin.com/in/nicolasdiez/
Twitter: https://twitter.com/claque2000
Description: AWS Proserve Consultant

**Comment by bls20AWS** [comment]
Thank-you, this has now been published.
https://serverlessland.com/patterns/sqs-lambda-terraform-python
