### ISSUE TITLE
New pattern submission - sfn-sqs

### ISSUE THREAD

**Issue by revanthreddy** [aws-samples/serverless-patterns#52]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AWS Step Function workflow to integrate with Amazon SQS.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
n/a

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Function to Amazon SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This SAM template deploys a Step Functions workflow, that takes in a payload and sends part of it to an Amazon SQS. In this pattern, the state machine DOES NOT WAIT for a callback from the queue. 

## Deployment commands
`sam deploy --guided
`
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/51

## Payload example (e.g. Lambda event payload from source service).
`
{
    "message": {
      "hello" : "world"
    }
}
`

_Note: Test payload is part of the cli command_

## Author bio 
Name: Revanth Anireddy
Photo URL: https://twitter.com/revanthreddy/photo
Twitter handle: @revanthreddy
Description (up to 255 chars): Senior Cloud Applications Architect @ AWS. 
Swimmer, Artist, Foodie, Movie & Sports trivia enthusiast in my spare time.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/sfn-sqs.
