### ISSUE TITLE
New pattern submission -  s3-eventbridge-terraform

### ISSUE THREAD

**Issue by heyjoahna** [aws-samples/serverless-patterns#546]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

## Title:
S3 to EventBridge Pattern Using Terraform

## Description:
Publish events directly from S3 to EventBridge and send notifications to SNS when an object is created.

## Resources:
[Use Amazon S3 Event Notifications with Amazon EventBridge](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/)

## Framework:
Terraform

## Author Bio:
Name: Joahna Abelgas
Description: I'm a Software Engineer currently specializing in Amazon Web Services (AWS) Infrastructure, Security, Management and Administration.
LinkedIn: https://www.linkedin.com/in/joahna/
Twitter: https://twitter.com/heyjoahna

**Comment by mavi888** [comment]
Here you can find it :) https://serverlessland.com/patterns/s3-eventbridge-sns-terraform
