### ISSUE TITLE
New pattern submission: SNS to SQS with Terraform

### ISSUE THREAD

**Issue by claque2000** [aws-samples/serverless-patterns#548]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

# Description:
This sample project demonstrates how to use a SQS queue to receive messages published on a SNS topic.
This pattern creates the following resources: SNS topic, SQS queue, SNS topic subscription with SQS protocol, SQS queue resource policy for SNS to push messages.
This pattern can combined with any pattern using SQS as source to build the infrastructure answering the desired goal, for example SQS to Lambda pattern.

# Resources:
* https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html
* https://aws.amazon.com/fr/blogs/compute/choosing-between-messaging-services-for-serverless-applications/

# Framework: 
Terraform

# Author
Name: Nicolas Diez
LinkedIn: https://linkedin.com/in/nicolasdiez/
Twitter: https://twitter.com/claque2000
Description: AWS Proserve Consultant

**Comment by jbesw** [comment]
Thanks for the submission! This is now live at: https://serverlessland.com/patterns/sns-sqs-terraform
