### ISSUE TITLE
New pattern submission - Lambda to SES

### ISSUE THREAD

**Issue by curtisdarst** [aws-samples/serverless-patterns#55]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This SAM template creates a Lambda function that sends an email with Amazon SES

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
nodejs

## YouTube videoId (optional e.g. "VI79XQW4dIM")
none

## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
Lambda to SES

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Utilizing Lambda to send an email with Amazon SES.
Permissions required: 
'ses:SendEmail'
 'ses:SendRawEmail'
Resource ARN should be provided of the individual email address that is verified by Amazon SES

## Deployment commands
sam deploy --guided

## GitHub PR for template: 
#54 

## Payload example (e.g. Lambda event payload from source service).
None

## Additional resources (optional: link and anchor text, up to 5 resources)
        Verifying identities in Amazon SES
        https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html

       Moving out of the Amazon SES sandbox
       https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

## Author bio 
Name: Curtis Darst
Photo URL: https://pbs.twimg.com/profile_images/1390393791488659458/S_dO1BOE_400x400.jpg
Twitter handle: curtisdarst
Description (up to 255 chars): Curtis is a Solutions Architect for EDU at Amazon Web Services based in the US.

**Comment by curtisdarst** [comment]
Latest commit made with enhancements of handling variables via event and additional documentation.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-ses.
