### ISSUE TITLE
Code has performance issue

### ISSUE THREAD

**Issue by vaquarkhan** [aws-samples/serverless-patterns#552]
Java code TicketFunction is calling the DDBUtils class, and each call creates a new Dynamodb connection. Dynamodb connection should be created outside the handler why we are creating new connection on each lambda call this is not best practice and coding style , please fix code and create DB connection out side of handler function and reuse in further call

**Comment by jbesw** [comment]
Thanks for reporting - this has been resolved with https://github.com/aws-samples/serverless-patterns/pull/554.
