### ISSUE TITLE
New pattern submission - CloudWatch-SFN-Glue using Terraform

### ISSUE THREAD

**Issue by rohit-masur** [aws-samples/serverless-patterns#557]
## Description
The Terraform template deploys a AWS Step Function, a AWS Glue Job, a Cloudwatch Event Rule, a Amazon S3 bucket and the minimum IAM resources required to run the application.

This pattern demonstrates the use of Terraform modules and deploys the below resources:
* Amazon S3 bucket and load the sample Python script as an object 
* Sample AWS Glue Job which executes the script in the S3 bucket
* AWS Step Function to invoke the AWS Glue Job synchronously. The Function will wait until the Job is completed
* Cloudwatch Event Rule which is configured to start the AWS Step Function evey 10 minutes

![architecture](https://user-images.githubusercontent.com/28831921/160027232-fd302472-d96c-4fa7-8d05-d6ab367e2b7b.png)

## Resources
Learn more about this pattern at Serverless Land Patterns: https://serverlessland.com/patterns/sfn-glue-terraform.

## Framework
Terraform

## GitHub PR for template:
[556](https://github.com/aws-samples/serverless-patterns/pull/556)

## Author
Name: Rohit G. Masur
LinkedIn: https://www.linkedin.com/in/rohit-masur-781b0528/
Description: Data and ML Engineer @ AWS

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/sfn-glue-terraform
