### ISSUE TITLE
Request for apigw-vpclink-pvt-alb-terraform doc update

### ISSUE THREAD

**Issue by bbideep** [aws-samples/serverless-patterns#560]
In the doc https://serverlessland.com/patterns/apigw-vpclink-pvt-alb-terraform, the below changes need to be done.

**Cleanup** section:
- Point 2 is not applicable and the steps need to follow https://github.com/aws-samples/serverless-patterns/tree/main/apigw-vpclink-pvt-alb-terraform#cleanup

**Additional resources** section:
Provided links don't seem to be matching the ones in https://github.com/aws-samples/serverless-patterns/blob/main/apigw-vpclink-pvt-alb-terraform/apigw-vpclink-pvt-alb-terraform.json#L23-L34

**Comment by jbesw** [comment]
Thanks for the correction! This has been updated.
