### ISSUE TITLE
New serverless pattern - cfn-custom-resource-s3-create

### ISSUE THREAD

**Issue by gadavis2** [aws-samples/serverless-patterns#57]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates an Amazon S3 object by using an AWS CloudFormation custom resource and an AWS Lambda function.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Node.js

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

CloudFormation to new S3 object (via Lambda custom resource).

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern creates an Amazon S3 object by using an AWS CloudFormation custom resource and an AWS Lambda function. Custom resources enable you to write custom provisioning logic in templates that CloudFormation runs anytime you create, update (if you changed the custom resource), or delete stacks.

This pattern deploys a Lambda function that is responsible for creating (and deleting) S3 objects. The function is given CRUD permissions on objects in the S3 bucket. When the stack is first created, CloudFormation sends a create request to the function. When the stack is deleted, CloudFormation sends a delete request to the function. The function ARN is stored as a CloudFormation Export named "function-s3-create". The function requires the following resource properties:

  - Bucket: The name of the S3 bucket where the object will be located.
  - Key: The name of the S3 object (eg: index.html).
  - ContentType: The content type of the S3 object (eg: application/json, text/css, text/html, text/plain).
  - Body: The content of the S3 object.

The template includes a CloudFormation custom resource with a ServiceToken that references the Lambda function ARN. The custom resource provides the function with the required properties to create a new S3 object.

## Deployment commands

sam deploy --guided

## GitHub PR for template: 

#56 

## Payload example (e.g. Lambda event payload from source service).

N/A

## Additional resources (optional: link and anchor text, up to 5 resources)

- [CloudFormation Custom Resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html)
- [Custom Resource Request Types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes.html)
- [Custom Resource Response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html)

## Author bio 
Name: Greg Davis
Photo URL: http://gregdavis.me
Twitter handle: n/a
Description (up to 255 chars): I am a Senior Solutions Architect, AWS Cloud Architect, Full-Stack Developer, Database Engineer, Data Integration Architect, and Serverless Enthusiast.

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/lambda-s3-cfn.
