### ISSUE TITLE
New pattern submission - sfn-dynamodb

### ISSUE THREAD

**Issue by revanthreddy** [aws-samples/serverless-patterns#59]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AWS Step Function workflow to integrate with Amazon DynamoDB

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
n/a

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
AWS Step Functions to Amazon DynamoDB

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The SAM template deploys a Step Functions workflow, that takes in a payload and puts the item in DynamoBb. Additionally, this workflow also shows how to read an item directly from the DynamoDB table. The SAM template contains the minimum IAM resources required to run the application.

## Deployment commands
```
sam deploy --guided
```
## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/58

## Payload example (e.g. Lambda event payload from source service).
```
{ "id": "1234567890" }
```
_Note: Test payload is part of the cli command_

## Author bio 
Name: Revanth Anireddy
Photo URL: https://twitter.com/revanthreddy/photo
Twitter handle: @revanthreddy
Description (up to 255 chars): Senior Cloud Applications Architect @ AWS.
Swimmer, Artist, Foodie, Movie & Sports trivia enthusiast in my spare time.

**Comment by jbesw** [comment]
This has been published at https://serverlessland.com/patterns/sfn-dynamodb.
