### ISSUE TITLE
New pattern submission - cdk-cloudfront-to-s3-and-lambda pattern

### ISSUE THREAD

**Issue by a-h** [aws-samples/serverless-patterns#6]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a CloudFront distribution that routes HTTP traffic to a Serverless REST API and S3 bucket.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

TypeScript

## YouTube videoId (optional e.g. "VI79XQW4dIM")

Not yet, but I can do a walkthrough.

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

CloudFront to API Gateway / Lambda Functions and S3.

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern deploys a CloudFront distribution and routes HTTP traffic to two backend services based on the URL. Any URLs that have a path beginning with `/api/` are routed to an API Gateway which integrates with Lambda Functions which are written in TypeScript. All other traffic is routed to an S3 bucket.

The pattern also includes examples of using Lambda@Edge integrated with CloudFront to implement redirects, and to add CORS headers to API requests.

This pattern will create IAM roles that allow Lambda functions to execute. These are described by CDK during the deployment process.

## Deployment commands

```
npx cdk deploy --all
```

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/5

## Payload example (e.g. Lambda event payload from source service).

The payload is a HTTP request. The Lambda function receives an APIGatewayProxyEventV2 - see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d14f07228ede33b23717f978c1f395d9570653cf/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L124

## Author bio 
Name: Adrian Hesketh
Photo URL: https://adrianhesketh.com/profile.jpg
Twitter handle: adrianhesketh
Description (up to 255 chars): Adrian Hesketh works at Infinity Works in the UK, helping organisations with digital transformation and service delivery.

**Comment by jbesw** [comment]
This pattern is now live at https://serverlessland.com/patterns/cloudfront-s3-lambda-cdk.

I'd like to keep patterns between 2-3 services max at the moment, btw. We are missing the very simple service-to-service integrations that we have built up in the SAM collections. If you would like to build any of these, that would be great!
