### ISSUE TITLE
New pattern submission: HTTP API to Step Function to HTTP API to Step Function

### ISSUE THREAD

**Issue by brysontyrrell** [aws-samples/serverless-patterns#61]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create an HTTP API that invokes a Step Function that invokes the HTTP API to invoke itself.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

SAM/CloudFormation

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

HTTP API to Step Function to HTTP API to Step Function...

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This template creates an API Gateway HTTP API that invokes a Step Function that invokes the same HTTP API. This pattern demonstrates the HTTP API -> Step Function integration and the Step Function -> HTTP API integration.

## Deployment commands

```shell
sam deploy
```

## GitHub PR for template: 

#49 

## Payload example (e.g. Lambda event payload from source service).

`POST` to the API endpoint with an empty body. The `ExecuteApi` output will provide the full URL to invoke.

## Author bio 
Name: Bryson Tyrrell
Photo URL: https://media-exp1.licdn.com/dms/image/C4E03AQFJcTd01L5vXg/profile-displayphoto-shrink_800_800/0/1567693724568?e=1622678400&v=beta&t=STGgHkgH09XmldMv5FZM0PW0-FRmr22F_GfKnl638OA
Twitter handle: bryson3gps
Description (up to 255 chars): Staff Systems Development Engineer at Jamf, and AWS Community Builders member.

**Comment by brysontyrrell** [comment]
@jbesw you know you want to 🙃

**Comment by jbesw** [comment]
Hi Bryson! At the moment, we are primarily focusing on the 2-service patterns, especially the missing ones with CDK. I'll hold this in the queue for when we expand to 3+ service patterns (and the UI changes are made to support this more easily). Thanks for submitting!

**Comment by brysontyrrell** [comment]
I mean it’s technically just two services? :badpokerface:

**Comment by jbesw** [comment]
Technically :-) I'll keep this in the queue until we open up the patterns further.

**Comment by jbesw** [comment]
Bryson, I'm going to close this for now since we are continuing to focus on the 2 and 3-pattern service integrations. Thanks for submitting.

**Comment by brysontyrrell** [comment]
That's probably for the best.
