### ISSUE TITLE
apigw-dynamodb-terraform: CloudWatch Logs role ARN must be set in account settings to enable logging

### ISSUE THREAD

**Issue by FredericHeem** [aws-samples/serverless-patterns#620]
Hi,
FYI, regarding the example `apigw-dynamodb-terraform`, the deployment fails with the following error:
```
╷
│ Error: Updating API Gateway Stage failed: BadRequestException: CloudWatch Logs role ARN must be set in account settings to enable logging
│ 
│   with aws_api_gateway_stage.MyApiGatewayStage,
│   on main.tf line 233, in resource "aws_api_gateway_stage" "MyApiGatewayStage":
│  233: resource "aws_api_gateway_stage" "MyApiGatewayStage" {
│ 
╵
```

**Comment by jbesw** [comment]
Contacted author to address - awaiting response.

**Comment by aboushad** [comment]
It seems that sometimes api gateway account setting can take longer time, and terraform does not detect the dependency automatically. To solve the issue an explicit **depends on** needs to be added in the aws_api_gateway_stage block.
I will push an update for this part, for now trying to redeploy should work for you.

**Comment by jbesw** [comment]
Thanks for making this change and improving the repo!
