### ISSUE TITLE
New pattern submission - sfn-eventbridge

### ISSUE THREAD

**Issue by davidmacc** [aws-samples/serverless-patterns#64]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern creates a Step Functions workflow that publishes events to EventBridge.

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

Step Functions to EventBridge

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

The AWS SAM template deploys a Step Functions workflow that publishes an event to an EventBridge event bus. An IAM Role allows the workflow execution to publish events onto the event bus. An EventBridge rule forwards all events to a CloudWatch Logs log group for easy inspection.

## Deployment commands

sam deploy --guided

## GitHub PR for template: 

#63

## Additional resources (optional: link and anchor text, up to 5 resources)

- [Use Amazon EventBridge to Build Decoupled, Event-Driven Architectures](https://serverlessland.com/learn/eventbridge)
- [Call EventBridge with Step Functions](https://docs.aws.amazon.com/step-functions/latest/dg/connect-eventbridge.html)
- [Introducing the Amazon EventBridge service integration for AWS Step Functions](https://aws.amazon.com/blogs/compute/introducing-the-amazon-eventbridge-service-integration-for-aws-step-functions/)

## Author bio 
Name: David Maccarone
Photo URL: https://avatars.githubusercontent.com/u/5736100?v=4
Twitter handle: 
Description (up to 255 chars): Senior Solutions Architect at Amazon Web Services

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/sfn-eventbridge.
