### ISSUE TITLE
 New serverless pattern - cdk-sfn-s3

### ISSUE THREAD

**Issue by Harshi719** [aws-samples/serverless-patterns#702]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

<img width="641" alt="architecture-diagram-sfn-s3" src="https://user-images.githubusercontent.com/95644530/172240361-7d7e68c4-3f67-4128-aa4b-7e7a9ed28fe5.png">

**Comment by Harshi719** [comment]
added architecture diagram

**Comment by Harshi719** [comment]
@boyney123  I dont see this pattern yet in serverless land .However code is merged into git repo. So i was wondering if anything is missed from my end.

**Comment by boyney123** [comment]
Yeah sorry should be able to see now https://serverlessland.com/patterns/cdk-sfn-s3
