### ISSUE TITLE
New pattern submission - AppSync Direct Lambda Resolvers

### ISSUE THREAD

**Issue by amigitamz** [aws-samples/serverless-patterns#72]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an AppSync API with a direct Lambda resolver

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
TypeScript

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AppSync to Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This CDK application deploys an AppSync API and a Lambda function. Lambda function is added as a data source for the API and the API uses it as a direct Lambda resolver. On querying the AppSync API, AppSync invokes the Lambda function and provides default payload to your Lambda function as well as a default translation from a Lambda function's response to a GraphQL type. 

## Deployment commands
cdk deploy
See the Github repo for detailed instructions

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/71

## Payload example (e.g. Lambda event payload from source service).

```
{
  "arguments": {
    "id": "1",
    "name": "MyTodo"
  },
  "identity": null,
  "source": null,
  "request": {
    "headers": {
      ......
      ......
    }
  },
  "prev": null,
  "info": {
    "selectionSetList": [
      "id",
      "name"
    ],
    "selectionSetGraphQL": "{\n id\n name\n}",
    "parentTypeName": "Mutation",
    "fieldName": "createTodo",
    "variables": {}
  },
  "stash": {}
}
```

## Additional resources (optional: link and anchor text, up to 5 resources)
[1] Introducing Direct Lambda Resolvers - https://aws.amazon.com/blogs/mobile/appsync-direct-lambda/
[2] Direct Lambda Resolvers mapping template reference - https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-lambda.html#direct-lambda-resolvers

## Author bio 
Name: Ami Patel
Photo URL: https://appsync-patterns-serverless.s3.amazonaws.com/author_image.png
Twitter handle: @AmiPatel73
Description (up to 255 chars): Cloud Applications Architect @ AWS

**Comment by jbesw** [comment]
Thanks for the contribution! Published at https://serverlessland.com/patterns/appsync-direct-lambda-resolver
