### ISSUE TITLE
New pattern submission - Elemental Media Connect, Media Live and Media Package

### ISSUE THREAD

**Issue by cornelcroi** [aws-samples/serverless-patterns#724]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.

This patterns demonstrates how to build a video streaming stack by leveraging Elemental Media Connect, Media Live and Media Package to ingesting SRT video stream and packages into HLS/DASH/MSS format. 

After deploying the stack, a user can start streaming in the following minutes.

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
CDK Typescript
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

Developer at heart, in 2018 joined AWS as a Solution Architect and since 2021 building, jointly with customers, the most exciting and innovative prototypes on AWS.

Linkedin: corneliucroitoru
Twitter: cornel_croi

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:

https://github.com/aws-samples/serverless-patterns/pull/723

**Comment by jbesw** [comment]
Hello, can you add example-pattern.json to the PR?

**Comment by cornelcroi** [comment]
Done!

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/patterns/elemental-mediaconnect-medialive-mediapackage soon.
