### ISSUE TITLE
Patterns not published

### ISSUE THREAD

**Issue by kirtap7** [aws-samples/serverless-patterns#737]
Hi!

A couple of patterns that were merged don't seem to have been published

- https://github.com/aws-samples/serverless-patterns/issues/720
https://github.com/aws-samples/serverless-patterns/tree/main/iot-kinesis-lambda-cdk
Not available here: https://serverlessland.com/patterns/iot-kinesis-lambda-cdk

- https://github.com/aws-samples/serverless-patterns/issues/718
https://github.com/aws-samples/serverless-patterns/tree/main/iot-s3-lambda-cdk
Not available here:  https://serverlessland.com/patterns/iot-s3-lambda-cdk

**Comment by boyney123** [comment]
Thanks, sorry about that, I will take a look

**Comment by boyney123** [comment]
Found the issue @kirtap7 , it's was something I forgot to do, I will get back to you when it's done, should have it within the next day or so, sorry about that!

**Comment by boyney123** [comment]
All sorted @kirtap7 , thanks !
