### ISSUE TITLE
New pattern submission - apigw-vpclink-pvt-alb

### ISSUE THREAD

**Issue by bbideep** [aws-samples/serverless-patterns#74]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

This pattern allows integration of public API gateway endpoint to a private Application Load Balancer with an ECS Fargate cluster behind it.

## Framework (currently we support SAM or CDK)

SAM

## Services from/to (e.g. "Lambda to EventBridge)

API Gateway to Private ALB via VPC Link

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

This pattern allows integration of public API gateway endpoint to a private Application Load Balancer with an ECS Fargate cluster behind it.
It allows to build a secure pattern without exposing the private subnet resources and can be accessed only via a VPC Link.
The SAM template in this pattern deploys the following resources. It requires a VPC id and private subnet ids as inputs. It is assumed that the VPC and subnets are already configured with the required network routes.
### Deployed resources:
* Requried Security Groups
* ECS Fargate cluster with service and task definitions
* Private Application Load Balancer with appropriate listener and target group
* VPC Link
* API gateway integration between the API endpoint and the private ALB via the VPC Link

## Deployment commands

sam deploy --guided

## GitHub PR for template: 

https://github.com/aws-samples/serverless-patterns/pull/73

## Additional resources (optional: link and anchor text, up to 5 resources)
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ApiGatewayV2.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECS.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vpc-links.html

## Author bio 
Name: Bideep Bezbaruah
Photo URL: https://www.linkedin.com/in/bideep/
Twitter handle: https://twitter.com/bideepbezbaruah
Description (up to 255 chars): Principal Architect/Engineer. I have built various distributed systems and cloud architectures, modernized and migrated applications to AWS for multiple large enterprise customers.

**Comment by jbesw** [comment]
Thanks for the contribution - can you provide an architecture diagram showing the primary services and their interactions?

**Comment by bbideep** [comment]
Please refer this diagram. Let me know if you would need it in any other format.

![serverlessland-apigw-vpclink-pvt-alb.png](https://user-images.githubusercontent.com/10212650/124639097-5bdf2500-de51-11eb-9e9f-f9fe3ac76570.png)

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigw-vpclink-pvt-alb.
