### ISSUE TITLE
Lambda to KinesisDataStream to Lambda

### ISSUE THREAD

**Issue by sabornibhattacharya** [aws-samples/serverless-patterns#749]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
The use case demonstrate usage of serverless producer and consumer for a Kinesis Data Stream where records would be pushed to the stream by the producer function using boto3 SDK and those records would be processed by the consumer function.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
[1] Tutorial: Using AWS Lambda with Amazon Kinesis - https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis-example.html
[2] Boto3 Kinesis client - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesis.html

- Framework: SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
https://www.linkedin.com/in/saborni-bhattacharya-5b523812a/

I am Saborni Bhattacharya and I love making technical contents. I feel excited to create new and unique use cases that the AWS products offer.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/748

**Comment by mavi888** [comment]
Thanks for your contribution - your pattern is now live here: https://serverlessland.com/patterns/lambda-kinesis-lambda
