### ISSUE TITLE
AppSync to EventBridge

### ISSUE THREAD

**Issue by amigitamz** [aws-samples/serverless-patterns#75]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This project contains CDK template for deploying an Amazon EventBridge event bus as a HTTP data source with an AWS AppSync API.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AppSync to EventBridge

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The given CDK template creates an AppSync API with an Amazon EventBridge event bus as a HTTP data source and an IAM role that provides the AppSync API permission to make PutEvents call to the event bus along with. Using the PutEvent mutation, you can add events to the event bus.

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/76

## Additional resources (optional: link and anchor text, up to 5 resources)
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html

## Author bio 
Name: Ami Patel
Photo URL: https://appsync-patterns-serverless.s3.amazonaws.com/author_image.png
Twitter handle: @AmiPatel73 
Description (up to 255 chars): Cloud Applications Architect @ AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/appsync-eventbridge-cdk.
