### ISSUE TITLE
New pattern submission - sfn-lambda-lambda

### ISSUE THREAD

**Issue by sabornibhattacharya** [aws-samples/serverless-patterns#761]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.

The pattern deploys a Step Functions Standard workflow that invokes a Lambda function and cascades the output returned to another Lambda function, which finally returns a response. The SAM template contains the minimum IAM resources required to run the application with logging enabled.

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).

https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-creating-lambda-state-machine.html
https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-handling-error-conditions.html
https://docs.aws.amazon.com/cli/latest/reference/stepfunctions/start-execution.html#start-execution
https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-state-machine-using-sam.html

- Framework: SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
https://www.linkedin.com/in/saborni-bhattacharya-5b523812a/
I am Saborni Bhattacharya and I love making technical contents.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/760

**Comment by bls20AWS** [comment]
published https://serverlessland.com/patterns/sfn-lambda-lambda
