### ISSUE TITLE
Corrections needed in serverlessland page

### ISSUE THREAD

**Issue by sabornibhattacharya** [aws-samples/serverless-patterns#764]
https://serverlessland.com/patterns/sfn-lambda-lambda

Under cleanup section currently it is - 
```Delete the stack: same delete.```

which should be -
```Delete the stack: sam delete.```

##### Also the image shows only 1  Lambda function in the workflow which should be 2 as per the pattern that I submitted.

**Comment by jbesw** [comment]
Thanks - this has now been fixed and you should see the update shortly.
