### ISSUE TITLE
New Pattern - public-alb-private-api-terraform

### ISSUE THREAD

**Issue by agawanea** [aws-samples/serverless-patterns#766]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
Serverless cross account ALB->PrivateAPI use-case using AWS Lambda, API Gateway, Application Load Balancer, VPC Endpoint

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html
https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-private-cross-account-vpce/

- Framework: currently, we support SAM or CDK.
Terraform
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
I am a Cloud Support Engineer (Serverless) at AWS
https://www.linkedin.com/in/agawabhi/

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/765

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/patterns/public-alb-private-api-terraform shortly.
