### ISSUE TITLE
 Corrections needed in serverlessland webpage #766

### ISSUE THREAD

**Issue by agawanea** [aws-samples/serverless-patterns#770]
https://serverlessland.com/patterns/public-alb-private-api-terraform

Page Title must be corrected to : Application Load Balancer to API Gateway Private Rest API

Under Cleanup section currently it is -
1. Delete the stack: sam delete --stack-name STACK_NAME.
2. Confirm the stack has been deleted: aws cloudformation list-stacks --query "StackSummaries[?contains(StackName,'STACK_NAME')].StackStatus"

which should be of terraform commands below:
1.  Delete all created resources: terraform destroy
2. Confirm all created resources has been deleted: terraform show

**Comment by jbesw** [comment]
This has now been updated.
