### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by DarthHaider** [aws-samples/serverless-patterns#782]
### Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This construct contains serverless patterns showing how to setup a S3 website hosting bucket that is served by a CloudFront distribution that also obfuscates the CloudFront Distribution domain via Cloudfront Origin Access Identity (OAI).

### Language:
Python

### YouTube videoId (optional e.g. "VI79XQW4dIM")
N/A

### Framework
CDK V2

### Services from/to (e.g. "Lambda to EventBridge)
S3 to CloudFront

### Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This python CDK Construct deploys an S3 bucket that is encrypted via S3 managed encryption as well as configured to host a website. The CloudFront distributions is configured to serve the website contents hosted in the S3 bucket over the CloudFront distribution network. The CloudFront Domain URL is obfuscated and restricted to users who access the CloudFront Orign Access Identity (OAI.). 

### Deployment commands
1. Within your CDK Python module directory(where all your cdk stacks are located) create a constructs folder
2. Place the `s3_cloudfront_oai_cdk.py` file in the constructs folder you created 
3. Import the construct into the desired stack you would like to use this construct (ex.`from .constructs.s3_website import S3CloudFrontOAI`)
4. Use this construct in your stack by defining it in your stack (ex. `myS3HostedWebsite = S3CloudFrontOAI(self, 's3-hosted-website')`)
5. In your terminal run `CDK Deploy` for the specified stack that uses this construct

### GitHub PR for template:
[#781](https://github.com/aws-samples/serverless-patterns/pull/781)
### Payload example (e.g. Lambda event payload from source service).
N/A

### Additional resources (optional: link and anchor text, up to 5 resources)
- [Restricting access to Amazon S3 content by using an origin access identity (OAI)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html)
- [Hosting a static website using Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html)
- [Amazon Cloudfront Origin Access Identity (OAI): What it is and How to Use it?](https://www.stormit.cloud/post/cloudfront-origin-access-identity)

### Author bio
Name: Faraz Haider
Photo URL: https://media-exp1.licdn.com/dms/image/C4E03AQHZtYFSzgUgcw/profile-displayphoto-shrink_200_200/0/1596493819241?e=1665014400&v=beta&t=BwDaz3rNBQX-RGvAfnmsGy0HOiwV7wL37m337nxeriA
Twitter handle: n/a
LinkedIn: fhaider2
Description (up to 255 chars): I am a Associate Cloud Consultant with Amazon Web Services and Serverless Enthusiast.

**Comment by jbesw** [comment]
Thanks for the contribution - this will be live at https://serverlessland.com/patterns/s3-cloudfront-oai soon.
