### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by dontirun** [aws-samples/serverless-patterns#790]
An [aws-cdk](https://github.com/aws/aws-cdk) construct that enables you to use AWS Step Functions to control concurrency in your distributed system. You can use this construct to distributed state machine semaphores to control concurrent invocations of contentious work.

This construct is based off of [Justin Callison's](https://github.com/JustinCallison) example [code](https://github.com/aws-samples/aws-stepfunctions-examples/blob/main/sam/app-control-concurrency-with-dynamodb/statemachines/dynamodb-semaphore.asl.json). 

https://github.com/dontirun/state-machine-semaphore

**Comment by jbesw** [comment]
Hello! Please follow the Issue Submisson template here: https://github.com/aws-samples/serverless-patterns/issues/new?assignees=jbesw&labels=&template=new-serverless-pattern-submission.md&title=New+pattern+submission. Unfortunately we can't test and merge code without the information provided/
