### ISSUE TITLE
The link https://serverlessland.com/patterns/apigw-sqs-sms-sam is not pointing to the correct template. Wrong template is merged

### ISSUE THREAD

**Issue by jhsiddhi** [aws-samples/serverless-patterns#791]
The link https://serverlessland.com/patterns/apigw-sqs-sms-sam is not pointing to the template I have published. Template file is wrong. Can you please try again? It should have a link like this: https://serverlessland.com/patterns/apigw-sns-sms

Further, I can update all files and raise a pr again. Let me know how should we proceed.

_Originally posted by @jhsiddhi in https://github.com/aws-samples/serverless-patterns/issues/780#issuecomment-1209009779_

**Comment by boyney123** [comment]
Thanks I will take a look at this

**Comment by boyney123** [comment]
Found the issue, should be fixed now. Thanks again for the contribution!

**Comment by boyney123** [comment]
@jhsiddhi https://serverlessland.com/patterns/apigw-sns-sms seems to be working for me, can you try another browser maybe?

**Comment by jhsiddhi** [comment]
@boyney123 thank you for looking into it. I tried different browser and asked my colleagues to try as well.  However, no luck there, the template as well as photograph is not loading. It is failing with 403: access denied error. Attaching HAR for your reference. Also, please remove this as it is not providing correct information: https://serverlessland.com/patterns/apigw-sqs-sms-sam
[pattern.har.zip](https://github.com/aws-samples/serverless-patterns/files/9302707/pattern.har.zip)
