### ISSUE TITLE
AppSync to SQS

### ISSUE THREAD

**Issue by onlybakam** [aws-samples/serverless-patterns#80]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create an AppSync GraphQl API that sends messages to an SQS queue

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

Node.js

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

AppSync to SQS

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

The  CDK template creates an AppSync API with an Amazon SQS as HTTP data source. An SQS queue is created, along with an IAM role that provides the AppSync API permission to send messages to that specific queue. Using the `sendMessage` query, you can add a message to the queue.

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

 #79 

## Additional resources (optional: link and anchor text, up to 5 resources)

* [Simplify access to multiple microservices with AWS AppSync and AWS Amplify](https://aws.amazon.com/blogs/mobile/appsync-microservices/)
* [https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html)

## Author bio 
Name: Brice Pellé
Photo URL: https://github.com/onlybakam.png
Twitter handle: @bricepelle
Description (up to 255 chars): Principal Solution Architect, AppSync - AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/appsync-sqs-cdk.
