### ISSUE TITLE
Lambda Kinesis Lambda "Launch Stack" button introduces permission issues in Cloudformation console deployment

### ISSUE THREAD

**Issue by tim-pugh** [aws-samples/serverless-patterns#800]
As the title mentions:

Go here: https://serverlessland.com/patterns/lambda-kinesis-lambda

click on "Launch Stack"

Deploy the stack

View the cloudformation console

should see (if errors out..) a permission issue deploying the ConsumerFunction... " Your access has been denied by S3, please make sure your request credentials have permissions to GetObject for da-public-assessts/patterns/lambda-kinesis/lambda/xxxxxxxxxxxxx"

If I had to guess it may be object level permissions on the s3 bucket.

**Comment by jbesw** [comment]
Hello! Can you try again? We made a change to fix this error but just need to verify from your side.

**Comment by tim-pugh** [comment]
All good and in working order, thanks for the quick fix!

**Comment by jbesw** [comment]
Thanks for reporting!
