### ISSUE TITLE
New pattern submission

### ISSUE THREAD

**Issue by davonte7** [aws-samples/serverless-patterns#809]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description
This pattern contains a sample AWS Cloud Development Kit (AWS CDK) template that deploys a Lambda Function with an S3 object created trigger to start an Amazon Transcribe job and place the results in another S3 bucket. This pattern deploys one Lambda Function and two S3 Buckets. The IAM permissions for the Lambda function are scoped to only allow getting and listing objects from the input S3 bucket and putting objects to the destination S3 bucket.

## Language
Python

## Services from/to
S3 to Lambda to Transcribe to S3

## Resources
- [Using an Amazon S3 trigger to invoke a Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html)
- [Guidelines and quotas - Amazon Transcribe](https://docs.aws.amazon.com/transcribe/latest/dg/limits-guidelines.html)

## Framework
CDK

## Deployment Commands
1. Within your CDK Python module directory(where all your cdk stacks are located) create a constructs folder and within the constructs folder, create an assets folder.
2. Place the `s3_lambda_transcribe_cdk.py` file in the constructs folder you created and the `file-uploaded-trigger` folder in the assets folder you created.
3. Import the construct into the desired stack you would like to use this construct (ex.`from .constructs.s3_lambda_transcribe_cdk import TriggerTranscribe`)
4. Use this construct in your stack by defining it in your stack (ex. `trigger_transcribe = TriggerTranscribe(self, 'trigger-transcribe')`)
5. In your terminal run `CDK Deploy` for the specified stack that uses this construct

## Author Bio
Name: Davonte Blakely
Photo URL: [LinkedIn Profile Picture](https://media-exp1.licdn.com/dms/image/C4D03AQGLZ2P84tYXvg/profile-displayphoto-shrink_800_800/0/1611861641822?e=1666224000&v=beta&t=h1OihmKSYq4sCP3fCaSvbyTVqdMPiJfVq_Bmxd8Hsss)
Twitter handle: n/a
Description: I am a Associate Cloud Developer and Serverless Enthusiast

## GitHub PR for template:
#808

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/s3-lambda-transcribe-cdk
