### ISSUE TITLE
DynamoDB client within handler

### ISSUE THREAD

**Issue by timpugh** [aws-samples/serverless-patterns#817]
https://github.com/aws-samples/serverless-patterns/blob/071eebc9e84f2f22351e01c8c594670f09087abe/apigw-lambda-dynamodb/src/index.py#L7

Hello!

Just stumbled across this after checking out the pattern. Believe the client should be above the lambda handler (sorry for not submitting a pull request, a bit tied up at the moment!).

**Comment by jbesw** [comment]
Resolved by https://github.com/aws-samples/serverless-patterns/pull/825
