### ISSUE TITLE
New pattern submission - apigw-rest-stepfunction

### ISSUE THREAD

**Issue by t1agob** [aws-samples/serverless-patterns#82]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an API Gateway REST endpoint that starts a Step Functions execution.

## Framework (currently we support SAM or CDK)
SAM

## Services from/to (e.g. "Lambda to EventBridge)
API Gateway REST to Step Functions

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This SAM template creates a API Gateway REST endpoint that uses an IAM role with StartExecution permissions on a Step Function deployed by the same SAM template. The Step Function persists information received as input from the API Gateway to a DynamoDB table. An IAM role is used to guarantee write permissions only to the Step Function.

## Deployment commands
sam deploy --guided

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/81

## Payload example (e.g. Lambda event payload from source service).
```json
    {
      "Id": "4f30bb61-39bc-47f2-91c6-a7dba009f919",
      "StartTimestamp": "2021-06-25T17:47:00Z"
    }
```
## Author bio 
Name: Tiago Barbosa
Photo URL: https://avatars.githubusercontent.com/u/2689939
Twitter handle: t1agob
Description (up to 255 chars): Tiago is a Senior Specialist Solutions Architect on the Developer Acceleration team (DevAx) at Amazon Web Services. Passionate Application Developer. ex-Microsoft.

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/apigw-rest-stepfunction.
