### ISSUE TITLE
New pattern submission - Lambda to Athena

### ISSUE THREAD

**Issue by sabornibhattacharya** [aws-samples/serverless-patterns#832]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
This sample project demonstrates how to a Lambda function to invoke a query execution to an Athena database table and fetch them from the same.

- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
How can I schedule an Amazon Athena query? - https://aws.amazon.com/premiumsupport/knowledge-center/schedule-query-athena
Boto3 client for Athena - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html#client
Creating tables in Athena - Creating tables using AWS Glue or the Athena console - https://docs.aws.amazon.com/athena/latest/ug/creating-tables.html#creating-tables-how-to

- Framework: currently, we support SAM or CDK.
SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
I am Saborni Bhattacharya working at AWS and I love making technical contents.

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/831/commits

**Comment by bls20AWS** [comment]
Merged
