### ISSUE TITLE
Pattern description needs update

### ISSUE THREAD

**Issue by ibrahimcesar** [aws-samples/serverless-patterns#836]
I made a PR #815  a few days ago that was merged for [Amazon API Gateway to AWS Lambda](https://serverlessland.com/patterns/apigw-lambda-cdk).

Since I upgraded the version of the CDK to v2, the instructions for deploy were not updated as placed in the README.md and some in the `apigw-lambda-cdk/example-pattern.json`. There's another way to me provide the informations to correct the instructions in the site?

Thanks!

**Comment by jbesw** [comment]
Thanks this change will be live soon on https://serverlessland.com/patterns/apigw-lambda-cdk.
