### ISSUE TITLE
New pattern submission - msk-lambda

### ISSUE THREAD

**Issue by ParnabBasak** [aws-samples/serverless-patterns#86]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a Lambda function that uses an Amazon MSK topic as an event source

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Nodejs 12.x

## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
MSK to Lambda
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
Lambda is a consumer application for your Kafka topic. It processes records from one or more partitions and sends the payload to the target function. Lambda continues to process batches until there are no more messages in the topic.

Lambda internally polls for new messages from the event source and then synchronously invokes the target Lambda function. Lambda reads the messages in batches and provides these to your function as an event payload. The maximum batch size is configurable. (The default is 100 messages.) 

The SAM template creates a Lambda Function that uses a AWSLambdaMSKExecutionRole IAM role to poll a certain topic within a certain MSK Stream as defined as the Event source in the template.
 
## Deployment commands
sam deploy --guided
## GitHub PR for template: 
#83 
## Payload example (e.g. Lambda event payload from source service).
```
{   "eventSource": "aws:kafka",
    "eventSourceArn": "arn:aws:kafka:sa-east-1:123456789012:cluster/vpc-2priv-2pub/751d2973-a626-431c-9d4e-d7975eb44dd7-2",
    "records": {
      "mytopic-0": [
          {
            "topic": "mytopic"
            "partition": "0",
            "offset": 15,
            "timestamp": 1545084650987,
            "timestampType": "CREATE_TIME",
            "value": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0Lg==",
          }
      ]
    }
}
```
## Additional resources (optional: link and anchor text, up to 5 resources)
- [Using Lambda with Amazon MSK](https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html)
- [Using Amazon MSK as an event source for AWS Lambda](https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/)

## Author bio 
Name: Parnab Basak
Photo URL: https://avatars.githubusercontent.com/u/18371977?v=4
Twitter handle: @ParnabBasak
Description (up to 255 chars): Parnab is a Solutions Architect for the Service Creation team in AWS. He specializes in creating net new solutions that are cloud native using modern s/w dev practices like Serverless, DevOps & Analytics

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/msk-lambda.
