### ISSUE TITLE
Kinesis EFO Example - Is this correct?

### ISSUE THREAD

**Issue by timpugh** [aws-samples/serverless-patterns#875]
I think with commit c45f983eea273665987b76412066d9eaa2decb8a it removed the EFO functionality.

If you look at the pattern on [serverlessland.com](https://serverlessland.com/patterns/kinesis-lambda-efo) and compare it to what is in the g[ithub examples latest commit](https://github.com/aws-samples/serverless-patterns/blob/main/kinesis-lambda/template.yaml), they differ.

**Comment by timpugh** [comment]
Actually I see what's occurring now:

If you go to the pattern on serverlessland.com, https://serverlessland.com/patterns/kinesis-lambda-efo, click on the github link, it brings you to a different example (the one I mentioned): https://github.com/aws-samples/serverless-patterns/tree/main/kinesis-lambda

So I think the serverlessland.com site needs to point to the correct pattern on github instead, which is located here: https://github.com/aws-samples/serverless-patterns/tree/main/kinesis-lambda-efo

**Comment by boyney123** [comment]
Hi @timpugh ,

Thanks for raising this, fix is going live now

**Comment by boyney123** [comment]
Now points to the right place, thanks again @timpugh
