### ISSUE TITLE
apigw-lambda-dynamodb-sam-java build problem

### ISSUE THREAD

**Issue by mihajloracic** [aws-samples/serverless-patterns#877]
DDBUtils class doesn't have software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider imported and it is missing im pom.xml.

**Comment by iworks-education** [comment]
Same error:

DDBUtils class doesn't have software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider imported and it is missing im pom.xml.
