### ISSUE TITLE
New pattern submission - private API Gateway

### ISSUE THREAD

**Issue by bttong** [aws-samples/serverless-patterns#88]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Configure Amazon API Gateway Private API endpoint with VPC Lambda

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
TypeScript

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
Private API Gateway to VPC Lambda

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This pattern in CDK offers a example to generate an Amazon API Gateway Private API endpoint with a greedy proxy ("{proxy+}") and "ANY" method from the specified path, meaning it will accept by default any method and any path. The VPC Lambda function provided in JavaScript only returns the path.

## Deployment commands
npx cdk bootstrap aws://accountnumber/region
npx cdk deploy --app 'ts-node .' --all

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/87

## Author bio 
Name: Rajneesh Ranjan
Photo URL: https://github.com/rajneeshr
Twitter handle:
Description (up to 255 chars): Rajneesh works at AWS Professional Services and is a Serverless and Container enthusiast.

Name: Britney Tong
Photo URL: https://avatars.githubusercontent.com/u/8812922?s=400&u=2b2d05ff8a3d21147a16fb6a50e3d3a1707822b2&v=4
Twitter handle:
Description (up to 255 chars): Britney is an Professional Service and a Serverless enthusiast at Amazon Web Services based in Austin, US. Prior to joining AWS Britney worked in a number of different technical roles specializing in IoT integration, workflow Automation, and Platform as a Service (PaaS).

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/cdk-private-api-lambda.

**Comment by bttong** [comment]
Thank you!
For additional resource section, would it be possible to update to these links?
Creating a private API in Amazon API Gateway - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html
How to invoke a private API - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html

**Comment by jbesw** [comment]
Yes - these are now updated.
