### ISSUE TITLE
New pattern submission: HTTP API Gateway to EventBridge in CDK

### ISSUE THREAD

**Issue by Hugoz** [aws-samples/serverless-patterns#91]
## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create an HTTP API Gateway that sends events to EventBridge.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
HTTP API Gateway to EventBridge

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
The CDK project creates an Amazon API gateway HTTP API endpoint. The endpoint uses service integrations to directly connect to Amazon EventBridge. An EventBridge rule sends all events to Cloudwatch Logs

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/90

## Payload example (e.g. Lambda event payload from source service).
```
curl --location --request POST '<your api endpoint>' --header 'Content-Type: application/json' \
--data-raw '{
    "Detail":{
        "message": "This is my test"
    }
}'
```

## Author bio 
Name: Hugo Sterin
Photo URL:
Twitter handle: hsterin
Description (up to 255 chars): Solutions Architect @ AWS

**Comment by jbesw** [comment]
Thanks for the contribution! This is now live at https://serverlessland.com/patterns/apigateway-http-eventbridge-cdk.
