### ISSUE TITLE
New pattern submission - lambda to lambda(async) through s3 bucket to transfer large payload

### ISSUE THREAD

**Issue by SeoyeonPark** [aws-samples/serverless-patterns#923]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

Note the following information for the model:
- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Resources should like to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK.
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

### Description (mid-length)
Transfer payload through S3 when Lambda function call another Lambda function asynchronously.

## Language
Python

## Framework
SAM

## Services from/to
Lambda function to Lambda function
or
Lambda function to S3, S3 trigger Lambda function (in case when the payload size is larger than invocation payload quota)

## Description
[README.md](https://github.com/SeoyeonPark/serverless-patterns/tree/SeoyeonPark-feature-lambda-s3-async-lambda-serverless/lambda-s3-async-lambda)

## Additional resources (optional: link and anchor text, up to 5 resources)
- [Lambda Quotas](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html#function-configuration-deployment-and-execution)
- [Asynchronous invocation](https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html)

## GitHub PR for template:
#922

**Comment by jbesw** [comment]
Merged: https://github.com/aws-samples/serverless-patterns/pull/922
