### ISSUE TITLE
New pattern submission: Create a Lambda function that triggers an AppSync GraphQL API

### ISSUE THREAD

**Issue by onlybakam** [aws-samples/serverless-patterns#93]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")

Create a Lambda function that triggers an AppSync GraphQL API.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)

NodeJS

## Framework (currently we support SAM or CDK)

CDK

## Services from/to (e.g. "Lambda to EventBridge)

Lambda to AppSync

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)

In this pattern, AWS AppSync provides a a schema that allows you to manage and read todos. A Lambda function is implemented that can interact with the GraphQL API. This function can create todos by using the codegen generated from the schema by the Amplify CLI codegen. The codegen provides the operations and the variable types, which makes it simple to interact with the AppSync GraphQL API from the Typescript function. This pattern is useful in event driven design that trigger your AppSync function from the backend. Those changes can they easily be reflected on front-end clients in real time by using AppSync subscriptions.

## Deployment commands

`cdk deploy`

## GitHub PR for template: 

#92 

## Additional resources (optional: link and anchor text, up to 5 resources)

1. [Exporting AppSync operations to a Lambda layer for easy reuse](https://docs.amplify.aws/guides/functions/appsync-operations-to-lambda-layer/q/platform/js)
2. [Simplify access to multiple microservices with AWS AppSync and AWS Amplify](https://aws.amazon.com/blogs/mobile/appsync-microservices/)
3. [Tutorial: HTTP Resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html)

## Author bio 
Name: Brice Pellé
Photo URL: https://github.com/onlybakam.png
Twitter handle: @bricepelle
Description (up to 255 chars): Principal Solution Architect, AppSync - AWS

**Comment by jbesw** [comment]
Thanks for your contribution! This is now live at https://serverlessland.com/patterns/appsync-lambda-graphql.
