### ISSUE TITLE
New pattern submission - appconfig-feature-flag-sam

### ISSUE THREAD

**Issue by menalb** [aws-samples/serverless-patterns#937]
## Description
Using AWS SAM template, this pattern creates

- AWS AppConfig Feature Flag configuration
- AWS Lambda that reads the feature flags from AWS AppConfig
- Amazon API Gateway HTTP API that triggers the AWS Lambda

The feature flag configuration in this example contains two flags:

- a simple boolean flag ON/OFF
- a flag that can be ON/OFF but, when it is ON, it has a numeric value

## Language
Typescript

## Framework
SAM

## Resources
- [AWS AppConfig](https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html)
- [AWS AppConfig Feature Flag](https://aws.amazon.com/it/blogs/mt/using-aws-appconfig-feature-flags/)
- [AWS AppConfig integration with Lambda extensions](https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-integration-lambda-extensions.html)
- [Learn to Use AWS AppConfig Feature Flags](https://catalog.us-east-1.prod.workshops.aws/workshops/2ee2fc71-0618-479c-86dd-1d5fb168eb20/en-US/getting-started)

## GitHub PR
[936](https://github.com/aws-samples/serverless-patterns/pull/936)

**Comment by jbesw** [comment]
Merged https://github.com/aws-samples/serverless-patterns/pull/936
