### ISSUE TITLE
New serverless pattern - REST API to Event Bridge

### ISSUE THREAD

**Issue by umaragu** [aws-samples/serverless-patterns#94]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
Create a REST API that can put events to EventBridge 
## Framework (currently we support SAM or CDK)
SAM
## Services from/to (e.g. "Lambda to EventBridge)
API Gateway to EventBridge
## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This template creates an API Gateway REST API that puts an event to Amazon EventBridge. This pattern addresses some nuances with defining the VTL template mapping when integrating with EventBridge. An IAM permission for putting events to EventBridge is created for API Gateway.

## Deployment commands
sam deploy
## Payload example (e.g. Lambda event payload from source service).
{"items":[
    {
    "Detail":"{\"data\":\"1234343\"}",
    "DetailType":"Test",
    "Source":"Test"
    }
]
}
## Author bio 
Name: Uma Ramadoss
Photo URL:
Twitter handle:
Description (up to 255 chars):

**Comment by jbesw** [comment]
Thanks for the submission! This is now live at https://serverlessland.com/patterns/apigateway-rest-eventbridge.
