### ISSUE TITLE
New pattern submission: s3-upload-presignedurl-api-cdk-ts

### ISSUE THREAD

**Issue by jeromevdl** [aws-samples/serverless-patterns#953]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

2. THIS PROCESS HAS BEEN SIMPLIFIED. All the information below must be provided in the "example-pattern.json" file cloned from the model **

You must ensure that the sections of the model README.md are completed in full.

## GitHub PR for template:
https://github.com/aws-samples/serverless-patterns/pull/948

**Comment by jbesw** [comment]
Merged in https://github.com/aws-samples/serverless-patterns/pull/948
