### ISSUE TITLE
New pattern submission - AppSync to StepFunctions (Synchronous Express Workflows)

### ISSUE THREAD

**Issue by amigitamz** [aws-samples/serverless-patterns#97]
To submit a template to the Serverless Patterns Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-patterns/blob/main/PUBLISHING.md).**

Use the model template located at https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model to set up a README, template and any associated code.

## Description (mid-length e.g. "Create a Lambda function that sends events to EventBridge.")
This project contains a sample AWS CDK template for running Step Functions synchronous express workflows from an AppSync API.

## Language: (optional e.g. "Python", if you have a Lambda function in your example)
Node.js

## Framework (currently we support SAM or CDK)
CDK

## Services from/to (e.g. "Lambda to EventBridge)
AppSync to StepFunctions (Synchronous Express Workflow)

## Description (this must include a throughout explanation of the pattern together with details of IAM permissioning)
This project contains a sample AWS CDK template which will create an AppSync API and State Machine for Express Workflows. The state machine will be added as an HTTP Data Source for AppSync API and the API will be granted permissions to make StartSyncExecution API call.

## Deployment commands
cdk deploy

## GitHub PR for template: 
https://github.com/aws-samples/serverless-patterns/pull/98

## Additional resources (optional: link and anchor text, up to 5 resources)
HTTP Resolvers - https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html
Synchronous Express Workflows - https://aws.amazon.com/blogs/compute/new-synchronous-express-workflows-for-aws-step-functions/

## Author bio 
Name: Ami Patel 
Photo URL: https://appsync-patterns-serverless.s3.amazonaws.com/author_image.png
Twitter handle: @AmiPatel73
Description (up to 255 chars): Cloud Application Architect @ AWS

**Comment by jbesw** [comment]
Thanks for the submission! This is now live at https://serverlessland.com/patterns/appsync-stepfunctions-cdk.
