### ISSUE TITLE
Getting the following issue on terraform plan

### ISSUE THREAD

**Issue by Mridula-Juluri** [aws-samples/serverless-patterns#970]
I am trying **apigw-http-api-lambda-terraform** on terraform plan getting the below error.
 
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 0s [id=8bab05d3529c8e4481b2d26a1879e1b41f367394]
╷
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 6d1b2715-c592-449e-8c50-f6f8a7e27ca7, api error ExpiredToken: The security token included in the request is expired
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 20, in provider "aws":
│   20: provider "aws" {
│

**Comment by Mridula-Juluri** [comment]
I have set up AWS Credentials and its working fine for me.

**Comment by c-los** [comment]
Hello, 
The aws provider block under main.tf is looking for AWS credentials under the default profile in the .aws/credentials file. 

```
provider "aws" {
  profile = "default"
  region = var.aws_region
}
```
You can rectify this issue by 
1/updating  the AWS credentials under the default profile on you .aws/credentials file 
2/ updating the profile parameter under the aws provider block with an existing named profile from your .aws/credentials file 3/comment out the `profile = "default"` line if you are passing AWS credential via environment variables.

Please reference the link below for additional information on this topic. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#provider-configuration

**Comment by jbesw** [comment]
Thanks for the info! Pls reopen if you continue to have issues.
